### ISSUE TITLE
can I use it with a Kinect ?

### ISSUE THREAD

**Issue by sulglv** [TadasBaltrusaitis/OpenFace#10]
hi  :) 
can i run the code with depth images obtained by a Kinect ?

**Comment by TadasBaltrusaitis** [comment]
Hi,

You can use it with the depth images obtained by Kinect (using the CLM-Z model). However, the latest and default model (CLNF) is as accurate as the one with depth images and is faster so I would not necesserilly recommend using the depth images.

Thanks,
Tadas

**Comment by sulglv** [comment]
It is faster without depth images. However, does it performance better with large head pose angles?
Or any suggests about large head pose angles?
Thanks 
:)

**Comment by vinjn** [comment]
Does it work with the infrared stream from Kinect V2?

**Comment by TadasBaltrusaitis** [comment]
If you are having particular issues with large head pose angles Kinect data might help, but in general on my experimental data the behavior was fairly similar when using CLNF (on RGB data) vs CLM-Z (on RGB-D data). With regards to Kinect V2 data I haven't tried but there shouldn't be a reason why it should not work.

**Comment by vinjn** [comment]
Ok, thx.
