### ISSUE TITLE
I need AU43 to detect eyes closed,how can i add au43

### ISSUE THREAD

**Issue by Ray8716397** [TadasBaltrusaitis/OpenFace#1002]
hello,i need au43 to calculate the eyes closed time in a video,please help

**Comment by Ray8716397** [comment]
i found OpenFace/model_training/AU_training/experiments/Bosphorus/models/AU_43_dyn.dat,but i dont know how to use it

**Comment by TadasBaltrusaitis** [comment]
By default OpenFace has AU45 being output every frame which should correspond to a blink (eyes closed) action.

**Comment by Ray8716397** [comment]
want to know how the time of eyes closed in a video, au45 seems can not to be able to calculate that
