### ISSUE TITLE
Looking at right-left output values as labels

### ISSUE THREAD

**Issue by FereshtehFeiz** [TadasBaltrusaitis/OpenFace#1019]
Hello, Thank you for this work. I want to have an precise output label for looking to right or left or straight. I read the Wiki and see If a person is looking left-right this will results in the change of gaze_angle_x (from positive to negative) and, if a person is looking straight ahead the angles will be close to 0 (within measurement error). 
Would be correct if I consider all the negative values: Looking Right, positive values: Looking Left and 0: Looking straight ? 
Any suggestion do you have to categorize these values to the correct label? 

Thanks
Fereshteh

**Comment by brmarkus** [comment]
Can you rely on the camera being aligned properly? Can you be sure the person is always straight in front of the camera?
Will the person have always more-or-less the same distance to the camera?
Can you rely the captured frame from the buffer is always (or never) be flipped?

You might need to do some calibration/experiments to check with your environment (distance, angles, resolution, camera-lens/calibration/de-warping) and notice the angles under with some thresholds&hysteresis/range.

(in a similar driver-monitoring project in a vehicle it is similar: different persons, different seat-settings, different distance, different lightings, reflections in pair of glasses)

**Comment by FereshtehFeiz** [comment]
My environment is in the case student following the lecture and it's important for this situation to understand student looking at right or left only, consider the camera is fixed and user has not so near or far distance, a normal distance with webcam camera.

**Comment by brmarkus** [comment]
Be prepared to do experiments in your environment - with your camera, lenses, field-of-view, distances, area, and just doing the "calibration".
I could imagine that you would need to use multiple cameras due to distortion at the borders and far distances.
Find a couple of volunteering students and record the angles over columns and rows the students are organized in.

In other words: there won't be just a table here in this repo where you look-up such mapping for left, right and straight, I fear.

**Comment by FereshtehFeiz** [comment]
Ok, so what I understood from the csv output gaze and head pose couldn't map it to a certain label that from this certain value to that certain value it's "looking right" or "looking left" 
by considering a certain distance and fixed environment for following remote lectures. 

Thank you

**Comment by brmarkus** [comment]
Hmm, so leaving the questions to the authors of "OpenFace"... to get the relative/absolute coordinate-system transformations explained&confirmed.
Looking "straight" but turning the head left&right versus keeping the head "straight" but looking left&right versus rotating the head and looking left&right.

**Comment by FereshtehFeiz** [comment]
ok if I want to make it simple and focus only on the gaze tracking, considering gaze_angle_x positive value as Left, negative value as Right and 0 as looking straight is correct?

**Comment by FereshtehFeiz** [comment]
![Gaze tracking  (1)](https://user-images.githubusercontent.com/34858445/188184125-7d5d69cf-521a-46b8-b801-d672c7df9a0c.png)
This is the sample output for gaze_angle_x

**Comment by FereshtehFeiz** [comment]
I solved this by this by IF formula in the excel to map the gaze_angle_x values to right, left and center.
