### ISSUE TITLE
The make command throws error in FaceLandmarkImg

### ISSUE THREAD

**Issue by jsinghh09** [TadasBaltrusaitis/OpenFace#1026]
Hi, 
So I have been trying to install and build openface on my Mac Intel chip system. 
I perform all the steps as stated in the installation guide however when I do the make command in the build directory, it fails at 84% with an error of 
Screenshots - https://drive.google.com/drive/folders/1k3gBuPeYgjXQnEdszCPlCOYiXMRM_KVq?usp=sharing

Please let me know how to resolve this.

**Comment by jsinghh09** [comment]
The error output for reference 
[ 84%] Linking CXX executable ../../bin/FaceLandmarkImg
Undefined symbols for architecture x86_64:
  "dlib::entropy_decoder_kernel_2::get_target(unsigned int)", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in FaceLandmarkImg.cpp.o
      dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&) in FaceLandmarkImg.cpp.o
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
      dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&) in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::entropy_decoder_kernel_2::set_stream(std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in FaceLandmarkImg.cpp.o
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in FaceLandmarkImg.cpp.o
      dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&) in FaceLandmarkImg.cpp.o
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
      dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&) in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::entropy_decoder_kernel_2::entropy_decoder_kernel_2()", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in FaceLandmarkImg.cpp.o
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::entropy_decoder_kernel_2::~entropy_decoder_kernel_2()", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in FaceLandmarkImg.cpp.o
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::base64::base64()", referenced from:
      dlib::get_serialized_frontal_faces() in FaceLandmarkImg.cpp.o
      dlib::get_serialized_frontal_faces() in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::base64::~base64()", referenced from:
      dlib::get_serialized_frontal_faces() in FaceLandmarkImg.cpp.o
      dlib::get_serialized_frontal_faces() in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "dlib::base64::decode(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const", referenced from:
      dlib::get_serialized_frontal_faces() in FaceLandmarkImg.cpp.o
      dlib::get_serialized_frontal_faces() in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/FaceLandmarkImg] Error 1
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
make: *** [all] Error 2

**Comment by davidmartinrius** [comment]
I have the exact same error

**Comment by davidmartinrius** [comment]
I finally solved it installing everything from the step by step guide. Don't use the install script.
