### ISSUE TITLE
Finding Gaze angle - Demo

### ISSUE THREAD

**Issue by vedipen** [TadasBaltrusaitis/OpenFace#103]
I am interested in finding the gaze angle rather than the gaze direction vector. 
In feature/ windows gui, while running ` matlab_runners/Demo/gaze_extraction_demo_vid.m` , tracking works fine but is unable to get gaze angles with respect to head pose; in Matalab r2015a, x64 bit windows
I get following error in command window
```
Index exceeds matrix dimensions.

Error in gaze_extraction_demo_vid (line 48)
gaze_angle = gaze(:,[11,12]);
```
Rest everything is working as expected. Any help will be greatly appreciated.
Thanks for sharing your code.

**Comment by TadasBaltrusaitis** [comment]
Are you using the non master branch version of the code? As that line of code is from a development branch which will include the gaze angle, but is not ready for public use yet.

Thanks,
Tadas

**Comment by vedipen** [comment]
Yes, I am.
Cool.. Will think of a workaround.

Thanks

**Comment by TadasBaltrusaitis** [comment]
The new version should come out by the end of the year, so if you wait a couple of weeks, that code should work.

**Comment by vedipen** [comment]
Great!

**Comment by rohitvarma1986** [comment]
Is the gaze angle with respect to camera or head pose ?

**Comment by TadasBaltrusaitis** [comment]
It is with respect to camera.
