### ISSUE TITLE
Does anyone know this time format "webcam_2023-03-06-11-27-32.csv"

### ISSUE THREAD

**Issue by letsgo0** [TadasBaltrusaitis/OpenFace#1036]
I get some output file ended with .csv. And its file name looks like naming as a time format which I don't know. 

I get nothing by searching on the internet.

e.g. 
webcam_2023-03-06-11-27-32.csv  (actually created time is 2023/3/6 19:58:24)
webcam_2023-03-06-11-27-32_of_details.txt  (actually created time is 2023/3/6 19:58:24)

Does anyone know?

**Comment by brmarkus** [comment]
The  Wiki "https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format" only explains the content/columns of the files.

You might start investigating with  e.g. this PullRequest "https://github.com/TadasBaltrusaitis/OpenFace/pull/911/files". Checking e.g. where "PostprocessOutputFile(std::string output_file)" gets called with the constructed filename.

**Comment by letsgo0** [comment]
Thanks. I checked some code snippets. It look like I have find the key function where filename is constructed. But it needs time to compile, debug, and validate. I will do it when i'am not busy.

Anyway, I'm very glad to have your tip. @brmarkus
