### ISSUE TITLE
Segfault: 11, in FaceAnalysis::ExtractAllPredictionsOfflineClass

### ISSUE THREAD

**Issue by Danielohayon** [TadasBaltrusaitis/OpenFace#104]
In FeatureExtraction.cpp in the `void post_process_output_file ` function, this line:
`face_analyser.ExtractAllPredictionsOfflineClass(predictions_class, certainties, successes, timestamps, dynamic);`
causes a segfault. 
We traced the segfault to these lines inside the function FaceAnalysis::ExtractAllPredictionsOfflineClass: 
`for (int w = -(window_size - 1) / 2; w <= (window_size - 1) / 2; ++w)  
			{  
				sum += au_vals_tmp[i + w];  
			}  
`
using a mac and running from the command line using this command: 
`bin/FeatureExtraction -q -au_static -f ../im1.jpg -of ../out`

**Comment by TadasBaltrusaitis** [comment]
Thanks for pointing this out. I just made a code change that should resolve this issue. Let me know if it works your end.
