### ISSUE TITLE
Location of Head in Pose 

### ISSUE THREAD

**Issue by ArtSebus** [TadasBaltrusaitis/OpenFace#105]
According to wiki Pose returns ` the location of the head with respect to camera in milometers` but in my application, I receive this location front of the head and not at the center of head. 

Is this result expected or is this considered and error. 

Thank you

**Comment by TadasBaltrusaitis** [comment]
The head pose should be from the center of the camera to the center of the face (as defined by the 68 facial landmarks), the discrepancy could be due to measurement error or inaccurate camera parameters (focal length and optical axis `fx,fy,cx,cy`)
