### ISSUE TITLE
The results of AUs are different when changed the video size

### ISSUE THREAD

**Issue by flasker** [TadasBaltrusaitis/OpenFace#106]
Thank you for this great work.

I have a video recording human face for 960X720, and feature extract gave me AUs of it.
After changed the video size to 480X360 and 720X540, the returned AUs are different.
And the AUs of split video compared to the AUs of original video are different too.

Which one should I trust, or should I just use HOG features?
My purpose is to get Valence and Arousal values.

**Comment by TadasBaltrusaitis** [comment]
The values will be slightly different as the resolution of the face and the quality of the image changes. For best performance the face in the image should be at least 120 pixels across (ear to ear)

Which ones are more useful depends very much on your application scenario and its goal, and the amount of training data you have available. You will need to experiment yourself and verify which one works best.

Thanks,
Tadas
