### ISSUE TITLE
Could not find the HAAR face detector location; Could not find CEN patch experts; ERROR: Could not load the landmark detector

### ISSUE THREAD

**Issue by BugMaker2002** [TadasBaltrusaitis/OpenFace#1064]
When I try to run the command: ./bin/FeatureExtraction -verbose -f "/share2/dataUBFC_rPPG/dataset2/subject1/vid.avi"
Some errors occurred:
![image](https://github.com/TadasBaltrusaitis/OpenFace/assets/110211332/f91e638f-8405-4b6b-adb5-9258d79f9785)
Could you tell me how to solve the problem?

**Comment by UCAS-WUHU111** [comment]
请问怎么解决的啊

**Comment by brmarkus** [comment]
> 请问怎么解决的啊 (What is the solution?)

Looks like the model files were not downloaded according the log message "for instructions of how to download them, see..."

EITHER

   install&build with the help of the script "https://github.com/TadasBaltrusaitis/OpenFace/blob/master/install.sh" (or manually perform all the steps inside the script)
and
   download the models by using the script "https://github.com/TadasBaltrusaitis/OpenFace/blob/master/download_models.sh" (or manually download them from the steps inside the script)

OR
use (the pre-built) Docker container image (OpenFace is built and installed inside the container, all needed dependencies already installed, model-files already downloaded).
