### ISSUE TITLE
Crashed when parsing "ccnf_patches_0.25_general.txt"

### ISSUE THREAD

**Issue by MaeThird** [TadasBaltrusaitis/OpenFace#108]
All the code is downloaded from the branch of master.When I launched FaceLandmarkImg after building,it crashed at parsing model file "ccnf_patches_0.25_general.txt":

![2016-12-25_214022](https://cloud.githubusercontent.com/assets/14851411/21471376/c06d8710-caeb-11e6-8190-9b0d2fd6eb47.png)
and the last step is 
![2016-12-25_213945](https://cloud.githubusercontent.com/assets/14851411/21471379/e8f357fa-caeb-11e6-8225-e0a01c2caed4.png)

Anything wrong with my downloaded model file ?

**Comment by TadasBaltrusaitis** [comment]
There shouldn't be, are you using the Release or Debug build, 64 or 32 bit architecture? There might be a chance that the model file is not found.
