### ISSUE TITLE
Gaze Detection from Webcam

### ISSUE THREAD

**Issue by geekysethi** [TadasBaltrusaitis/OpenFace#109]
I am working on a project for live webcam eye gaze. I was wondering if it was possible to use FaceLandmarkVid.exe with webcam device and get the same gaze estimation in the text file (as from FeatureExtraction from input file) in realtime.  
Please let me know of a solution.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Currently only FeatureExtraction.exe provides an output text file, to get a text file from live webcam with gaze estimates you would need to either change `FeatureExtraction.cpp` or `FaceLandmarkVid.cpp` accordingly.
