### ISSUE TITLE
what the process of compile in window help

### ISSUE THREAD

**Issue by xalteropsx** [TadasBaltrusaitis/OpenFace#1096]
KEEP getting this error while compiling 

![image](https://github.com/user-attachments/assets/6d6c067f-e1a2-4cc5-ba10-3fb5001f79e6)

1>------ Rebuild All started: Project: Utilities, Configuration: Debug x64 ------
1>ImageCapture.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>RecorderCSV.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>RecorderHOG.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>RecorderOpenFace.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>RecorderOpenFaceParameters.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>SequenceCapture.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>stdafx_ut.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>VisualizationUtils.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>Visualizer.cpp
1>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
1>Generating Code...
1>0 File(s) copied
1>stdafx_ut.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
1>Utilities.vcxproj -> R:\fail\openf\x64\Debug\Utilities.lib
1>File not found - Debug
1>0 File(s) copied
1>0 File(s) copied
1>0 File(s) copied
1>0 File(s) copied
1>Done building project "Utilities.vcxproj".
2>------ Rebuild All started: Project: LandmarkDetector, Configuration: Debug x64 ------
2>stdafx.cpp
2>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
2>CCNF_patch_expert.cpp
2>LandmarkDetectorModel.cpp
2>LandmarkDetectorFunc.cpp
2>LandmarkDetectorUtils.cpp
2>LandmarkDetectionValidator.cpp
2>Patch_experts.cpp
2>PAW.cpp
2>PDM.cpp
2>SVR_patch_expert.cpp
2>CEN_patch_expert.cpp
2>CNN_utils.cpp
2>FaceDetectorMTCNN.cpp
2>LandmarkDetectorParameters.cpp
2>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\CEN_patch_expert.cpp)
2>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\FaceDetectorMTCNN.cpp)
2>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\CNN_utils.cpp)
2>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\LandmarkDetectorParameters.cpp)
2>0 File(s) copied
2>LandmarkDetector.vcxproj -> R:\fail\openf\x64\Debug\LandmarkDetector.lib
2>0 File(s) copied
2>0 File(s) copied
2>Done building project "LandmarkDetector.vcxproj".
3>------ Rebuild All started: Project: GazeAnalyser, Configuration: Debug x64 ------
4>------ Rebuild All started: Project: FaceAnalyser, Configuration: Debug x64 ------
3>GazeEstimation.cpp
4>FaceAnalyserParameters.cpp
4>stdafx_fa.cpp
4>SVM_dynamic_lin.cpp
4>SVM_static_lin.cpp
4>SVR_dynamic_lin_regressors.cpp
4>SVR_static_lin_regressors.cpp
4>FaceAnalyser.cpp
4>Face_utils.cpp
3>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\stdafx_fa.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\SVM_dynamic_lin.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\SVR_static_lin_regressors.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\Face_utils.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\SVR_dynamic_lin_regressors.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\FaceAnalyserParameters.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\FaceAnalyser.cpp)
4>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute (compiling source file src\SVM_static_lin.cpp)
3>0 File(s) copied
3>GazeAnalyser.vcxproj -> R:\fail\openf\x64\Debug\GazeAnalyser.lib
3>File not found - Debug
3>0 File(s) copied
3>0 File(s) copied
3>0 File(s) copied
3>0 File(s) copied
3>Done building project "GazeAnalyser.vcxproj".
4>0 File(s) copied
4>stdafx_fa.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
4>FaceAnalyser.vcxproj -> R:\fail\openf\x64\Debug\FaceAnalyser.lib
4>0 File(s) copied
4>Done building project "FaceAnalyser.vcxproj".
5>------ Rebuild All started: Project: FaceLandmarkImg, Configuration: Debug x64 ------
5>FaceLandmarkImg.cpp
5>r:\fail\openf\lib\3rdparty\dlib\include\dlib\console_progress_indicator.h(153): warning C4834: discarding return value of function with 'nodiscard' attribute
5>0 File(s) copied
5>dlib.lib(base64_kernel_1.obj) : warning LNK4099: PDB 'dlib.pdb' was not found with 'dlib.lib(base64_kernel_1.obj)' or at 'R:\fail\openf\x64\Debug\dlib.pdb'; linking object as if no debug info
5>dlib.lib(entropy_decoder_kernel_2.obj) : warning LNK4099: PDB 'dlib.pdb' was not found with 'dlib.lib(entropy_decoder_kernel_2.obj)' or at 'R:\fail\openf\x64\Debug\dlib.pdb'; linking object as if no debug info
5>dlib.lib(test_for_odr_violations.obj) : warning LNK4099: PDB 'dlib.pdb' was not found with 'dlib.lib(test_for_odr_violations.obj)' or at 'R:\fail\openf\x64\Debug\dlib.pdb'; linking object as if no debug info
5>FaceLandmarkImg.vcxproj -> R:\fail\openf\x64\Debug\FaceLandmarkImg.exe
5>File not found - Debug
5>0 File(s) copied
5>0 File(s) copied
5>0 File(s) copied
5>0 File(s) copied
5>Done building project "FaceLandmarkImg.vcxproj".
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========

**Comment by brmarkus** [comment]
Does it work with a Release config instead of Debug config?

**Comment by xalteropsx** [comment]
@brmarkus  thnx u bro awesome work like charm
