### ISSUE TITLE
Running bin/FaceLandmarkImg doesn't give back any output

### ISSUE THREAD

**Issue by tarekmehrez** [TadasBaltrusaitis/OpenFace#111]
After several attempts to run bin/FaceLandmarkImg, the script didn't output any results. I tried to follow your command line args in https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments but got nothing.

How I am running it:
`bin/FaceLandmarkImg -gaze -f ../image_sequence/001.jpg -of output.txt`

The output:
```
Loading the model
Reading the CLNF landmark detector/tracker from: bin/model/main_clnf_general.txt
Reading the landmark detector module from: bin/model/clnf_general.txt
Reading the PDM module from: bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: bin/model/tris_68.txt....Done
Reading the intensity CCNF patch experts from: bin/model/patch_experts/ccnf_patches_0.25_general.txt....Done
Reading the intensity CCNF patch experts from: bin/model/patch_experts/ccnf_patches_0.35_general.txt....Done
Reading the intensity CCNF patch experts from: bin/model/patch_experts/ccnf_patches_0.5_general.txt....Done
Reading part based module....inner
Reading the CLNF landmark detector/tracker from: bin/model/model_inner/main_clnf_inner.txt
Reading the landmark detector module from: bin/model/model_inner/clnf_inner.txt
Reading the PDM module from: bin/model/model_inner/pdms/pdm_51_inner.txt....Done
Reading the intensity CCNF patch experts from: bin/model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
Done
Reading part based module....left_eye_28
Reading the CLNF landmark detector/tracker from: bin/model/model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: bin/model/model_eye/clnf_left_synth.txt
Reading the PDM module from: bin/model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: bin/model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: bin/model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading part based module....right_eye_28
Reading the CLNF landmark detector/tracker from: bin/model/model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: bin/model/model_eye/clnf_right_synth.txt
Reading the PDM module from: bin/model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: bin/model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: bin/model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading the landmark validation module....Done
Model loaded
```

I even tried the matlab script matlab matlab_runners/Demos/gaze_extraction_demo_vid.m, but didn't work giving me the following error:

```
Error using dlmread (line 122)
The file './output_features_vid/2015-10-15-15-14_gaze.txt' could not be opened because: No such file
or directory

Error in gaze_extraction_demo_vid (line 40)
gaze  = dlmread([filename, '_gaze.txt'], ',', 1, 0); 
```
Am I missing something here?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

Can you try providing the full path after the `-of` command? Does the image appear with tracked landmarks or the detected face? If there is no face (or face is not detected) no output file will be created. You can also try running the `FeatureExtraction` binary, as that will always create an output file.

You are running the code on the unix platform? The matlab demos currently work only on windows (you would need to modify the code for them to work on macs or linux).

**Comment by monajalal** [comment]
This worked for me (give absolute path of both input and output):
`root@1f969349fd06:/opt/OpenFace/build/bin# ./FaceLandmarkImg -aus_static -f /opt/OpenFace/build/bin/angry1.jpg -of /opt/OpenFace/build/bin/output.txt`

**Comment by elahia** [comment]
@monajalal  Hello dear mona,
 I want to start the code in Matlab, so what should be the first .m file that I have to execute!
Already I ran it in visual studio it was fine and the recorder recorded my face by connecting to webcam
but in Matlab when I run "run_demo_videos.m" (and other run_demo files)  some demos start to run and not my webcam!
would you please help me to get my own video!

Cheers
Elahe

**Comment by TadasBaltrusaitis** [comment]
The best place to start on running the code in Matlab is from:
`matlab_version\demo`

Specifically have a look at - `face_video_demo.m` this will run landmark detection on videos.
