### ISSUE TITLE
best quality options

### ISSUE THREAD

**Issue by lulu1315** [TadasBaltrusaitis/OpenFace#112]
hello.
I'm using sequences of png images extracted from a video clip.I'm not looking for speed or realtime analysis but aiming for the best quality/accuracy detection.
so far I'm using FeatureExtraction , with -f ima.\%04d.png as an input and the following options : 
-asvid
-wild
-multi-view 1
-q
I'v been playing with -au_static on or off to see the difference

two questions : 
-is this the best way to go ?
-what exactly is multiview doing?
thanks in advance
luc

**Comment by TadasBaltrusaitis** [comment]
Hi Luc,

If you are using `-asvid` then `-wild` and `-multi-view 1` will not have any effect, those flags are intended for individual image analysis.

With regards to `-au_static`, the results will be better with this flag set if the videos are really short or do not contain changing expressions. For example if a video is shorter than a couple of seconds or if the person is always keeping the same expression (e.g. smiling) I would recommend using `-au_static`. However, if the videos are a couple of minutes long and there is a large range of expressions I would not use `-au_static`, for anything in between you would need to experiment yourself.

The purpose of `multi-view` is to help landmark detection in cases of where the image is not frontal, it evaluates several hypotheses of orientation and picks the best detected one.

Thanks,
Tadas

**Comment by lulu1315** [comment]
thanks a lot for these clarifications....and happy new year :)
luc
