### ISSUE TITLE
Problem while Installing OpenFace in Ubuntu 14.04

### ISSUE THREAD

**Issue by hrushikesht** [TadasBaltrusaitis/OpenFace#114]
After the final `make` command, I get the following error.

`In file included from /home/deithart/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:59:0:
/home/deithart/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:8:31: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include <opencv2/imgproc.hpp>
                               ^
compilation terminated.
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
make: *** [all] Error 2`

Help needed.

**Comment by IvyGongoogle** [comment]
@hrushikesht  I have the same problem? how do solve it?
