### ISSUE TITLE
Problems install OpenFace in Ubuntu 14.04

### ISSUE THREAD

**Issue by hrushikesht** [TadasBaltrusaitis/OpenFace#115]
I did the final `make` in the openface installation. I got the following error.
I have successfully installed opencv3.

`[ 95%] Building CXX object exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o
Linking CXX executable ../../bin/FaceLandmarkImg
CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o: In function `cv::String::String(std::string const&)':
FaceLandmarkImg.cpp:(.text._ZN2cv6StringC2ERKSs[_ZN2cv6StringC5ERKSs]+0x34): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o: In function `main':
FaceLandmarkImg.cpp:(.text.startup+0x390): undefined reference to `cv::CascadeClassifier::CascadeClassifier(cv::String const&)'
FaceLandmarkImg.cpp:(.text.startup+0x39d): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x6ea): undefined reference to `cv::imread(cv::String const&, int)'
FaceLandmarkImg.cpp:(.text.startup+0x6fa): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0xf7f): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
FaceLandmarkImg.cpp:(.text.startup+0xf8e): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x1080): undefined reference to `cv::imread(cv::String const&, int)'
FaceLandmarkImg.cpp:(.text.startup+0x108d): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x2654): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
FaceLandmarkImg.cpp:(.text.startup+0x265e): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x2905): undefined reference to `cv::String::allocate(unsigned long)'
FaceLandmarkImg.cpp:(.text.startup+0x2927): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
FaceLandmarkImg.cpp:(.text.startup+0x292f): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x2a29): undefined reference to `cv::String::allocate(unsigned long)'
FaceLandmarkImg.cpp:(.text.startup+0x2ac2): undefined reference to `cv::String::allocate(unsigned long)'
FaceLandmarkImg.cpp:(.text.startup+0x2adc): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
FaceLandmarkImg.cpp:(.text.startup+0x2ae4): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x307e): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x309e): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x3461): undefined reference to `cv::String::deallocate()'
FaceLandmarkImg.cpp:(.text.startup+0x36ff): undefined reference to `cv::String::deallocate()'
CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o:FaceLandmarkImg.cpp:(.text.startup+0x3727): more undefined references to `cv::String::deallocate()' follow
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `cv::Mat::Mat<double, 2, 2>(cv::Matx<double, 2, 2> const&, bool) [clone .constprop.1188]':
LandmarkDetectorModel.cpp:(.text+0x1dc): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorModel.cpp:(.text+0x21f): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
LandmarkDetectorModel.cpp:(.text+0x227): undefined reference to `cv::String::deallocate()'
LandmarkDetectorModel.cpp:(.text+0x25a): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `cv::Mat::Mat<float, 2, 2>(cv::Matx<float, 2, 2> const&, bool) [clone .constprop.1189]':
LandmarkDetectorModel.cpp:(.text+0x3cc): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorModel.cpp:(.text+0x40f): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
LandmarkDetectorModel.cpp:(.text+0x417): undefined reference to `cv::String::deallocate()'
LandmarkDetectorModel.cpp:(.text+0x44a): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `LandmarkDetector::CLNF::NU_RLMS(cv::Vec<double, 6>&, cv::Mat_<double>&, std::vector<cv::Mat_<float>, std::allocator<cv::Mat_<float> > > const&, cv::Vec<double, 6> const&, cv::Mat_<double> const&, cv::Mat_<double> const&, cv::Matx<double, 2, 2> const&, cv::Matx<float, 2, 2> const&, int, int, bool, int, cv::Mat_<double>&, LandmarkDetector::FaceModelParameters const&)':
LandmarkDetectorModel.cpp:(.text+0x4f27): undefined reference to `cv::Mat::diag(cv::Mat const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `LandmarkDetector::CLNF::NU_RLMS(cv::Vec<double, 6>&, cv::Mat_<double>&, std::vector<cv::Mat_<float>, std::allocator<cv::Mat_<float> > > const&, cv::Vec<double, 6> const&, cv::Mat_<double> const&, cv::Mat_<double> const&, cv::Matx<double, 2, 2> const&, cv::Matx<float, 2, 2> const&, int, int, bool, int, cv::Mat_<double>&, LandmarkDetector::FaceModelParameters const&) [clone .constprop.1187]':
LandmarkDetectorModel.cpp:(.text+0x7a01): undefined reference to `cv::Mat::diag(cv::Mat const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `LandmarkDetector::CLNF::CLNF(LandmarkDetector::CLNF const&)':
LandmarkDetectorModel.cpp:(.text+0xc94f): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorModel.cpp:(.text+0xc96f): undefined reference to `cv::CascadeClassifier::load(cv::String const&)'
LandmarkDetectorModel.cpp:(.text+0xc97c): undefined reference to `cv::String::deallocate()'
LandmarkDetectorModel.cpp:(.text+0xd442): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `LandmarkDetector::CLNF::operator=(LandmarkDetector::CLNF const&)':
LandmarkDetectorModel.cpp:(.text+0xdfbf): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorModel.cpp:(.text+0xdfdd): undefined reference to `cv::CascadeClassifier::load(cv::String const&)'
LandmarkDetectorModel.cpp:(.text+0xdfe5): undefined reference to `cv::String::deallocate()'
LandmarkDetectorModel.cpp:(.text+0xe00c): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorModel.cpp.o): In function `cv::String::String(char const*)':
LandmarkDetectorModel.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x30): undefined reference to `cv::String::allocate(unsigned long)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `cv::Mat::Mat(int, int, int, void*, unsigned long) [clone .constprop.778]':
LandmarkDetectorUtils.cpp:(.text+0xc1a): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorUtils.cpp:(.text+0xc67): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
LandmarkDetectorUtils.cpp:(.text+0xc6f): undefined reference to `cv::String::deallocate()'
LandmarkDetectorUtils.cpp:(.text+0xc97): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DrawBox(std::vector<std::pair<cv::Point_<int>, cv::Point_<int> >, std::allocator<std::pair<cv::Point_<int>, cv::Point_<int> > > >, cv::Mat, cv::Scalar_<double>, int)':
LandmarkDetectorUtils.cpp:(.text+0x2382): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::Draw(cv::Mat, cv::Mat_<double> const&, cv::Mat_<int> const&)':
LandmarkDetectorUtils.cpp:(.text+0x2600): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
LandmarkDetectorUtils.cpp:(.text+0x268f): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
LandmarkDetectorUtils.cpp:(.text+0x2985): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
LandmarkDetectorUtils.cpp:(.text+0x2bc0): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::Draw(cv::Mat, cv::Mat_<double> const&)':
LandmarkDetectorUtils.cpp:(.text+0x2eb3): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
LandmarkDetectorUtils.cpp:(.text+0x2f33): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DrawLandmarks(cv::Mat, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > >)':
LandmarkDetectorUtils.cpp:(.text+0x3486): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
LandmarkDetectorUtils.cpp:(.text+0x3507): undefined reference to `cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFaces(std::vector<cv::Rect_<double>, std::allocator<cv::Rect_<double> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&)':
LandmarkDetectorUtils.cpp:(.text+0x7d1c): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFaces(std::vector<cv::Rect_<double>, std::allocator<cv::Rect_<double> > >&, cv::Mat_<unsigned char> const&)':
LandmarkDetectorUtils.cpp:(.text+0x81f9): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorUtils.cpp:(.text+0x8256): undefined reference to `cv::CascadeClassifier::CascadeClassifier(cv::String const&)'
LandmarkDetectorUtils.cpp:(.text+0x8260): undefined reference to `cv::String::deallocate()'
LandmarkDetectorUtils.cpp:(.text+0x8329): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DrawBox(cv::Mat, cv::Vec<double, 6>, cv::Scalar_<double>, int, float, float, float, float)':
LandmarkDetectorUtils.cpp:(.text+0x9feb): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::matchTemplate_m(cv::Mat_<float> const&, cv::Mat_<double>&, cv::Mat&, cv::Mat&, cv::Mat_<float> const&, std::map<int, cv::Mat_<double>, std::less<int>, std::allocator<std::pair<int const, cv::Mat_<double> > > >&, cv::Mat_<float>&, int)':
LandmarkDetectorUtils.cpp:(.text+0xd790): undefined reference to `cv::integral(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFacesHOG(std::vector<cv::Rect_<double>, std::allocator<cv::Rect_<double> > >&, cv::Mat_<unsigned char> const&, dlib::object_detector<dlib::scan_fhog_pyramid<dlib::pyramid_down<6u>, dlib::default_fhog_feature_extractor> >&, std::vector<double, std::allocator<double> >&)':
LandmarkDetectorUtils.cpp:(.text+0x101a9): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(Patch_experts.cpp.o): In function `LandmarkDetector::Patch_experts::Response(std::vector<cv::Mat_<float>, std::allocator<cv::Mat_<float> > >&, cv::Matx<float, 2, 2>&, cv::Matx<double, 2, 2>&, cv::Mat_<unsigned char> const&, cv::Mat_<float> const&, LandmarkDetector::PDM const&, cv::Vec<double, 6> const&, cv::Mat_<double> const&, int, int)::{lambda(int)#1}::operator()(int) const':
Patch_experts.cpp:(.text+0xb96): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
Patch_experts.cpp:(.text+0x11a7): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
Patch_experts.cpp:(.text+0x11b8): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(Patch_experts.cpp.o): In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x16d): undefined reference to `cv::String::allocate(unsigned long)'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x1c7): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x1cf): undefined reference to `cv::String::deallocate()'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x1fd): undefined reference to `cv::String::allocate(unsigned long)'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x24a): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x252): undefined reference to `cv::String::deallocate()'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x269): undefined reference to `cv::String::deallocate()'
Patch_experts.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x27c): undefined reference to `cv::String::deallocate()'
../../lib/local/FaceAnalyser/libFaceAnalyser.a(FaceAnalyser.cpp.o): In function `cv::Mat::Mat(int, int, int, void*, unsigned long) [clone .constprop.454]':
FaceAnalyser.cpp:(.text+0x112): undefined reference to `cv::String::allocate(unsigned long)'
FaceAnalyser.cpp:(.text+0x15f): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
FaceAnalyser.cpp:(.text+0x167): undefined reference to `cv::String::deallocate()'
FaceAnalyser.cpp:(.text+0x18c): undefined reference to `cv::String::deallocate()'
../../lib/local/FaceAnalyser/libFaceAnalyser.a(FaceAnalyser.cpp.o): In function `FaceAnalysis::FaceAnalyser::ExtractCurrentMedians(std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<cv::Vec<double, 3>, std::allocator<cv::Vec<double, 3> > >&)':
FaceAnalyser.cpp:(.text+0x3d2e): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
FaceAnalyser.cpp:(.text+0x3d38): undefined reference to `cv::String::deallocate()'
FaceAnalyser.cpp:(.text+0x3d8c): undefined reference to `cv::String::deallocate()'
../../lib/local/FaceAnalyser/libFaceAnalyser.a(Face_utils.cpp.o): In function `FaceAnalysis::Extract_FHOG_descriptor(cv::Mat_<double>&, cv::Mat const&, int&, int&, int)':
Face_utils.cpp:(.text+0x6186): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
Face_utils.cpp:(.text+0x6806): undefined reference to `_IplImage::_IplImage(cv::Mat const&)'
../../lib/local/FaceAnalyser/libFaceAnalyser.a(Face_utils.cpp.o): In function `FaceAnalysis::Visualise_FHOG(cv::Mat_<double> const&, int, int, cv::Mat&)':
Face_utils.cpp:(.text+0x75ef): undefined reference to `cv::String::allocate(unsigned long)'
Face_utils.cpp:(.text+0x763e): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
Face_utils.cpp:(.text+0x7648): undefined reference to `cv::String::deallocate()'
Face_utils.cpp:(.text+0x76a7): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorFunc.cpp.o): In function `CorrectGlobalParametersVideo(cv::Mat_<unsigned char> const&, LandmarkDetector::CLNF&, LandmarkDetector::FaceModelParameters const&)':
LandmarkDetectorFunc.cpp:(.text+0x44f4): undefined reference to `cv::matchTemplate(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, int, cv::_InputArray const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorFunc.cpp.o): In function `LandmarkDetector::DetectLandmarksInVideo(cv::Mat_<unsigned char> const&, cv::Mat_<float> const&, LandmarkDetector::CLNF&, LandmarkDetector::FaceModelParameters&)':
LandmarkDetectorFunc.cpp:(.text+0x627a): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorFunc.cpp:(.text+0x629c): undefined reference to `cv::CascadeClassifier::load(cv::String const&)'
LandmarkDetectorFunc.cpp:(.text+0x62a6): undefined reference to `cv::String::deallocate()'
LandmarkDetectorFunc.cpp:(.text+0x7145): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorFunc.cpp.o): In function `LandmarkDetector::DetectLandmarksInImage(cv::Mat_<unsigned char> const&, cv::Mat_<float>, LandmarkDetector::CLNF&, LandmarkDetector::FaceModelParameters&)':
LandmarkDetectorFunc.cpp:(.text+0xa8a8): undefined reference to `cv::CascadeClassifier::load(cv::String const&)'
LandmarkDetectorFunc.cpp:(.text+0xa8b0): undefined reference to `cv::String::deallocate()'
LandmarkDetectorFunc.cpp:(.text+0xa951): undefined reference to `cv::String::allocate(unsigned long)'
LandmarkDetectorFunc.cpp:(.text+0xa9ba): undefined reference to `cv::String::deallocate()'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(PDM.cpp.o): In function `LandmarkDetector::PDM::CalcParams(cv::Vec<double, 6>&, cv::Mat_<double> const&, cv::Mat_<double> const&, cv::Vec<double, 3>)':
PDM.cpp:(.text+0x68b6): undefined reference to `cv::Mat::diag(cv::Mat const&)'
../../lib/local/FaceAnalyser/libFaceAnalyser.a(GazeEstimation.cpp.o): In function `FaceAnalysis::EstimateGaze(LandmarkDetector::CLNF const&, cv::Point3_<float>&, float, float, float, float, bool)':
GazeEstimation.cpp:(.text+0x2e1b): undefined reference to `cv::String::allocate(unsigned long)'
GazeEstimation.cpp:(.text+0x2ed6): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
GazeEstimation.cpp:(.text+0x2ee3): undefined reference to `cv::String::deallocate()'
GazeEstimation.cpp:(.text+0x47e0): undefined reference to `cv::String::deallocate()'
../../lib/local/FaceAnalyser/libFaceAnalyser.a(GazeEstimation.cpp.o): In function `FaceAnalysis::DrawGaze(cv::Mat, LandmarkDetector::CLNF const&, cv::Point3_<float>, cv::Point3_<float>, float, float, float, float)':
GazeEstimation.cpp:(.text+0x6092): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
GazeEstimation.cpp:(.text+0x6697): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/FaceLandmarkImg] Error 1
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
make: *** [all] Error 2`

**Comment by TadasBaltrusaitis** [comment]
It seems like it's an issue with linking to OpenCV, make sure it is installed correctly. Might be worth looking at similar issues:
https://github.com/TadasBaltrusaitis/OpenFace/issues/110
https://github.com/TadasBaltrusaitis/OpenFace/issues/101

Thanks,
Tadas
