### ISSUE TITLE
can i used it by C#?

### ISSUE THREAD

**Issue by leehavin** [TadasBaltrusaitis/OpenFace#117]
can i used it by C#?
What time can provide C # version？
thanks

**Comment by TadasBaltrusaitis** [comment]
The C# version is coming out very soon, I am doing some final testing of it at the moment.

**Comment by t4taurus** [comment]
I really respect you sir for your nice work.We are waiting for C# version.

**Comment by TheBoJaN** [comment]
Any updates on a C# port?

**Comment by TadasBaltrusaitis** [comment]
Not yet, for a Work in progress version see - https://github.com/TadasBaltrusaitis/OpenFace/tree/Windows-GUI

**Comment by NumesSanguis** [comment]
With a C# version, would it be possible to use it in a game-engine like Unity?

**Comment by Luchianno** [comment]
+1 Guy waiting for C# version! Great library by the way. It would be awesome to have a C# wrapper.

**Comment by foxhard** [comment]
Nice library, I'm waiting for C# version too.

**Comment by Cloudmersive** [comment]
Any progress on this?

**Comment by Arwwarrr** [comment]
yea any progress?

**Comment by TadasBaltrusaitis** [comment]
Yes, you can use C# with OpenFace,, for example of how to use it, see `OpenFaceDemo` and `OpenFaceOffline` projects. There is no documentation as such, but those projects show how to use all the needed functionality for using OpenFace libraries in C#.

You can also have a look at the following wrapper - https://github.com/Kawaian/SharpFace
