### ISSUE TITLE
Ubuntu 16.10 needs updated FindTBB.cmake

### ISSUE THREAD

**Issue by grabya** [TadasBaltrusaitis/OpenFace#118]
can be found here: https://raw.githubusercontent.com/justusc/FindTBB/master/FindTBB.cmake

**Comment by TadasBaltrusaitis** [comment]
Thanks!

**Comment by Arash1234** [comment]
Does OpenFace work with TBB version 4.4 or 2017 ?

**Comment by TadasBaltrusaitis** [comment]
The version I have tested with is 4.4
