### ISSUE TITLE
runtime for FeatureExtraction?

### ISSUE THREAD

**Issue by yuxunhe** [TadasBaltrusaitis/OpenFace#119]
Hello!
I was running FeatureExtraction with the options -no2Dfp -no3Dfp -noMparams -noPose -noGaze on a 30-second mp4-format video clip and the program ran for approximately 10 minutes. It is supposed to run that long? Is there something I might be doing wrong? Is there any way that I can make it run faster? Thank you!

**Comment by TadasBaltrusaitis** [comment]
I should take roughly 30 seconds for 30 second video (plus loading the model which could take 5-10 seconds). Are you sure you are using Release mode version rather than the Debug one, as the Debug executable is much slower.

**Comment by yuxunhe** [comment]
I think I'm using release mode... is there a way to check?

**Comment by yuxunhe** [comment]
I re-built it under release mode just in case, and it's still running for a long time. Does it have anything to do with the video format I'm using? I'm feeding it mp4 videos, because it doesn't seem to be extracting data from avi videos

**Comment by TadasBaltrusaitis** [comment]
It shouldn't be the issue with mp4 videos, unless the resolution is extremely high. Which exacutable are you using? You need to make sure it is in the `x64\Release\FeatureExtraction.exe` or `Release\FeatureExtraction.exe` rather than the `Debug` equivalents. Also see the following note - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation#release-mode

**Comment by yuxunhe** [comment]
I'm running the program on Mac - could that be a problem?

**Comment by TadasBaltrusaitis** [comment]
That is really strange, it should be running fast in Mac as well, the only idea I had was the Release vs Debug mode by running:
    cmake -D CMAKE_BUILD_TYPE=RELEASE .
    make

Does it run faster on other types of videos? What is the running speed from a webcam using `FaceLandmarkVid` executable?

**Comment by yuxunhe** [comment]
I believe that's how I built it. The FaceLandmarkVid executable doesn't have the lag...
I built OpenFace on a windows computer and it ran just fine. Maybe it's some compatibility issues with Mac?

**Comment by TadasBaltrusaitis** [comment]
That is really strange, it might be something to do with video decoding, can you try converting the files to some other format before processing them? Especially as FaceLandmarkVid seems to run quite fast. Another possible option is the actual writing of the data is slow to disk? It's hard to tell without profiling the code.

**Comment by yuxunhe** [comment]
Yeah… Also the avi files that come with the OpenFace package just can’t be analyzed at all. Like the program still runs without a problem but the output has no data in it.

**Comment by TadasBaltrusaitis** [comment]
Using which executable? `FaceLandmarkVid` does not provide any output, just visualizes the tracking.

**Comment by yuxunhe** [comment]
FeatureExtraction.

**Comment by TadasBaltrusaitis** [comment]
That is really strange, it might be an issue with the video codec, can you open and play those video files? One way to test it is to write a very basic video reading and playing C++ OpenCV script. As I do not have access to a mac I am not able to easily help with debugging this issue.

**Comment by Joker316701882** [comment]
I'm a green hand here.
And when I'm trying to running FeatureExtraction, it always shows that 'failed to open vedio source'.
I'm using Win10, and run command line like this:
'FeatureExtraction -f ../vedios/0188_03_021_al_pacino'
BTW, the original version provide run-time AU-predition, but the latest version seems can't predict AU through webcam. Do I have to change some codes in FeatureExtraction.cpp?

**Comment by TadasBaltrusaitis** [comment]
It might be the misspelling? It should be `-f ../videos/0188_03_021_al_pacino` or `-f ../../videos/0188_03_021_al_pacino` depending on where your executable is.

**Comment by Joker316701882** [comment]
Thank you for your reply. It finally works. Seems that the latest version doesn't provide visualization on AU prediction...I really love v0.1 OpenFace.exe. 
This whole OpenFace system is fantastic anyway.
