### ISSUE TITLE
Gaze Estimation in Rendering of Eyes for Eye-Shape Registration and Gaze Estimation

### ISSUE THREAD

**Issue by karanahujax** [TadasBaltrusaitis/OpenFace#12]
Is this code the same code used in the paper "Rendering of Eyes for Eye-Shape Registration and Gaze Estimation" for testing on the Max Planck Database? If not, what changes were made. 

Also why is offset taken as (0,-3.5,0) in GazeEstimation.cpp? I.e. why this particular value and should it not be along the Z-direction?

**Comment by TadasBaltrusaitis** [comment]
The code for eye region landmark registration is the same, but for gaze estimation on Max Planck Database we used a CNN based approach which is not included in OpenFace.

With regards to the -3.5 value we found that the approach we used was slightly biased and adding the constant lead to slightly better results.
