### ISSUE TITLE
Face Recognition on Multi face detection

### ISSUE THREAD

**Issue by Muscio-1605187** [TadasBaltrusaitis/OpenFace#121]
Hello Tadas,
I'm running the FaceLandmarkVidMulti project and I would to apply a face recognition to the detected faces. About this I have a question:
Is vector<cv::Rect_<double>> face_detections the one that contains the face detected with the landmark already appied to them; there is another data structure that does not contains the landmarks? Because the pink landmarks don't allow to make a good recognition. I tried to display the face detected and they are al with the landmarks.
Thank you in advance for your attention.
Regards,
Mario

**Comment by TadasBaltrusaitis** [comment]
Hi Mario,

The `vector<cv::Rect> face_detections` contains face bounding boxes and not the detected facial landmarks. The detected landmarks can be found in `clnf_models` variable and to see how they can be accessed see the `Draw` function in line 394. 

Thanks,
Tadas
