### ISSUE TITLE
How to do in my CMake project so as to find the compiled OpenFace library?

### ISSUE THREAD

**Issue by wguo68** [TadasBaltrusaitis/OpenFace#123]
I am using cmake to generate VS project. How to edit my CMakeLists.txt to find the OpenFace package?

**Comment by TadasBaltrusaitis** [comment]
I did not test cmake with VisualStudio, but there is already a  `.sln` file which you can open with Visual Studio 2015 without the need for cmake.

**Comment by What-a-stupid-username** [comment]
I have this issue too.
I'm trying to use find_package(OpenFace) in cmake by setting the path of OpenFace to "./build/OpenFace" or "./build/lib/cmake/OpenFace". These two paths both have an "OpenFaceConfig.cmake" file in it, but none of them can work correctly.
Can anyone give some help???

Here is the cmake error output:

"./build/lib/cmake/OpenFace":
`Boost version: 1.58.0
A library with BLAS API found.
Searching for TBB in: /usr/include
CMake Warning at /usr/local/lib/cmake/dlib/dlibConfig.cmake:42 (message):
  The variable 'dlib_INCLUDE_DIRS' is deprecated! Instead, simply use
  target_link_libraries(your_app dlib::dlib).  See
  http://dlib.net/examples/CMakeLists.txt.html for an example.
Call Stack (most recent call first):
  OpenFace/build/lib/cmake/OpenFace/OpenFaceConfig.cmake:9999 (__deprecated_var)
  CMakeLists.txt:7 (find_package)


CMake Error at OpenFace/build/lib/cmake/OpenFace/OpenFaceConfig.cmake:12 (message):
  File or directory
  /home/hjk/Desktop/test/OpenFace/build/../lib/local/GazeAnalyser/include;../lib/local/FaceAnalyser/include;../lib/local/LandmarkDetector/include;../lib/local/Utilities/include;


                              /usr/local/include;/usr/include;/usr/include;
                              /usr/include;
                              /usr/include/boost; referenced by variable OpenFace_INCLUDE_DIRS does not exist !
Call Stack (most recent call first):
  OpenFace/build/lib/cmake/OpenFace/OpenFaceConfig.cmake:38 (set_and_check)
  CMakeLists.txt:7 (find_package)



"./build/OpenFace":
Configuring incomplete, errors occurred!`
`Boost version: 1.58.0
A library with BLAS API found.
Searching for TBB in: /usr/include
CMake Error at OpenFace/build/OpenFace/OpenFaceConfig.cmake:36 (include):
  include could not find load file:

    /home/hjk/Desktop/test/OpenFace/build/OpenFace/OpenFaceTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Warning at /usr/local/lib/cmake/dlib/dlibConfig.cmake:42 (message):
  The variable 'dlib_INCLUDE_DIRS' is deprecated! Instead, simply use
  target_link_libraries(your_app dlib::dlib).  See
  http://dlib.net/examples/CMakeLists.txt.html for an example.
Call Stack (most recent call first):
  OpenFace/build/OpenFace/OpenFaceConfig.cmake:9999 (__deprecated_var)
  CMakeLists.txt:7 (find_package)


CMake Error at OpenFace/build/OpenFace/OpenFaceConfig.cmake:12 (message):
  File or directory /home/hjk/Desktop/test/include/OpenFace;

                              /usr/local/include;/usr/include;/usr/include;
                              /usr/include;
                              /usr/include/boost; referenced by variable OpenFace_INCLUDE_DIRS does not exist !
Call Stack (most recent call first):
  OpenFace/build/OpenFace/OpenFaceConfig.cmake:38 (set_and_check)
  CMakeLists.txt:7 (find_package)


Configuring incomplete, errors occurred!`

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue persists.
