### ISSUE TITLE
Face Recognition on Multiple IP Cameras

### ISSUE THREAD

**Issue by vdaneshmand** [TadasBaltrusaitis/OpenFace#126]
Hi;

I was wondering if there is any way I can run the application to do face recognition on multiple IP cameras. I'd be thankful if anyone can help me.

Thanks,
Vahid

**Comment by TadasBaltrusaitis** [comment]
Hi,

This package does not do face recognition, but rather facial behaviour analysis. Face recognition is performed by the other OpenFace - https://github.com/cmusatyalab/openface

Thanks,
Tadas

**Comment by vdaneshmand** [comment]
Hi Tadas;

You're right. I meant face detection. Does it work with multiple IP cameras?

Thanks again.

Cheers,
Vahid

**Comment by TadasBaltrusaitis** [comment]
It does not support multiple devices, so you would need to adapt the code for that purpose. However, that should not be too difficult. An easy way to do this would be just to run multiple instances of the code with each connecting to a different camera.
