### ISSUE TITLE
Issue with lambdas

### ISSUE THREAD

**Issue by somacoder** [TadasBaltrusaitis/OpenFace#128]
For some reason I am having issues with lambdas when running make at lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/scan_fhog_pyramid.h:515

OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/scan_fhog_pyramid.h:515: error: expected primary-expression before ‘[’ token

There are additional lambdas farther down in scan_fhog_pyramid.h as well.

I am compiling on linux.

**Comment by TadasBaltrusaitis** [comment]
Could it be an issue with you not using C++11 for the code compilation?

Thanks,
Tadas

**Comment by somacoder** [comment]
That was my first thought, but even with setting in the root CMakeLists:
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
I am still getting the error.

Sorry if I am missing something obvious here. Thanks!

**Comment by somacoder** [comment]
Found it. Dumb error. There was an issue with which gcc version cmake was pointing to on the cluster I am on. Sorry and hope you didn't waste time on this.

**Comment by TadasBaltrusaitis** [comment]
No worries, glad you managed to resolve your issue!

**Comment by chrisluu** [comment]
What about the accuracy and speed of OpenFace in landmark detection?Thanks for answer.
