### ISSUE TITLE
Messaging server

### ISSUE THREAD

**Issue by dshahrokhian** [TadasBaltrusaitis/OpenFace#129]
I have seen that the messaging server is still under "coming soon". I am working on a project that requires streaming data being sent over to a front-end. Is there any specific part of the project I could build upon?

**Comment by TadasBaltrusaitis** [comment]
Yes, the streaming server is still under development. You should have a look at the FaceLandmarkVid.cpp executable which extracts the features in real time and visualizes them, you should be able to create a communication protocol there. You should also look at FeatureExtraction.cpp which performs feature extraction from videos and outputs it into files to see how each feature is extracted.

**Comment by dshahrokhian** [comment]
Thank you, Tadas.
