### ISSUE TITLE
What does face_image_demo_eyes.m do?

### ISSUE THREAD

**Issue by hki541** [TadasBaltrusaitis/OpenFace#13]
Hi 
I just downloaded whole file on github (https://github.com/TadasBaltrusaitis/OpenFace) and found that there is a file which is not mentioned in readme.
(located in matlab_version\demo\face_image_demo_eyes.m) 

I found that in this file at line 19, the  first parameter of function Load_Patch_Experts() which should be the file direction is point to the author's c drive and I can not find the file name “svr_patches_*_synth.mat”  in the whole open face folder.Therefore I can not run this file.

I would like to know that if this file can label landmark only on eyes without the whole face. If so, would you release the new version of the code? If not, what would this code do? 

Thanks.

**Comment by TadasBaltrusaitis** [comment]
Hi,

It is left over from a slightly older version of the code. The functionality for this has been moved to the C++ version of the code, what it was supposed to do is track eyes once the facial landmarks have been detected (that is what the hierarchical C++ model does).

For using that model you would still need to have access to facial landmark detection (so the whole face would have to be visible). Unless you use an external eye detector. 

I will try finding the .mat file for the eye model if I still have it.

Thanks,
Tadas

**Comment by TadasBaltrusaitis** [comment]
The newest version of the code can now track more precise eye landmarks in a demo script.
