### ISSUE TITLE
Error finding TBB in Raspberry Pi

### ISSUE THREAD

**Issue by Arash1234** [TadasBaltrusaitis/OpenFace#130]
I'm trying to compile OpenFace in Raspberry Pi and I get the following error. It says it cannot find TBB, but it also says it has found version 4.3. What I'm missing here ?

I also tried version 2017 and I got the same message, It finds it and mentions its version but it cannot continue compiling process. 

> OpenCV information:
>   OpenCV_INCLUDE_DIRS: /usr/local/include/opencv;/usr/local/include
>   OpenCV_LIBRARIES: opencv_videostab;opencv_videoio;opencv_video;opencv_superres;opencv_stitching;opencv_shape;opencv_photo;opencv_objdetect;opencv_ml;opencv_imgproc;opencv_imgcodecs;opencv_highgui;opencv_flann;opencv_features2d;opencv_core;opencv_calib3d
>   OpenCV_LIBRARY_DIRS: 
> -- Boost version: 1.61.0
> -- Found the following Boost libraries:
> --   filesystem
> --   system
> Boost information:
>   Boost_INCLUDE_DIRS: /usr/local/include
>   Boost_LIBRARIES: /usr/local/lib/libboost_filesystem.so;/usr/local/lib/libboost_system.so
>   Boost_LIBRARY_DIRS: /usr/local/lib
> CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>   Could NOT find TBB (missing: TBB_LIBRARY) (found version "4.3")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>   cmake/modules/FindTBB.cmake:291 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:30 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/OpenFace/OpenFace/CMakeFiles/CMakeOutput.log".
> See also "/home/pi/OpenFace/OpenFace/CMakeFiles/CMakeError.log".
> You have changed variables that require your cache to be deleted.
> Configure will be re-run and you may have to reset some variables.
> The following variables have changed:
> CMAKE_CXX_COMPILER= clang++
> 
> -- Generating done
> -- Build files have been written to: /home/pi/OpenFace/OpenFace

**Comment by TadasBaltrusaitis** [comment]
The version I have tested with is TBB 4.4, have a look at this issue as it might be able to find TBB - https://github.com/TadasBaltrusaitis/OpenFace/issues/118

**Comment by Arash1234** [comment]
Ok I Figured it out. You need to change FindTBB.cmake. I'll post it soon. or maybe I'll  request a pull .

**Comment by abhiTronix** [comment]
@Arash1234 https://github.com/abhiTronix/TBB_Raspberry_pi precompiled binaries :)
