### ISSUE TITLE
get face pose of unconstrained image

### ISSUE THREAD

**Issue by alfredtofu** [TadasBaltrusaitis/OpenFace#132]
How to get face pose of unconstrained image if we don't know camera parameters?  In `FeatureExtraction.cpp`, camera parameters will be rough estimated if not given and in consequence it will lead to inaccurate results. Any good ideas to improve it?

**Comment by TadasBaltrusaitis** [comment]
Without knowing the camera it was taken with and it's settings (or having access to the camera) that is very difficult to estimate. If you have access to the camera you could perform camera calibration (http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html?)
