### ISSUE TITLE
Data format for MPII Gaze estimation

### ISSUE THREAD

**Issue by yyxiongzju** [TadasBaltrusaitis/OpenFace#134]
Hi, @TadasBaltrusaitis 

I tried to reproduce the experimental result for MPII Gaze estimation. Since in MPIIGaze dataset, it contains 
Data folder, Annotation Subset folder, and Evaluation Subset. I used the data in Normalized folder of Data folder. It seems in your implementation, you used one Data.mat for each person, like p00. But you used filenames, it is a vector for MPIIGaze dataset. After running extract_mpii_gaze_test.m

 fname = sprintf('%s/%s/%d_%d_%d_%d_%d_%d_%d_det_0.pose', output, p_dirs(p).name,...
             filenames(i,1), filenames(i,2), filenames(i,3), filenames(i,4),...
             filenames(i,5), filenames(i,6), filenames(i,7));
I encountered errors,
Index exceeds matrix dimensions.

Error in extract_mpii_gaze_test (line 68)
             filenames(i,1), filenames(i,2), filenames(i,3), filenames(i,4),...
I was wondering how you make the Data.mat from MPIIGaze dataset for your implementation of gaze estimation?

**Comment by TadasBaltrusaitis** [comment]
Hi,

I used a part of MPII Gaze dataset with full face images and Data.mat files. However, I believe that portion is not publicly available, and only cropped images are available, on which OpenFace will not work.

Thanks,
Tadas
