### ISSUE TITLE
change the size of image output from video  

### ISSUE THREAD

**Issue by helang818** [TadasBaltrusaitis/OpenFace#137]
Dear Tadas,
Recently, I use the CLM-framework （openface） to extract facial features. The CLM（openface） is an important tool, which provide great convenience for our research. However, the size of image which generated by CLM（openface） is 112*112, I try to modify the size, althou can complie successfully, while use to extract image by frame fail. Could you please help to me tackle with the problem?  For example，128*128 or 200*200

Best,

**Comment by helang818** [comment]
Sorry， size is 112*112，miss the *

**Comment by TadasBaltrusaitis** [comment]
Hi,

This is a known bug, I fixed it in the Windows-GUI branch but have not moved it to the master one yet. I am planning on finishing the Windows branch in a month or so and will integrate the fix then.

Thanks,
Tadas

**Comment by helang818** [comment]
Hi,
May be you can tell where to modify, I will compile and debug by myself. Because of using face images to extract other features.
Thanks 
Lang

**Comment by TadasBaltrusaitis** [comment]
The changes should be in `FeatureExtraction.cpp` and `FaceAnalyser.h`/`FaceAnalyser.cpp`, I haven't looked at which lines exactly I changed.

**Comment by helang818** [comment]
Hi，
OK, I have find the line in the program, If you update the bug, please let me know. I will follow you work. 
good luck.
Lang

**Comment by TadasBaltrusaitis** [comment]
The bug should be fixed now.

-Tadas
