### ISSUE TITLE
Gaze tracking does not work anymore

### ISSUE THREAD

**Issue by mlpo** [TadasBaltrusaitis/OpenFace#139]
I pulled from remote repo today, and since the gaze tracking no longer works on example programs (FaceLandmarkVid and FaceLandmarkVidMulti).

Before (commit [7c20913](https://github.com/TadasBaltrusaitis/OpenFace/tree/7c209131ff04d5c08ddf78a1536d67e1d36c6c69)):
![with](https://cloud.githubusercontent.com/assets/1258839/23675048/564bca20-0378-11e7-9172-a361b925e1a4.png)

After (master, commit [a3e6631](https://github.com/TadasBaltrusaitis/OpenFace/tree/a3e66319b51763b6e83b01037b6dd2eb4d7c8a6e)):
![without](https://cloud.githubusercontent.com/assets/1258839/23675063/5c64bdf4-0378-11e7-83be-65ae0ab7bd3b.png)

I tried to look a bit to identify the cause of this problem, and I noticed the following: at [line 144 of FaceLandmarkVid.cpp](https://github.com/TadasBaltrusaitis/OpenFace/blob/master/exe/FaceLandmarkVid/FaceLandmarkVid.cpp#L144), `face_model.eye_model` is equal to 1 in the build that works (commit [7c20913](https://github.com/TadasBaltrusaitis/OpenFace/tree/7c209131ff04d5c08ddf78a1536d67e1d36c6c69)) and equal to 0 in the build that does not work (master). However, I do not know why.

Same computer and same toolchain (gcc 6.3.1, opencv 3.2.0).

**Comment by somacoder** [comment]
I have been using Feature Extraction and Gaze Estimation is not working there either in the latest build. However, this is after compilation on a somewhat finicky CentOS6 build, so I can't say for sure if it the same problem here, as I haven't identified a root cause yet.

**Comment by herozhang** [comment]
I have same problem

**Comment by TadasBaltrusaitis** [comment]
I have fixed the issue in the new master. It should work now. Let me know if you're still having issues.

-Tadas
