### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by DRwenbo** [TadasBaltrusaitis/OpenFace#14]
Hello, I downloaded the entire folder but I have no way to run gaze_extraction_demo_vid.m this file, because I want to learn the direction of line of sight detection algorithm. I come from a high school student in China, please help me to solve this problem.
Error：
Error using dlmread (line 120)
The file '?_gaze.txt' could not be opened because: Invalid argument

Error in gaze_extraction_demo_vid (line 40)
gaze  = dlmread([2015-10-15-15-14, '_gaze.txt'], ',', 1, 0);

**Comment by DRwenbo** [comment]
help  me

**Comment by TadasBaltrusaitis** [comment]
You will need to compile the C++ code in order to run any of the demo scrips. Have you done that?

**Comment by DRwenbo** [comment]
hello,I am come form china! 
should I need to compile C++ code?
I just want to know how the line of sight direction is analyzed in the m file.
Can you tell me how I can do it，
I want to know the process? 
I was a rookie，help me   thank u！

**Comment by TadasBaltrusaitis** [comment]
Please follow the instructions in the wiki:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation or
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

**Comment by DRwenbo** [comment]
.EXE file to stop working When I use matlab to run to strating tracking！
How do I use the file I downloaded?（OpenFace_0.1_command_line）！

**Comment by DRwenbo** [comment]
Unable to start the program LandmarkDetector.lib, when I was compiling with vs2015

**Comment by DRwenbo** [comment]
featureEXtraction.exe stop working!!     orz..........

**Comment by TadasBaltrusaitis** [comment]
When you compile with VisualStudio 2015 and select `FaceLandmarkVid` project as a StartUp one does it work? Have you made sure to compile 64 bit Release version of the code?

**Comment by wguo68** [comment]
crashed to work. I did as this following:
FaceLandmarkImg.exe -f face.jpg -oi out.jpg

**Comment by TadasBaltrusaitis** [comment]
Are you using the downloaded executables or have you compiled them yourself?

**Comment by buweiaini** [comment]
excuse me ,I use  the downloaded executables, and I have installed the   64-bit Visual C++ redistributable package,,,,but when I double click the  *FaceLandmarkImg.exe*or other .exe files in（OpenFace_0.1_command_line）,,,,,,it crash,,,can you help me ,thank you !

**Comment by TadasBaltrusaitis** [comment]
Hi,

I updated the executables now - [https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation#binaries](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation#binaries)

Can you check if they work for you now?

Thanks,
Tadas
