### ISSUE TITLE
why gaze_0_x, gaze_0_y, gaze_0_z output always equle 0 or 1?

### ISSUE THREAD

**Issue by herozhang** [TadasBaltrusaitis/OpenFace#140]
use ./bin/FeatureExtraction on a face-video file,
but I find the output file like this:
frame, timestamp, confidence, success, gaze_0_x, gaze_0_y, gaze_0_z, gaze_1_x, gaze_1_y, gaze_1_z
4,  0.1001,  0.913637,  1,  0,  0,  -1,  0,  0,  -1

if I use ./bin/FaceLandmarkVid on the same video,
I can get gaze coordinate like this:
gaze: dir_x_1, dir_y_1, dir_z_1, dir_x_2, dir_y_2, dir_z_2: 
{
0.289997 0.272289 -0.917475 -0.103108 0.313129 -0.944097
}

Is not my understanding wrong?

I use the master version of openface.

**Comment by TadasBaltrusaitis** [comment]
Hi, there was a bug in the current version of feature extraction. It should be able to extract teh gaze correctly now. Let me know if you're still encounter the issue.
