### ISSUE TITLE
Which part of Multi-PIE database you train the expert models?

### ISSUE THREAD

**Issue by xiaoxiongli** [TadasBaltrusaitis/OpenFace#142]
Dear @TadasBaltrusaitis,

As you know, the Multi-PIE database is huge: about 350G Bytes. 

Which part of Multi-PIE database you are using to train the Patch Experts models?

thank you very much~ ^_^

**Comment by TadasBaltrusaitis** [comment]
I use a subset for which facial landmark annotations are available. You can find the scripts for training patch experts here, they include the extraction of Multi-PIE database training data - https://github.com/TadasBaltrusaitis/CCNF
