### ISSUE TITLE
How to adjust the Bounding Box after face detection using a new face detector?

### ISSUE THREAD

**Issue by xiaoxiongli** [TadasBaltrusaitis/OpenFace#143]
Dear @TadasBaltrusaitis,
	As you know, the OpenFace framework have two type of face detector, one is from dlib(HOG-SVM based), the other is from OpenCV(haar based)	. Right Now, I am using a PICO based face detector because of its faster speed.
       But I encounter a problem that How to adjust the Bounding Box after face detection using this new PICO face detector. I find that in each detector you adjust the Bounding Box detected such like this:
For dlib detector:

		// CLNF expects the bounding box to encompass from eyebrow to chin in y, and from cheeck outline to cheeck outline in x, so we need to compensate
		// The scalings were learned using the Face Detections on LFPW and Helen using ground truth and detections from the HOG detector

		// Move the face slightly to the right (as the width was made smaller)
		o_regions[face].x = (face_detections[face].rect.get_rect().tl_corner().x() + 0.0389 * face_detections[face].rect.get_rect().width())/scaling;
		// Shift face down as OpenCV Haar Cascade detects the forehead as well, and we're not interested
		o_regions[face].y = (face_detections[face].rect.get_rect().tl_corner().y() + 0.1278 * face_detections[face].rect.get_rect().height())/scaling;

		// Correct for scale
		o_regions[face].width = (face_detections[face].rect.get_rect().width() * 0.9611)/scaling; 
		o_regions[face].height = (face_detections[face].rect.get_rect().height() * 0.9388)/scaling;

So, I wonder that How can we Calculate the parameters(such like 0.0389, 0.1278, 0.9611...)?
Is there any code I can get to Do this job^_^?

thank you very much~ ^_^

**Comment by TadasBaltrusaitis** [comment]
Please see this issue - https://github.com/TadasBaltrusaitis/OpenFace/issues/47
