### ISSUE TITLE
Problem parsing certain videos

### ISSUE THREAD

**Issue by dshahrokhian** [TadasBaltrusaitis/OpenFace#144]
I have been facing some issues when trying to parse videos like [this](https://drive.google.com/file/d/0B7DuHbX0-8kyYWNkN2d5dXhrUjQ/view?usp=sharing), executing:

`FaceLandmarkVid -f issue.avi -ov "openface_video.mkv" >> issue.log`

These are the [output video](https://drive.google.com/file/d/0B7DuHbX0-8kyZC0xYnNIakxqZWc/view?usp=sharing) and [what is printed in the terminal](https://drive.google.com/file/d/0B7DuHbX0-8kyRE54dmdTdEROc3M/view?usp=sharing).

Thanks,
Dani

**Comment by TadasBaltrusaitis** [comment]
It seems like the face detection failed, in videos like this, that will be the main bottleneck. I am looking at alternative face detectors for such challenging scenarios. However, it will take some time before they are integrated into OpenFace.

Thanks,
Tadas

**Comment by dshahrokhian** [comment]
Hello @TadasBaltrusaitis 

My main concern is why does it mess-up the length and FPS of the original video? The original video is 3 seconds long 25 FPS, while the output of OpenFace doesn't detect any faces and shortens the video to just two frames. Shouldn't it just output nothing and keep the original frame-rate and length of the video?

Thanks,
Dani

**Comment by TadasBaltrusaitis** [comment]
Hi Dani,

I see what's happening. I ran it myself and have the same problem. It seems like OpenCV is not able to read the video properly and is only able to read 2-3 frames of it. One solution for this is to convert the videos first with a tool like `ffmpeg`. As the video seems to be corrupted in some way (it is not able to "track" on my machine and the number of frames reported is wrong).

Thanks,
Tadas

**Comment by dshahrokhian** [comment]
Thanks for the clarification, Tadas.

**Comment by dshahrokhian** [comment]
Just an update: Using `ffmpeg` to convert the videos to `.mkv` works.

`ffmpeg -i <original video> -vcodec ffv1 -acodec pcm_s16le <output video>`
