### ISSUE TITLE
Installation Script for Ubuntu 16.10

### ISSUE THREAD

**Issue by Andymic** [TadasBaltrusaitis/OpenFace#146]
I have successfully manage to get OpenFace to compile on Ubuntu 16.10 and it would be nice to prevent anyone from going through what I went through. Would you consider adding an installation script to the repo? - I can submit a pull request.

**Comment by TadasBaltrusaitis** [comment]
Sure, an install script for Ubuntu 16.10 would be helpful. 

What particular difficulties did you encounter that were not covered in the wiki?

**Comment by Andymic** [comment]
The wiki covered Ubuntu 14.04 and 15.10 so for 16.10 some of things I had to do were:
- Downgraded G++ and GCC to 4.9 to build: open_cv and compile OpenFace
- There were linker issues caused by libc++...since GCC 5.1 libstdc++ has been used (also introduced a new library ABI)
- Also needed to downgrade clang ++ to 3.7

**Comment by dshahrokhian** [comment]
I made one for myself for my project (tested in 3 different machines). Feel free to use it or add it to the wiki/repo @TadasBaltrusaitis

[Installation [Ubuntu 16.04 LTE]](https://github.com/dshahrokhian/DeepMotion/blob/master/install.sh)

**Comment by TadasBaltrusaitis** [comment]
Thanks for the pointers, why was it necessary to downgrade G++, GCC and clang?

**Comment by Andymic** [comment]
As of GCC 5 a new ABI was introduced that provided a new implementation for std::string and std::list (to comply with c++ 11 standards) therefore it may introduce incompatibility issues when linking against libraries that were compiled with older versions of GCC. 

There is a way around this that could nullify the need to downgrade GCC. Newer versions of the compiler support both older and new ABI therefore in the cmake arguments we can specify which one to use and see if it'll compile.

**Comment by TadasBaltrusaitis** [comment]
The installation instructions have been updated, let me know if the issue still persists though
