### ISSUE TITLE
FeatureExtraction on all images in a directory using fdir

### ISSUE THREAD

**Issue by smadha** [TadasBaltrusaitis/OpenFace#149]
Hi - Thanks again for this fantastic project. Can you please help me relate output features with input directory of images.

I am able to generate output CVS using `-fdir` option in below fashion. I get a file with `n` rows for `n` images but I am not sure how to relate a row to an image.
```
 bin/FeatureExtraction -fdir ./imgs/ -of ./imgs/feat.csv -q -au_static
```

I am unable to generate individual files as per below description.
>-fdir <directory> run the feature extraction on every image (.jpg and .png) in a directory (the output will be stored in individual files for the whole directory)

I have tried below commands too, but I was unable to achieve individual output.
```
 bin/FeatureExtraction -fdir ./imgs/ -ofdir ./imgs/ -q -au_static
```
```
 bin/FeatureExtraction -fdir ./imgs/  -q -au_static
```

Thanks a lot for your help

**Comment by TadasBaltrusaitis** [comment]
Hi,

Thanks for bringing this up, I did not consider the fact that there will be an ambiguity of mapping the row with the image. At the moment it uses the ordering that boosts directory iterator provides, which I believe might be platform dependent, but is most likely ordered alphanumerically. One way to verify this is by actually drawing the landmarks and seeing if they match the image. 

I will add an additional column in the filename for the next version of OpenFace.

To get an individual output per image you can use `FaceLandmarkImg` as it provides most of the functionality provided by `FeatureExtraction`, but with a different output.

Thanks,
Tadas

**Comment by TadasBaltrusaitis** [comment]
You can now use FaceLandmarkImg for resolving this ambiguity, the functionality of `FaceLandmarkImg` and `FeatureExtraction` are equivalent.
