### ISSUE TITLE
FaceLandmarkVid.exe: 0xC000001D: Illegal Instruction

### ISSUE THREAD

**Issue by beraldofilippo** [TadasBaltrusaitis/OpenFace#15]
Hi, I'm getting this strange exception when deploying FaceLandmarkVid using Release x64 configuration on VS2015 Enterprise. It takes me to line 649 of interpolation.h ad precisely to `const double x_scale = (in_img.nc()-1)/(double)std::max<long>((out_img.nc()-1),1);`

Really strange behavior since using Release configuration with Win32 is OK (though not reaching the same FPS as it does on the same machine with linux: Win goes around 20fps and Linux goes around 30fps - I know that the docs says it's worth running in x64 for better performance...) >> Makes me think there's something with 64bit addressing and so on...

Trying to change SDK to UWP (Windows 10 SDK) does not solve the problem.

Anyone experiencing the same issues?

**Comment by TadasBaltrusaitis** [comment]
Hi,

The reason for the error might be due to the instruction set the compiler is instructed to use. What version of the code are you using? I changed it a couple of days ago to use AVX instead of AVX2 which should have resolved the 64bit issue on older machines.

Thanks,
Tadas

**Comment by beraldofilippo** [comment]
I've just updated the code to your last commit, it seems to solve the issue.
Thank you!
