### ISSUE TITLE
How to get gaze-point coordinates on the screen where i look 

### ISSUE THREAD

**Issue by Lewandowski09** [TadasBaltrusaitis/OpenFace#151]
Hello,Tadas!
You have done a very nice work,thank you so much!

Now,we have obtained the direction of each eye,we also want to know where the gaze-direction locate on  screen?The screen only show the real-time video now,how can i make it as one part of the gaze-system?
If we can find the gaze-point on the screen,maybe we can do some operation.

**Comment by TadasBaltrusaitis** [comment]
There is no such functionality in OpenFace currently: https://github.com/TadasBaltrusaitis/OpenFace/issues/24

Thanks,
Tadas
