### ISSUE TITLE
Why the DFT's size should be max(M, N),  not M+N-1?

### ISSUE THREAD

**Issue by xiaoxiongli** [TadasBaltrusaitis/OpenFace#153]
Dear Tadas:
        I feel confuse that when we calculate the normalized cross-correlation, why we set the DFT input size to max(M, N), not M+N-1?
        
for example,  in the openface code template size = 11, window size = 9,  so the searching window  interest_area = (11+9-1)=19.  then we get M = 19(image), N=11(template). then here dft function's input size is max(M,N)=19 (actually padding to 20 for faster calculate)

        dft(dst, dst, 0, _templ.rows);                            <---- template  19x19
        dft( dftImg, dftImg, 0, dsz.height );                 <-----image  19x19
        cv::mulSpectrums(img_dft, dftTempl1, dftImg, 0, true);
        cv::dft( dftImg, dftImg, cv::DFT_INVERSE + cv::DFT_SCALE, bsz.height );  <---idft  19x19
        
But, As you know, when we do signal processing, according to convolution theorem, to avoid aliasing, we should do like this:

    void Conv2DFT(Mat& convRes, const Mat& img, const Mat& kernel, ConvolutionType type, int ddepth)
    {
         int dft_rows = getOptimalDFTSize(img.rows + kernel.rows - 1);   
         int dft_cols = getOptimalDFTSize(img.cols + kernel.cols - 1);  

that is  to avoid aliasing, we should padding zero and use the size M+N-1 = 19+11-1 = 29.

Why? ...  after i read the paper "fast normalize cross-correlation", this paper do not discuss this issue, so i still feel confuse...

**Comment by TadasBaltrusaitis** [comment]
Hi,

The code does use DFT internally for normalized cross-correlation computation as a speedup, we are not interested in the DFT output as such, but we just want an equivalent output to that of a multiplication (dot product) between the normalized kernel and the per patch normalized image. And the dot product between the kernel and normalized image is equivalent to applying normalized cross-correlation, which can be done in DFT space.

I am not sure I understand your question, as my version of cross-correlation function, does use the same optimal dft size computation:
`dftsize.width = cv::getOptimalDFTSize(corr.cols + _templ.cols - 1);`
`dftsize.height = cv::getOptimalDFTSize(corr.rows + _templ.rows - 1);`

Thanks,
Tadas

**Comment by xiaoxiongli** [comment]
maybe here we just want to calculate the normalized cross-correlation，and this is nothing to do with the general digital signal processing...
