### ISSUE TITLE
FeatureExtraction running fail

### ISSUE THREAD

**Issue by ricerd95** [TadasBaltrusaitis/OpenFace#154]
Dear Tadas,

First of all, thank you for your hard work, these had really helped me a lot in my project. But when I try to compile the FeatureExtraction.cpp I received the following error.

_> Reading the landmark validation module....Done
> Fatal error: Failed to open video source, exiting_

I not very sure what is the problem causing this error. Hope you may assist me on this issue.

Thank you.

Regards,
Ri Cerd

**Comment by TadasBaltrusaitis** [comment]
This could be due to several reasons, the program cannot open the video file provided (for example it is encoded in a way it can't recognize), the video file is corrupted, the video file location is incorrect, or no video file is specified.

-Tadas

**Comment by ricerd95** [comment]
May I know which line program does the file location specified? Sorry I was new to this :(

**Comment by TadasBaltrusaitis** [comment]
Have a look at the following wiki entry, it explains what command line arguments can be used: https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by ricerd95** [comment]
Okay will have a look on it, thank you for the help.
