### ISSUE TITLE
FeatureExtraction fail to run

### ISSUE THREAD

**Issue by ricerd95** [TadasBaltrusaitis/OpenFace#155]
Dear Tadas,

Sorry for troubling you again, I had tried to understand the command line link you gave me, but yet I still unable to find the file directory being specified in the .cpp file. Besides that, do I need to run it with CMD and specify the file location through CMD or I could just run it with VS?

Error Message:
```
Reading the landmark validation module....Done
Fatal error: Failed to open video source, exiting
```

Thank you.

Regards,
Ri Cerd

**Comment by Mariasaaaavedra** [comment]
I have the same error. have you fix it yet??

Maria Saavedra

**Comment by anatanevska** [comment]
Hi, for me this issue was with a missing part in the main() function of FeatureExtraction. In the original version of the code there wasn't any attempt to open the webcam if there was no input picture/video specified, which is why it fails. 

With adding the else{} block it seems to work fine:

				// Check if fps is nan or less than 0
				if (fps_vid_in != fps_vid_in || fps_vid_in <= 0)
				{
					INFO_STREAM("FPS of the video file cannot be determined, assuming 30");
					fps_vid_in = 30;
				}
			}
			// Modification starts here - possible to read from webcam now
			else
			{
				INFO_STREAM("Attempting to capture from device: " << d);
				video_capture = cv::VideoCapture(d);

				// Read a first frame often empty in camera
				cv::Mat captured_image;
				video_capture >> captured_image;
			}
			// Modification ends here
			if (!video_capture.isOpened())
			{
				FATAL_STREAM("Failed to open video source, exiting");
				return 1;
			}
			else
			{
				INFO_STREAM("Device or file opened");
			}

			video_capture >> captured_image;

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, let me know if the error persists.
