### ISSUE TITLE
FeatureExtraction -ov generates empty video

### ISSUE THREAD

**Issue by nicolocarissimi** [TadasBaltrusaitis/OpenFace#156]
Hi,

when I try to output the video with `-ov` param, I get an empty file.
I'm using the prebuilt binaries for windows and the command (one of many combinations) is `FeatureExtraction.exe -fdir \path\to\input_dir -outroot \path\to\output_dir -of out.csv -ov out.avi -au_static -wild -asvid`.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed re-open if persists
