### ISSUE TITLE
HAVE ANYONE MET SOME COMPILE ERROR??

### ISSUE THREAD

**Issue by yinnxinn** [TadasBaltrusaitis/OpenFace#157]
LIAKE THESE:
/usr/local/include/OpenFace/LandmarkDetectorModel.h:174:2: error: ‘LandmarkDetector::CLNF::CLNF(const LandmarkDetector::CLNF&)’ cannot be overloaded
  CLNF(const CLNF& **other);**
  ^
/usr/local/include/OpenFace/LandmarkDetectorModel.h:165:2: error: with ‘LandmarkDetector::CLNF::CLNF(const LandmarkDetector::CLNF&)’
  CLNF(const CLNF& other);
  ^
/usr/local/include/OpenFace/LandmarkDetectorModel.h:177:9: error: ‘LandmarkDetector::CLNF& LandmarkDetector::CLNF::operator=(const LandmarkDetector::CLNF&)’ cannot be overloaded
  CLNF & operator= (const CLNF& other);
         ^
/usr/local/include/OpenFace/LandmarkDetectorModel.h:168:9: error: with ‘LandmarkDetector::CLNF& LandmarkDetector::CLNF::operator=(const LandmarkDetector::CLNF&)’
  CLNF & operator= (const CLNF& other);

**Comment by TadasBaltrusaitis** [comment]
Closing. Re-open if persists.
