### ISSUE TITLE
Different Z values using clnf_model.hierarchical_models[part].GetShape(fx, fy, cx, cy) vs. clnf_model.GetShape(fx, fy, cx, cy)

### ISSUE THREAD

**Issue by crisie** [TadasBaltrusaitis/OpenFace#159]
Hi,

I'm extracting the 3D landmark values in camera space given camera calibration using clnf_model.GetShape(fx, fy, cx, cy), and the pupil values using: 

cv::Mat eyeLdmks3d = clnf_model.hierarchical_models[part].GetShape(fx, fy, cx, cy);
cv::Point3f pupil = GetPupilPosition(eyeLdmks3d);

(as done in FaceAnalysis::EstimateGaze).

I would expect the 3d coordinates of the eye landmarks obtained with the first method to be rather similar to the pupil values obtained with the second method; however, I'm obtaining very different results, especially for the Z coordinate, where I get a difference of up to 50 cm. According to my setup, 
the obtained values using the first method are correct, so I'm confused about the result using the second method, as it also affects the gaze vector estimation.

Is there any plausible explanation for this?

Thanks!

**Comment by crisie** [comment]
Dear @TadasBaltrusaitis ,

Could you please shed some light on this?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

The models are fit separately and might not result in the same 3D values. 

The 3D values of the `clnf_model.GetShape(fx, fy, cx, cy)` call should be a bit more reliable as it tracks more points. There is a risk that the shape in `clnf_model.hierarchical_models[part].GetShape(fx, fy, cx, cy);` is overfitting a bit (finding an unusual configuration of the shape that still results in the correct 2D locations of eye region landmarks), that is why the gaze estimation does not use them directly by casting a ray from eye center through the pupil.

Thanks,
Tadas
