### ISSUE TITLE
FeatureExtraction frontalized landmarks?

### ISSUE THREAD

**Issue by dshahrokhian** [TadasBaltrusaitis/OpenFace#160]
I have noticed that the landmarks that appear in the output of FeatureExtraction are located with respect to the video coordinates. Is there any built-in function that we can use for retrieving the normalized landmarks instead, with respect to the center of the face? Something like point 30 or 31 being the origin (0,0) and the rest of the landmarks with respect to that origin. 

![Landmarks](https://camo.githubusercontent.com/c761816989ff17a1a6f2edb79b2ca8aff9bfd0c1/687474703a2f2f696275672e646f632e69632e61632e756b2f6d656469612f75706c6f6164732f696d616765732f3330302d772f6669677572655f315f36382e6a7067)

I am wondering if this can be implemented using the pose estimates (you must be doing something similar somewhere to predict AUs), since it would be a nice command-line argument to have for people wanting to do Facial Behavior analysis instead of just visualization.

Otherwise, there is [this algorithm](http://www.openu.ac.il/home/hassner/projects/frontalize/) that works using landmarks, but I feel like this would waste the work already done for estimating the head pose.

Thanks,
Dani

**Comment by dshahrokhian** [comment]
@TadasBaltrusaitis any insights?

**Comment by TadasBaltrusaitis** [comment]
Hi, 

To get the 3D locations of face landmarks with respect to the face center, use the following command:
`clnf_model.pdm.CalcShape3D(landmarks_3D, clnf_model.params_local);`

To get the 2D locations, just multiply the 3D ones by the scaling parameter in the `global_params` and get rid of the `Z` values.

**Comment by dshahrokhian** [comment]
Thank you @TadasBaltrusaitis.

EDIT: `clnf_model` is named `face_model` in `FeatureExtraction.cpp`.
