### ISSUE TITLE
HELP PLEASE, OpenFace Windows VS 2015

### ISSUE THREAD

**Issue by Mariasaaaavedra** [TadasBaltrusaitis/OpenFace#161]
I have an issue trying to run the code. The code is compiled but ut says 

Reading the landmark validation module....Done
Fatal error: Failed to open video source, exiting
Press any key to continue . . .

I need to get the AU from some videos. Would you please help me understand how to do this?

Thank you!

**Comment by aarti9** [comment]
I could run code on my windows machine. Used recorder to record my video and then featureExtractor to output frames. I still need to figure out how and where to output AU so I can detect or predict emotion. Make sure you have the paths correct while running command. I had below

C:\OpenFace-master\x64\Release>FeatureExtraction.exe -f "../../videos/Aarti.avi" -outroot "output" -simalign "output" -verbose

**Comment by TadasBaltrusaitis** [comment]
A possible reason why the system failed to open the video source is because it cannot the file provided, the file is corrupted.

To specify the output location you can use the following flag:
`"-of outputLocation.csv"`

Thanks,
Tadas

**Comment by aarti9** [comment]
Thanks Tadas. Yes I figured I wasn't putting -of parameter for AU output. I now have output file giving AUs for each frame. One question though, there was this right pane in a demo which showed live AU bars with % confidence level on a video. How do we get that working. Do we have to plug in call in javascript or something?

**Comment by TadasBaltrusaitis** [comment]
That is present in a Windows-GUI demo which is currently a work in progress, you can have a look at it here - https://github.com/TadasBaltrusaitis/OpenFace/tree/Windows-GUI
