### ISSUE TITLE
Feature extraction for multiple faces

### ISSUE THREAD

**Issue by tchinchuthomas** [TadasBaltrusaitis/OpenFace#162]
Hi Tadas,

I would like to know if I can use feature extraction module to get features for multiple faces in a video.

Thanks

**Comment by yplypl** [comment]
i think you need try to get the images from one video first，using opencv to get images from local video file or using ffmpeg to get images from rtsp server is not a tough problem。

**Comment by TadasBaltrusaitis** [comment]
It is possible to do, but you will need to do some extra coding. 

`FaceAnalysis::FaceAnalyser` object expects the images given to it to be from the same person, as it does person normalization and calibration. So you will need to make sure that when you are tracking multiple people in a video, you give the `LandmarkDetector::CLNF` tracker corresponding to the right person.

This might be challenging if people are coming in to or leaving the scene, or if people pass each other. Then you would need to perform person re-identification which OpenFace does not do.

For an example of how to do multiple face tracking, see `FaceLandmarkVidMulti.cpp`. However, it does not keep track of who the person being tracked is.

Thanks,
Tadas

**Comment by tchinchuthomas** [comment]
Okay Thank you. I will give it a try.
