### ISSUE TITLE
Multiple-face detection in FaceLandmarkImg

### ISSUE THREAD

**Issue by gicheonkang** [TadasBaltrusaitis/OpenFace#164]
Hi !
In FaceLandmarkImg, I run the source code with command
`./FaceLandmarkImg -f sample.jpg` (two people's face in sample.jpg)

But, the result image was cropped-image with each people.
Two images are shown of each people.
Is there a no way to show multiple face's landmark in one image file?

**Comment by TadasBaltrusaitis** [comment]
The way visualization works now it just provides images separately for each face, it should not be too difficult to change the code to display the landmarks on multiple faces though.
