### ISSUE TITLE
is there a way to scale and rotate landmark upright? similar or calling extract_image_chips from dlib?

### ISSUE THREAD

**Issue by amoyeh** [TadasBaltrusaitis/OpenFace#165]
I would like to know Is there a way to crop the image and rotate it upright like what dlib extract_image_chips function does?
I am only interested in the landmark and action units values, the value of eye gaze and head 3d positions is not needed.
Thank you very much for your help.

**Comment by TadasBaltrusaitis** [comment]
I am not familiar with that dlib function, but have a look at similarity aligned faces - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

Thanks,
Tadas
