### ISSUE TITLE
What is the meaning of model_params in FeatureExtraction?

### ISSUE THREAD

**Issue by G0m3e** [TadasBaltrusaitis/OpenFace#166]
Hi, I don't understand what is params_global and params_local in model_params. 
  In your paper, it says "The PDM used in OpenFace was trained on two datasets -LFPW [11] and Helen [36] training sets. This resulted in a model with 34 non-rigid and 6 rigid shape parameters." But I don't know what are their real meanings?
Thanks.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Local parameters (34 non-rigid) are parameters controlling non-rigid face shape, in other words things like facial expression and face shape (long, vs round, vs wide faces etc.). In my thesis they are q in equation 4.6 and are explained in detail in section 4.2.2 (https://www.cl.cam.ac.uk/~tb346/pub/thesis/phd_thesis.pdf)

If you are familiar with Principal Component Analysis (PCA), they are the dimensionality reduced components of the 68 facial landmarks. So individually each can represent a particular basis which roughly corresponds to an expression or face shape, but are not always easily mapped to one. If you want to visualize them and see their effect, have a look at `matlab_version/pdm_generation/visualise_PDMs.m`, this will visualize the first 5 ps and what effect on the face they have.

The global parameters, on the other hand, control the placement of the face in the image and are responsible for translation (x and y), scale/size, and the rotation of the face.

**Comment by G0m3e** [comment]
Thank you very much for your help, I understand a lot now.
