### ISSUE TITLE
have anyone ever met these errors when compile ??

### ISSUE THREAD

**Issue by yinnxinn** [TadasBaltrusaitis/OpenFace#167]
### 

/usr/local/include/OpenFace/LandmarkDetectorModel.h:174:17: error: expected ‘,’ or ‘...’ before ‘&&’ token
  CLNF(const CLNF&& other);
                 ^
/usr/local/include/OpenFace/LandmarkDetectorModel.h:174:25: error: invalid constructor; you probably meant ‘LandmarkDetector::CLNF (const LandmarkDetector::CLNF&)’
  CLNF(const CLNF&& other);
                         ^
/usr/local/include/OpenFace/LandmarkDetectorModel.h:177:30: error: expected ‘,’ or ‘...’ before ‘&&’ token
  CLNF & operator= (const CLNF&& other);
###

**Comment by gicheonkang** [comment]
check your compiler : )

**Comment by yinnxinn** [comment]
I solved the problem. i'm such a newbie to ubuntu
