### ISSUE TITLE
Why facial landmark needs 3D model?

### ISSUE THREAD

**Issue by gicheonkang** [TadasBaltrusaitis/OpenFace#168]
Hi I'm reimplementing your project into Android app. (FaceLandmarkImg)
I'm in trouble detecting landmark for the function below

`LandmarkDetector::DetectLandmarksInImage`
There is a function name `CalcShape3D` function, you commented "mapping 2d to 3d".
But, Android can't compute so fast at all (I think it is 3D model). 

So, Is there any alternatives to that? 
I just want to detect landmarks ( no head pose, no gaze estimates )
Thank you

**Comment by TadasBaltrusaitis** [comment]
The face landmark detection and tracking assume a 3D face shape model and it is not possible to remove that without significantly changing the approach. Also removing that would not lead to much faster (if at all) tracking.

Furthermore, the `CalcShape3D` function is actually very cheap compared to the rest of processing costs.
