### ISSUE TITLE
FaceLandmarkImg.exe crashed when running on windows7 

### ISSUE THREAD

**Issue by wguo68** [TadasBaltrusaitis/OpenFace#17]
I used this program like this : FaceLandmarkImg.exe -f face.jpg 
but crashed!
![bad](https://cloud.githubusercontent.com/assets/4994038/16079043/92914f9c-3334-11e6-8fd0-9d73b64b7e37.jpg)

**Comment by TadasBaltrusaitis** [comment]
I would need some more details. Did you compile the executable yourself or did you download it?

**Comment by PVNathan** [comment]
Was this issue solved? I am facing the same problem. I downloaded the executable. The other exe files work but not FaceLandMarkImg
Thanks
