### ISSUE TITLE
compile c# version

### ISSUE THREAD

**Issue by doczoidberg** [TadasBaltrusaitis/OpenFace#171]
I downloaded the C# version from the Windows GUI branch.

I had to rename the 140 directories to 141. But I still get an error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3821	'tbb::internal::concurrent_vector_base_v3::concurrent_vector_base_v3(void)': managed type or function cannot be used in an unmanaged function	CppInerop	d:\openface-windows-gui\lib\3rdparty\tbb\include\tbb\concurrent_vector.h	215	
Error	C2711	'tbb::internal::concurrent_vector_base_v3::concurrent_vector_base_v3': this function cannot be compiled as managed, consider using #pragma unmanaged	CppInerop	d:\openface-windows-gui\lib\3rdparty\tbb\include\tbb\concurrent_vector.h	203	

```

I use VS2017 on Win10 btw. What can I do?

**Comment by doczoidberg** [comment]
I had to use
```
#pragma managed(push, off)
#pragma warning (pop)
```
in `concurrent_vector.h` and `concurrent_hash_map.h`

there are also some version issues in filenames 141/140

**Comment by TadasBaltrusaitis** [comment]
Hi Daniel, the code is actually intended for VS2015 and will work out of the box with it, the issue is the compiled binaries and libraries of 3rd party tools, that were compiled for VS2015
