### ISSUE TITLE
I had this error when I execute install.sh : Illegal option -o pipefail 

### ISSUE THREAD

**Issue by raul93611** [TadasBaltrusaitis/OpenFace#172]
How can I solve this problem???

**Comment by dshahrokhian** [comment]
What is your `zsh --version` or `bash --version`? It might be too old. `pipefail` was introduced in [#601](https://github.com/junegunn/fzf/pull/601). Try updating.

**Comment by raul93611** [comment]
Thank you....................... Now OpenFace is already installed. But I have a question .....How can I compare two faces to determine if they are the same?

**Comment by chiragraman** [comment]
Please open a separate issue for the second question, it isn't related to the original issue.

For a quick answer, the simplest way would be to compare the aligned face images or their HOG features. You could also compare the structure of the faces by computing an RMS distance between the landmarks. 

You could also look at the other OpenFace repository https://cmusatyalab.github.io/openface/ that does provide support for similarity detection.
