### ISSUE TITLE
how can I use openface web ?????

### ISSUE THREAD

**Issue by raul93611** [TadasBaltrusaitis/OpenFace#173]
I followed the steps to install openface and I tried all the options in the command line arguments , it is amazing but I want to try Demo 1 openface web and I don't know how I can do that.

**Comment by TadasBaltrusaitis** [comment]
Hi,

What do you mean by OpenFace web? There is no web version of OpenFace

**Comment by dshahrokhian** [comment]
I think you are mistaking this repo with [bamos/openface](https://github.com/cmusatyalab/openface).

**Comment by raul93611** [comment]
yeah ....you are right ........I am sorry
