### ISSUE TITLE
Is it possible to process Hog for AU extraction?

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#178]
I have two questions.
1. Is it possible to process video in 2-step?
 Extract AU (using HOG file) after face tracking.

2. Is it possible to extract AU from multiple faces? or any trick (like above 2-step approach)

**Comment by TadasBaltrusaitis** [comment]
No without coding extra functionality. But it is definitely possible. For step 2, have a look at the multiple face tracking executable, it will give you some guidance of how to track multiple faces, you could use those separate tracks for AU extraction. Although, you will need to be careful to give the same person's track to each corresponding `FaceAnalyser`
