### ISSUE TITLE
OpenFace (and CLM) reference frame?

### ISSUE THREAD

**Issue by alecive** [TadasBaltrusaitis/OpenFace#18]
Hi @TadasBaltrusaitis , is there a place in which I can find the reference frames used by CLM and OpenFace? I assume you're using pretty standard reference frames, but I would like to have a definitive reference on this.

Thank you!

**Comment by TadasBaltrusaitis** [comment]
What exactly do you mean by reference frames?

**Comment by alecive** [comment]
@TadasBaltrusaitis I was referring to the location and orientation of the x,y,z axis of the camera and world frames.

(at least in CLM), there are these two methods:
```
CLMTracker::GetCorrectedPoseWorld(clm_models[model], fx, fy, cx, cy);
```
and
```
CLMTracker::GetCorrectedPoseCamera(clm_models[model], fx, fy, cx, cy);
```

which return a `Vec6d` with 3D position and yaw, pitch, roll. But this 6D vector is created with respect to what reference frames?

**Comment by TadasBaltrusaitis** [comment]
Apologies for the delay. The `PoseWorld` refers to world reference frame with the camera sitting at `(0,0,0)` and the `X,Y,Z` axes aligned to it with `Z` pointing out of the camera. The `PoseCamera` refers to camera rotation frame, so if a person is looking at the camera the rotation should be `(0,0,0)`, it is more useful for interaction purposes.

In both cases `X,Y,Z` are with respect to camera which is `(0,0,0)` and they are measured in millimeters.

Hope this answers your question.

**Comment by alecive** [comment]
Thank you for the information! I will re-open the issue if I need more information, but for now it's ok. Thank you again!
