### ISSUE TITLE
Landmark validation module

### ISSUE THREAD

**Issue by gvelchuru** [TadasBaltrusaitis/OpenFace#181]
Hi,

I got the docker container running, but I get the error "Reading the landmark validation module...Done
Fatal error: File does not exist"
How do I get this module?

**Comment by TadasBaltrusaitis** [comment]
Hi,

The error refers to the application not finding the file to process and not a missing module. Make sure you provide an existing file using `-f <location>`

Thanks,
Tadas

**Comment by gvelchuru** [comment]
Thank you!
