### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by gvelchuru** [TadasBaltrusaitis/OpenFace#182]
Hi, 

During the make process I get the following error:
"CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o: In function `main':
/home/gauthv/OpenFace/exe/FaceLandmarkImg/FaceLandmarkImg.cpp:(.text+0x8c2a): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
/home/gauthv/OpenFace/exe/FaceLandmarkImg/FaceLandmarkImg.cpp:(.text+0x99d4): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFaces(std::__1::vector<cv::Rect_<double>, std::__1::allocator<cv::Rect_<double> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&)':
/home/gauthv/OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorUtils.cpp:(.text+0x18373): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:128: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:252: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
"
Any idea for what this might be?

**Comment by aravindcheruvu** [comment]
Can you please explain how did you solve this issue?
