### ISSUE TITLE
Illegal instruction in x64 Build

### ISSUE THREAD

**Issue by AlEmerich** [TadasBaltrusaitis/OpenFace#184]
Hi everyone,

When I try to build in Debug/Release for x64 archi, I get a runtime error caused by exe_common.inl called illegal instruction.

Have you ever experienced some problems building your soft in x64 ? My processor is an old Intel Celeron so maybe your soft made instruction my processor doesn't have.

**Comment by TadasBaltrusaitis** [comment]
That's most likely the case, older processors do not have all the instruction sets. As the performance of 32bit and 64bit versions is very similar, I would suggest using the 32 bit version.

An alternative would be to turn off or change the Properties->C/C++->Code Generation->Enable Enhanced Instruction Set on all the projects.

Thanks,
Tadas

**Comment by JerryIsdale** [comment]
I ran into issues building/running for an i7-6700HQ processor. It blew up down in xstring when running as x64.  There are a whole bunch of warnings from dlib/image_processing/shape_predictor and  tbb/enumberable_thread_specific.h about use of Shift instructions, etc.
Looks like there is stuff down there that is NOT compatible with x64

**Comment by JerryIsdale** [comment]
Couple insights: 
 FaceLandmarksVid tool runs just fine.\, whether I have and of the Enhanced Instruction Set options set or unset.
The FaceLandmarksImg however, seems run into weird stuff when it is unpacking the parameters.
I put the suggested cmd line options from the [WindowsInstall page ](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation) into the Project Properties>Debugging>COmmand Arguments, and it was crashing at approx line 466 in the if(!outs_pts_dri.empty()) block.  I took a clue from the block above and wrtapped the create_directory_from_file call with an if (!input_image_files.empty())...
this avoids the program crashing, but does not fix the problem.
Apparently input_image_files does not get properly processed in x64, while it does in win32.

**Comment by JerryIsdale** [comment]
got it.  The output build files go in different places depending on the use of x64 and Win32.
Because I was specifying the WorkingDirectory as $(TargetDir) and the targets go into different levels of files, it was wrong.  
If I change it to use $(SolutionDir) and set cmd line parameters to use ./ instead of ../ it works just fine.
so NOT a code problem.
