### ISSUE TITLE
where can i download the folder "openCV_haarcascade_frontalface_alt"?

### ISSUE THREAD

**Issue by xiaoxiongli** [TadasBaltrusaitis/OpenFace#187]
Dear  Tadas, 

@TadasBaltrusaitis 

When I run the file collect_transform_ocv.m, it seems that we need the folder 
 "openCV_haarcascade_frontalface_alt" and its contents.  So where can i download the folder "openCV_haarcascade_frontalface_alt"?    

I just want to reproduce face compensate(ocv.mat and run learn_mapping.m) as yours.
         
And i know this folder is generate by opencv's haar face detector,  would you please give me some tips about the parameters you used in opencv's function  "detectMultiScale",  since i use the cascade.detectMultiScale(grayImage, rect, 1.2, 2, 0, cv::Size(50, 50));  but it seems these parameters can not generate the faces(for face compensate) as yours...

thank you very much ^_^

**Comment by TadasBaltrusaitis** [comment]
Hi,

I don't believe I have that data anymore (at least I couldn't find it). I believe I used the same parameters for face detection as you specified:
`classifier.detectMultiScale(intensity, face_detections, 1.2, 2, 0, cv::Size(50, 50));`

Also you need to make sure that you are using the following detector - `haarcascade_frontalface_alt.xml`

Why do you think those parameters cannot generate the ones in the `ocv.mat` file?

Thanks,
Tadas

**Comment by xiaoxiongli** [comment]
Dear Tadas,

@TadasBaltrusaitis


First of all, when I run learn_mapping.m(using ocv.mat), it seems it have 3283 items, and i have a glance at file collect_transform_ocv.m, it seems use 4 database:  afw(337 images), lfpw's trainset(2000), ibug(135) and helen's trainset(811).  337+2000+135+811 = 3283,  So ocv.mat is generate from these 4 database, right? 

Second, Which version of OpenCV do you use to generate ocv.mat?  in your paper you said you use OpenCV 2.4.0 and in the OpenFace code you use OpenCV 3.1.0,  and I compare the haarcascade_frontalface_alt.xml file in these two OpenCV version, And I find that it is totally different. 

Third, take  lfpw's image "1051618982_1.jpg" for example.  in the OpenCV3.1.0 we detect the face and get the bounding box( cv::Rect={461 174 249 249} ),  and in your ocv.mat,  we get like this: 
bboxes(0) = {377.5780, 119.895, 89, 54, 254, 254}, so the bounding box is  { 463.578, 173.895, 254, 254 }, it is  similar as before but not the same.  

And I also feel confusing about the first two float number(shift) :   377.5780  and  119.895,    Why we use a shift during detect the face and which shift value should we use??  it is possible to just let the shift be 0?

**Comment by TadasBaltrusaitis** [comment]
Hi,

I don't remember which version I was using to construct ocv.mat, it might have been OpenCV 2.4. You're right that they might be somewhat different, but I don't think the difference is that large.

I see where the confusion is. As a lot of datasets have multiple faces, I first cropped the image to the face of interest (for which landmark annotations exist), the shift parameter actually corresponds to that cropping. So to get to the actual bounding box us `377.58 + 89=466.9`, which is actually quite close to your values.

Thanks,
Tadas

**Comment by xiaoxiongli** [comment]
Dear Tadas,

@TadasBaltrusaitis

      I got it,  and i try OpenCV3.1's face detection and I set shift to 0, then i get a compenrate such like s_width=0.8543，s_height=0.8251, s_tx=0.0696, s_ty=0.2251,  it works!!!

      Of course,  if the images have more than one faces, i need do a check according to  the annotations.

      thank you very much. ^_^
