### ISSUE TITLE
Mouth tracking is much worse than upper face...

### ISSUE THREAD

**Issue by antithing** [TadasBaltrusaitis/OpenFace#189]
Hi, thank you for making this code available, it is very useful.  I am having trouble with a couple of things however... If you have a minute, could you help me out?

The tracking points around the mouth seem to track much worse than the rest of the face. When the mouth is opened, the points on the lower lip do not follow. Is there something I can tweak to make these points stick better? 

The AU values are very noisy, again especially around the mouth. When the face is still, they seems to jump around too much to use. Is this normal?

thanks again!

**Comment by TadasBaltrusaitis** [comment]
Hi,

The precise tracking of lip outline when the mouth is open is a known problem. In the coming months we will be releasing a new version of the tracker that should address some of these issues.

With regards to AUs, some noise is expected and you could employ some smoothing techniques of the signals to address it. What do you mean by too much? This will also depend on lighting conditions and facial appearance (such as facial hair).

**Comment by antithing** [comment]
Hi, and thank you for taking the time to reply.  I have added smoothing, and normalization of the AU values from 0 - 1, and am seeing an improvement. As far as the mouth goes, I am playing with the straight dlib tracking code, based on this:

https://github.com/JackGit/hello-dlib-tracker/blob/master/main.cpp

and I see a much more stable mouth outline. Would it be possible to pass the shapes from this, instead of a cv::mat, into your FaceAnalyser to get the AU values? Thanks again!

**Comment by TadasBaltrusaitis** [comment]
It's possible as the landmarks follow the same 68 point markup, but I have not tried it.
