### ISSUE TITLE
trying to make a node.js solution. have figured out opencv but stuck at dlib. do you have any alternate biniding that you know could be used

### ISSUE THREAD

**Issue by avisangray** [TadasBaltrusaitis/OpenFace#19]

**Comment by TadasBaltrusaitis** [comment]
dlib is used for face detection and HOG feature computation, you can replace face detection with OpenCV for HOG feature computation you will probably need to port dlib's code as I'm not aware of another C++ implementation of that flavour of HOG.

**Comment by avisangray** [comment]
solved it. thanks a ton
