### ISSUE TITLE
pitch, yaw, roll?

### ISSUE THREAD

**Issue by hyejinJ** [TadasBaltrusaitis/OpenFace#191]
Hi, I'd like to extract the pitch, yaw, roll values from your codes.
When using FeatureExtraction.exe, I can see that it outputs pose_T{x,y,z} and pose_R{x,y,z} of each faces.
What are they and are they related to pitch, yaw, and roll?

Thanks in advance.

**Comment by TadasBaltrusaitis** [comment]
Yes, the pose_R{x,y,z} are the Euler angles representing pose. 

You can find a more detailed explanation of all output values here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#featureextraction

Thanks,
Tadas

**Comment by EoghanHynes** [comment]
Wiki states:

"This can be seen as pitch (Rx), yaw (Ry), and roll (Rz). "

is (Rx) really pitch (looking up to the ceiling or down to the floor) or is this a typo ??

judging from the output this appears to indeed be the case, but Im just double checking.

thanks

**Comment by TadasBaltrusaitis** [comment]
Yes, Rx is pitch (up/down), Ry is yaw (left/right), Rz is roll (tilt of the head)

Why do you believe that it is a typo?

**Comment by EoghanHynes** [comment]
It conventional Cartesian coordinate notation in school books etc, the y-axis is given as 'up-down', x-axis = 'left-right', z-axis = 'in-out'.

**Comment by TadasBaltrusaitis** [comment]
I see where the confusion is coming from. 

I am using the same convention of x-axis left-right, z-axis 'in-out' etc., however, if you think about rotation around y-axis which is up-down, you will get the head rotating to the left-right etc. This is well illustrated in various images if you google `roll pitch yaw`

**Comment by EoghanHynes** [comment]
Now I understand.

Thank you!
