### ISSUE TITLE
Kinect v2 depth data

### ISSUE THREAD

**Issue by cigdemturan** [TadasBaltrusaitis/OpenFace#192]
Hi Tadas,

I am running an experiment to analyse the facial behavior of certain settings. I am using Kinect v2 to acquire the depth data with a further plan of using OpenFace to obtain Action Units.

I read #77 and I understood that I need to convert the depth data to a 16-bit png image (I already do it). My question is about the resolution of the depth data. As you also probably know, Kinect v2 resolutions differ in depth and color data and I guess for OpenFace, both frames need to be in the same resolution.

I wish to know which way you would suggest me:
   map the depth frame to color space
OR
   map the color frame to depth space.

And are there more points that I shouldn't miss?

Thank you!
Cigdem

**Comment by TadasBaltrusaitis** [comment]
Hi Cigdem,

OpenFace expects both the color and depth images to be of the same resolution and each pixel to be in correspondence. This can be achieved through camera calibration, it does not matter too much which way the mapping is done, but so far I have mostly been aligning depth to color frame.

As an aside, the CLNF version of the tracker (used by default) is as accurate as CLM-Z (depth based model) in most cases. I would evaluate how both of them work in your setting before deciding to use the depth one as well.

Thanks,
Tadas
