### ISSUE TITLE
Can not be detected when I close my eyes

### ISSUE THREAD

**Issue by Andrew-Deng** [TadasBaltrusaitis/OpenFace#194]
Thanks to opensource such surprising project.@TadasBaltrusaitis
But I found a problem ,It seems that Gaze tracking don't detect closing of eyes.
How to realize it. Training a custom AU?

**Comment by matlabalpha** [comment]
I have a same problem.We observed that the direction of the gaze vector in Matlab and the direction of the participant's eye gaze is different, as shown below:
![6bgbs9o5qr23otlk b0 sq](https://cloud.githubusercontent.com/assets/29198910/26814623/8e169a74-4ab9-11e7-8940-2a0134a939e5.jpg)
![9j33 ayp3t f mdo 0 w6](https://cloud.githubusercontent.com/assets/29198910/26814628/984f153e-4ab9-11e7-9a12-10c13541bee7.jpg)


The participants' head is facing the camera whilst the participant's is asked to look at a sticker we placed on the ceiling to the left and right of the participant without moving or tilting their head; the gaze direction depicted in Matlab seems to be pointed towards or directed towards the camera for the majority of the time, is there something we are doing wrong?

**Comment by TadasBaltrusaitis** [comment]
Hi,

While OpenFace is accurate in general, the software will not be accurate all the time. Especially if the person is wearing glasses with reflection on them or if the image quality is not high enough. You don't seem to be doing anything wrong, OpenFace is just not able to reliably detect eye gaze in the images you provided.
