### ISSUE TITLE
[question] Should be CUDA enabled for FaceLandmarkVid?

### ISSUE THREAD

**Issue by archenroot** [TadasBaltrusaitis/OpenFace#195]
Hi, I just got this compiled on my Gentoo AMD64 system with GCC 5.4.0, CUDA 8.0 and lapack/cblas/blas stack from science gentoo overlay.

Now when I try FaceLandmarkVid, I don't see anything running on my GPU chip. Is that expected behavior or not?

**Comment by TadasBaltrusaitis** [comment]
OpenFace is not GPU enabled, so no computations will take place on the GPU.
