### ISSUE TITLE
OpenFace for UIImage

### ISSUE THREAD

**Issue by DebanjanChakrabortyCN** [TadasBaltrusaitis/OpenFace#196]
I recently came across your code and checked it. It's really cool, but because it is done on Video, it was really slow, so I used a static image 

I generated cvMatFromUIImage and then passed it to the processImage function that was defined in ViewController.mm (it was a protocol defined in CvVideoCameraDelegate). 

The thing is, as I call run_Image_FaceAR code , it shows that all landmarks were detected but visualise_tracking isn't drawing the box.
 Can you tell me , where am I getting wrong?

**Comment by TadasBaltrusaitis** [comment]
Do you mean this project? https://github.com/FaceAR/OpenFaceIOS, as the functions and variable names you are using are not in the original OpenFace. 

If so, I'm not able to provide support as that is not my project, but an extension to OpenFace by someone else.

**Comment by DebanjanChakrabortyCN** [comment]
Yeah, that's the project. Sorry for the wrong post
