### ISSUE TITLE
Problems in Using different dataset with different number of landmarks

### ISSUE THREAD

**Issue by syyuan1993** [TadasBaltrusaitis/OpenFace#197]
I'm using a dataset containing 106 landmarks, starting from the beginning, training the PDM. However, there are several pretrained(?) parameters stored in files including tri_68.mat, pdm_68_multi_pie.mat and I couldn't find the relating code generating these files. Could you please tell me what are those and how could I compute them by myself? A piece of code or paper would help a lot! Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

The triangulation was generated using simple Delaunay triangulation. However, it is only needed for the face tracking validation step and if you are going to use the model only for landmark detection in images you do not need to generate it. 

While pdm_68_multi_pie is useful for aligning the face to be upright it is also not strictly needed. You could also align to it by using the overlapping landmarks in your 106 and 68 landmark annotations.
 
Thanks,
Tadas

**Comment by syyuan1993** [comment]
Thanks! One another question, when I train the patch experts using Train_all_pathc_experts (in CCNF git hub), it uses patch_experts struct which include thetas. However, when initialize this struct, there is no such variable initialized. Did I miss something? Thanks!

**Comment by syyuan1993** [comment]
Found it! Thanks a lot!
