### ISSUE TITLE
Link Bbroken in description

### ISSUE THREAD

**Issue by Luchianno** [TadasBaltrusaitis/OpenFace#199]
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation
Here at this place:
"For the binaries to work you need to have Visual Studio 2015 installed or need to install the 64-bit Visual C++ redistributable package, that can be found here." <- this link is broken

**Comment by TadasBaltrusaitis** [comment]
Thanks, fixed.
