### ISSUE TITLE
Landmarks 2d format

### ISSUE THREAD

**Issue by Neill3d** [TadasBaltrusaitis/OpenFace#2]
Hi, I've found a bit strange in the 2d landmarks format when float fraction part and a separator between values share the same symbol ','
 For example: 0,1,0,981,275,12,268,09,271,85,289,85,328,27,... etc.
here x1 is 981,275, etc.
P.S. I've tried the OpenFace application from the main page - http://www.cl.cam.ac.uk/research/rainbow/projects/openface/
 In the source I've found that FeatureExtraction has a different file store code.

**Comment by TadasBaltrusaitis** [comment]
Hi,

I think the reason might actually be the localization (as different regions use different style significant digits), which bit of the code are you using? Are you using the GUI or the command line?

With regards to your second question, I'm updating the GUI now, if you were using the application from the download link it is the outdated one and will be changed somewhat. The newer version will have the same functionality but should be more stable and better documented.

Thanks,
Tadas

**Comment by Neill3d** [comment]
Hi,

 I have a russian localization, I'm not sure where to look which one is actualy using, it could be something like Windows-1251 for example.
 I was using a GUI version (which now I see is out of date). I'll wait for a new one.
Thank you.
