### ISSUE TITLE
Generation of 2D Screen Gaze target from 3D Gaze Direction

### ISSUE THREAD

**Issue by karanahujax** [TadasBaltrusaitis/OpenFace#20]
With reference to the Max Planck Gaze in the wild database (https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild-mpiigaze/), how do you convert the 3D gaze direction vector to the 2D Screen Gaze Target Coordinate?

**Comment by TadasBaltrusaitis** [comment]
OpenFace does not provide such functionality - you would need to perform this yourself. For this you will need to know the relative location of camera to the screen alongside the screen coordinates. If you do it purely from the 3D gaze direction and 3D location of the eyes then it will be just fairly straightforward geometry/trigonometry. Alternatively, for better results you can perform person specific calibration and adjustments.

**Comment by karanahujax** [comment]
Okay, given I have the screen plane and the the gaze direction, how will I calculate the screen intersection without the 3D location of the eyes? I ask this because in your paper "Rendering of Eyes for Eye-Shape Registration and Gaze Estimation", you follow appearance based gaze estimation in which the output is the 3D gaze direction vector and there is no information about the 3D location of the eyes.

**Comment by TadasBaltrusaitis** [comment]
You can access the 3D location of eyes from the landmark detection module (for best results you will need to know the focal length of the camera).

As I think I mentioned before, OpenFace does not include the appearance based gaze estimation from "Rendering of Eyes for Eye-Shape Registration and Gaze Estimation", but that approach would also only provide you with gaze vectors and would still require knowing where eyes are for screen coordinates.

**Comment by karanahujax** [comment]
Thanks for the quick reply. I have now managed to get the screen intersection point. Do you have any particular paper or calibration method in mind that I can follow?

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, I haven't worked on calibration myself but you can try some of the following methods or papers cited in them:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.80.1419&rep=rep1&type=pdf
https://perceptual.mpi-inf.mpg.de/files/2013/10/pfeuffer13_uist.pdf

**Comment by utkarshvadar** [comment]
@karanahujax how did you managed to get screen intersection point.

**Comment by jonelkhoury** [comment]
@karanahujax Yes, could you please tell us how you were able to get the screen intersection point using the gaze vector?
Thanks!

**Comment by karanahujax** [comment]
Once you get the 3d gaze vector, then it is a simple ray-plane intersection, with the plane being the laptop screen. Assuming that the laptop is on the same plane as the webcam, that would become the z=0 plane. Hence the intersection will be between those two. In cases that have an external screen, the coordinates of the screen must be known  as well, for example through a 4-point calibration procedure.
