### ISSUE TITLE
[question] Training the models with a different number of landmarks

### ISSUE THREAD

**Issue by YuvalNirkin** [TadasBaltrusaitis/OpenFace#201]
Hi Tadas,
I would like to train your 3 models on a 21 landmark points dataset with partial occlusions, but your "Create_pdm_wild.m" script is hard-coded for 68 points.
Could you please guide me what would be the best way to go about it?

Thanks in advance,
Yuval

**Comment by TadasBaltrusaitis** [comment]
Hi Yuval,

Have a look at - https://github.com/TadasBaltrusaitis/OpenFace/issues/197

Thanks,
Tadas
