### ISSUE TITLE
[ 53%] Built target opencv_cudaarithm Makefile:160: recipe for target 'all' failed

### ISSUE THREAD

**Issue by IvyGongoogle** [TadasBaltrusaitis/OpenFace#204]
hello, I have install opencv2.4.9. But I see the demand for opencv3.1.0 in `Unix Installation` . So can opencv2.4.9 work? 

Beside, when I install opencv3.1 as the instruction in install.sh, it shows error:

```
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/core.cpp.o
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/arithm.cpp.o
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/reductions.cpp.o
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/element_operations.cpp.o
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Linking CXX static library ../../lib/libopencv_cudaarithm.a
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Built target opencv_cudaarithm
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
how to fix it?
can you give some advises?
thank you very much!

**Comment by IvyGongoogle** [comment]
@TadasBaltrusaitis looking forward to your advice.

**Comment by IvyGongoogle** [comment]
@TadasBaltrusaitis looking forward to your advice.

**Comment by IvyGongoogle** [comment]
@TadasBaltrusaitis looking forward to your advice.

**Comment by TadasBaltrusaitis** [comment]
Try installing OpenCV using the original instructions and not the install.sh script - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation#ubuntu-1404

**Comment by IvyGongoogle** [comment]
@TadasBaltrusaitis thank you. but it does work, My cuda is 8.0. python is 2.7.  Now I still fail to install opencv3.1/3.2 which let me carzy.

**Comment by vladimircape** [comment]
Same issue

**Comment by zhiqwang** [comment]
I meet the same error when I installing opencv-3.4.2, and I found the gcc's version compiling the NVCC is 7, which is conflicting to the version of gcc when I compile opencv. And I change the gcc version to 7, this error vanished.

**Comment by TadasBaltrusaitis** [comment]
Please reopen if above has not resolved the issue.

**Comment by POSCOmydream** [comment]
@zhiqwang Thank you for good solution. I solve my error using your solotion.

**Comment by pedrobagatin** [comment]
There is no easier way than reinstalling cuda?
