### ISSUE TITLE
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1

### ISSUE THREAD

**Issue by IvyGongoogle** [TadasBaltrusaitis/OpenFace#208]
hello, spending much time for compiling OpenFace, I get error:
```
lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/build.make:62: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o' failed
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all' failed
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
how to fix it?
looking forward to your reply.

**Comment by TadasBaltrusaitis** [comment]
Hi, 

Could you provide more details? The error is too vague at the moment to see why it is failing. 

What OS are you using? Have you followed all the instructions in the wiki?

Thanks,
Tadas

**Comment by IvyGongoogle** [comment]
@TadasBaltrusaitis thank for your reply. I using ubuntu16.04, cuda8.0. As I can not success for compiling opencv3.1 from source. So I want to try directly compiling OpenFace using my original opencv2.4.13 environment and got the error I described above. So must I using opencv3.1/3.2 to compiling and run OpenFace?

**Comment by TadasBaltrusaitis** [comment]
Hi,

The official version uses OpenCV 3.1, I don't know if it will work with any of the OpenCV 2.x versions. The cuda version should not have an impact as no GPU processing is used by OpenFace.

**Comment by IvyGongoogle** [comment]
@TadasBaltrusaitis thank for your reply. Finally I successfully compile opencv3.1 using `cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_GTK=ON -D WITH_GTK_2_X=ON -D CUDA_NVCC_FLAGS="-D_FORCE_INLINES" ..`. 

But I have another error when compiling later OpenFace:

```
[ 92%] Linking CXX executable ../../bin/FaceLandmarkImg
/usr/bin/cmake: /home/ztgong/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:149: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:252: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
crazy..

**Comment by huberemanuel** [comment]
I'm getting the same error, have you solved?

**Comment by TadasBaltrusaitis** [comment]
Should be fixed, re-open if error persists.

**Comment by Varshul** [comment]
Hey @TadasBaltrusaitis  I am trying to build inside the docker container on a mac.

`[ 60%] Building CXX object lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o
`
`/home/openface-build/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:499:234: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
make: *** [all] Error 2`

Can you please help out?

**Comment by TadasBaltrusaitis** [comment]
Hi,

Could you provide more details? The error is too vague at the moment to see why it is failing, the snipped you posted does not contain the actual error (try compiling single threaded for a clearer error messages - e.g. use `make` instead of `make -j4`), alternatively look for lines that start with Error.

What OS are you using? Have you followed all the instructions in the wiki?

Thanks,
Tadas

**Comment by anthopper** [comment]
Hi, I am trying to install OpenFace and get the following error on build:

/usr/local/include/dlib/image_processing/../opencv/cv_image.h:136:22: error: no viable conversion from 'const cv::Mat' to
      'IplImage' (aka '_IplImage')
            IplImage temp = img;
                     ^      ~~~
/usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/core/types_c.h:327:1: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'const cv::Mat' to 'const _IplImage &' for 1st
      argument
_IplImage
^
/usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/core/types_c.h:327:1: note: candidate constructor
      (the implicit move constructor) not viable: no known conversion from 'const cv::Mat' to '_IplImage &&' for 1st argument
/usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/core/mat.hpp:1642:28: note: candidate template ignored: could not
      match 'vector<type-parameter-0-0, allocator<type-parameter-0-0> >' against '_IplImage'
    template<typename _Tp> operator std::vector<_Tp>() const;
                           ^
/usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/core/mat.hpp:1643:35: note: candidate template ignored: could not
      match 'Vec<type-parameter-0-0, cn>' against '_IplImage'
    template<typename _Tp, int n> operator Vec<_Tp, n>() const;
                                  ^
/usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/core/mat.hpp:1644:42: note: candidate template ignored: could not
      match 'Matx<type-parameter-0-0, m, n>' against '_IplImage'
    template<typename _Tp, int m, int n> operator Matx<_Tp, m, n>() const;
                                         ^
/usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/core/mat.hpp:1646:45: note: candidate template ignored: could not
      match 'array<type-parameter-0-0, _Size>' against '_IplImage'
    template<typename _Tp, std::size_t _Nm> operator std::array<_Tp, _Nm>() const;
                                            ^
2 errors generated.
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2

**Comment by TadasBaltrusaitis** [comment]
This seems to be an issue with OpenCV 4.2 which seems to have breaking changes over OpenCV 4.1, can you try linking agains OpenCV 4.1?

**Comment by chfooky** [comment]
tash@tash-desktop:~/OpenFace/build$ sudo make
Scanning dependencies of target LandmarkDetector
[ 2%] Building CXX object lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o
g++-8: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++-8: error: unrecognized command line option ‘-msse2’
g++-8: error: unrecognized command line option ‘-msse3’
lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/build.make:62: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o' failed
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all' failed
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

sir can you plz help me out..im facing same issue

**Comment by chfooky** [comment]
> Hi,
> 
> Could you provide more details? The error is too vague at the moment to see why it is failing, the snipped you posted does not contain the actual error (try compiling single threaded for a clearer error messages - e.g. use `make` instead of `make -j4`), alternatively look for lines that start with Error.
> 
> What OS are you using? Have you followed all the instructions in the wiki?
> 
> Thanks,
> Tadas

tash@tash-desktop:~/OpenFace/build$ sudo make
Scanning dependencies of target LandmarkDetector
[ 2%] Building CXX object lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o
g++-8: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++-8: error: unrecognized command line option ‘-msse2’
g++-8: error: unrecognized command line option ‘-msse3’
lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/build.make:62: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o' failed
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all' failed
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

sir can you plz help me out..im facing same issue
ubunto 18,Jetson Neno ARM64(Tx2)
