### ISSUE TITLE
How to measure accuracy of gaze estimation?

### ISSUE THREAD

**Issue by francoised99** [TadasBaltrusaitis/OpenFace#21]
Firstly, I would like to thank you for a great multi-threaded framework. I just wanted to clarify how to measure accuracy of the gaze estimation:

One way is to take the tan inverse of the error_distance/distance from screen. But in your paper titled "Learning an appearance-based gaze estimator from one million synthesised images", you mention that "The eye gaze error was computed as median angle between ground truth and estimated
eye gaze vectors in degrees." Can you please explain this to me? (Does this mean the accuracy is calculated in terms of difference of the yaw and pitch from original ground truth)

**Comment by TadasBaltrusaitis** [comment]
Hi,

The eye gaze error is the angle distance between two eye gaze vectors (ground truth and estimated). This can be computed as t, so if you have two vectors you can compute the angle using the formula from here - https://en.wikipedia.org/wiki/Dot_product#Geometric_definition

Thanks,
Tadas
