### ISSUE TITLE
Question when training my own landmarks model in Matlab.

### ISSUE THREAD

**Issue by yanhn** [TadasBaltrusaitis/OpenFace#211]
I'd like to find the landmarks of mouth, 20 pts rather than 68 pts.
I thoght I managed to generate the pdm model but got the wrong result when do the alignment use my own ccnf model. And below is the main  procedure I tried:
Firstly, I used **Collect_wild_annotations.m** function to parse "Helen" dataset of facial landmarks and save as XX.mat file.
Secondly, I used **Reconstruct_Torresani.m** to reconstruct the mouth data.
Thirdly, I used **Create_pdm_wild.m** to generate the corresponding pdm model .mat file.
After those I used **visualise_PDMs.m** to see if I generate pdm models correctly and here's what I got:
<img src=http://chuantu.biz/t5/115/1498270959x1020114780.png />

Then, in another [git project](https://github.com/TadasBaltrusaitis/CCNF) , I used **Prepare_data_wild_all.m** to prepare the data using the same dataset. 
Finally, I used **Script_Training_wild.m** to generate the final model.

During all these procedure I focused on the mirror index and made some fix to make program runnable.

But the output mostly shows zeros and occasionally occurs irregular pts.

While I'm reviewing my code, hoping some one can give some advice to help. Thanks.

**Comment by TadasBaltrusaitis** [comment]
Hi,

How were you running the program? You would need to initialize the newly trained model close to the actual mouth location, either by using some sort of mouth detector or by using the rest of 68 landmarks to provide an initial location. If you want to see some examples of how to initialize partial models like this, look at the `hierarchical_models` in the C++ code, or the `face_image_demo_eyes.m` file for Matlab example of how it works.

Thanks,
Tadas

**Comment by yanhn** [comment]
Hi Tadas
       I got the idea, I need to provide a rect around mouth before the points alignment, just like the whole face alignment. Thank you. And I'll check the code that you mentioned.

Thanks,
