### ISSUE TITLE
exception throw

### ISSUE THREAD

**Issue by ShirleyYim** [TadasBaltrusaitis/OpenFace#213]
Hi,
  I runned the program with vs2015 on windows 7. The landmarks detected successfully at the first time triggered the following exception though the detect result is right:
Exception thrown at 0x000007FEFC86A06D in FaceLandmarkVid.exe: Microsoft C++ exception: cv::Exception at memory location 0x0000000011BFD540.
   could you please help resolve the bug? thank you very much.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed, re-open if problem persists.
