### ISSUE TITLE
Install OpenFace on macOS.

### ISSUE THREAD

**Issue by sashulyak** [TadasBaltrusaitis/OpenFace#214]
Hi!

I'm trying to use OpenFace in my face detection project on macOS Sierra.
Making of examples goes fine. But I cannot find any guide how to use the library with external projects.

Could you add some CmakeLists.txt example?

**Comment by TadasBaltrusaitis** [comment]
Hi,

Sorry for the delay, please have a look at OSX installation instructions - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation

**Comment by sashulyak** [comment]
Oh, cool! Thank you!

**Comment by indur11** [comment]
hey, anyone if have time please help me. I am not been able to install open face in mac. I don't have any technical background , so i am looking for simple written instructions to install open face in mac m1

**Comment by bahadirbk** [comment]
@indur11 have u managed to install and run openface on m1 mac ?

**Comment by prasad-yashdeep** [comment]
I believe the solution doesn't work for M1 based macs
