### ISSUE TITLE
Coordinates for FeatureExtraction, suppress visualization

### ISSUE THREAD

**Issue by gvelchuru** [TadasBaltrusaitis/OpenFace#215]
Apologies if this has been answered already, but are the coordinates for face parts from FeatureExtraction measured from the top left of the image?

Additionally, I am using a setup with slow graphics, is it possible to suppress visuals while running FeatureExtraction?

**Comment by TadasBaltrusaitis** [comment]
The coordinates start from top left of the image (0,0) corresponds to top left corner.

To suppress the visualization/graphics use `-q` flag in the command line.

Thanks,
Tadas
