### ISSUE TITLE
how to train scpecial eyebrow patch expert? 

### ISSUE THREAD

**Issue by dedoogong** [TadasBaltrusaitis/OpenFace#216]
I'm trying to use OpenFace to detect landmarks of asian's faces , but weirdly, it frequently fails to find eyebrows. So, I think if I prepare asain's eyebrow ground truth landmark data + the corresponding images, I could improve the performance of the eyebrow patch experts. right?

Is it possible to run the train script only for the eyebrow parts?

Thank you!
Seunghyun Lee.

**Comment by TadasBaltrusaitis** [comment]
There are multiple ways to address this, first would be to just retrain the patch experts for the eyebrow landmarks using additional data (or even specific group target data). This would be fairly straightforward to do and you would just need to replace the patch experts for those landmarks with your trained ones. To train the specific ones you will need to use the Matlab CCNF code - https://github.com/TadasBaltrusaitis/CCNF

Another option would be to train an *eyebrow* model e.g. using an approach taken by - https://github.com/TadasBaltrusaitis/OpenFace/issues/211

Thanks,
Tadas
