### ISSUE TITLE
Is there a way to avoid face cropping and alignment?

### ISSUE THREAD

**Issue by Akabana01** [TadasBaltrusaitis/OpenFace#218]
Hello there.

Reading the command line options, I see no option to avoid cropping and alignment of the processed images. Is there a way around this? The images I am using are already aligned, and the processing done by FaceLandmarkImg.exe ruins this alignment. I am only interested in the landmark points, their coordinates in the same reference frame as the original images. 

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

The aligned and cropped images are optional, the landmark points output by `FaceLandmarkImg` are in the original image space and not in the cropped space, so running it should result in your desired output.

Thanks,
Tadas

**Comment by Akabana01** [comment]
Oh, I see. Now I feel like an idiot for asking; I should have double checked first. I am truly sorry for bothering you with this.

Thank you so much for taking the time to answer.
