### ISSUE TITLE
Why the program can not run normally  on windows10and VS2015?

### ISSUE THREAD

**Issue by Lqian72363** [TadasBaltrusaitis/OpenFace#22]
Hello, I downloaded zip.You said that we don't need to download anything additional to run the project, just open "OpenFace.sln" using Visual Studio 2015 and compile the code.I did it but failed.I wonder if there exists some details that i don't know.Cause when i open the "OpenFace.sln" ,VS tells that the project ''LandmarkDetector''comes from an untrusted location and when compile it, the VS cannot 
start the program 
''D:\OpencvProject\OpenFace-master\OpenFace-master\x64\Release\'LandmarkDetector.lib''
Can you tell me which step appears the problem?

**Comment by TadasBaltrusaitis** [comment]
The problem is that you are trying to execute LandmarkDetector which is a library and not an executable. See NOTE 2 in the following wiki page:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation#release-mode

Thanks,
Tadas

**Comment by priyanksharma477** [comment]
I downloaded and extracted openface binary for landmark detection in windows 64 bit. I ran FaceLandmarkVid application file on cmd, webcam opened successfully and the points were detected. But where is the output file stored with coordinate values? Also, I just need to detect ear points, how to do that?

**Comment by TadasBaltrusaitis** [comment]
Hi,

FaceLandmarkVid does not provide output files with landmark coordinates. Please see the following https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments and https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

**Comment by priyanksharma477** [comment]
Output Format says FaceLandmarkImg and FeatureExtraction create output text file. I ran these application from your zip, cmd opens, processes something then goes off. Nothing happens......Please help..

**Comment by TadasBaltrusaitis** [comment]
You also need to provide input files for them, the wiki provides instructions of how to do it. There is currently no version that provides output from a live stream.

**Comment by priyanksharma477** [comment]
Do I need to separately download FaceLandmarkImg code from you github to provide input file and get output file.?

**Comment by TadasBaltrusaitis** [comment]
All the code and binaries are packaged together, you should not need to download on of them separately.

**Comment by priyanksharma477** [comment]
Facial landmark points gives point number 3 and 15 close to ear lobe. But my project requires exact marker on the lobe. How can I get those coordinates because openface does not generate those points. Is there any way that I can calculate exact lobe coordinate given nearby landmark points?

**Comment by TadasBaltrusaitis** [comment]
The system does not do ear landmarks, you would need to retrain models specifically for ear lobe detection if you wanted to do that if you want exact ear lobe locations.

**Comment by priyanksharma477** [comment]
Hello. I am working on a project where I need exact ear lobe points. How can I modify your code to get those points as well in every poses. please help

**Comment by tanyasjeff** [comment]
Hello. I have several questions related to trying to get OpenFace to work on a windows machine. I have downloaded OpenFace_0.4.1_win_x86. The first question that I have is that I've seen mention here and there about using OpenFace.sln. However I've looked within my unzipped folder and I don't see anything called OpenFace.sln. Has this changed?

**Comment by TadasBaltrusaitis** [comment]
Hi,

You downloaded the executables and not the code, the will allow you to run OpenFace but not edit the source code, to get the source code you need to download it from github or clone the repository. There's a green `clone or download` button here - https://github.com/TadasBaltrusaitis/OpenFace
