### ISSUE TITLE
Head pose YPR range

### ISSUE THREAD

**Issue by srika91** [TadasBaltrusaitis/OpenFace#225]
Hello Sir,
What is the YPR range that can be obtained in head pose estimation?
regards

**Comment by TadasBaltrusaitis** [comment]
Best performance (less than 5 degrees error) is achieved +-30 degrees head turn (yaw), +-20 degrees chin up or down (pitch), and +-50 degrees head tilt (roll). Tracking is possible outside those ranges but the performance suffers somewhat.
