### ISSUE TITLE
AU_r vs AU_c consistency?

### ISSUE THREAD

**Issue by Bilabong67** [TadasBaltrusaitis/OpenFace#228]
Hi,
After a few tests with OpenFace, I have noticed that some outputs on AU seem strange.
For example, on certain frames of a video, I have say AU14_c=1 (i.e. AU is present) while AU14_r=0 (AU intensity is 0). Or vice versa.
How is this possible?
Thanks in advance for your precious help

**Comment by TadasBaltrusaitis** [comment]
Hi,

The methods for recognising AU presence and intensity are trained on different datasets (as some datasets, such as SEMAINE, only had presence labels), so the consistency is not guaranteed.

**Comment by Bilabong67** [comment]
Hi Tadas,

Thank you very much for your answer.

This is what I suspected regarding the consistency.

Is it correct to assume that AU_c have been trained on the AU_r databases (considering presence if AU intensity >=1, absence otherwise) + only presence databases?

Meaning AU_c should be more accurate than AU_r because they have been trained on more databases (assuming we only care for presence/absence)?

I am asking this because I want to deduce emotion presence from AU presence, so I would like to know if I should use AU_r or AU_c to achieve best possible accuracy

**Comment by TadasBaltrusaitis** [comment]
Yes, you're right, AU_c have been trained on more datasets, including all AU_r databases. With regards to accuracy, AU_r will be more accurate if you have access to a video of the same person that includes neutral expressions as the model callibrates to a particular person by inferring what the neutral expression looks like. If you are working on images then _c may give best accuracy.

**Comment by Bilabong67** [comment]
Great thanks! I am indeed interested by video analysis rather than image analysis.

But how is it that AU_c isn't more accurate on videos as well given it has been trained on more datasets? Why isn't the calibration applied to AU_c as well?

**Comment by TadasBaltrusaitis** [comment]
The type of calibration done is only possible for intensity prediction models, it corrects for the model consistently over or under predicting. This is not easily done for classification. In some cases AU_c will be more accurate if the target dataset is similar to one used for training the AU_c, but in practice I found regression models (AU_r) to be the most accurate ones.

**Comment by aydin006** [comment]
Hi Tadas,

I'm working on the pain score. Which one would be more accurate to study?
