### ISSUE TITLE
Link library for landmark detector- HELP

### ISSUE THREAD

**Issue by Jgaldos** [TadasBaltrusaitis/OpenFace#23]
Hi, I installed a tested the library with command calls and works perfectly. Now I'm trying to use it in a qt project and I'm having trouble with the API calls, i'm trying the code on the wiki section for landmark detector and I get the error
"OpenFace/build/lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectionValidator.cpp.o): undefined reference to symbol"

What I'm missing? This is my qt .pro confing

##opencv
INCLUDEPATH += /usr/local/include/opencv
LIBS += -L/usr/local/lib ##-lopencv_core -lopencv_imgcodecs -lopencv_highgui
LIBS += `pkg-config opencv --libs`

##landmark detector
INCLUDEPATH +=/home/pp/OpenFace/lib/local/LandmarkDetector/include 
LIBS += -L/home/pp/OpenFace/build/lib/local/LandmarkDetector -lLandmarkDetector

INCLUDEPATH +=/home/pp/OpenFace/lib/3rdParty/dlib/include 
LIBS+= -L/home/pp/OpenFace/build/lib/3rdParty/dlib -ldlib
LIBS += -pthread
CONFIG += link_pkgconfig
PKGCONFIG += x11

Thanks

**Comment by TadasBaltrusaitis** [comment]
I have not tested the project using qt so cannot help much here, it seems like the compiler is not able to link the the LandmarkDetector.a (is there a `/` missing?).

Have you compiled the LandmarkDetector project?

Maybe someone else with more qt experience could answer.

**Comment by Jgaldos** [comment]
I tested the command detector with command lines just like the installation guide shows, and it works fine. It must be a qt problem.
Did you test the API calls on Ubuntu 14.04? What IDE did you used?

**Comment by TadasBaltrusaitis** [comment]
I haven't explicitly tested the API on Ubuntu, I only tested the compilation and the test scripts from the Ubuntu installation guide (which do include the API calls themselves, so this would indicate that the API calls should work).

You can always try editing the code in one of C++ files that generates the executable (for example FeatureExtractor.cpp) and see if the API calls work.

As Ubuntu is not my development platform (I use Visual Studio on Windows) I haven't used an IDE for the tests.

Thanks,
Tadas

**Comment by Jgaldos** [comment]
Hi,  I solved the problem. It is more a ubuntu related problem, because I tested the API Call on mac and works without trouble. 

the problem is how LandmarkDetector.a is build, it build making all the call and links to 3rdParty libraries as a static library, QT shows errors because it doesn't find opencv and the others 3rdParty on ubuntu system (I'm still don't know why, I write all the path to the libraries on the Openface build).

So the solution is change all the library build from STATIC to SHARED on the opencv build and on your libs CMakelist.txt. This are all my change to make it work on ubuntu:

**eliminate old opencv **
sudo find /usr/ -name "*opencv*" -exec rm -rf {} \; 

**Compile Opencv as a dynamic library**
Clean build folder in opencv-3.1.0 with command mr -rf *
run cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_SHARED_LIBS=ON ..
run make -j6
run sudo make install

**Compile Openface as a dynamic library**
-modify dlib to make it a dynamic lib 
edit  OpenFace/lib/3rdParty/dlib/CMakeLists.txt
CHANGE add_library(dlib STATIC ${source_files} ) TO add_library(dlib SHARED ${source_files} )
-SAVE FILE

open OpenFace/lib/local/FaceAnalyser/CMakeLists.txt
CHANGE add_library( FaceAnalyser ${SOURCE} ${HEADERS}) TO add_library( FaceAnalyser SHARED ${SOURCE} ${HEADERS})
save file

open OpenFace/lib/local/LandmarkDetector/CMakeLists.txt
change add_library( LandmarkDetector ${SOURCE} ${HEADERS}) TO add_library( LandmarkDetector SHARED ${SOURCE} ${HEADERS})
ADD target_link_libraries(LandmarkDetector ${OpenCV_LIBS}  ${Boost_LIBRARIES}  ${TBB_LIBRARIES})


clean OpenFace/build with rm -rf *

cmake -D CMAKE_BUILD_TYPE=RELEASE ..

Thanks for answer me, I hope this help someone with the same problem.
Bye

**Comment by Jgaldos** [comment]
I forget, this is the .pro file for QT if someone needs it:

CONFIG += c++11
CONFIG += link_pkgconfig
PKGCONFIG += x11

PKGCONFIG += opencv
CONFIG += link_pkgconfig

TARGET = untitled

TEMPLATE = app



SOURCES += main.cpp \
    drawingfunc.cpp \
    strutcs.cpp \
    csuEBGMUtil.cpp \
    csuEBGMSimilarity.cpp \
    readfilefunc.cpp



# opencv
INCLUDEPATH += /usr/local/include
LIBS += -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_viz -lopencv_core


#boots
INCLUDEPATH += /usr/include/boost
LIBS += -L/usr/lib/x86_64-linux-gnu -lboost_filesystem -lboost_system -lIlmImf -lz -lHalf -ljasper -ltiff -lpng12

# dlib
INCLUDEPATH +=/home/pp/OpenFace/lib/3rdParty/dlib/include
LIBS += -L/home/pp/OpenFace/build/lib/3rdParty/dlib -ldlib
#LIBS += -lX11
#LIBS+=-DDLIB_NO_GUI_SUPPORT



# tbb
LIBS += -ltbb -ltbbmalloc -ltbbmalloc_proxy

# blas and lapack
LIBS += -llapack -lblas
#LIBS += -framework Accelerate

# openface
INCLUDEPATH +=/home/pp/OpenFace/lib/local/LandmarkDetector/include ##correcto para include landmark.h
LIBS += -L/home/pp/OpenFace/build/lib/local/LandmarkDetector -lLandmarkDetector
LIBS += -L/home/pp/Librerias/opencv-3.1.0/build/3rdparty/lib -llibwebp
LIBS += -L/home/pp/Librerias/opencv-3.1.0/3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64 -lippicv

LIBS += -pthread -ljpeg
LIBS += -ldl -fPIC

**Comment by TadasBaltrusaitis** [comment]
Glad you managed to resolve the problem and thanks for the instructions. I'm sure they'll be very helpful.

**Comment by shal233** [comment]
@Jgaldos : I am using ubuntu 14.04 and Qt5.6 as my platform. I compiled OpenCV-3.1 and OpenFace as a dynamic library as you suggested. cmake was successful. I encounter a problem when I do a 'make' in the build folder. The error is -
Linking CXX executable ../../bin/FaceLandmarkImg
/usr/bin/ld: warning: libicui18n.so.56, needed by //home/viki/src/Qt_new/5.6/gcc_64/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.56, needed by //home/viki/src/Qt_new/5.6/gcc_64/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.56, needed by //home/viki/src/Qt_new/5.6/gcc_64/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
//home/viki/src/Qt_new/5.6/gcc_64/lib/libQt5Core.so.5: undefined reference to `u_strToLower_56'
//home/viki/src/Qt_new/5.6/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_getStandardName_56' 
and a bunch of other undefined references..
I checked that libicui18n.so.56, libicudata.so.56 and libicuuc.so.56 are all present in the same path as /home/viki/src/Qt_new/5.6/gcc_64/lib/. LD_LIBRARY_PATH and PATH point out to Qt5.6's bin and lib folders. I am surprised what Qt has to do with OpenFace build. Since the programs were created in MSVS, there is a problem compiling them? Do I have to create .pro files for all the programs? I am new to these stuff. Can you please help me?

**Comment by Jgaldos** [comment]
Hi, could you post your .pro file? I think it has something to do with that...

**Comment by shal233** [comment]
I found the reason for the problem and fixed it. Apparently, the cmake used was a different version than that is in Qt 5.6. So I copied Qt5.6 cmake to the default cmake path and updated Qt path in .bashrc file. sudo apt-get update && sudo apt-get upgrade did magic. :P

**Comment by danielng01** [comment]
Hello guys I get this error when I was trying to build Iris under Ubuntu.
I solved it by removing
CONFIG += static
from the .pro file

**Comment by ChrizzyM87** [comment]
Thanks a lot Jgaldos ! Your instructions for building OpenFace as a shared library helped me a lot!
I got an Seg. Fault error at the constructor of the FaceAnalyser after linking the GNU Scientific Library. Using OpenFace as shared library solved the problem!
