### ISSUE TITLE
opencv error in clm-z processing.

### ISSUE THREAD

**Issue by cnsla** [TadasBaltrusaitis/OpenFace#230]
when I select clm-z in commandline processing, it shows the error below.
I am working on OS X sierra.

"Starting tracking
OpenCV Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array') in arithm_op, file /tmp/opencv3-20161231-93843-1a11dpc/opencv-3.2.0/modules/core/src/arithm.cpp, line 659
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20161231-93843-1a11dpc/opencv-3.2.0/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op"

**Comment by TadasBaltrusaitis** [comment]
Hi,

You will have to be more specific. What are the exact command line arguments are you using?

Thanks,
Tadas

**Comment by cnsla** [comment]
./Featureextraction -f /Volumes/Documentary/Model_Testing/$CurVid.mp4 -of /Volumes/Documentary/Model_Testing/clmz/$CurVid'_clmz.txt' -simalign /Volumes/Documentary/Model_testing/clmz/$CurVid'_clmz'/ -hogalign /Volumes/Documentary/Model_testing/clmz/$CurVid'_clmz.hog' -mloc "model/main_clm-z.txt"


It was my command.
i used CurVid as variable to… (i.e. export CurVid=test.mp4)

Bests,
J.

**Comment by TadasBaltrusaitis** [comment]
I see what the issue is, CLM-Z model is not compatible with facial expression analysis (Action Unit recognition), hence the executable fails. I will fix this in the future versions of the code.

Is there any reason you are using the CLM-Z model? The newer clnf models are much more accurate.

**Comment by cnsla** [comment]
Thanks for the update.

There is no specific reason to use CLM-Z.
I wanted to try it to compare the performance in faces with (sometimes) very complex background.
(i.e. movies)

**Comment by TadasBaltrusaitis** [comment]
CLM-Z will not help with background issues if you do not have a depth stream to accompany the video, your best bet at the moment is CLNF

**Comment by TadasBaltrusaitis** [comment]
You can now use CE-CLM model which should be more resistant to complex backgrounds.
