### ISSUE TITLE
compile for arm

### ISSUE THREAD

**Issue by XHuaSheng** [TadasBaltrusaitis/OpenFace#231]
Hello Tadas, I want to transplant Openface to ARM, I have cross compiled OpenCV, Boost and DLIB. But there is a problem with compiling TBB. Is there a way to replace TBB, or do not use TBB. Looking forward to your reply.

**Comment by TadasBaltrusaitis** [comment]
The TBB dependency makes things quite a bit faster, but you could take it out and replace the TBB parallel for loops with regular loops, or by using OpenMP (an example of how to use OpenMP is in `PatchExperts.cpp`

**Comment by waterball2016** [comment]
I remember that the compilation output of opencv contains TBB.
Can you get real-time performance on ARM? I haven't tried it yet, but I'm a little worried about it.

**Comment by JimSEOW** [comment]
@XHuaSheng can you share the ARM folk?

**Comment by George-NET** [comment]
@XHuaSheng  could you pls share the ARM folk thanks.

**Comment by XHuaSheng** [comment]
@TadasBaltrusaitis Thanks for your reply. that helped me a lot. I have implemented the transplant on ARM, but the speed is slow, I can not get real-time performance.

**Comment by TadasBaltrusaitis** [comment]
Have you tried using OpenMP to parallelise some of the code? As real-time performance requires parallelising some of the computations.

**Comment by lzwhard** [comment]
Hi,XHuaSheng

I found it very slow on the platform of Hi3516, where it took about 500s to run FaceLandmarkImg to detect one picture. How about your result? slower than me or faster?

tks,
lzw

**Comment by dingjunhang** [comment]
Hi，lzwhard
it took about 40s to run FaceLandmarkImg to detect one picture on the platform of Hi3536.
tks,
ding

**Comment by XHuaSheng** [comment]
@TadasBaltrusaitis 
HI，Tada   I have changed the code to be this in LandmarkDetectorModel.cpp:
                #ifdef _OPENMP
		#pragma omp parallel for
		#endif
		// Do the hierarchical models in parallel
		for(int part_model =0 ; part_model<hierarchical_models.size() ; part_model++)
		/////////////tbb::parallel_for(0, (int)hierarchical_models.size(), [&](int part_model)//////xhs

I'm not sure this is right or not.  

And when cross compile I used this command:  cmake -fopenmp -D CMAKE_BUILD_TYPE=RELEASE ..  
The results did not change significantly.

Could you give me some advice?  Thanks for you .

**Comment by XHuaSheng** [comment]
@lzwhard 能留个联系方式吗，用英语有点费劲。。。

**Comment by lzwhard** [comment]
qq 739544972

**Comment by TadasBaltrusaitis** [comment]
The more important part where openMP would help is in `PatchExperts.cpp` in the `Response` function, you also need to make sure that _OPENMP is defined in macros.

Thanks,
Tadas

**Comment by WasonWood** [comment]
using a 21 points model, FaceLandmarkVid can go to 60+ fps on my iPhone6 without TBB & OpenMP

**Comment by XHuaSheng** [comment]
@WasonWood   Wow that's great. Could you tell me more details about the 21-point model? Do I need to train this model by myself? How can i replace and use it?  waiting for your reply

**Comment by WasonWood** [comment]
#211

**Comment by hewolde** [comment]
hi,
Can you please post how to build openface from a Dockerfile in ARM board with Ubuntu 16.04 in a docker container? I am not sure which base image to use in the Dockerfile for ARM architecture.
Thanks

**Comment by TadasBaltrusaitis** [comment]
I have not tried building OpenFace for ARM architecture, it seems like a blocker would be compiling TBB and possibly BLAS, you would need to remove that functionality in order to build for ARM.

**Comment by santo4ul** [comment]
Hi, Is there any update on this? I couldn't find any `PatchExperts.cpp` as mentioned above. Has the code base changed since this issue was raised?

Thank you.

**Comment by santo4ul** [comment]
Looks like OpenFace 2.1.0 onwards, TBB support has been removed. Is it safe to assume that 2.1.0 can be compiled on ARM without any issues?

`  * Removing TBB dependency (#590)`

Thanks,
San

**Comment by TadasBaltrusaitis** [comment]
The code has indeed change and the TBB dependancy has been removed, and I see you managed to build for ARM from your other raised issue (https://github.com/TadasBaltrusaitis/OpenFace/issues/668), is it safe to close this issue as well?

**Comment by santo4ul** [comment]
@TadasBaltrusaitis I think it is safe to close this issue.
