### ISSUE TITLE
How to speed up the landmark detection

### ISSUE THREAD

**Issue by waterball2016** [TadasBaltrusaitis/OpenFace#233]
Really great work. the landmarks detected are quite stable.

I tried the openface on my laptop, time cost on landmark detection (without face detection) is about 90ms. Is there any trick to speed it up?

**Comment by TadasBaltrusaitis** [comment]
A number of them will result in reduction of accuracy, but you could look at:
https://github.com/TadasBaltrusaitis/OpenFace/issues/38
