### ISSUE TITLE
Add Anaconda warning for compiling OpenCV

### ISSUE THREAD

**Issue by NumesSanguis** [TadasBaltrusaitis/OpenFace#237]
When Anaconda is installed, somehow OpenCV finds the outdated GCC 4.x instead of GCC 5.4, according to: https://stackoverflow.com/questions/40322301/compile-opencv-3-on-ubuntu-16-04-linking-error-usr-lib-x86-64-linux-gnu-libsox

This results in OpenFace giving the error:
usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status

Could you add a warning to the installation docs so that people won't be struggling with this issue?

And maybe make it a bit more clearer 20161018AM_Session3_P1.avithat there is an install script for Ubuntu 16.04 (I read over it and spend a long time following the instructions of other versions)
E.g.: Make a Heading with Ubuntu 16.04 and just put `./install.sh` under it.

**Comment by TadasBaltrusaitis** [comment]
Thanks for the suggestions!

**Comment by ying86615791** [comment]
the building of dlib will search the variable $PATH, if anaconda path is added to $PATH, then it will automaticlly add dependencies (e.g., lib...).
just remove anaconda path ("/home/hy/anaconda2/bin" for me) from $PATH,
then rebuild dlib,
finally, it works
