### ISSUE TITLE
General Question - Can we overlay 3D objects on face by tracking the head pose ?

### ISSUE THREAD

**Issue by farazirfan47** [TadasBaltrusaitis/OpenFace#239]
I am working on an AR project and decided to use openFace because awesome work done in openFace, I just want to know can I overlay some 3D objects on face in real time ? I want to integrate it with unity.

**Comment by TadasBaltrusaitis** [comment]
Thanks for taking an interest in OpenFace. OpenFace can provide you with the 3D and 2D locations of facial landmarks (given the focal length), so you could use that information to do 3D object overlay on the face in real time, check out 'FaceLandmarkVid' executable and the wiki to see how to get landmark locations in real time from a webcam or a video file.

**Comment by farazirfan47** [comment]
Thanks
