### ISSUE TITLE
The coordinate returned by EstimateGaze()

### ISSUE THREAD

**Issue by deepakakkil** [TadasBaltrusaitis/OpenFace#24]
I did not see this information anywhere in the paper.  What is the coordinate system used by the estimategaze(), My initial tests show gaze.X and gaze.Y varies between -0.50 to +0.50 in normal laptop use scenario (as seen through built in camera of the laptop).  What is the origin of the coordinate system (camera origin or egocentric) ? 

Also, is there any built in way to translate this to screen coordinates ?

**Comment by TadasBaltrusaitis** [comment]
The EstimateGaze() function returns a 3D gaze vector from the eye in the camera coordinate system (camera origin is `0,0,0`. Hope this answers your question.

There is no built in version for screen coordinates. That would require knowing the relative position of the camera and the screen.
