### ISSUE TITLE
make error,  redefinition of argument 

### ISSUE THREAD

**Issue by wjtan99** [TadasBaltrusaitis/OpenFace#244]
At the make step, I ran into this error, 

[ 87%] Building CXX object exe/FaceLandmarkVidMulti/CMakeFiles/FaceLandmarkVidMulti.dir/FaceLandmarkVidMulti.cpp.o
Linking CXX executable ../../bin/FaceLandmarkVidMulti
[ 88%] Building CXX object lib/local/FaceAnalyser/CMakeFiles/FaceAnalyser.dir/src/FaceAnalyser.cpp.o
In file included from /usr/local/include/boost/next_prior.hpp:20:0,
                 from /usr/local/include/boost/utility.hpp:19,
                 from /usr/local/include/boost/range/size.hpp:25,
                 from /usr/local/include/boost/range/functions.hpp:20,
                 from /usr/local/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/local/include/boost/range/iterator_range.hpp:13,
                 from /usr/local/include/boost/range/as_literal.hpp:22,
                 from /usr/local/include/boost/algorithm/string/trim.hpp:19,
                 from /usr/local/include/boost/algorithm/string.hpp:19,
                 from /home/ubuntu/opensource/OpenFace/lib/local/FaceAnalyser/src/FaceAnalyser.cpp:50:
/usr/local/include/boost/core/enable_if.hpp:33:10: error: redefinition of default argument for ‘class T’
   struct enable_if_c {

My env is Ubuntu 14.04 LTS, python 3.4, Cuda 8.0, boost-1.56.0, opencv-3.1.0.  
What could be the problem?   Thanks a lot.

**Comment by TadasBaltrusaitis** [comment]
Can you try down-grading boost to 1.55.0, as I had issues with dlib clashing with boost with newer versions (https://github.com/TadasBaltrusaitis/OpenFace/issues/242).

Thanks,
Tadas

**Comment by wjtan99** [comment]
Hi, Tadas, 
Thanks for your quick reply.  After I posted the question, I disabled the dlib under directory 3rdparty by editing the cmake file and installed dlib 19.6.  Now the above error was gone but had the new error  

/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp: In function ‘int main(int, char**)’:
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp:284:11: error: ‘tbb’ was not declared in this scope
    vector<tbb::atomic<bool> > face_detections_used(face_detections.size());
           ^
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp:284:29: error: template argument 1 is invalid
    vector<tbb::atomic<bool> > face_detections_used(face_detections.size());
                             ^
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp:284:29: error: template argument 2 is invalid
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp:284:51: error: invalid type in declaration before ‘(’ token
    vector<tbb::atomic<bool> > face_detections_used(face_detections.size());
                                                   ^
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp:287:4: error: ‘tbb’ is not a class, namespace, or enumeration
    tbb::parallel_for(0, (int)clnf_models.size(), [&](int model){
    ^
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp: In lambda function:
/home/ubuntu/opensource/OpenFace/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp:308:44: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
       if(face_detections_used[detection_ind].compare_and_swap(true, false) == false)
                                            ^
make[2]: *** [exe/FaceLandmarkVidMulti/CMakeFiles/FaceLandmarkVidMulti.dir/FaceLandmarkVidMulti.cpp.o] Error 1
make[1]: *** [exe/FaceLandmarkVidMulti/CMakeFiles/FaceLandmarkVidMulti.dir/all] Error 2

It means that tbb is not defined.  
Can you advice the version of your boost, dlib, and tbb?  

Thanks a lot.

**Comment by TadasBaltrusaitis** [comment]
You need to include the line `#include <tbb/tbb.h>` in the `FaceLandmarkVidMulti.cpp`, as it was being included by my modified version of dlib

**Comment by wjtan99** [comment]
Hi, 
I changed the CMakeLists.txt to not use boost in system. Instead, I used the one under 3rdparty. Now it can compile and build without problem.  when I ran 

./bin/FaceLandmarkImg -fdir "../samples/" -ofdir "./demo_img/" -oidir "./demo_img/" -wildSegmentation fault (core dumped)
I have seg fault.   Do you have any suggestions?  

Thanks a lot again.

**Comment by wjtan99** [comment]
I uninstalled boost 1.65.0 and use the default boost 1.54.0 in my system. Now it works.  
Thanks for your help.
