### ISSUE TITLE
How i can get full image with face points and gaze cube? 

### ISSUE THREAD

**Issue by palich12** [TadasBaltrusaitis/OpenFace#245]
I want get full image with face points and gaze vectors and cube, like in demo 
https://github.com/TadasBaltrusaitis/OpenFace/blob/master/imgs/au_sample.png

**Comment by TadasBaltrusaitis** [comment]
This is currently only supported for videos, run either `FaceLandmarkVid` or `FaceLandmarkVidMulti` with a video file or a webcam. For more detailed information please see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by palich12** [comment]
Ok, thanks
