### ISSUE TITLE
Why fail to track lower lip when mouth is opened?

### ISSUE THREAD

**Issue by itminner** [TadasBaltrusaitis/OpenFace#246]
Thank you for making such a great project, the facemark tracking is more stable.
One problem is, when mouth open, lower lip facemarks can not follow.
I learned this is a known issue, but I want to know the reason. Can I fix this issue myself?
Many thanks : )

**Comment by itminner** [comment]
I have tried to increase the size of interest area, retrain patch expert with my data, but it didn't help.

**Comment by TadasBaltrusaitis** [comment]
The new version should be able to track lips better.

**Comment by R00iBaard** [comment]
What was the fix for this? I am experiencing this at the moment running the latest version. I am running model/main_clm_general.txt as well as haar face detection with "use_face_template" enabled to run as light as possible on rpi.

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, the main_clm_general model is the issue, you would need to use the newer models (either CLNF or ideally CEN) for better lower lip tracking, however they are much slower and probably unsuitable fro rpi.
