### ISSUE TITLE
ttb project file is lost in solution

### ISSUE THREAD

**Issue by palich12** [TadasBaltrusaitis/OpenFace#247]
Threading Building Blocks project file is lost in solution. So I can't rebuilt it to v141 toolset in VS 2017

**Comment by TadasBaltrusaitis** [comment]
What do you mean the project file is lost? You could use already precompiled TBB dll's and libs for VS 2017 from https://github.com/01org/tbb/releases

**Comment by palich12** [comment]
Ok, thanks
