### ISSUE TITLE
Possibility for real time AU labelling?

### ISSUE THREAD

**Issue by Bilabong67** [TadasBaltrusaitis/OpenFace#248]
Well, everything is in the title :)
Is OpenFace capable of doing real-time labelling / coding of Action Units, e.g. from a webcam stream?

If so, how can this be achieved?

Many thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

Not by default. as there is some post-processing of AU predictions after the whole video is done, making them more accurate. You could always just provide the webcam feed to the `FeatureExtraction` executable (will require changing the code a bit). However, it will not be as accurate as the offline version.

Thanks,
Tadas

**Comment by Bilabong67** [comment]
Thank you! By any chance, could you tell me if it is possible to make OpenFace calls directly in python?

**Comment by TadasBaltrusaitis** [comment]
Not just yet, but I'm hoping to include that functionality eventually.

**Comment by amogh112** [comment]
@Bilabong, could you make real time AU labelling work?

**Comment by Bilabong67** [comment]
Nope, but if you are able to do it I would be very interested in your
solution! Thanks
ᐧ

2018-03-02 10:32 GMT+01:00 amogh112 <notifications@github.com>:

**Comment by TadasBaltrusaitis** [comment]
Current version of OpenFace now supports real time AU extraction from a webcam using `FeatureExtraction` or `FaceLandmarkVidMulti` executables.
