### ISSUE TITLE
Binary failed to run on windows 8.1 

### ISSUE THREAD

**Issue by RafficMaleo** [TadasBaltrusaitis/OpenFace#251]
Hello , 

I am unable to run the .exe files even after installing the 64 bit C++ redistributable package.I do not want to compile the source.

**Comment by TadasBaltrusaitis** [comment]
Hi,

What exact issue are you encountering, what is the command you used? Did you try both the 32 and 64 bit binaries?

Thanks,
Tadas

**Comment by RafficMaleo** [comment]
Yes. i did . i run these from the command line 1-FaceLandmarkVid ,2- FaceLandmarkVidMulti , 3- FeatureExtraction
![image](https://user-images.githubusercontent.com/273251/30658485-51004288-9e2a-11e7-91b5-73c9a89f5e67.png)

**Comment by TadasBaltrusaitis** [comment]
What command line arguments did you provide?

**Comment by RafficMaleo** [comment]
1- FaceLandmarkVid -f medicals.png
2- FaceLandmarkVid -device 

All these failed to run.

**Comment by TadasBaltrusaitis** [comment]
`FaceLandmarkVid` executable is intended for videos and not images, try providing it with a video file (using the full path to it, and using quotation marks if there are spaces to it, e.g. `FaceLandmarkVid -f "C:\location dir\my_file.avi`). 

Also when using `-device` flag you need to specify the camera number, e.g. `-device 0`, the first webcam is assumed by default, so you should run it as `FaceLandmarkVid.exe` without any parameters and it will run from the first webcam (make sure the webcam is connected though).

Also try installing the visual C++ 2015 redistributable (both 32 and 64 bit versions).

Thanks,
Tadas
