### ISSUE TITLE
Can't find "OpenFace.sln"

### ISSUE THREAD

**Issue by sbchung** [TadasBaltrusaitis/OpenFace#252]
I downloaded the windows binaries in the page:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation

with the link
https://github.com/TadasBaltrusaitis/OpenFace/releases/download/OpenFace_v0.2.3/OpenFace_0.2.3_win_x64.zip

after unzipping it, I can't find the "OpenFace.sln". Where can I find it?

Thank You :)

**Comment by TadasBaltrusaitis** [comment]
The windows binaries do not include the `OpenFace.sln` file as they are intended to just be used, the solution file allows you to compile the newest version of the code yourself. To find it download the project code (by either cloning it with git or downloading directly.
