### ISSUE TITLE
The output txt file of gaze is what?

### ISSUE THREAD

**Issue by HouseCui** [TadasBaltrusaitis/OpenFace#253]
In this programe the output file of gaze ,the gaze_0_x and gaze_1_x is the left and right eye gaze estimate?
But when I turn the head the data is not similar with the fixed head。In the two videos I staring at the same point.

**Comment by TadasBaltrusaitis** [comment]
Yes, they correspond to different eyes, averaging them will lead to a bit more robust gaze vector. 

The vectors will not always be accurate, especially when the head is turned as the eyes are not any more visible.

Thanks,
Tadas

**Comment by HouseCui** [comment]
Why when the head is turned the eyes vectors are not accurate?

**Comment by TadasBaltrusaitis** [comment]
It is a more challenging problem, less of the eye is visible, so detecting the iris becomes more challenging and this leads to less accuracy.

I am not sure I understand your second question though.

-Tadas

**Comment by HouseCui** [comment]
The second question is if I want to know where my view point falls in the specific area on the computer screen what data do I need to know ? And how to count it.

Thanks
Cui

**Comment by palich12** [comment]
Can i get accuracy value for gaze vectors in curient frame?

**Comment by TadasBaltrusaitis** [comment]
OpenFace does not provide gaze targets on the screen, as that requires calibration of camera to the screen. But it would be a nice extension to the tool eventually.

What do you mean by "accuracy value for gaze"? Do you mean a confidence measure? If so OpenFace does not have a way of knowing how accurate the gaze estimation is at a current frame, but there is a confidence measure of face tracking that you could use instead.
