### ISSUE TITLE
Problems with Opencv 2.4.11

### ISSUE THREAD

**Issue by vicapve** [TadasBaltrusaitis/OpenFace#254]
Dear Tadas

I've tried your code in opencv 3 and it works. I make several modifications for performing face recognition in the frequency domain. However, I'm interesting in running this code in opencv 2.4.11. but I have some errors in:

// Do the hierarchical models in parallel
tbb::parallel_for(0, (int)hierarchical_models.size(), [&](int part_model){		{
// Only do the synthetic eye models if we're doing gaze
if (!( (hierarchical_model_names[part_model].compare("right_eye_28") == 0 || hierarchical_model_names[part_model].compare("left_eye_28") == 0) &&
 !params.track_gaze))
  {

it seems that dimensions do not correspond, here is:
OpenCV Error: Assertion failed (!src[i].empty() && src[i].dims <= 2 && src[i].cols == src[0].cols && src[i].type() == src[0].type()) in vconcat, file .../opencv-2.4.11/modules/core/src/matrix.cpp, line 1794

Do you have any idea?
Thanks

**Comment by TadasBaltrusaitis** [comment]
I think that might be an issue with vconcat semantics between OpenCV 3 and 2.4 differing as the older version is not able to append to an empty matrix. You would have to rewrite that vconcat usage in order to use an older version of OpenCV.

-Tadas

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue persists.
