### ISSUE TITLE
for statement expected before 'tbb'

### ISSUE THREAD

**Issue by Kindpire** [TadasBaltrusaitis/OpenFace#255]
in file Patch_expertes.cpp line 164.
for statement expected before 'tbb'
I think once we enabled tbb, the openmp are not necessary.

**Comment by TadasBaltrusaitis** [comment]
You're right, that's a hangover from an earlier version that used OpenMP for parallelization instead of TBB, however as it is not a for loop the OpenMP statement doesn't really do anything.

**Comment by Kindpire** [comment]
Yes. "#pragma omp parallel for" should be followed with a for loop, but find a tbb function.
