### ISSUE TITLE
Make failed at 91% on Mac

### ISSUE THREAD

**Issue by surya00060** [TadasBaltrusaitis/OpenFace#256]
[ 64%] Built target dlib
[ 79%] Built target LandmarkDetector
[ 89%] Built target FaceAnalyser
[ 91%] Linking CXX executable ../../bin/FaceLandmarkImg
Undefined symbols for architecture x86_64:
  "cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)", referenced from:
      LandmarkDetector::DetectFaces(std::__1::vector<cv::Rect_<double>, std::__1::allocator<cv::Rect_<double> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&) in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
  "cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      _main in FaceLandmarkImg.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/FaceLandmarkImg] Error 1
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
make: *** [all] Error 2

**Comment by TadasBaltrusaitis** [comment]
It looks like an issue of linking to OpenCV, and the model is not able to find it. Make sure OpenCV is installed.

**Comment by surya00060** [comment]
i have installed opencv 3.3.0.3

**Comment by surya00060** [comment]
I uninstalled Anaconda and then code ran successfully .
Thanks .
