### ISSUE TITLE
Installing in OSX 10.11.6

### ISSUE THREAD

**Issue by vegahu** [TadasBaltrusaitis/OpenFace#258]
Hi!

I would like to share how I get it to work on my system in case it's useful for someone else because I have some issues with boost.
I follow the instructions on the wiki with some little changes, mainly I downloaded boost 1.64 manually and change a couple of lines in CMakeCache.txt because i get this error:

```
make[2]: *** No rule to make target `/usr/local/lib/libboost_filesystem-mt.dylib', needed by `bin/FaceLandmarkImg'.  Stop.
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
make: *** [all] Error 2
```

TBB AND OPENCV3

```
brew install tbb opencv3
./bootstrap.sh 
```
DOWNLOAD AND INSTALL BOOST 1.64

```
boost_1_64_0$ ./b2
boost_1_64_0$ ./b2 install
```

OPENFACE
```
OpenFace-master$ cmake -D CMAKE_BUILD_TYPE=RELEASE
```

MODIFY file CMakeCache.txt

Replace this:

//Boost filesystem library (debug)
Boost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_filesystem-mt.dylib

//Boost filesystem library (release)
Boost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libboost_filesystem-mt.dylib

With this:

//Boost filesystem library (debug)
Boost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_filesystem.dylib

//Boost filesystem library (release)
Boost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libboost_filesystem.dylib

And finally:
```
OpenFace-master$ make
```

Thanks for make this available to all!

Hugo

**Comment by TadasBaltrusaitis** [comment]
Thanks for the instructions! I'm sure they will be helpful to people, I included a link to them in the wiki.

**Comment by JadonMing** [comment]
```
//Boost system library (debug)
Boost_SYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_system.dylib

//Boost system library (release)
Boost_SYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libboost_system.dylib
```
Well noted that this also need to be amended. Took me a while to spot this.

**Comment by hanton** [comment]
hi @vegahu , there is a typo in
`OpenFace-master$ cmake -D CMAKE_BUILD_TYPE=RELEASE` -> `OpenFace-master$ cmake -D CMAKE_BUILD_TYPE=RELEASE .`

:)
