### ISSUE TITLE
Action units Intensities are Negative

### ISSUE THREAD

**Issue by rajithan** [TadasBaltrusaitis/OpenFace#260]
I saw that action unit's intensity values are negative. How this be possible. In the document it says, it should be between 0 -- 5.

**Comment by TadasBaltrusaitis** [comment]
It should not happen, are those the values in the output file? It is possible that the intermediate steps output negative values, that later get corrected in the post-processing.

**Comment by rajithan** [comment]
Yes, the values are in the output file.  Any idea how to resolve that

**Comment by TadasBaltrusaitis** [comment]
Is it possible for you to share the video for reproducing the bug, as I would like to fix it.

**Comment by rajithan** [comment]
Unfortunately, I am unable to share the data. I was thinking, if the face tracking is breaking, then the regression task for actions units having problem.

**Comment by TadasBaltrusaitis** [comment]
If you could reproduce the same issue on public data, let me know so I could have a look at that issue.

-Tadas

**Comment by 854811200** [comment]
I also get negative value on Action Unit (especially on AU01,02,04)
when I test
./build/bin/FeatureExtraction -f path_of_video -vis-aus -aus
the video is downloaded from 
https://www.youtube.com/watch?v=DLvUUMo4OLA

OS:macOS High Sierra 10.13.6 (17G3025)
OpenCV version:3.4.3_1
wait for your reply,thanks

**Comment by TeddyAlbina** [comment]
Well i have the same problem i integrate openface in aws lambda and gets negative AUs, i copy paste the code of FeatureExtraction  minus everything that output csv.
