### ISSUE TITLE
pupil coordinates is lost in output of FaceLandmarkImg

### ISSUE THREAD

**Issue by palich12** [TadasBaltrusaitis/OpenFace#261]
FaceLandmarkImg output files contain gaze vectors but havent's coordinates of pupils or centes of eyes apples. How i can get it?

**Comment by TadasBaltrusaitis** [comment]
They do not in the current version, the next version will include them. Currently the only way to access them is through the code.

-Tadas

**Comment by palich12** [comment]
Ok, but i see it on output image, may be, it bosible get it by calc average coordinates of some face points?

**Comment by TadasBaltrusaitis** [comment]
You won't be able to calculate them from the coordinates output to the file by the current version, the only way to access them at the moment is by modifying the C++ code.

**Comment by palich12** [comment]
Okey, so i will be waiting next version. may be you need some help for it?

**Comment by TadasBaltrusaitis** [comment]
This has been fixed
