### ISSUE TITLE
The gaze estimaton is direction vector

### ISSUE THREAD

**Issue by HouseCui** [TadasBaltrusaitis/OpenFace#263]
Hello Tadas：
First I want to say the OpenFace is a very practical a framework。And I want to do somthing in gaze
estimation。

For the gaze of the output data can I understand that the head posture is the same as the angle of the left and right eyes? Such as the head position in the X = pitch, Y = yaw, Z = roll? And if I can use these code to calculate the angle:

`
        int yaw = (int)(pose_estimate_to_draw[4] * 180 / 3.1415926 + 0.5);
       
        int roll = (int)(pose_estimate_to_draw[5] * 180 / 3.1415926 + 0.5);

	int pitch = (int)(pose_estimate_to_draw[3] * 180 /3.1415926 + 0.5);

	std::cout<<"yaw:"<<yaw<<"roll:"<<roll<<"pitch:"<<pitch<<endl`

**Comment by TadasBaltrusaitis** [comment]
Hi,

Glad you are finding OpenFace useful. You are right about head pose angles, they represent pitch, yaw, and roll. The code for angle calculation looks correct.

Thanks,
Tadas
