### ISSUE TITLE
landmark detection with provided bounding box of faces

### ISSUE THREAD

**Issue by lbwang2006** [TadasBaltrusaitis/OpenFace#265]
hi, how to detect landmarks with provided bbox of faces？

**Comment by TadasBaltrusaitis** [comment]
For C++ version have a look at the wiki https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#facelandmarkimg, specifically the `-fdir` command.

For Matlab you could modify one of the experiment scripts that load a list of bounding boxes and corresponding images (e.g. `Script_CLNF_wild_iccv.m`)

**Comment by TadasBaltrusaitis** [comment]
You can now use `-bboxdir` flag to specify directory with bounding boxes of faces.
