### ISSUE TITLE
Link Error when Compiling on Visual Studio 2017

### ISSUE THREAD

**Issue by kneupper** [TadasBaltrusaitis/OpenFace#267]
I have selected FaceLandmarkImg as the startup project. I have all of the Windows binaries downloaded. However, I get an error when trying to build with the description "cannot open file 'libboost_filesystem-vc141-mt-gd-1_60.lib'". I have successfully located this library on my computer and added the path to the project's library directories. I realize that it may have something to do with running VS2017 instead of 2015. Any thoughts on what might be going wrong? 
![error message](https://user-images.githubusercontent.com/32854782/31638815-a07b97d0-b2a3-11e7-866f-9eb06785e6ac.PNG)

**Comment by TadasBaltrusaitis** [comment]
Using Visual Studio 2017 might be an issue, all of the 3rd party libraries (OpenCV, boost, TBB) have been compiled for VS2015 and might not be compatible with VS2017, you will need to compile or find binaries to those libraries and link to them accordingly.
