### ISSUE TITLE
Crop image face without facial landmarks

### ISSUE THREAD

**Issue by pvskand** [TadasBaltrusaitis/OpenFace#268]
I have run the code using the following command `FaceLandmarkImg.exe -wild -fdir "../samples/" -ofdir "../matlab_runners/demo_img/" -oidir "../matlab_runners/demo_img/" `. I just need the cropped out image of the person and not the cropped out image with the facial landmarks. Is there a way to do that?

**Comment by TadasBaltrusaitis** [comment]
For that you will either need to modify the visualization code, or use the output `.pts` files to crop out the image yourself.

**Comment by pvskand** [comment]
Yeah I was trying to look for the coordinates in `.pts` file but couldn't find the bounding box coordinates. Which one are they?

**Comment by TadasBaltrusaitis** [comment]
It's not directly in the `.pts` file, but you can find the minimum and maximum of the 2D `x` and `y` landmark locations, which will provide you a bounding box.
