### ISSUE TITLE
How to get the confidence value?

### ISSUE THREAD

**Issue by redjpx** [TadasBaltrusaitis/OpenFace#270]
Hi Tadas,

Your open source project is really a masterpiece! It is amazing. One simple question here. I am working on the OpenFace_v0.1. I got output files from OpenFace.exe. One record of dataset.pose shows:
frame,success,**confidence**,pose_X(mm),pose_Y(mm),pose_Z(mm),pitch(rad),yaw(rad),roll(rad)
0,1,**0.846**,4.027,31.591,190.235,0.018,0.100,-0.037
I could not figure the confidence value out. Could you please share me the way to how to get it? Or any algorithm?
I looking forward to your reply. Thanks a lot!

**Comment by TadasBaltrusaitis** [comment]
Thanks for taking an interest in OpenFace. Confidence indicates how well the model things face tracking went, it is estimated during a validation step. I think the version 0.1 uses a support vector machine for this, but newer versions use a convolutional neural network, you can find a bit more detail here - https://github.com/TadasBaltrusaitis/OpenFace/blob/master/matlab_version/face_validation/readme.txt

Typically, I interpret confidence below 0.7 as a failure in landmark detection.

**Comment by pranavsdev** [comment]
Hi Tadas,

Is it possible to cite this information (convolutional neural network are used to calculate the confidence) from any published paper?

**Comment by TadasBaltrusaitis** [comment]
Hi,

This paper describes the neural networks used for response map computation (the predictions of which are summed to get overall confidence) - https://arxiv.org/pdf/1611.08657.pdf
