### ISSUE TITLE
How to do if to reduce the landmark points?

### ISSUE THREAD

**Issue by zhuyong999** [TadasBaltrusaitis/OpenFace#271]
Hi,
     I  don't need so much  68 Facial Landmark points , the main reason is that  much time to cost when detecting the  68 landmark points , can i only detect 20 or 30 according to my needs?  how to do it ? Is  it difficult?  i want to know that  if i  only detect 30 landmark points  how much can i speed up ? Does this make sense?
    thanks

**Comment by TadasBaltrusaitis** [comment]
It is possible, one way is to retrain the model which is quite involved, another way is to turn off the visibilities of certain landmarks in the model file or even the code by setting them to 0, the model will still infer where they should be, but will not perform computations to determine them directly speeding things up. If you're interested I can provide more details.

**Comment by zhuyong999** [comment]
Thank you!   
 I am interested . please provide me  more details!

**Comment by TadasBaltrusaitis** [comment]
To do this you would need to change the variable;
`clnf_model.patch_experts.visibilities`

It describes which landmarks are visible at a particular scale and view, if you set a value of it to 0, the patch expert (the expensive step) for that landmark will not be computed. 

The algorithm is multi-scale so it goes through multiple iterations, you could turn off some landmarks at scale 0, with little cost to accuracy, but some gain in speed. I recommend you try turning the same landmark off at all views for simplicity at first, but you can experiment with the visibilities to see what suits you best.

**Comment by zhuyong999** [comment]
Thank you. I'll try it.

**Comment by zhuyong999** [comment]
does the  variable need to change?   the  visibilities  in  clnf_model.hierarchical_models:
clnf_model.hierarchical_models[i].patch_experts.visibilities 
 I don't understand the use of these variables. Which part of the face does it control?

**Comment by TadasBaltrusaitis** [comment]
I would start with the non hierarchical model visibilities, so just `clnf_model.patch_experts.visibilities`. 

The visibilities structure is as follows:
scale [4] -> view [7] -> landmarks [68], 

If you want to turn a particular landmark off, you can set that landmark to 0 in visibilities variable for all four scales and seven views.

The algorithm is multi-scale so it goes through multiple iterations, you could turn off some landmarks at the first scale, with little cost to accuracy, but some gain in speed. You should try experimenting with these values yourself, as I have not done it and do not know the exact effects it will have.

**Comment by harish2006** [comment]
Hi Tadas,
        I was trying to implement this in the HeadPoseLive program and added in the following lines just after               var visibilities = face_model.GetVisibilities(); // line 431 in the corresponding MainWindow.xaml.cs

                for (int ii = 35; ii < 68; ii++)
                {
                    visibilities[ii] = false;
                }

This doesn't seem to alter the behaviour of the model registration. Is this the right way?

 I also searched through the code base for "clnf_model.patch_experts.visibilities" or "clnf_model.hierarchical_models[i].patch_experts.visibilities" that you are mentioned in this thread but am not finding it. Can you point to the correct way to turn off the costly landmark registration step across scales in the HeadPoseLive program?

best,
Harish

**Comment by harish2006** [comment]
> does the variable need to change? the visibilities in clnf_model.hierarchical_models:
> clnf_model.hierarchical_models[i].patch_experts.visibilities
> I don't understand the use of these variables. Which part of the face does it control?

Hi zhuyong99, were you able to implement this ? I want to turn off the lower half landmarks in the face as that is typically occluded in my case. I am trying to modify Tadas's C# code, HeadPoseLive program.

**Comment by TadasBaltrusaitis** [comment]
You need to modify the underlying C++ code rather than the C# code as that only returns the visibilities, rather than allowing to modify them.
