### ISSUE TITLE
How to add face tracking in my own face detection?

### ISSUE THREAD

**Issue by YjDai** [TadasBaltrusaitis/OpenFace#273]
Open face has a good performance in face tracking. I want to add face tracking in my own face detection, where I only have 5 points? 
I've already debugged FaceLandmarkVidMulti.cpp, it is too long, I am so confused.

**Comment by TadasBaltrusaitis** [comment]
Hi,

I'm not entirely sure what you want to accomplish? Do you want to replace the face detector? It should not be too difficult, but you need to ensure that the face detection you provide is the style that OpenFace expects. It has to be a tight box around the 68 facial landmarks, from top of eyebrows down to chin and from one side of the face to another.

**Comment by YjDai** [comment]
@TadasBaltrusaitis Thank you! Yes, I want to replace the face detector and face alignment,  just keep the face tracking  module.  I don't know if that's possible？

**Comment by TadasBaltrusaitis** [comment]
There is not much of a tracking module in OpenFace, it just uses the previous detected landmark locations to initialise the landmark detector in the new frame. It also has a validation module that confirms if the landmark alignment worked or if it needs to be restarted with face detection. There are some other small tweaks, but those are the main steps.

Just replacing face detector would be easy, replacing face alignment will be more difficult as a lot of other modules rely on the 68 facial landmarks, including the face validation step which is part of the tracking. Gaze and expression analysis also rely on the 68 landmarks.
