### ISSUE TITLE
Relationship with "cmusatyalab/openface" from cmu

### ISSUE THREAD

**Issue by Latootoo** [TadasBaltrusaitis/OpenFace#274]
I'm quite curious about the relationship between this version of openface with "[cmusatyalab/openface](https://github.com/cmusatyalab/openface.git)" which is also from CMU, but another institution and using quite different methods to implement the face recognition. In my view, this version works better, but "[cmusatyalab/openface](https://github.com/cmusatyalab/openface.git)" seems to be more popular. Really weird !! Who can tell me the difference between this two version ?

**Comment by TadasBaltrusaitis** [comment]
Hi, the only relationship is the accidental naming coincidence. The two OpenFace projects are actually performing very different tasks, mine looks more at facial behavior (face tracking, head pose, eye gaze, and facial expression), while the cmusatyalab one is concerned with face recognition - knowing who the person is.
