### ISSUE TITLE
How to check the gaze tracking accuracy?

### ISSUE THREAD

**Issue by HouseCui** [TadasBaltrusaitis/OpenFace#275]
Hello Tadas:
    In the paper of "Rendering of Eyes for Eye-Shape Registration and Gaze Estimation ",you say the error in the MPIIGaze(degrees) u=7.9. I want to konw how to caculate the gaze tracking degrees and how to caculate the error in the MPIIGaze?

**Comment by TadasBaltrusaitis** [comment]
Hi,

First, the error you are referring to reported on MPIIGaze is from a CNN system that is not used in OpenFace. OpenFace can get an error of 9.4 on MPIIGaze (but that is a cross-dataset result, so the comparison is not exactly fair).

Second, unfortunately, the subset of MPIIGaze that we evaluated on is not publicly available. You could try getting in touch with the dataset authors to request access to it, and then you could use a script available in OpenFace to evaluate on it (`matlab_runners\Gaze Experiments\extract_mpii_gaze_test.m`).
