### ISSUE TITLE
Build with Visual Studio 2017 toolset v141

### ISSUE THREAD

**Issue by rathaROG** [TadasBaltrusaitis/OpenFace#276]
Hi! I like your OpenFace and I may use this for a part of my research. I've tried to prepare for Visual Studio 2017 with toolset v141 respectively to the other parts of my projects. There are still some issues when building, so I tried to do it CMake, but it failed. Could you give me some clues if I want to make everything from scratch with CMake. What extra libraries do I need? Or is it impossible?

**Comment by TadasBaltrusaitis** [comment]
Did you recompile all the 3rd party dependencies for Visual Studio 2017? That might be the biggest issue.

The CMake file is intended for building on Ubuntu and OSX and has not been tested for Windows, but I believe that it should be possible to port it for Windows as well, but that might take some work. You do not need extra libraries you just need to make sure you have the Visual Studio 2017 compatible ones and are including their headers and linking to them.

**Comment by rathaROG** [comment]
Yes that's what I'm going to do. I have just recompiled and prepared all of them (latest of all boost, dlib, OpenCV, TBB, OpenBlas, and also Blas from LAPACK) for VS2017 with latest platform toolset v141. Your OpenFace is all good and works well without any problem if I don't upgrade and build with platform toolset v140. The problem happens only with latest toolset v141. I wonder if it would fixed if I recompile everything like this.. but there seem many more things to config.

**Comment by TadasBaltrusaitis** [comment]
Any more details of what exactly is failing? I wonder what is stopping the toolset upgrade? As I'll eventually want to move the version to Visual Studio 2017 as well.

**Comment by rathaROG** [comment]
These are the error in debug x64:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'tbb_debug.lib'	FaceLandmarkImg	C:\DEVLibs\OpenFace\vc141\exe\FaceLandmarkImg\LINK	1	
Error	MSB3073	The command "xcopy /I /E /Y /D /C "C:\DEVLibs\OpenFace\vc141\lib\3rdParty\tbb\bin\x64\v141\tbb_debug.dll" "C:\DEVLibs\OpenFace\vc141\x64\Debug\"
:VCEnd" exited with code 4.	GazeAnalyser	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	123	
Error	MSB3073	The command "xcopy /I /E /Y /D /C "C:\DEVLibs\OpenFace\vc141\lib\3rdParty\tbb\bin\x64\v141\tbb_debug.dll" "C:\DEVLibs\OpenFace\vc141\x64\Debug\"
:VCEnd" exited with code 4.	dlib	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	123	
Error	LNK1104	cannot open file 'libboost_filesystem-vc141-mt-gd-1_60.lib'	Recording	C:\DEVLibs\OpenFace\vc141\exe\Recording\LINK	1	
Error	LNK1104	cannot open file 'tbb_debug.lib'	FaceLandmarkVidMulti	C:\DEVLibs\OpenFace\vc141\exe\FaceLandmarkVidMulti\LINK	1	
Error	LNK1104	cannot open file 'tbb_debug.lib'	FaceLandmarkVid	C:\DEVLibs\OpenFace\vc141\exe\FaceLandmarkVid\LINK	1	
Error	LNK1104	cannot open file 'tbb_debug.lib'	FeatureExtraction	C:\DEVLibs\OpenFace\vc141\exe\FeatureExtraction\LINK	1	

```

**Comment by TadasBaltrusaitis** [comment]
This seems to be an issue with library locations, it seems like there is not tbb .dll and .lib files in the locations the compiler would expect them.

**Comment by TadasBaltrusaitis** [comment]
This is because the Visual Studio solution actually encodes the platform toolset in TBB library location using:
`$(SolutionDir)lib\3rdParty\tbb\lib\$(PlatformShortName)\$(PlatformToolset)`, so it expects the library to be in a v141 directory.

This is also the case for the tbb dll and for boost library.

**Comment by rathaROG** [comment]
Yes you're right. And what is your suggestion for this? Visual studio supposed those libs to be upgraded too. By the way, I'm now working on the other part of my projects.. I will look into that very soon. Thank you so much for your support!

**Comment by TadasBaltrusaitis** [comment]
They might have been upgraded, but not placed in the right folders (I don't know how VS does that), so you could try moving them manually to expected locations.

**Comment by rathaROG** [comment]
Ok I see. I'll try to do. Thank!

**Comment by linyia01** [comment]
i have the same error .i just use vs2017 and download latest code .use ddefault selected .How did you solve it? thanks
