### ISSUE TITLE
Make fails at 92% 

### ISSUE THREAD

**Issue by linux-devil** [TadasBaltrusaitis/OpenFace#277]
I am using ubuntu 17 , following is my ubuntu version 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

I used following : https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

`[ 91%] Linking CXX executable ../../bin/FaceLandmarkImg
CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o: In function `main':
/home/harshit/Documents/OpenFace/exe/FaceLandmarkImg/FaceLandmarkImg.cpp:(.text+0x68e2): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
/home/harshit/Documents/OpenFace/exe/FaceLandmarkImg/FaceLandmarkImg.cpp:(.text+0x818f): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFaces(std::__1::vector<cv::Rect_<double>, std::__1::allocator<cv::Rect_<double> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&)':
/home/harshit/Documents/OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorUtils.cpp:(.text+0x1111e): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:155: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:308: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by TadasBaltrusaitis** [comment]
This seems to be a problem with linking to OpenCV, are you sure OpenCV is successfully installed?
