### ISSUE TITLE
error: no type named 'channel_type' in 'cv::DataType<unsigned int>' 

### ISSUE THREAD

**Issue by freebooterish** [TadasBaltrusaitis/OpenFace#282]
Attempting to build OpenFace-OpenFace_v0.2.5 on macOS the build fails with:

**/usr/local/include/opencv2/core/mat.hpp:2150:37: error: no type named 'channel_type' in
      'cv::DataType<unsigned int>'
    typedef typename DataType<_Tp>::channel_type channel_type;**

**Comment by TadasBaltrusaitis** [comment]
Is OpenCV 3.1 installed on your system?

**Comment by freebooterish** [comment]
yes, I installed the opencv-3.3.1 from source code with EXTRA MODULES opencv_contrib-3.3.1

**Comment by linux-devil** [comment]
Make sure you link your opencv.

**Comment by TadasBaltrusaitis** [comment]
This might be an issue with OpenCV 3.3, which I have not tried yet. The main supported version of OpenCV for OpenFace is 3.1

**Comment by freebooterish** [comment]
It'OK after I installed opencv3.2.0 from source tar.

**Comment by JavierVillegas** [comment]
In Opencv 3.3 I had to uncomment the line
#define OPENCV_TRAITS_ENABLE_DEPRECATED
in traits.hpp

**Comment by TadasBaltrusaitis** [comment]
Thanks for the suggestions, once I move the code to OpenCV 3.3 I will need to adapt to the changes.
