### ISSUE TITLE
AU intensities matching with AU occurences

### ISSUE THREAD

**Issue by monajalal** [TadasBaltrusaitis/OpenFace#285]
So here for AU3 intensity is 0 but the occurrence is one. Shouldn't the occurrence be 0 too? 

```
au intensities: 17
{
AU01 0.740623
AU02 0
AU04 0
AU05 0
AU06 2.59863
AU07 2.15513
AU09 0
AU10 1.48733
AU12 3.34686
AU14 0.815891
AU15 0
AU17 0
AU20 0
AU23 0
AU25 3.02598
AU26 0.811727
AU45 0
}
au occurences: 18
{
AU01 0
AU02 0
AU04 0
AU05 0
AU06 1
AU07 1
AU09 0
AU10 1
AU12 1
AU14 1
AU15 0
AU17 0
AU20 0
AU23 1
AU25 1
AU26 1
AU28 0
AU45 0
```

Here is the image:
<img width="409" alt="screen shot 2017-11-12 at 5 38 40 pm" src="https://user-images.githubusercontent.com/1892917/32704305-ca4052da-c7d0-11e7-8b50-f30747b01ffa.png">

**Comment by TadasBaltrusaitis** [comment]
Hi,

There is no guarantee of consistency between intensity and occurence predictions as they have been trained on slightly different datasets - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units#intensity-and-presence-of-aus

Thanks,
Tadas
