### ISSUE TITLE
Issue with the build process

### ISSUE THREAD

**Issue by amattek** [TadasBaltrusaitis/OpenFace#287]
Hello,

Thank you for this package.

I am trying to install the package using a Mac (10.12.6). Following the instructions on the Wiki, I installed Homebrew, Command Line Tools for XCode, XQuartz, and boost. I then downloaded the OpenFace-master folder, and tweaked the CMakeLists.txt file as recommended. When I run the specified build command from within the master folder like this:

cmake -D CMAKE_BUILD_TYPE=RELEASE 

I get an error saying: "-bash: cmake: command not found"

If I try to run install.sh from this folder like this:

bash install.sh

I get an error saying: "sudo: apt-get: command not found"

Am I missing a step in the installation?

Thank you!

**Comment by chiragraman** [comment]
Hello!

I believe you either don't have cmake installed, or it is not on your environment path. That should explain the `cmake: command not found` error.

The install script is for the Linux platform since it assumes the use of the apt package manager.

Hope this helps.

**Comment by chiragraman** [comment]
Hello!

Just checking back to see if this has been resolved. If it is, it would be great if you could post what the issue was and the fix that resolved it, for other people who might be facing the same issue. 

Unless there is still a problem, I am going to close this issue for inactivity.

**Comment by amattek** [comment]
Hey!
Thank you for getting back to me. I have decided to try the MATLAB version
instead to see if I have better luck, as I am not that well versed in Unix
or Linux.
I am still in the process of accessing the open datasets that are required
for training the PCA model.

Thank you!
Ali
