### ISSUE TITLE
Is it possible to use Kalman filter to increase accuracy  and performance?

### ISSUE THREAD

**Issue by EDMIG** [TadasBaltrusaitis/OpenFace#288]
Great Work! 

I did a survey ,  and found it  was  straightforward to use Kalman  filter on {s, tx, ty} and local parameters,  
but  much more complicated on Euler angles {ex, ey, ez}!

Does anyone have any suggestion or reference? any comment is preferred !

Thx.

**Comment by TadasBaltrusaitis** [comment]
You're very right, that modeling temporal properties of other parameters is much easier than that of rotations. You can have a look at linearizing small rotations using Rodrigues' formula (https://en.wikipedia.org/wiki/Rodrigues%27_rotation_formula)

A similar tactic is already used for performing updates for rotation parameters ex, ey, and ez
