### ISSUE TITLE
Where did you get triangulation matrix?

### ISSUE THREAD

**Issue by simonenkoav** [TadasBaltrusaitis/OpenFace#289]
Thanks fro making your project open source! 
I'm trying to use your approach for estimating 3D shape of hand.
When creating train and test data for CNN (scripts Create_data_train.m and Create_data_test.m, respectively), you are using triangulation matrix from file tri_68.mat. That was not generated anywhere in your code, just added in the third commit since the creation of repository. Where did you get or how did you generate this matrix? As I suppose, I cannot dispense with it, but I don't understand how to get it in my case.
Thank you in advance.

**Comment by TadasBaltrusaitis** [comment]
The CNN scripts are just for tracking validation and are an optional step in OpenFace. The triangulation can be calculated using Delaunay method.

**Comment by simonenkoav** [comment]
Thanks! You've confirmed my fears about my misunderstanding the purposes of this CNN... My aim is to get 3D shape from 2D projections, but I don't get whether you solve similar problem anywhere in the code :(

**Comment by TadasBaltrusaitis** [comment]
If you have 2D projections and a 3D shape model (a linear model or just a mean shape), have a look at `fit_PDM_ortho_proj_to_2D.m` script as that will attempt to find the 3D shape from the projections. 

If you just have a set of 2D projections and no 3D model, have a look at `matlab_version\pdm_generation` and the readme there, I used that code to reconstruct a 3D model of the face using non-rigid structure from motion method of Torresani et al.
