### ISSUE TITLE
Mac launch issue

### ISSUE THREAD

**Issue by a-x-** [TadasBaltrusaitis/OpenFace#29]
I was install `openface`
and try to run it:
`bin/FaceLandmarkImg -f ./image_sequence/005.jpg`

```
dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.6.dylib
  Referenced from: /usr/local/opt/opencv3/lib/libopencv_imgcodecs.3.1.dylib
  Reason: image not found
[1]    17647 trace trap  bin/FaceLandmarkImg -f ./image_sequence/005.jpg`
```

I tried to install the `webp`, but it ships without `libwebp.6.dylib`

**Comment by a-x-** [comment]
os x capitan

**Comment by TadasBaltrusaitis** [comment]
Are you sure the image in question exists? Or that the executable can find it?

**Comment by a-x-** [comment]
yeah.

i solve the problem now by reinstalling opencv like this (`--with-webp`):
`brew install homebrew/science/opencv3 --with-examples --with-contrib --with-tbb  --with-webp --with-python3`
