### ISSUE TITLE
How can I speed up clm if I just use eye and mouth landmark?

### ISSUE THREAD

**Issue by lzwhard** [TadasBaltrusaitis/OpenFace#290]
When I just make the mouth landmark using the script motified by face_image_demo_eyes.m
I gave it an initialition position of mouth which is a little bit bias from groud truth.
but after run fiting fuction, the position can not be updated to the groud truth.
Maybe the picture here can make it clear, [link](http://b2f0d0e9.wiz03.com/share/s/2OYd3F2kzALe2PHFAU1b6ql41QmcuQ0FzAvU2lzwi53pFtG6)

**Comment by TadasBaltrusaitis** [comment]
I don't know what modifications you made, so am not able to provide advice, there can be a lot of potential issues of why this is not working.

**Comment by lzwhard** [comment]
Thank u for your reply.
I want to speed up the landmark of tracking video.
Can you give me some advices?

**Comment by TadasBaltrusaitis** [comment]
Please have a look at the following issues:
https://github.com/TadasBaltrusaitis/OpenFace/issues/38
https://github.com/TadasBaltrusaitis/OpenFace/issues/271
