### ISSUE TITLE
Issue with building

### ISSUE THREAD

**Issue by megh1241** [TadasBaltrusaitis/OpenFace#292]
Hi !

I followed the installation steps on Ubuntu 16.04 and it was successful until the "make" step for OpenFace. The error that I get is as follows (after executing make): The previous step i.e CMake worked without errors.

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find TBB (missing: TBB_LIBRARIES) (found version "4.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindTBB.cmake:264 (find_package_handle_standard_args)
  CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/meghana/Downloads/OpenFace-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/meghana/Downloads/OpenFace-master/build/CMakeFiles/CMakeError.log".
Makefile:132: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

I have attached the CMakeOutput.log and CMakeError.log files
[CMakeError.log](https://github.com/TadasBaltrusaitis/OpenFace/files/1496739/CMakeError.log)
[CMakeOutput.log](https://github.com/TadasBaltrusaitis/OpenFace/files/1496740/CMakeOutput.log)

**Comment by NumesSanguis** [comment]
I'm also having an issue with building, but with the include OpenCV 3.1.
When I run `./install.sh` it stops at :
[OpenFace_error_OpenCV31.txt](https://github.com/TadasBaltrusaitis/OpenFace/files/1533757/OpenFace_error_OpenCV31.txt)

<details><summary>Last part of output</summary>
[ 55%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ocl_test.cpp.o
/usr/bin/ld: warning: libjpeg.so.8, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libjasper.so, may conflict with libjpeg.so.9
/home/nishida-stef-ubuntu/anaconda3/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
apps/annotation/CMakeFiles/opencv_annotation.dir/build.make:116: recipe for target 'bin/opencv_annotation' failed
make[2]: *** [bin/opencv_annotation] Error 1
CMakeFiles/Makefile2:7366: recipe for target 'apps/annotation/CMakeFiles/opencv_annotation.dir/all' failed
make[1]: *** [apps/annotation/CMakeFiles/opencv_annotation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/orb.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/bagofwords.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/draw.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast_score.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/fed.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/AKAZEFeatures.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/KAZEFeatures.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/nldiffusion_functions.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/gftt.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/keypoint.cpp.o
[ 55%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze.cpp.o
[ 56%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/blobdetector.cpp.o
[ 56%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/mser.cpp.o
[ 56%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/opencl_kernels_features2d.cpp.o
[ 56%] Linking CXX static library ../../lib/libopencv_features2d.a
[ 56%] Built target opencv_features2d
[ 56%] Linking CXX static library ../../lib/libopencv_ts.a
[ 56%] Built target opencv_ts
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
</details>

But when I try to use OpenCV 3.3, I get different problems: https://github.com/TadasBaltrusaitis/OpenFace/issues/300

**Comment by chiragraman** [comment]
Meghana, looking at your CMakeError log it seems like CMake couldn't find pthreads. Are you certain that you have it installed? If you are using apt, I believe ` libpthread-stubs0-dev` is the correct package.

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue persists.
