### ISSUE TITLE
Is there any way to improve  landmarks' accuracy for  open-wide mouth?

### ISSUE THREAD

**Issue by EDMIG** [TadasBaltrusaitis/OpenFace#293]
Hi,

I  have tested some  images and videos  with open-wide mouth expression, and found the mouth's landmarks have lower precision than other's. is there any method or tactic to improve  these landmarks'  accuracy?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Not in the current version, but the next version (out in a couple of months) will be more accurate (including mouth region area).

**Comment by danpilat** [comment]
Hi @TadasBaltrusaitis ! great to hear about the planned improvements. Having a lot of trouble with lower lip recognition. Just wondering if the current 0.3.0 version that's out there has the improvements you are talking about in this post or they are still upcoming?

**Comment by TadasBaltrusaitis** [comment]
The performance improvements are not in 0.3.0, the changes in 0.3.0 were to general code layout and interface needed to integrate the performance improvements (coming in 2-3 months)

**Comment by R00iBaard** [comment]
What was the fix for this? I am experiencing this at the moment running the latest version. I am running model/main_clm_general.txt as well as haar face detection with "use_face_template" enabled to run as light as possible on rpi.

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, the main_clm_general model is the issue, you would need to use the newer models (either CLNF or ideally CEN) for better lower lip tracking, however they are much slower and probably unsuitable fro rpi.
