### ISSUE TITLE
Problem of Training Data Download

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#297]
Hello,
I contacted the people developed the SEMAINE database, and successfully approved to access to the SEMAINE.
But the people directed FERA15 confirmed that they used selected (and more seriously, annotated separately) subset of SEMAINE database.
Is there any way to access FERA15 version of SEMAINE?
Unfortunately, no response from the FERA2015 official resource download site for more than a month.

**Comment by TadasBaltrusaitis** [comment]
Due to end user license agreements I would not be able to share the datasets.
