### ISSUE TITLE
can i used it by C#?

### ISSUE THREAD

**Issue by billzw** [TadasBaltrusaitis/OpenFace#3]
can i used it by C#?

**Comment by TadasBaltrusaitis** [comment]
Not yet, but it will be soon (in a week or two)

**Comment by gpribi** [comment]
Is there any face recognition demo in C#? Thanks

**Comment by Camuvingian** [comment]
Any news on the C# wrapper?

**Comment by mimorphism** [comment]
im sorry but do we have a c# wrapper as of this moment

**Comment by TadasBaltrusaitis** [comment]
Sorry for the delay, but not as of this moment yet, although I'm actively working on it at the moment and it is definitely getting closer.

**Comment by paleicikas** [comment]
any news about c#?

**Comment by gpribi** [comment]
nope

2018-02-16 16:44 GMT-03:00 Artūras Paleičikas <notifications@github.com>:

**Comment by TadasBaltrusaitis** [comment]
Yes, you can use C# now. There is currently no documentation, but you can find a set of examples in the gui folder and if you open the solution file in Visual Studio it includes three C# projects using OpenFace C++ bindings.
