### ISSUE TITLE
OpenCV 3.3 no output file / segmentation fault

### ISSUE THREAD

**Issue by NumesSanguis** [TadasBaltrusaitis/OpenFace#300]
When trying to run OpenCV, I don't get any output data file with FaceLandmarkImg or FaceLandmarkVid. FeatureExtraction returns a segmentation fault without the flag --noAUs. FaceLandmarkVid does properly output video tracking while running and as output file.

System:

- Ubuntu16.04.3 LTS
- Nvidia GTX 1080Ti
- OpenCV 3.3

OpenFace setup:

0. `conda create --name OpenFace` && `source activate OpenFace`
1. `conda install -c conda-forge opencv`
2. Edit install.sh and remove first part about OpenCV 3.1 (everything under # OpenCV Dependency)
3. `sudo chmod 755 install.sh`
4. `./install.sh` (no errors)
5. Fix GIO issue, add to Bashrc: `export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/`

What I tried:

- `./FaceLandmarkImg -f real_human.jpg -of test.csv -oi test.jpg` (Doesn't create any file) 

<details><summary>LandmarkImg output</summary>

	Loading the model
	Reading the CLNF landmark detector/tracker from: model/main_clnf_general.txt
	Reading the landmark detector module from: model/clnf_general.txt
	Reading the PDM module from: model/pdms/In-the-wild_aligned_PDM_68.txt....Done
	Reading the Triangulations module from: model/tris_68.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.25_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.35_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.5_general.txt....Done
	Reading part based module....inner
	Reading the CLNF landmark detector/tracker from: model/model_inner/main_clnf_inner.txt
	Reading the landmark detector module from: model/model_inner/clnf_inner.txt
	Reading the PDM module from: model/model_inner/pdms/pdm_51_inner.txt....Done
	Reading the intensity CCNF patch experts from: model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
	Done
	Reading part based module....left_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_left.txt
	Reading the landmark detector module from: model/model_eye/clnf_left_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading part based module....right_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_right.txt
	Reading the landmark detector module from: model/model_eye/clnf_right_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading the landmark validation module....Done
	Model loaded
	Reading the AU analysis module from: AU_predictors/main_static_svms.txt
	Reading the AU predictors from: AU_predictors/AU_all_static.txt... Done
	Reading the PDM from: AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
	Reading the triangulation from:AU_predictors/tris_68_full.txt... Done

</details>

-----

- `./FaceLandmarkVid -f test.mp4 -of test.csv -ov test_lm.mp4` (only creates output video)

<details><summary>LandmarkVid output</summary>

	Reading the CLNF landmark detector/tracker from: model/main_clnf_general.txt
	Reading the landmark detector module from: model/clnf_general.txt
	Reading the PDM module from: model/pdms/In-the-wild_aligned_PDM_68.txt....Done
	Reading the Triangulations module from: model/tris_68.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.25_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.35_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.5_general.txt....Done
	Reading part based module....inner
	Reading the CLNF landmark detector/tracker from: model/model_inner/main_clnf_inner.txt
	Reading the landmark detector module from: model/model_inner/clnf_inner.txt
	Reading the PDM module from: model/model_inner/pdms/pdm_51_inner.txt....Done
	Reading the intensity CCNF patch experts from: model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
	Done
	Reading part based module....left_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_left.txt
	Reading the landmark detector module from: model/model_eye/clnf_left_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading part based module....right_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_right.txt
	Reading the landmark detector module from: model/model_eye/clnf_right_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading the landmark validation module....Done
	Attempting to read from file: test.mp4
	Device or file opened
	OpenCV: FFMPEG: tag 0x58564944/'DIVX' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
	OpenCV: FFMPEG: fallback to use tag 0x00000020/' ???'
	Starting tracking

</details>

-----

- `./FeatureExtraction -f real_human.jpg -of test.csv` (Segmentation fault (core dumped), test.csv is created with values, but AU_r can have negative value, maybe related to?: https://github.com/TadasBaltrusaitis/OpenFace/issues/260)

<details><summary>FeatureExtraction output</summary>

	Reading the CLNF landmark detector/tracker from: model/main_clnf_general.txt
	Reading the landmark detector module from: model/clnf_general.txt
	Reading the PDM module from: model/pdms/In-the-wild_aligned_PDM_68.txt....Done
	Reading the Triangulations module from: model/tris_68.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.25_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.35_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.5_general.txt....Done
	Reading part based module....inner
	Reading the CLNF landmark detector/tracker from: model/model_inner/main_clnf_inner.txt
	Reading the landmark detector module from: model/model_inner/clnf_inner.txt
	Reading the PDM module from: model/model_inner/pdms/pdm_51_inner.txt....Done
	Reading the intensity CCNF patch experts from: model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
	Done
	Reading part based module....left_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_left.txt
	Reading the landmark detector module from: model/model_eye/clnf_left_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading part based module....right_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_right.txt
	Reading the landmark detector module from: model/model_eye/clnf_right_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading the landmark validation module....Done
	Reading the AU analysis module from: AU_predictors/main_dynamic_svms.txt
	Reading the AU predictors from: AU_predictors/AU_all_best.txt... Done
	Reading the PDM from: AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
	Reading the triangulation from:AU_predictors/tris_68_full.txt... Done
	Attempting to read from file: real_human.jpg
	Device or file opened
	Starting tracking
	0% Postprocessing the Action Unit predictions
	Segmentation fault (core dumped)

</details>

-----

- `./FeatureExtraction -f real_human.jpg -of test.csv -noAUs` (output file created, but without AU and weird Starting tracking 0%)

<details><summary>FeatureExtraction output no AUs</summary>

	Reading the CLNF landmark detector/tracker from: model/main_clnf_general.txt
	Reading the landmark detector module from: model/clnf_general.txt
	Reading the PDM module from: model/pdms/In-the-wild_aligned_PDM_68.txt....Done
	Reading the Triangulations module from: model/tris_68.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.25_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.35_general.txt....Done
	Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.5_general.txt....Done
	Reading part based module....inner
	Reading the CLNF landmark detector/tracker from: model/model_inner/main_clnf_inner.txt
	Reading the landmark detector module from: model/model_inner/clnf_inner.txt
	Reading the PDM module from: model/model_inner/pdms/pdm_51_inner.txt....Done
	Reading the intensity CCNF patch experts from: model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
	Done
	Reading part based module....left_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_left.txt
	Reading the landmark detector module from: model/model_eye/clnf_left_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading part based module....right_eye_28
	Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_right.txt
	Reading the landmark detector module from: model/model_eye/clnf_right_synth.txt
	Reading the PDM module from: model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
	Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
	Done
	Reading the landmark validation module....Done
	Reading the AU analysis module from: AU_predictors/main_dynamic_svms.txt
	Reading the AU predictors from: AU_predictors/AU_all_best.txt... Done
	Reading the PDM from: AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
	Reading the triangulation from:AU_predictors/tris_68_full.txt... Done
	Attempting to read from file: real_human.jpg
	Device or file opened
	Starting tracking
	0% 

</details>

**Comment by TadasBaltrusaitis** [comment]
The issue is with OpenCV 3.3, it has some breaking changes with OpenFace and the latest supported version of OpenCV is 3.1 (in the future I will move to OpenCV 3.3. though)

**Comment by NumesSanguis** [comment]
Is OpenFace 0.3.0 supporting / going to support OpenCv 3.3? It would be nice to know instead of finding it out by going through the whole compiling again.

**Comment by TadasBaltrusaitis** [comment]
The support of OpenCV 3.3 is on my TODO list, however, I do not have a time estimate of when that will happen.

**Comment by NumesSanguis** [comment]
Okay, no problem. I'm looking forward to the progress of this project.

**Comment by TadasBaltrusaitis** [comment]
Support for OpenCV 3.3 and above has been added now.

**Comment by NumesSanguis** [comment]
Thank you for putting effort in upgrading your software. I just tried to install using the `install.sh` script, but unfortunately I'm having some problems.

My setup:

- Ubuntu 16.04
- Nvidia 1080Ti
- Pull date master: 2018-02-07 05:00 (UTC time)
- Anaconda: `conda create --name openface_install`
- Dependency installed https://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html

What I tried:

- `./install.sh`
- `pip install opencv-python` (https://pypi.python.org/pypi/opencv-python) (https://stackoverflow.com/a/41301866)
- Different Anaconda OpenCV packages

When I run `./install.sh`, around 65% it crashes. See the error log below. When I use `pip install opencv-python` or other Anaconda packages to install OpenCV, both OpenCV and OpenFace install succesfully. However when I try to run `./FaceLandmarkVid`, I get the error:

    Reading the landmark validation module....Done
    No input specified, attempting to open a webcam 0
    Attempting to read from webcam: 0
    Device or file opened
    Starting tracking
    OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file /tmp/build/80754af9/opencv_1512687413662/work/modules/highgui/src/window.cpp, line 593
    terminate called after throwing an instance of 'cv::Exception'
      what():  /tmp/build/80754af9/opencv_1512687413662/work/modules/highgui/src/window.cpp:593: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

    Aborted (core dumped)

I installed the dependencies, so libgtk2.0-dev should be on my PC.

<details><summary>install.sh output short (55%-65%) OpenCV</summary>

    Scanning dependencies of target opencv_videoio
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap.cpp.o
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_images.cpp.o
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_mjpeg_encoder.cpp.o
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_mjpeg_decoder.cpp.o
    [ 55%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/caffe/caffe_importer.cpp.o
    [ 55%] Linking CXX static library ../../lib/libopencv_photo.a
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_dc1394_v2.cpp.o
    [ 55%] Built target opencv_photo
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o
    [ 55%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/caffe/caffe_shrinker.cpp.o
    [ 55%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
    [ 55%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/batch_norm_layer.cpp.o
    [ 56%] Linking CXX static library ../../lib/libopencv_videoio.a
    [ 56%] Built target opencv_videoio
    [ 56%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/lrn_layer.cpp.o
    [ 56%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/elementwise_layers.cpp.o
    Scanning dependencies of target opencv_highgui
    [ 56%] Processing OpenCL kernels (superres)
    Scanning dependencies of target opencv_superres
    [ 56%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/src/super_resolution.cpp.o
    [ 56%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/src/frame_source.cpp.o
    [ 56%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/window.cpp.o
    [ 56%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/src/optical_flow.cpp.o
    [ 56%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/roiSelector.cpp.o
    [ 56%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/src/btv_l1_cuda.cpp.o
    [ 56%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/window_gtk.cpp.o
    [ 56%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/src/btv_l1.cpp.o
    [ 56%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/src/input_array_utility.cpp.o
    [ 56%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/region_layer.cpp.o
    [ 56%] Linking CXX static library ../../lib/libopencv_highgui.a
    [ 56%] Built target opencv_highgui
    [ 56%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/shift_layer.cpp.o
    [ 57%] Building CXX object modules/superres/CMakeFiles/opencv_superres.dir/opencl_kernels_superres.cpp.o
    [ 57%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o
    [ 57%] Linking CXX static library ../../lib/libopencv_superres.a
    Scanning dependencies of target opencv_ts
    [ 57%] Built target opencv_superres
    [ 57%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/padding_layer.cpp.o
    [ 57%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/cuda_perf.cpp.o
    [ 57%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_gtest.cpp.o
    [ 57%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts.cpp.o
    [ 57%] Processing OpenCL kernels (features2d)
    Scanning dependencies of target opencv_features2d
    [ 57%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast_score.cpp.o
    [ 57%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/brisk.cpp.o
    [ 57%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ocl_perf.cpp.o
    [ 57%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/flatten_layer.cpp.o
    [ 57%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/cuda_test.cpp.o
    [ 58%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/matchers.cpp.o
    [ 58%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/main.cpp.o
    Scanning dependencies of target opencv_annotation
    [ 58%] Building CXX object apps/annotation/CMakeFiles/opencv_annotation.dir/opencv_annotation.cpp.o
    [ 59%] Linking CXX executable ../../bin/opencv_annotation
    [ 59%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_perf.cpp.o
    [ 59%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast.cpp.o
    [ 59%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/reshape_layer.cpp.o
    [ 59%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/feature2d.cpp.o
    [ 59%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/dynamic.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/max_unpooling_layer.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/akaze.cpp.o
    /usr/bin/ld: warning: libjpeg.so.8, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libjasper.so, may conflict with libjpeg.so.9
    /home/nishida-stef-ubuntu/anaconda3/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
    collect2: error: ld returned 1 exit status
    apps/annotation/CMakeFiles/opencv_annotation.dir/build.make:120: recipe for target 'bin/opencv_annotation' failed
    make[2]: *** [bin/opencv_annotation] Error 1
    CMakeFiles/Makefile2:7815: recipe for target 'apps/annotation/CMakeFiles/opencv_annotation.dir/all' failed
    make[1]: *** [apps/annotation/CMakeFiles/opencv_annotation.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/evaluation.cpp.o
    [ 60%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_arrtest.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/blank_layer.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/fully_connected_layer.cpp.o
    [ 60%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_func.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/eltwise_layer.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/orb.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/bagofwords.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/slice_layer.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/detection_output_layer.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/layers_common.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/draw.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast_score.cpp.o
    [ 60%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ocl_test.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/concat_layer.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/mvn_layer.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast.cpp.o
    [ 60%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/fed.cpp.o
    [ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/pooling_layer.cpp.o
    [ 61%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/AKAZEFeatures.cpp.o
    [ 61%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/normalize_bbox_layer.cpp.o
    [ 61%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/convolution_layer.cpp.o
    [ 61%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/permute_layer.cpp.o
    [ 61%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/KAZEFeatures.cpp.o
    [ 61%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/nldiffusion_functions.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/split_layer.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/resize_nearest_neighbor_layer.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/reorg_layer.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/gftt.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/proposal_layer.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/scale_layer.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/keypoint.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/crop_layer.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/blobdetector.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/mser.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/opencl_kernels_features2d.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/prior_box_layer.cpp.o
    [ 62%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/softmax_layer.cpp.o
    [ 62%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast.avx2.cpp.o
    [ 63%] Linking CXX static library ../../lib/libopencv_ts.a
    [ 63%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/op_halide.cpp.o
    [ 63%] Built target opencv_ts
    [ 63%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/nms.cpp.o
    [ 63%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_io.cpp.o
    [ 63%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/tensorflow/tf_importer.cpp.o
    [ 63%] Linking CXX static library ../../lib/libopencv_features2d.a
    [ 63%] Built target opencv_features2d
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/halide_scheduler.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/darknet/darknet_importer.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/darknet/darknet_io.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/dnn.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_pool.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/common.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_inner_product.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_lrn.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/math_functions.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/ocl4dnn/src/ocl4dnn_softmax.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/init.cpp.o
    [ 64%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o
    [ 65%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THFile.cpp.o
    [ 65%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THGeneral.cpp.o
    [ 65%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THDiskFile.cpp.o
    [ 65%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.o
    [ 65%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o
    [ 65%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o
    [ 65%] Linking CXX static library ../../lib/libopencv_dnn.a
    [ 65%] Built target opencv_dnn
    Makefile:160: recipe for target 'all' failed
    make: *** [all] Error 2

</details>

**Comment by TadasBaltrusaitis** [comment]
Hi,

The issue seems to be with OpenCV installation rather than OpenFace, I haven't seen this issue myself but maybe someone else could help. One option you can try is uninstalling OpenCV and letting the `install.sh` script install it for you.

**Comment by NumesSanguis** [comment]
That was my first option, but building OpenCV that way failed. Please click the > under "OpenCV install fail when using ./install.sh error log:" (Just now I added a header for visibility)

**Comment by TadasBaltrusaitis** [comment]
Could it be an issue with anaconda? Some people have reported that uninstalling anaconda sometimes resolves certain issues.
