### ISSUE TITLE
How to run through command line in Unix 16.04

### ISSUE THREAD

**Issue by shivangsoni** [TadasBaltrusaitis/OpenFace#302]
I am a new user of open-face it would be great if someone helps me to run real-time face detection through the command line. So file I had done the setup for the open face in my system by executing ./install.sh.

Then is echoed OpenFace successfully installed
********************************************************************
What commands are needed to be executed in order start working? I already read the WIKI provided but the bit confused about the usage of commands.

Any type of help on this issue is highly appreciated

**Comment by NumesSanguis** [comment]
I agree with you that the Wiki is lacking.

Go inside your `OpenFace` folder. If you successfully build OpenFace, there should be a `build` folder. Go to `build/bin/`. You should see e.g. `FaceLandmarkImg`, `FaceLandmarkVid`, etc. Put a image / video in here and open / cd with a terminal to this folder. Run e.g. the following command:

    ./FaceLandMarkImg -f some_img.jpg -of some_img_of.txt

If you want to open your image / video from somewhere else, just change the path, e.g.: `-f ../../images/some_img.jpg`. You can also add any other command found in the wiki: [https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments).

**Comment by shivangsoni** [comment]
Thank you

**Comment by NumesSanguis** [comment]
It might not detect a face. Feature Extraction will definitely create an output file:

    ./FeatureExtraction -f some_video.mp4 -of some_video_of.txt

Note that in this command only "some_video.mp4" should exist, "some_video_of.txt" will be created by OpenFace

Or should see some visual video with tracking and when finished it should save this video when you do:

    ./FaceLandmarkVid -f some_video.mp4 -ov some_video_ov.mp4

Again, only "some_video.mp4" should exist, "some_video_ov.mp4" is created.

**Comment by shivangsoni** [comment]
Thank you very much. These above commands are working fine.

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue persists.
