### ISSUE TITLE
eye_lmks don't appear in the 3d landmarks mode

### ISSUE THREAD

**Issue by wasimf** [TadasBaltrusaitis/OpenFace#303]
Hi ,
When running the FaceLandmarkImg.exe with "-gaze" parameter I managed to get the eye_lmks with the 2d landmarks. 
When running with 3d landmarks the eye_lmks are missing in the output. 

Any idea ?
Thanks in advance ...

**Comment by TadasBaltrusaitis** [comment]
This will be fixed in the next version of OpenFace and you will get access to 3D eye landmarks.

**Comment by wasimf** [comment]
Thanks for the reply . Do you have an estimation when it will be ? 
May you have a hint where to fix in the code, so I can integrate in the meanwhile till you fixed it formally. 

Thanks ...

**Comment by TadasBaltrusaitis** [comment]
You should be able to extract 3D eye landmark locations now
