### ISSUE TITLE
How to get the value of pitch,yaw,roll in the iamge

### ISSUE THREAD

**Issue by qmj123** [TadasBaltrusaitis/OpenFace#305]
Hi !
I want to know that how to get the value of pitch,yaw,roll in the iamge.
Using  matlab, how to get?
Can you help me?
Thank you very much!

**Comment by TadasBaltrusaitis** [comment]
You can do that easily using the C++ executables, specifically FaceLandmarkImg (have a look at https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments)

The Matlab scripts do not directly output head pose, you would need to modify them.

**Comment by qmj123** [comment]
I am very excited to see your reply.
Thank you very much!

**Comment by TadasBaltrusaitis** [comment]
The interface has just changed for image analysis, and it should be easier to extract head pose information for them, see the wiki for more details:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments
