### ISSUE TITLE
Error while building openface

### ISSUE THREAD

**Issue by snsharma1311** [TadasBaltrusaitis/OpenFace#307]
While running install.sh script got the following error:
Note: I have installed all the dependencies given in the documentation

Scanning dependencies of target LandmarkDetector
[ 62%] Building CXX object lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:165:25: error: redeclaration of ‘IMREAD_UNCHANGED’
     IMREAD_UNCHANGED  =-1,
                         ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:65:8: note: previous declaration ‘cv::ImreadModes IMREAD_UNCHANGED’
        IMREAD_UNCHANGED            = -1, //!< If set, return the loaded image as is (with alpha channel, otherwise it gets cropped).
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:167:24: error: redeclaration of ‘IMREAD_GRAYSCALE’
     IMREAD_GRAYSCALE  =0,
                        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:66:8: note: previous declaration ‘cv::ImreadModes IMREAD_GRAYSCALE’
        IMREAD_GRAYSCALE            = 0,  //!< If set, always convert image to the single channel grayscale image.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:169:24: error: redeclaration of ‘IMREAD_COLOR’
     IMREAD_COLOR      =1,
                        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:67:8: note: previous declaration ‘cv::ImreadModes IMREAD_COLOR’
        IMREAD_COLOR                = 1,  //!< If set, always convert image to the 3 channel BGR color image.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:171:24: error: redeclaration of ‘IMREAD_ANYDEPTH’
     IMREAD_ANYDEPTH   =2,
                        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:68:8: note: previous declaration ‘cv::ImreadModes IMREAD_ANYDEPTH’
        IMREAD_ANYDEPTH             = 2,  //!< If set, return 16-bit/32-bit image when the input has the corresponding depth, otherwise convert it to 8-bit.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:173:24: error: redeclaration of ‘IMREAD_ANYCOLOR’
     IMREAD_ANYCOLOR   =4
                        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:69:8: note: previous declaration ‘cv::ImreadModes IMREAD_ANYCOLOR’
        IMREAD_ANYCOLOR             = 4,  //!< If set, the image is read in any possible color format.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:178:27: error: redeclaration of ‘IMWRITE_JPEG_QUALITY’
     IMWRITE_JPEG_QUALITY =1,
                           ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:81:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_JPEG_QUALITY’
        IMWRITE_JPEG_QUALITY        = 1,  //!< For JPEG, it can be a quality from 0 to 100 (the higher is the better). Default value is 95.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:179:30: error: redeclaration of ‘IMWRITE_PNG_COMPRESSION’
     IMWRITE_PNG_COMPRESSION =16,
                              ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:87:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PNG_COMPRESSION’
        IMWRITE_PNG_COMPRESSION     = 16, //!< For PNG, it can be the compression level from 0 to 9. A higher value means a smaller size and longer compression time. Def
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:180:27: error: redeclaration of ‘IMWRITE_PNG_STRATEGY’
     IMWRITE_PNG_STRATEGY =17,
                           ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:88:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PNG_STRATEGY’
        IMWRITE_PNG_STRATEGY        = 17, //!< One of cv::ImwritePNGFlags, default is IMWRITE_PNG_STRATEGY_DEFAULT.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:181:26: error: redeclaration of ‘IMWRITE_PNG_BILEVEL’
     IMWRITE_PNG_BILEVEL =18,
                          ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:89:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PNG_BILEVEL’
        IMWRITE_PNG_BILEVEL         = 18, //!< Binary level PNG, 0 or 1, default is 0.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:182:35: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_DEFAULT’
     IMWRITE_PNG_STRATEGY_DEFAULT =0,
                                   ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:103:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_DEFAULT’
        IMWRITE_PNG_STRATEGY_DEFAULT      = 0, //!< Use this value for normal data.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:183:36: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_FILTERED’
     IMWRITE_PNG_STRATEGY_FILTERED =1,
                                    ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:104:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_FILTERED’
        IMWRITE_PNG_STRATEGY_FILTERED     = 1, //!< Use this value for data produced by a filter (or predictor).Filtered data consists mostly of small values with a some
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:184:40: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY’
     IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY =2,
                                        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:105:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY’
        IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY = 2, //!< Use this value to force Huffman encoding only (no string match).
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:185:31: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_RLE’
     IMWRITE_PNG_STRATEGY_RLE =3,
                               ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:106:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_RLE’
        IMWRITE_PNG_STRATEGY_RLE          = 3, //!< Use this value to limit match distances to one (run-length encoding).
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:186:33: error: redeclaration of ‘IMWRITE_PNG_STRATEGY_FIXED’
     IMWRITE_PNG_STRATEGY_FIXED =4,
                                 ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:107:8: note: previous declaration ‘cv::ImwritePNGFlags IMWRITE_PNG_STRATEGY_FIXED’
        IMWRITE_PNG_STRATEGY_FIXED        = 4  //!< Using this value prevents the use of dynamic Huffman codes, allowing for a simpler decoder for special applications.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:187:25: error: redeclaration of ‘IMWRITE_PXM_BINARY’
     IMWRITE_PXM_BINARY =32
                         ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:90:8: note: previous declaration ‘cv::ImwriteFlags IMWRITE_PXM_BINARY’
        IMWRITE_PXM_BINARY          = 32, //!< For PPM, PGM, or PBM, it can be a binary format flag, 0 or 1. Default value is 1.
        ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:190:62: error: default argument given for parameter 2 of ‘cv::Mat cv::imread(const string&, int)’
 CV_EXPORTS_W Mat imread( const string& filename, int flags=1 );
                                                              ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:152:18: note: previous specification in ‘cv::Mat cv::imread(const String&, int)’ here
 CV_EXPORTS_W Mat imread( const String& filename, int flags = IMREAD_COLOR );
                  ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:192:54: error: default argument given for parameter 3 of ‘bool cv::imwrite(const string&, cv::InputArray, const std::vector<int>&)’
               const vector<int>& params=vector<int>());
                                                      ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:225:19: note: previous specification in ‘bool cv::imwrite(const String&, cv::InputArray, const std::vector<int>&)’ here
 CV_EXPORTS_W bool imwrite( const String& filename, InputArray img,
                   ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:24:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/home/shashank/opencv/modules/highgui/include/opencv2/highgui/highgui.hpp:197:68: error: default argument given for parameter 4 of ‘bool cv::imencode(const string&, cv::InputArray, std::vector<unsigned char>&, const std::vector<int>&)’
                             const vector<int>& params=vector<int>());
                                                                    ^
In file included from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:23:0,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/local/include/opencv2/imgcodecs.hpp:259:19: note: previous specification in ‘bool cv::imencode(const String&, cv::InputArray, std::vector<unsigned char>&, const std::vector<int>&)’ here
 CV_EXPORTS_W bool imencode( const String& ext, InputArray img,
                   ^
In file included from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix/../serialize.h:158:0,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix/matrix.h:9,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix.h:6,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/scan_image.h:9,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing.h:6,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/frontal_face_detector.h:7,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorModel.h:43,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorUtils.h:42,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:44:
/home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix/../smart_pointers/shared_ptr.h:299:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
             std::auto_ptr<Y>& r
                  ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/boost/filesystem/path_traits.hpp:29,
                 from /usr/include/boost/filesystem/path.hpp:25,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:44,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix/../serialize.h:158:0,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix/matrix.h:9,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix.h:6,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/scan_image.h:9,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing.h:6,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/frontal_face_detector.h:7,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorModel.h:43,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorUtils.h:42,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:44:
/home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../matrix/../smart_pointers/shared_ptr.h:331:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
             std::auto_ptr<Y>& r
                  ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/boost/filesystem/path_traits.hpp:29,
                 from /usr/include/boost/filesystem/path.hpp:25,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:44,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads/../smart_pointers_thread_safe.h:6:0,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads/thread_pool_extension.h:14,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads.h:17,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/structural_svm_problem_threaded.h:13,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/structural_svm_object_detection_problem.h:8,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/structural_object_detection_trainer.h:9,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/remove_unobtainable_rectangles.h:11,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing.h:15,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/frontal_face_detector.h:7,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorModel.h:43,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorUtils.h:42,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:44:
/home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads/../smart_pointers/shared_ptr_thread_safe.h:263:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
             std::auto_ptr<Y>& r
                  ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/boost/filesystem/path_traits.hpp:29,
                 from /usr/include/boost/filesystem/path.hpp:25,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:44,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads/../smart_pointers_thread_safe.h:6:0,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads/thread_pool_extension.h:14,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads.h:17,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/structural_svm_problem_threaded.h:13,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/structural_svm_object_detection_problem.h:8,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/structural_object_detection_trainer.h:9,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/remove_unobtainable_rectangles.h:11,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing.h:15,
                 from /home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/frontal_face_detector.h:7,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorModel.h:43,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/LandmarkDetectorUtils.h:42,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:44:
/home/shashank/OpenFace/lib/3rdParty/dlib/include/dlib/image_processing/../image_processing/../svm/../threads/../smart_pointers/shared_ptr_thread_safe.h:294:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
             std::auto_ptr<Y>& r
                  ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/boost/filesystem/path_traits.hpp:29,
                 from /usr/include/boost/filesystem/path.hpp:25,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/./include/stdafx.h:44,
                 from /home/shashank/OpenFace/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/build.make:62: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o' failed
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all' failed
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TadasBaltrusaitis** [comment]
My guess is that you may have multiple versions of OpenCV installed and the compiler seems to be including both, leading to clashes
