### ISSUE TITLE
Compile error on TX2

### ISSUE THREAD

**Issue by ycdhqzhiai** [TadasBaltrusaitis/OpenFace#310]
I want to compile Openface on Jetson TX2, I get error:
![image](https://user-images.githubusercontent.com/12273405/34432328-3b579ece-ecb1-11e7-9c15-636d339c5df9.png)

how to solve it?someone can help me?thx

**Comment by TadasBaltrusaitis** [comment]
It seems like the issue is Jetson TX2 not supporting sse instructions, you could try removing the following lines from CMakeLists.txt in the dlib folder:

    add_definitions(-DDLIB_HAVE_SSE2)
    add_definitions(-DDLIB_HAVE_SSE3)
    add_definitions(-DDLIB_HAVE_SSE41)

**Comment by TadasBaltrusaitis** [comment]
Closing the issue, as installation has changed and dlib built separately can be used.

Re-open if persists.
