### ISSUE TITLE
Windows GUI 

### ISSUE THREAD

**Issue by CpkoHub** [TadasBaltrusaitis/OpenFace#312]
Hello,

I would like to know if the new Windows GUI is in preparation.

 I would like to use it for AU extraction and be able to export in .csv.

 I tried to use the Version 0-5.1 but have seen that  only a part of all AU (from 1 to 28) are tracked with this version and that the application generate two files File AU_Class and  AU_Reg which seem like a CSV format (and want to know if it is ok to use this format).

Could you help me with that ?

Many thanks.

**Comment by TadasBaltrusaitis** [comment]
Hi,

I'm actively working on the new GUI version at the moment, I don't have an estimated time of completion, but hoping for the end of the month.

Thanks,
Tadas

**Comment by TadasBaltrusaitis** [comment]
Windows GUI has just been released!
