### ISSUE TITLE
feature/Windows-GUI isn't compiling

### ISSUE THREAD

**Issue by wasimf** [TadasBaltrusaitis/OpenFace#315]
Hi , 

I downloaded the feature/Windows-GUI , and trying to compile but get compilation error. 
Actually I need it to get integration of the OpenFace with my c# code. 

Any ides please ? 
Thanks ...

**Comment by TadasBaltrusaitis** [comment]
It's still very much in work in progress mode and certain commits will not compile. I'm actively working on it now and hoping to have a working GUI version soon.

**Comment by TadasBaltrusaitis** [comment]
GUI has just been released
