### ISSUE TITLE
Landmark shaking in particular pose angle

### ISSUE THREAD

**Issue by waterball** [TadasBaltrusaitis/OpenFace#317]
Hi, I use OpenFace to detect landmarks and to rebuild pose. I find when posing in certain angle, the cube and landmarks drawn keep shaking.  By the way, I use the default setting of all parameters and did not change anything.  Any suggestions? Thanks!

**Comment by TadasBaltrusaitis** [comment]
There are certain angles in which the result is a bit jittery, it is a known issue. The next version of OpenFace will include a better landmark detector which should reduce the issue.

**Comment by waterball** [comment]
OK. Thanks. Looking forward to the next version

**Comment by TigerHix** [comment]
@TadasBaltrusaitis This issue still exists in the latest version of OpenFace when reading from a webcam with default configuration (`OptimizeForVideo`). Any workarounds?

![qqqq](https://user-images.githubusercontent.com/3406505/81500948-6466ba80-92a3-11ea-931f-452f23a960b0.gif)

**Comment by TadasBaltrusaitis** [comment]
The issue has been reduced since the last version, but not completely eliminated, there is not much that can be done easily to resolve this (you can try smoothing the predicted values)
