### ISSUE TITLE
Mac Installation tbb

### ISSUE THREAD

**Issue by sisyphus1110** [TadasBaltrusaitis/OpenFace#32]
Hi Tadas,
Hello from ICT!

OpenFace runs perfectly on my windows machine, but when I tried to install on Mac, it cannot find TBB;

> cmake -D CMAKE_BUILD_TYPE=RELEASE .
> OpenCV information:
>   OpenCV_INCLUDE_DIRS: /usr/local/Cellar/opencv3/3.1.0_3/include/opencv;/usr/local/Cellar/opencv3/3.1.0_3/include
>   OpenCV_LIBRARIES: opencv_videostab;opencv_videoio;opencv_video;opencv_superres;opencv_stitching;opencv_shape;opencv_photo;opencv_objdetect;opencv_ml;opencv_imgproc;opencv_imgcodecs;opencv_highgui;opencv_flann;opencv_features2d;opencv_core;opencv_calib3d
>   OpenCV_LIBRARY_DIRS: 
> -- Boost version: 1.60.0
> -- Found the following Boost libraries:
> --   filesystem
> --   system
> Boost information:
>   Boost_INCLUDE_DIRS: /usr/local/include
>   Boost_LIBRARIES: /usr/local/lib/libboost_filesystem-mt.dylib;/usr/local/lib/libboost_system-mt.dylib
>   Boost_LIBRARY_DIRS: /usr/local/lib
> X11 information:
>   X11_INCLUDE_DIR: /usr/X11R6/include
>   X11_LIBRARIES: /usr/X11R6/lib/libSM.dylib;/usr/X11R6/lib/libICE.dylib;/usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib
>   X11_LIBRARY_DIRS: 
> CMake Error at /Applications/CMake.app/Contents/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>   Could NOT find TBB (missing: TBB_ROOT_DIR TBB_INCLUDE_DIR TBB_LIBRARY)
> Call Stack (most recent call first):
>   /Applications/CMake.app/Contents/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>   cmake/modules/FindTBB.cmake:291 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:32 (find_package)
> 

I also tried to add something to the CMakeLists.txt similar to what you suggested in Wiki for finding OpenCV, something like, `find_package( TBB HINTS ~/OpenFace/lib/3rdParty/tbb/`... But it didn't work..

**Comment by TadasBaltrusaitis** [comment]
Hi,

Do you have TBB installed on your machine? The version in `~/OpenFace/lib/3rdParty/tbb/` is for a Windows machine.

Thanks,
Tadas

**Comment by sisyphus1110** [comment]
oops, just installed TBB for mac and it worked! Thank you!
