### ISSUE TITLE
The newest version doesn't provide txt output.

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#320]
I re-ran the AU_training scripts with 0.3.0
However, it doesn't give AU output, or params.txt
in BP4D, 
(i.e. "F001_Surprise.params.csv" instead "F001_Surprise.params.txt")
And, no AU is analyzed with any command combinations.

**It seems work properly for movie clips, but has issue when processing the folder with images.**
(when I process the clips, it gives properly the params.txt)

**Comment by TadasBaltrusaitis** [comment]
Hi,

The .txt files have been replace with .csv files now, can you send me the content of your csv files? They should contain AU values. 

What were the command line arguments you used?

To process image directories use the -fdir command with FeatureExtraction executable.

**Comment by iPsych** [comment]
I tested same command with 0.2.5 and 0.3.0 in OS X Sierra,
I found the latter gives only 
frame, timestamp, confidence, success columns in .csv.
the former gives proper .txt file.

Is there any update reflecting 0.3.0 update in AU_training procedures?

**Comment by TadasBaltrusaitis** [comment]
The interface changed somewhat and the same commands will not work, please have a look at - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by iPsych** [comment]
I checked that page too.
I think something is not working properly with -fdir option, since video clips (mpeg, mp4, mov) processed fine.

Did you trained the AU again after the update or not?

**Comment by TadasBaltrusaitis** [comment]
All the results before the update to 0.3.0 should be the same or very similar. Could you let me know the exact command line arguments you used?

The AU module was not retrained.

**Comment by iPsych** [comment]
I found that 
 - train_static_regressors.m
 - train_static_classifiers.m
 - train_dynamic_regressors.m
works properly.
However, the train_dynamic classifiers gives the error.
"Index exceeds matrix dimensions.

Error in Prepare_HOG_AU_data_generic_dynamic (line 58)
train_appearance_data = train_appearance_data(reduced_inds,:);

Error in train_dynamic_classifiers (line 51)
        [train_samples_bp4d, train_labels_bp4d, valid_samples_bp4d, valid_labels_bp4d, ~, PC, means, scaling] =
        Prepare_HOG_AU_data_generic_dynamic(train_recs, devel_recs, au, BP4D_dir, hog_data_dir);
 "
So I checked the size in that script.

>> size(labels_other)

ans =

       75586          10

>> size(labels_train)

ans =

       75586           1

>> size(valid_ids_train_hog)

ans =

       11093           1

>> size(valid_ids_train)

ans =

       75586           1

**Comment by Heyxiang** [comment]
@TadasBaltrusaitis  https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments   
 windows x64  no output
