### ISSUE TITLE
FaceLandmarkImg failed to find the face landmark features.

### ISSUE THREAD

**Issue by michaelhuang74** [TadasBaltrusaitis/OpenFace#322]
For the following image, I ran the following command on Ubuntu 14.04. But the FaceLandmarkImg didn't generate the .csv file.

sudo ./bin/FaceLandmarkImg -f "littlegirl.jpg" -wild

![littlegirl_600](https://user-images.githubusercontent.com/23154573/34965886-291a265e-fa1d-11e7-84a0-5a5d553dad94.jpg)

**Comment by TadasBaltrusaitis** [comment]
The issue is that the HOG face detector is not able to detect a face in this image due to the face pose. The new version (coming in 2-3 months) will be able to handle such images.

**Comment by TadasBaltrusaitis** [comment]
OpenFace 2.0 has now been released and it should be able to handle such images much better.
