### ISSUE TITLE
Unsymmetric AU output support

### ISSUE THREAD

**Issue by NumesSanguis** [TadasBaltrusaitis/OpenFace#324]
The AU output currently is always symmetric, that means that OpenFace cannot encode raising only left-eyebrow or right-mouth-corner. Do you think support for this is coming soon?

Example ouput: AU02_r_L: 0.8

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, we do not have much training data for asymmetric expressions, so support is not coming soon.
