### ISSUE TITLE
I am in problems with OpenFace

### ISSUE THREAD

**Issue by profelove** [TadasBaltrusaitis/OpenFace#326]
Hello smart guys!

I am starting my experiment about facial expression through a videogame. I dont know any about programming and I want to use the facial expressions software for it. I installed the all folder to install OpenFace v.1 and it is working well, in executable .Windows.  Openface: https://www.cl.cam.ac.uk/~tb346/res/openface.htmlhttps://www.cl.cam.ac.uk/~tb346/res/openface.html

This folder dont need libraries and other things, only I am clicking on the Openface, it record the face.  The problem is that this version have not the timestamp, only it give me the frames.  I checked your chat about this topic but I cannot install the new version of openface in my computer.  I attach the photos of the software that I have about OpenFace now. 
![timestamp open face request](https://user-images.githubusercontent.com/35535993/35054847-f401fa0e-fbad-11e7-8691-ee8db3d0c6c7.jpg)
![data openface](https://user-images.githubusercontent.com/35535993/35054988-4d0733bc-fbae-11e7-929b-4f2de65ffe3e.jpg)

Please could you help me? :(

Alexandra

**Comment by TadasBaltrusaitis** [comment]
A new version of OpenFace that can be used as a GUI that will have timestamps is coming soon.
