### ISSUE TITLE
winx64 FeatureExtraction.exe -f "C:\my videos\video.avi" no output

### ISSUE THREAD

**Issue by Heyxiang** [TadasBaltrusaitis/OpenFace#327]
@TadasBaltrusaitis   winx64 FeatureExtraction.exe -f "C:\my videos\video.avi" no output

**Comment by Heyxiang** [comment]
There is no output with the win x64 zip you compiled, but with the output that I compiled myself.

**Comment by TadasBaltrusaitis** [comment]
Where is the FeatureExtraction.exe located? You might not have permissions to write to that directory? The output will create a processed directory in the current directory of the command prompt. Can you post the exact output in the command line?
