### ISSUE TITLE
how to get the position of eyeball?

### ISSUE THREAD

**Issue by NoodlesVision** [TadasBaltrusaitis/OpenFace#328]
hi

cv::Mat offset = (cv::Mat_<double>(3, 1) << 0, -3.5, 7.0);
cv::Mat eyeballCentreMat = (faceLdmks3d.row(36+eyeIdx*6) + faceLdmks3d.row(39+eyeIdx*6))/2.0f +(cv::Mat(rotMat)*offset).t();

cv::Point3f gazeVecAxis = RaySphereIntersect(cv::Point3f(0,0,0), rayDir, eyeballCentre, 12) - eyeballCentre;

would you please explain the code above? thanks!

**Comment by Spatiumensura** [comment]
Hello, 

also, I have recognized, that the offset vector changed with the tag 0.2.5 from 

cv::Mat offset = (cv::Mat_(3, 1) << 0, -3.5, 0.0);

to 

cv::Mat offset = (cv::Mat_(3, 1) << 0, -3.5, 7.0);

What is the reason for this fix?

Many thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

The locations of the eye corners are not the center of the eyeball, the offset allows for a better estimate of the eyeball center.
 
The update to the offset was determined by performing experiments on MPII dataset and the new offset resulted in better gaze estimation accuracy.

**Comment by NoodlesVision** [comment]
Hello TadasBaltrusaitis

i notice that the function RaySphereIntersect(cv::Point3f(0,0,0), rayDir, eyeballCentre, 12) is sloving a quadratic equation. i think there are two intersections when a line intersects a sphere in 3D space, why choose "float t = (-b - sqrt(b*b - 4 * a*c)) / 2 * a"  as the answer?  is  "float t = (-b + sqrt(b*b - 4 * a*c)) / 2 * a"  ok?

also, after i calculate the roots of the quadratic equation two times, i get the belowing:

**float a = (dx - x0)*(dx - x0) + (dy - y0)*(dy - y0) + (dz - z0)*(dz - z0);// different 
float b = 2 * (dx - x0)*(x0 - cx) + 2 * (dy - y0)*(y0 - cy) + 2 * (dz - z0)*(z0 - cz);//different**
float c = cx*cx + cy*cy + cz*cz + x0*x0 + y0*y0 + z0*z0 + -2 * (cx*x0 + cy*y0 + cz*z0) - r*r;

//float t = (-b + sqrt(b*b - 4 * a*c)) / 2 * a; // is this ok?
float t = (-b - sqrt(b*b - 4 * a*c)) / 2 * a;
	 
**return rayOrigin + (rayDir - rayOrigin) * t; // different**

it's a little different with yours, i am confused now。so what 's your opinion?


many thanks!

**Comment by TadasBaltrusaitis** [comment]
As you mention there are two intersections between the ray and sphere (if they intersect at all). We are interested in the first intersection, as that is when the ray hits the front of the eyeball (and not the back). Lower `t` will give the first intersection, and the `t` that is computed by subtracting will be the first `t`. You can always confirm that by computing both of them and choosing the lower `t`.

**Comment by Spatiumensura** [comment]
Hello Tadas, 

I have another question regarding the gaze computation: Why are you calculating the intersection of the camera-pupil-ray with the eye-ball to get the gaze orientation, i. e. draw a line from the intersection to the eye-ball-center? Wouldn't it be possible to directly take the vector from eye-ball-center to pupil-position as gaze direction?

Many thanks!

**Comment by TadasBaltrusaitis** [comment]
It would be, however, the 3D location of the pupil is not that accurate and is often noisy. So experimentally we found it more accurate to do it the other way (even though it feels counter-intuitive).
