### ISSUE TITLE
Wrong hog size when I train using BP4D.

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#329]
I think the hog size is wrong when I train AUs with extracted information.

Can you check the matrix size of proper .hog file of BP4D?

In my case, some are 7560x4465, and  15120x4465.
When I re-extract with another compiled version of openface, it's 18816x4465.

The size is measured by Read_HOG_files_dynamic_pp.m with putting the below code in line 87
            display(sprintf('hog Size is %d',size(hog_data)))
Bests,
J.

**Comment by TadasBaltrusaitis** [comment]
The matrix size will depend on the number of frames in the video/sequence, what numbers are you reporting? Which videos do you mean?

Thanks,
Tadas
