### ISSUE TITLE
how to fetch more action units ?

### ISSUE THREAD

**Issue by zxc586794azxc** [TadasBaltrusaitis/OpenFace#332]
The au of openface just has 18 action units, so I want to know how to fetch more action units and output them?
thank you!

**Comment by TadasBaltrusaitis** [comment]
You would need to collect or find a dataset that has the extra action units you want to recognise, then you could train a recogniser for them using the code in OpenFace.

**Comment by zxc586794azxc** [comment]
hi, thank you for your reply. But I'm wondering the following two questions. 
1. Is the dataset you said the other AU excluding existing ones?    
2. Which code in OpenFace can I use to train recogniser?  I can't find the code it can train out like this AU_1_dynamic.dat

thank you for your help

**Comment by TadasBaltrusaitis** [comment]
I'm not sure I understand your first question. Instructions of how to train AU modules can be found here - https://github.com/TadasBaltrusaitis/OpenFace/tree/master/matlab_version/AU_training

**Comment by zxc586794azxc** [comment]
My first question is, excluding the existing 18 AUs, how to train other AUs, such as the other facial muscle's movements.
Does that use the code you attached?

Thank you for your help!

**Comment by TadasBaltrusaitis** [comment]
You can use the code that I linked to, but the more difficult bit is actually finding the data that labeled with the other action units you are interested in.

**Comment by zxc586794azxc** [comment]
What's the datatype of the data you mentioned? The training process is finding some pictures which have specific action units and use them into matlab code?  Thank you!

**Comment by TadasBaltrusaitis** [comment]
Yes, you want pictures or videos labeled per frame for the action units you would want to predict, then you could use the matlab code to train models on them. Do note that you need a reasonable amount of examples for a reliable model (100s or 1000s of pictures)
