### ISSUE TITLE
60FPS Processing

### ISSUE THREAD

**Issue by calben** [TadasBaltrusaitis/OpenFace#333]
Hullo everyone,

I've added video settings to capture at a higher framerate like the below:

		video_capture.set(cv::CAP_PROP_FPS, 60);
		video_capture.set(cv::CAP_PROP_FRAME_HEIGHT, 720);
		video_capture.set(cv::CAP_PROP_FRAME_WIDTH, 1280);

It does seem to be capturing at the correct framerate, but somewhere later in the code the target framerate seems to still be set to 30fps.
The output hovers around 30, occasionally hitting 31.

How do I remove this suggested framerate and process the input at the full 60fps?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
The processing speed is not limited to the capture speed, even if your camera can capture 60 or even 120 FPS, the processing of the images will most likely be slower. The framerates you can reach will depend on the computational power of your machine. If you are interested you can profile the code to see which parts end up taking the most time.
