### ISSUE TITLE
Increase size of Feature Extraction

### ISSUE THREAD

**Issue by daniezest** [TadasBaltrusaitis/OpenFace#337]
Hi, I would like to be able to increase the size of the extracted face. e.g. I would like to include other features such as hair, ears and parts of the neck. 

Is this possible through the Feature Extraction function?

**Comment by TadasBaltrusaitis** [comment]
You would need to edit the code to achieve that, currently there is no support for not masking out the rest of the face. If you are interested, have a look at `AlignFaceMask` function in `Face_utils.cpp`. I am considering adding support for non masked output faces in future releases though, as that can often be useful.
