### ISSUE TITLE
Seeking solution to downgrade openCV to 3.1

### ISSUE THREAD

**Issue by JadonMing** [TadasBaltrusaitis/OpenFace#339]
Hi, I've followed the installation guidance for Mac OS. Since Homebrew only holds version 3.4 of opencv and it is currently incompatible with OpenFace, can anyone indicate a way to install opencv 3.1 on Mac OS?

(Source code of opencv 3.1 can be found on Internet. It seems that I need to compile it manually.)

**Comment by JadonMing** [comment]
Solution in
[https://github.com/TadasBaltrusaitis/OpenFace/pull/335](url)
works for me. This can be closed. Many thanks to @mlamarre

**Comment by thanhmvu** [comment]
That url is dead

**Comment by TadasBaltrusaitis** [comment]
That url is dead, as the fix has been integrated into the master version.

**Comment by Hugomeyer95** [comment]
Hello, I m sorry I didn't get how to fix the downgrade of OpenCV issue on mac.
I also have the source code of the 3.3 version but no idea how to install it.

**Comment by zequnyu** [comment]
My problem and solution was on version 1.x, so I don’t know what’s the difference for now. Actually you can find the pull history on Pull Request -> closed -> #335 ->files changed, where you can view the code. GitHub url is strange.

**Comment by Hugomeyer95** [comment]
Ok thanks I ll have a look!
