### ISSUE TITLE
Running and testing 

### ISSUE THREAD

**Issue by jhpark1013** [TadasBaltrusaitis/OpenFace#34]
I don’t think I’m running this correctly. On Unix installation file you said to test it with videos with the following code: ./bin/FaceLandmarkVid -f "../videos/changeLighting.wmv"
However, I don’t see the “bin" directory. I see that the FaceLandmarkVid file is in the “exe” directory. On the linux terminal, I’m running (From within the exe directory) this: FaceLandmarkVid -f “../videos/changeLighting.wmv” 
And I get an error saying “FaceLandmarkVid: Command not found”. And if I run the cpp file, I get a permission error.
Sorry if this is a trivial problem. What am I doing wrong?
Thanks

**Comment by TadasBaltrusaitis** [comment]
If you followed instruction for compilation you should have the following directory structure:
`OpenFace/build/bin/` all the executables should live in the `bin` directory. For the example code to run you should be in the `build` directory, as it attempts to run the executable in `bin` directory on a video from `videos` directory.

Let me know if you see the same directory structure.

Thanks,
Tadas

**Comment by jhpark1013** [comment]
Thanks for getting back to me. I don't see the FaceLandmarkVid file/directory in OpenFace/build/bin. All I see is the AU_predictors, classifiers, and model directories.

**Comment by TadasBaltrusaitis** [comment]
It seems like the code was not compiled correctly, or maybe not output in the right directories. Does the compilation succeed? Does the file `FaceLandmarkVid` exist anywhere?

**Comment by 5ong** [comment]
Hi,
I have the same issue running the docker image: there is no "bin" folder under "build". Please point me to the right direction.

Thanks,
-5ong

**Comment by TadasBaltrusaitis** [comment]
What is the output from the compiler? Does running `make` result in any errors?

Thanks,
Tadas

**Comment by Faiz-p** [comment]
After executing the provided code in Colab, I didn't observe the creation of a "bin" directory. Instead, I noticed an "exe" folder, which does not contain any executable files. Others have encountered the same issue mentioned previously. Has a solution been found?

**Comment by brmarkus** [comment]
Were any logs caputured while the set-up in Colab?

**Comment by Faiz-p** [comment]
Hello, thank you for your prompt response, I attempted to utilize the
script available at
https://colab.research.google.com/github/ykitaguchi77/Colab_Scripts/blob/master/OpenFace_colab.ipynb
However i encountered an error during execution:
/bin/bash: line 1: ./OpenFace/build/bin/FaceLandmarkVidMulti: No such file
or directory

it seems there might be some issue related to the path or setup. i would
appreciate any guidance on resolving the matter. your assistance is highly
valued
Thank You

**Comment by brmarkus** [comment]
Were you patient enough with the several steps - because especially the first step can take VERY VERY LONG - and needs to be finished completely and successfully before you try to continue with the next steps...

Are you sure all the previous steps run successfully before you tried the (third) step calling `!./OpenFace/build/bin/FaceLandmarkVidMulti -f video.mp4 -out_dir processed`?

**Comment by Faiz-p** [comment]
i Don't know why but running the first step is not taking longer for me

**Comment by Faiz-p** [comment]
No build was created after execution, FaceLandmarkVid was found on exe
folder which is not executable.
