### ISSUE TITLE
Boost version for current OpenFace on Mac

### ISSUE THREAD

**Issue by JadonMing** [TadasBaltrusaitis/OpenFace#340]
I spent hours to install it on my Mac OS.

It turned out that brew will install the latest version of boost, which is 1.66, and it causes errors due to its incompatibility with dlib.

I first follow the instruction in Wiki as it mentioned that we may need to downgrade to boost 1.50.

It turned out to me that this version(1.5) doesn't work on my Mac (10.11.6). I also notice that in `CMakeLists.txt` it has `find_package( Boost 1.5.9 REQUIRED COMPONENTS filesystem system)`.

And finally I followed [https://github.com/TadasBaltrusaitis/OpenFace/issues/258](url) to install version 1.64 manually, this works!

Does it indicate that boost version should be **greater than 1.59 but smaller than 1.65**?

Also in issue 258 the solution to install boost 1.64 is a bit incomplete. I hope the following snippet could be helpful to people (added **prefix** to link files).
```
./bootstrap.sh --prefix=/usr/local
./b2
./b2 install
```
For the boost version issue, if my guess is correct, this should be stressed in Wiki until the problem is completely solved by new version of OpenFace. Current Wiki on Mac installation is a bit misleading. I hope people with the same problem won't spend hours (really takes long time to wait for boost to be manually compiled) on installation.

**Comment by TadasBaltrusaitis** [comment]
Thanks for your suggestions! I will include your description in the wiki. As I don't have a Mac, it's a bit tricky for me to debug these issues.
