### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Jeff19944** [TadasBaltrusaitis/OpenFace#341]
Hello,

I met this kind of problem,"FeatureExtraction.exe: command not found" when i did "FeatureExtraction.exe -f "../R04.mp4"". Could you please help me?

**Comment by TadasBaltrusaitis** [comment]
Hi,

Do you have FeatureExtraction.exe in the current directory? What OS are you using? You will need to provide a bit more detail for me to help you debug.

**Comment by Jeff19944** [comment]
No, i don't have the FeatureExtraction.exe in the current directory. I am using Linux. I don't know that much about the code so i just did "cmake CMakeLists.txt" then "make", is there anything that i should do before ""FeatureExtraction.exe -f"?

**Comment by TadasBaltrusaitis** [comment]
Please read installation instructions - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

The .exe files are only used on Windows, for running the commands on unix and Windows please carefully read -
 https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by Jeff19944** [comment]
Ok, thank you so much!
