### ISSUE TITLE
Subface model mat size.

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#342]
The original .mat files downloaded from github are below sizes

**lower**
4464x1207
1x4464
1x4464

**rigid**
4464x1401
1x4464
1x4464

**upper**
4464x1210
1x4464
1x4464

However, when I create subface model with createSubFaceModels.m, there are fluctuations. I suspect the last lines which keep 98% of variability, but not sure. Is it normal to fluctuate in size? or did I made some mistake in prior steps?

**Lower**
4464x1191 -> 1194 ->1193
1x4464
1x4464

**rigid**
4464x1357 ->1362 -> 1363
1x4464
1x4464

**upper**
4464x 1191 ->1194
1x4464
1x4464

**Comment by TadasBaltrusaitis** [comment]
Are you getting different number of principal components for each run? I think the small differences in the number of components should have a fairly minimal effect on the rest of the performance as long as the other code is correct. Did you have all the other datasets for PCA construction? As missing some of them could have led to small differences as well.

**Comment by iPsych** [comment]
I think something wrong with the processing of BP4D.
when I exclude it in the training codes, it seems work properly.

but when I add it, it gives index exceeds error in hog preperation steps.
