### ISSUE TITLE
AU training and new version 

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#343]
Hello,
Does newest version which support the opencv 3.3 also fit to existing AU training codes? 
I think the result format is changed and I am worrying about possible incompatibility.

**Comment by TadasBaltrusaitis** [comment]
Thanks for reminding me of this, I have not yet adapted the AU training scripts to match the new executables. I will do so shortly.

**Comment by TadasBaltrusaitis** [comment]
This has been fixed now.
