### ISSUE TITLE
Windows binaries link wikia outdated

### ISSUE THREAD

**Issue by NumesSanguis** [TadasBaltrusaitis/OpenFace#345]
Just a small heads-up you probably want to change your hardcoded link to 1 version of your binary to your release page.

So add https://github.com/TadasBaltrusaitis/OpenFace/releases to https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation.

**Comment by TadasBaltrusaitis** [comment]
Thanks for spotting the issue!
