### ISSUE TITLE
how to get pdm_68_multi_pie.mat

### ISSUE THREAD

**Issue by xunkaixin** [TadasBaltrusaitis/OpenFace#346]
I'm using a dataset containing 21 landmarks, and have some landmarks different with 68.

can you give me some advise to get the mat?
      
Comment this code, is OK? 

**
% Also align the model to a Multi-PIE one for accurate head orientation
% also align the mean shape model (an aligned 68 point PDM from Multi-PIE dataset)
M_wild = M;

load('pdm_68_multi_pie.mat', 'M');
M_align = M;

n_points = numel(M)/3;

M_wild = reshape(M_wild, n_points, 3);

% work out the translation and rotation needed
[ R, T ] = AlignShapesKabsch(M_wild, reshape(M_align, n_points,3));

% Transform the wild one to be in the same reference as the Multi-PIE one
M_aligned = (R * M_wild')';

M_aligned(:,1) = M_aligned(:,1) + T(1);
M_aligned(:,2) = M_aligned(:,2) + T(2);
M_aligned(:,3) = M_aligned(:,3) + T(3);

M_aligned = M_aligned(:);
V_aligned = V;

% need to align the principal components as well
for i=1:size(V,2)
    
    V_aligned_pie_curr = (R * reshape(V(:,i), n_points, 3)')';
    V_aligned(:,i) = V_aligned_pie_curr(:);    
    
end

V = V_aligned;
M = M_aligned;
**

thanks

**Comment by TadasBaltrusaitis** [comment]
Do you still have a question or did you manage to resolve the issue?

**Comment by xunkaixin** [comment]
i try to comment the code and generate pdm_21.mat and tri_21.mat, but when i show the pdm,  the figure doesn't look right
