### ISSUE TITLE
how to deal with "39 points for profile faces"?

### ISSUE THREAD

**Issue by xunkaixin** [TadasBaltrusaitis/OpenFace#348]
hi,
   in menpo dataset, there  are 39 points mark-up used for annotations in profile faces.
   i found in matlab code , it convert the 39 points to 68 points, but the other points set to 0,
  is it OK?  how to deal with the zero points in training?

**Comment by TadasBaltrusaitis** [comment]
The patch expert training code ignores the non-visible landmarks when training the, so those points are just ignored. As each patch expert for each landmark is independent, this does not cause any issues.

**Comment by xunkaixin** [comment]
thank you
