### ISSUE TITLE
FeatureExtraction: -pose still outputs all possible data....

### ISSUE THREAD

**Issue by spamrefuse** [TadasBaltrusaitis/OpenFace#349]
The manual at [Command-line-arguments](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments) says:

> By default the executable will output all features (tracked videos, HOG files, similarity aligned images and a .csv file with landmarks, action units and gaze). You might not always want to extract all the output features, you can specify the desired output using the following flags:

However, when I do

`FeatureExtraction -pose -f input.mp4 -of output.dat`

it still prints the extensive default output to the output file.....

Is this a bug?

-R.

**Comment by spamrefuse** [comment]
In fact, I cannot find any lines in the source code that deal with "-pose", "-gaze", etc.
Is the online documentation of the optional flags ahead of the actual code implementation?
-R

**Comment by TadasBaltrusaitis** [comment]
Are you using the newest version of the code? This is a recent change to the interface. Have a look at `RecorderOpenFaceParameters.cpp` to see how the flags are implemented in the code.

**Comment by spamrefuse** [comment]
I tried to find a version number of some sort, but there seems to be none. Does the OpenFace code do without?

Well, I have downloaded the latest from git (master, that is), but I get stuck with the OpenCV 3.4.0 requirement, whereas I currently have OpenCV 3.3.0-dev. Is this a recent requirement by OpenFace?

-R.

**Comment by spamrefuse** [comment]
As you suggest on the website for Linux Installation, I have installed Boost 1.61 (on Ubuntu 16.04, which requires Boost 1.58). When I compile OpenFace, it ends with conflict warnings about libboost:

`/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by //usr/lib/x86_64-linux-gnu/libmirclient.so.9, may conflict with libboost_system.so.1.61.0`
`/usr/bin/ld: warning: libboost_filesystem.so.1.58.0, needed by //usr/lib/x86_64-linux-gnu/libmircommon.so.7, may conflict with libboost_filesystem.so.1.61.0`

When I run the executable FeatureExtraction, it gives a Segmentation Fault.

Any ideas how to deal with this, or is Ubuntu 16.04 just too old for your recent OpenFace code?

Thanks!
-R.

**Comment by spamrefuse** [comment]
Alas, OpenFace compiles fine on Ubuntu 17.10, but the executable crashes immediately also with a "Segmentation fault (core dump)".

I compiled again with debug flags, and found the culprit at around line 68 of

lib/local/LandmarkDetector/src/LandmarkDetectorParameters.cpp.

I have added extra std::cout statements to check where and when the executable crashes:
```
std::cout << "arguments[0] = " << arguments[0] << "\n";
std::cout << "boost::filesystem::path(arguments[0]) = " << boost::filesystem::path(arguments[0]) << "\n";
std::cout << "boost::filesystem::path(arguments[0]).parent_path() = " << boost::filesystem::path(arguments[0]).parent_path() << "\n";
boost::filesystem::path root = boost::filesystem::path(arguments[0]).parent_path();
```
When I run "bin/FeatureExtraction" in the build directory, I get:
```
arguments[0] = bin/FeatureExtraction
boost::filesystem::path(arguments[0]) = "bin/FeatureExtraction"
Segmentation fault (core dumped)
```
Apparently something is wrong with `boost::filesystem::path(arguments[0]).parent_path()`.

I have boost version 1.62.0.1-amd64 on Ubuntu 17.10.
Does this reveal a bug in boost or in OpenFace?

Regards,
R.

**Comment by TadasBaltrusaitis** [comment]
Ubuntu 16.04 is not too old for OpenFace, it runs on even older versions (as long as the dependencies are installed and you have a C++ 11 compiler)

The warnings you mention should not cause issues, I have the same compilation warnings when compiling.

The detailed debug info is really helpful, this seems like it would be a boost issue. What happens if you manually set the result of that line to "bin", parent_path should return the directory the file is in, it is used for locating model files (as the binary could be called from anywhere, but the model files are stored relative to the executable). This would mean your code would not work when called from another directory, but this might be useful for debugging.

Also can you try calling the same method on different paths? This might allow debugging the issue further.

**Comment by spamrefuse** [comment]
Good to know. Then I switched back to 16.04 and I fixed the problem!

In the [Unix Installation wiki](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation) I modified your suggestion for "Get Clang and libc++:" into:
`sudo apt-get install clang libc++-dev libc++abi-dev`
which picks and installs clang version 3.8, instead of enforcing version 3.7 on your wiki.

Then I again compiled and installed OpenCV 3.4.0 and Boost 1.61.
At the end of the OpenFace compilation I get:
```
[100%] Linking CXX executable ../../bin/FeatureExtraction
/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by //usr/lib/x86_64-linux-gnu/libmirclient.so.9, may conflict with libboost_system.so.1.61.0
/usr/bin/ld: warning: libboost_filesystem.so.1.58.0, needed by //usr/lib/x86_64-linux-gnu/libmircommon.so.7, may conflict with libboost_filesystem.so.1.61.0
[100%] Built target FeatureExtraction
```
Note that libboost_system.so.1.58.0 is required by Ubuntu 16.04 and cannot be removed. However, this conflict in libraries does not seem to cause noticeable trouble.

----------------------------
I use and slightly modify your FeatureExtraction.cpp code. I have a few suggestions:
- output usage information when no arguments are given:
```
int main (int argc, char **argv)
{
	vector<string> arguments = get_arguments(argc, argv);

	// no arguments: output usage
	if (arguments.size() == 1)
	{
		INFO_STREAM("For command line arguments see:");
		INFO_STREAM(" https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments\n");
		return 0;
	}

```
- When converting to grayscale, convert the already captured image, instead of reading again the same frame:
```
			// Converting to grayscale
			//cv::Mat_<uchar> grayscale_image = sequence_reader.GetGrayFrame();
			cv::Mat_<uchar> grayscale_image;
			cv::cvtColor(captured_image, grayscale_image, cv::COLOR_BGR2GRAY);
```
Regards,
R.

**Comment by TadasBaltrusaitis** [comment]
Thanks for the suggestions! I will add them in the next version.
