### ISSUE TITLE
Matlab version

### ISSUE THREAD

**Issue by AJ611** [TadasBaltrusaitis/OpenFace#35]
When I run the face_image_demo.m in matlab_version, it returns me error in Load_Patches_Experts at line 5 , which is colourPatchFiles = dir([col_patch_dir col_patch_file]);

"output argument "patches" (and maybe others) not assigned during call to "Load_Patch_Experts".

**Comment by TadasBaltrusaitis** [comment]
That's odd as the code works fine for me. Are you executing it from the `OpenFace\matlab_version\demo` directory, as it looks for patch expert files relatively to that directory in `OpenFace\matlab_version\models\general`

Thanks,
Tadas

**Comment by AJ611** [comment]
Thank you. I solved it. I need to be careful with the directory of the files involved.

**Comment by AJ611** [comment]
Hello,
What is 'hierarch' in 'model' folder? If I'm not mistaken its contain patch expert models right? But how to use it? Because when I applied it, (I try on `face_image_demo.m`), it gives me error as follow:
`Attempted to access visibilities (1, 7); index out of bounds because size(visibilities)=[1,6].`

**Comment by TadasBaltrusaitis** [comment]
Hi,

Look at the `face_image_demo_eyes.m` script for an example. The `hierarch` folder includes specialist face part models that require the overall landmarks to be initialized so they start fitting in the local area. You will see that this model will track the eye-region more accurately and also will track landmarks that the original 68 points don't cover, such as the iris and the pupil.
