### ISSUE TITLE
Can OpenFace be used for noncommercial nonacademic application?

### ISSUE THREAD

**Issue by errno-mmd** [TadasBaltrusaitis/OpenFace#351]
The README.md says that I should contact innovation@cmu.edu if I need a commercial license,
but I don't know what I should do in a noncommercial nonacademic case.
May I use the OpenFace in my application that generates pose / motion files for 3D character CGs?

**Comment by TadasBaltrusaitis** [comment]
As long as it is a noncommercial use, you can use OpenFace for your projects.

**Comment by errno-mmd** [comment]
Thank you so much!
