### ISSUE TITLE
Display Landmarks locations in 3D on ed Model

### ISSUE THREAD

**Issue by wasimf** [TadasBaltrusaitis/OpenFace#352]
Hi , 
I managed to run the last code and extract the 3D landmarks . 
I'm looking for away to display them on 3d model of the face (obj file)
Is there a practical way you can advice ?

Thanks in advance ...

**Comment by TadasBaltrusaitis** [comment]
You could try finding the closest point to the surface or point cloud (depending on the 3D model format) and visualize those points. Alternatively if you have a corresponding texture you could draw the detected points on the texture for easy visualization. I assume you used the texture image for detecting the landmarks? You could just edit that image (paint the detected landmarks on it) for visualization (although you might get some stretching etc.).
