### ISSUE TITLE
Specifying the frame rate for FeatureExtraction

### ISSUE THREAD

**Issue by krishnadots** [TadasBaltrusaitis/OpenFace#353]
I have a video dataset whose frame rate is around 60 fps. But I want to extract the features using FeatureExtraction at a rate of 30 fps. 
1) Does  FeatureExtraction have a command line argument to specify the frame rate for feature extraction? I did not see an option for this in the command line argument section of the wiki. 

2) In this case, will the timestamp field  for the extracted frames reflect the correct timestamps as they appear in the original video?

thanks

**Comment by TadasBaltrusaitis** [comment]
OpenFace processes each frame that is provided to it, and you cannot control processing frame rate. You can edit the code to skip every other frame or you could convert the fps of the video yourself by using a tool like ffmpeg before passing it to OpenFace.
