### ISSUE TITLE
Tracking multiple faces from webcam

### ISSUE THREAD

**Issue by TomByrne** [TadasBaltrusaitis/OpenFace#356]
Hi, I'm having trouble tracking multiple faces via a camera.
I'm running on Windows, via the command line.

When I use FeatureExtraction I get all of the information I need (in the output CSV).
The limitation here seems to be that it can only track a single face.

When I use FaceLandmarkVidMulti, i can see in the webcam tracking window that it is able to track multiple faces, unfortunately it doesn't seem to write to a CSV file.

I don't need much information, fundamentally just how many people are looking at the screen at any time.

Any help would be much appreciated.

**Comment by TadasBaltrusaitis** [comment]
FeatureExtraction is limited to a single face (explained in a bit more detail here https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments). The reason for this is because re-identification of faces is not supported in OpenFace at the moment, and that is a pre-requisite for facial expression analysis on multiple faces. 

I am thinking of adding this support in the future, as this seems to be a use case that a lot of people are interested in.

In the meantime, you could either edit the `FaceLandmarkVidMulti.cpp` yourself to add the functionality or you could use `FaceLandmarkImg` which can output data about multiple faces, but is not very suitable for videos as it would be quite slow (depends if you need real-time or not).

**Comment by TadasBaltrusaitis** [comment]
There is currently no functionality to output multiple tracked face information for sequences, even without AUs. The tracking is implemented, but output is not (just visualization). In the future version I'm planning to add this functionality.

**Comment by TomByrne** [comment]
Ok, understood.
I look forward to this functionality.

**Comment by TadasBaltrusaitis** [comment]
Multiple face support has been added. It is still experimental, so I would appreciate any feedback.

**Comment by TomByrne** [comment]
I've given it a quick test, looks good.

**Comment by MyraBaba** [comment]
I have below error in MultipleFace:

OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /Users/alpullu/Projects/opencv/modules/highgui/src/window.cpp, line 356

libc++abi.dylib: terminating with uncaught exception of type cv::Exception: opencv/modules/highgui/src/window.cpp:356: error: (-215) size.width>0 && size.height>0 in function imshow

**Comment by MyraBaba** [comment]
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /Users/alpullu/Projects/opencv/modules/highgui/src/window.cpp, line 356












libc++abi.dylib: terminating with uncaught exception of type cv::Exception: opencv/modules/highgui/src/window.cpp:356: error: (-215) size.width>0 && size.height>0 in function imshow

**Comment by MyraBaba** [comment]
I have below error : 

OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file opencv/modules/highgui/src/window.cpp, line 356
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/alpullu/Projects/opencv/modules/highgui/src/window.cpp:356: error: (-215) size.width>0 && size.height>0 in function imshow

**Comment by MyraBaba** [comment]
I have below error:

OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file opencv/modules/highgui/src/window.cpp, line 356
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/alpullu/Projects/opencv/modules/highgui/src/window.cpp:356: error: (-215) size.width>0 && size.height>0 in function imshow

**Comment by TadasBaltrusaitis** [comment]
Is this specifically in the FaceLandmarkVidMulti? More context on the error would be helpful, what command line arguments are you using?

**Comment by MyraBaba** [comment]
Yes I got this from FaceLandmarkVidMulti.  It is working 10-15 secs detect more than 1 faces. than it gave this error.

OS : Mac os X sierra

**Comment by MyraBaba** [comment]
Bytheway FaceLandmarkVid and Multi doenst using the full spu ? I have 8 core but only 1,5 is active?

How we can utilize all of them ?

**Comment by TadasBaltrusaitis** [comment]
Would you be able to share the video you are using or attach a debugger to the code to say which line is causing the issue? 

With regards to parallelization, OpenFace uses TBB internally to process each face separately, also some parallelzation is used when processing each face also using TBB. What framerates are you seeing?
