### ISSUE TITLE
A question about unilateral expression (AU)

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#357]
Hello,
I hope to hear your personal opinion as the developer of OpenFace.

If I train OpenFace AU with additional data,
Do you think it's OK or desirable to include an expression including unilateral AU (i.e. the contempt with Unilateral AU1 and AU2 ) or better to exclude them?

I am not sure it will helpful to detect AU1 and 2 better.

Best,
J.

**Comment by TadasBaltrusaitis** [comment]
Now the training data includes mostly bilateral expressions (with the exception of AU14). Adding unilateral AU might help in recognising unilateral expressions as now OpenFace would fail on them. Another option would be to have bilateral and unilateral AU1 or AU2 as separate classes. I don't think that adding unilateral AU1 would help in recognising bilateral AU1 though.
