### ISSUE TITLE
Question about FeatureExtraction - pose: conversion pixel to millimeter?

### ISSUE THREAD

**Issue by spamrefuse** [TadasBaltrusaitis/OpenFace#358]
Hi,
We are analyzing the pose data using FeatureExtraction on videos.

The pose output data is given in millimeters, but it is somewhat obscure how the info given by the image frames (in units of pixels) is converted to millimeters for the pose....

The [website on pose](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#featureextraction) explains it with somewhat broken (and incomplete?) sentences:

`Where the landmarks are no longer in pixel values but in millimetres and we also report head pose and gaze (this however needs accurate estimates of fx,fy,cx,cy. This functionality is useful for batch image processing where the camera is the same and we want to know pose and gaze.
`

Does this say: "the values of fx,fy,cx,cy are used for converting pixels into millimeter for the pose?"
Where (and how) in the code is the unit conversion done?
Does all this also work for 180-degrees 'fish-eye' cameras?

Thanks!
SR.

**Comment by palich12** [comment]
Cubic pixels))  It is impossible!

**Comment by spamrefuse** [comment]
?? Can you explain a little more?

**Comment by TadasBaltrusaitis** [comment]
There are two steps that are used for converting the pixels to millimeters. 

First of all, it is assumed that the face is of an "average size", that is the interpupillary distance is 65 mm (this is not always correct but a decent approximation). 

This allows us to know the 3D shape (in millimeters) of the object that is being project to the image. We then solve the perspective n point problem (https://en.wikipedia.org/wiki/Perspective-n-Point) to get the pose of the object (position and orientation).
