### ISSUE TITLE
How to generate the pdm model with Multi-PIE dataset

### ISSUE THREAD

**Issue by elecun** [TadasBaltrusaitis/OpenFace#36]
Hi.

There only exist the script for generating PDM using wild dataset.
It generates the model file named 'pdm_68_aligned_wild.mat' well.
But, for more accurate head orientation, 'pdm_68_multi_pie.mat' model file should be required as you comment in the source file.
So, how can I generate the pdm model file with Multi-PIE dataset (pdm_68_multi_pie.mat)?
(I have Multi-PIE dataset and its labels)

thank you in advance

**Comment by TadasBaltrusaitis** [comment]
Hi,

I used an already created Multi-PIE PDM - `pdm_68_multi_pie.mat` and do not have the code to generate the exact version of it. However, you should be able to modify the code for creating the PDM from a wild dataset.

I actually found the in the wild PDM to be more accurate for head poses in the end. I only use the Multi-PIE PDM to align it to a frontal face pose.

Thanks,
Tadas
