### ISSUE TITLE
how to get the 3d data of the full head?

### ISSUE THREAD

**Issue by PengYang123** [TadasBaltrusaitis/OpenFace#360]
In PDM, I could get the 68 landmark_3d data. Is it possible to get the full 3d head model data? For my understanding, the landmark_3d data(mean_shape) should be subset of a certain 3d head model but i don't know which model it is.

**Comment by TadasBaltrusaitis** [comment]
The entire head model is actually made up of only 68 landmarks, there is no more detailed model behind it.
