### ISSUE TITLE
how can you get headpose location in mm (on headposelive gui)

### ISSUE THREAD

**Issue by 5730684221-AB** [TadasBaltrusaitis/OpenFace#362]
i really want to know how to calculate headpose location( x y z in mm) that you show on gui(HeadposeLive)  i really need to study about camera calibration , please i really need your help 
 sorry for my bad english ps i am new to this sorry if my question is stupid

**Comment by TadasBaltrusaitis** [comment]
Sorry, I'm not sure I understand your question. Are you asking how the head pose is computed or how to get it out of OpenFace?

**Comment by 5730684221-AB** [comment]
I think my question is how head pose is computed

**Comment by TadasBaltrusaitis** [comment]
There are two steps that are used for computing the head pose.

Facial landmark detection assumes that the face can be modelled as a parametric 3D model of a face that controls identity and expression. It is assumed that the face is of an "average size", that is the interpupillary distance is 65 mm (this is not always correct but a decent approximation).

This allows us to know the 3D shape (in millimeters) of the object that is being projected to the image (the 2D landmarks). We then solve the perspective n point problem (https://en.wikipedia.org/wiki/Perspective-n-Point) to get the pose of the object (position and orientation).
