### ISSUE TITLE
Can OpenFace use the OpenCV camera calibration parameters for distortion?

### ISSUE THREAD

**Issue by spamrefuse** [TadasBaltrusaitis/OpenFace#363]
Hi,

OpenCV (3.4 in my case) comes with convenient camera calibration tools, that provide the focal length (fx, fy), the optical center (cx, cy) and the distortion correction parameters.

OpenFace has command line arguments to set fx, fy, cx, and cy, but I don't see how OpenFace can make use of the OpenCV parameters that handle the camera distortion.

Or have I overlooked something?

Thanks,
R.

**Comment by TadasBaltrusaitis** [comment]
It does not do any internal image undistortion, if you want to use the distortion correction parameters you would need to undistort the images/videos yourself before inputting them to OpenFace.

Thanks,
Tadas

**Comment by spamrefuse** [comment]
Thank you for the quick response!
R.
