### ISSUE TITLE
got Error  in comparison.py

### ISSUE THREAD

**Issue by Alamincse12** [TadasBaltrusaitis/OpenFace#364]
![error1](https://user-images.githubusercontent.com/36919917/36786307-f2fff32e-1c53-11e8-9452-75cc0674b163.png)
I installed OpenFace by hand in ubuntu 14.04
Now , how can i run the demo code(comparison.py)?
I was placed the comparison.py in the home directory.
And run the code in the home directory.
I got Error.
Traceback (most recent call last):
File "comparison.py", line 33, in
import openface
ImportError: No module named openface
error1

**Comment by TadasBaltrusaitis** [comment]
OpenFace does not have a python interface, you can use it in C++, C# and Matlab.
