### ISSUE TITLE
How to include forehead?

### ISSUE THREAD

**Issue by pitt123** [TadasBaltrusaitis/OpenFace#366]
Hi.
I'm using the record aligned faces but they never contain the forehead.
Is it possible to change any parameter to keep the forehead on the recorded image?

My objective was to crop the image as this triangle mesh:
https://cdn-images-1.medium.com/max/1200/1*wh1N-kogDMaZYS17lqyqeQ.jpeg

Thank you.

**Comment by TadasBaltrusaitis** [comment]
The newest version supports producing non masked out images, you can use the `-nomask` flag for that you could also zoom out a bit of the image with `-simscale 0.6` or `-simscale 0.5` to capture more of the forehead..
