### ISSUE TITLE
Tracking multiple faces.

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#369]
In the recently updated photo of “Facial Landmark and head pose tracking”,
There is multiple tracking with ‘active models’ parameter.
Does the function for tracking multiple faces are included in 0.41 version?

**Comment by TadasBaltrusaitis** [comment]
Yes it is, but the support for multi-face tracking is still experimental. Please let me know if you encounter issues.

**Comment by ra1995** [comment]
Hi, I have written a code to track multiple faces. Even though I give different face_detections to different face_models, the same face is tracked. Please help. Here is the snippet:

`                       for (int i = 0; i < MAX_FACES; i++) {
			if (frame_ctr % DOWN_SAMPLE == 0) {
				face_models[i].Reset();
				face_models[i].detection_success = false;

                                //skip if no bbox is available
				if ((int) bboxes.size() <= i) {
					face_trackers[i] = false;
					continue;
				}
				detection_success[i] = LandmarkDetector::DetectLandmarksInVideo(
						frame, bboxes[i], face_models[i], det_parameters[i],
						gray_frame);
				if (detection_success[i]) {
					face_trackers[i] = true;
					cv::Vec6d pose_estimate = LandmarkDetector::GetPose(
							face_models[i], sequence_reader.fx,
							sequence_reader.fy, sequence_reader.cx,
							sequence_reader.cy);
					face_poses[i] = pose_estimate;
					if ((int) bboxes.size() > i) {
						cv::rectangle(frame, bboxes[i], cv::Scalar(0, 0, 255),
								3);
					}
				} else {
					face_trackers[i] = false;
				}
				continue;
			}
                        //track good predictions
			if (face_trackers[i]) {
				detection_success[i] = LandmarkDetector::DetectLandmarksInVideo(
						frame, face_models[i], det_parameters[i], gray_frame);
				if (!detection_success[i]) {
					face_trackers[i] = false;
				} else {
					cv::Vec6d pose_estimate = LandmarkDetector::GetPose(
							face_models[i], sequence_reader.fx,
							sequence_reader.fy, sequence_reader.cx,
							sequence_reader.cy);
					face_poses[i] = pose_estimate;
					if ((int) bboxes.size() > i) {
						cv::rectangle(frame, bboxes[i], cv::Scalar(0, 0, 255),
								3);
					}
				}
			}
		}`

Thanks.

[FaceLandmarkVid.txt](https://github.com/TadasBaltrusaitis/OpenFace/files/2455038/FaceLandmarkVid.txt)

**Comment by ra1995** [comment]
I solved it by using the provided detectors instead of my own custom detector. I guess it has something to do with the size and shape of the bounding box returned. I was using YOLO.

**Comment by TadasBaltrusaitis** [comment]
It is possible to use your own custom detector, but it needs to be adapted to the right size (a lot of detectors have their own definition of what counts as a face, some are wider some are taller etc.). OpenFace expects a very tight bounding box around facial landmarks it is detecting. I have some snippets of code that show how to adapt your detector in `model_training\bounding_box_mapping`
