### ISSUE TITLE
Issue building on Mac

### ISSUE THREAD

**Issue by mgm248** [TadasBaltrusaitis/OpenFace#37]
<img width="487" alt="screen shot 2016-07-27 at 9 50 49 pm" src="https://cloud.githubusercontent.com/assets/20707533/17220613/d8ca0aa8-54a4-11e6-83d5-8522660bf73c.png">

I am running into an issue when I run "make" after I have run "cmake -D CMAKE_BUILD_TYPE=RELEASE ."  Seems like the program is not finding 'opencv2/imgcodecs.hpp', even though I believe opencv2 is there. I have tried running it with the tweaks to CMake and without, and I end up with the same result. Any help would be appreciated.

**Comment by TadasBaltrusaitis** [comment]
Did you run:
`brew install opencv3`? It seems like CMake cannot find it? Does CMake report anything about OpenCV? Look for a line `OpenCV information:` after running `cmake`

**Comment by mgm248** [comment]
Here's what I see:
OpenCV information:
 OpenCV_INCLUDE_DIRS: /usr/local/include/opencv;/usr/local/include;/usr/local/include/opencv2
  OpenCV_LIBRARIES: opencv_videostab;opencv_video;opencv_ts;opencv_superres;opencv_stitching;opencv_photo;opencv_ocl;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d
  OpenCV_LIBRARY_DIRS: 

Looks like it can find everything but the library directories. Any thoughts?

**Comment by mgm248** [comment]
<img width="489" alt="screen shot 2016-07-29 at 9 56 22 am" src="https://cloud.githubusercontent.com/assets/20707533/17256815/059a5b08-5574-11e6-8ba9-90e876b74817.png">

Forgot to mention, when I install opencv3, this is the message I get. Wondering if that is affecting anything

**Comment by timotheecour** [comment]
had same issue after installing opencv3 on linuxbrew,
fix:

```
OpenCV_DIR=$homebrew_D/Cellar/opencv3/3.1.0_3/share/OpenCV ccmake ~/git_clone/openface_tadas
```

**Comment by gabrielstuff** [comment]
Met the same issue and had to remove opencv2 as https://github.com/TadasBaltrusaitis/OpenFace/issues/37#issuecomment-236256105 suggested.
