### ISSUE TITLE
how to derive gaze angle from gaze vector?

### ISSUE THREAD

**Issue by amsan7** [TadasBaltrusaitis/OpenFace#370]
I'm using the docker image which doesn't provide gaze angle, so I was wondering how to get it from the gaze vector coordinates. Thanks!

**Comment by TadasBaltrusaitis** [comment]
You can have a look at the code that does it in `GazeEstimation.cpp`:

	cv::Point3f gaze_vector = (gaze_vector_1 + gaze_vector_2) / 2;

	double x_angle = atan2(gaze_vector.x, -gaze_vector.z);
	double y_angle = atan2(gaze_vector.y, -gaze_vector.z);

	return cv::Vec2d(x_angle, y_angle);
