### ISSUE TITLE
How can I convert to FBX format or C3D format, I want to use his data for MotionBuilder or Maya.

### ISSUE THREAD

**Issue by wenquan0821** [TadasBaltrusaitis/OpenFace#371]
How can I convert to FBX format or C3D format, I want to use his data for MotionBuilder or Maya.

**Comment by TadasBaltrusaitis** [comment]
I'm not very familiar with those formats, so can't help you here, you can always build a plugin yourself!

**Comment by NumesSanguis** [comment]
I hope to realize this functionality soon in my FACSvatar project: [https://github.com/NumesSanguis/FACSvatar/](https://github.com/NumesSanguis/FACSvatar/)

My project relies on FACS data, and therefore on a model that can use this FACS data to animate its facial expressions. It doesn't work with 3D data of a face if that's what you're looking for.  So I don't know how (yet) how to transfer only the facial data, without including the model. But take a look, it might be useful for you in some way.

**Comment by wenquan0821** [comment]
Yes, I am also studying this project. thank you for your reply.
