### ISSUE TITLE
error while linking CXX executable ../../bin/FaceLandmarkImg 

### ISSUE THREAD

**Issue by buddhashrestha** [TadasBaltrusaitis/OpenFace#372]
Hi!

I am using ubuntu 17.10 and successfully install all the dependencies as mentioned here : 
[https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation](url) 

But, as I compiled the project inside build folder and tried to 'make' the project, I got following error:

`Scanning dependencies of target FaceLandmarkImg                                                
[ 92%] Building CXX object exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o       
[ 93%] Linking CXX executable ../../bin/FaceLandmarkImg
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFaces(std::__1::vector<cv::Rect_<double>, std::__1::allocator<cv::Re
ct_<double> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&)':                    
/home/buddha/projects/tadasOpen/OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorUtils.cpp:(.text+0x5bb3): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputAr
ray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'                                                      
../../lib/local/Utilities/libUtilities.a(RecorderOpenFace.cpp.o): In function `Utilities::RecorderOpenFace::WriteObservation()':                                                              
/home/buddha/projects/tadasOpen/OpenFace/lib/local/Utilities/src/RecorderOpenFace.cpp:(.text+0x813a): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1:
:vector<int, std::__1::allocator<int> > const&)'                                               
/home/buddha/projects/tadasOpen/OpenFace/lib/local/Utilities/src/RecorderOpenFace.cpp:(.text+0x84cf): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1:
:vector<int, std::__1::allocator<int> > const&)'                                               
clang: error: linker command failed with exit code 1 (use -v to see invocation)                
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:130: recipe for target 'bin/FaceLandmarkImg' failed                                                                             
make[2]: *** [bin/FaceLandmarkImg] Error 1     
CMakeFiles/Makefile2:364: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed                                                                                   
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2                  
Makefile:129: recipe for target 'all' failed   
make: *** [all] Error 2                        
`

I'm not sure how to debug this?

**Comment by TadasBaltrusaitis** [comment]
This seems like a linking to OpenCV issue. You might want to check that OpenCV installed correctly.

**Comment by buddhashrestha** [comment]
Hi, Thank you. I started everything from the beginning and it worked.

Now, when I try to run the example, I get the following error:

command I tried : ./bin/FaceLandmarkVid -f "../samples/changeLighting.wmv" -f "../samples/2015-10-15-15-14.avi"

Error:
Could not find the landmark detection model to load
Reading the CLNF landmark detector/tracker from: model/main_clnf_general.txt
Couldn't open the model file, aborting
Attempting to read from file: ../samples/changeLighting.wmv
Device or file opened
Starting tracking
OpenCV Error: Assertion failed (type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3))) in gemmImpl, file /usr/share/opencv-3.4.0/modules/core/src/matmul.cpp, line 1218
terminate called after throwing an instance of 'cv::Exception'
  what():  /usr/share/opencv-3.4.0/modules/core/src/matmul.cpp:1218: error: (-215) type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3)) in function gemmImpl

**Comment by buddhashrestha** [comment]
ok, so I recloned the project and tried to reinstall everything again using the install.sh script. While running the script, it tried to install opencv, where running `make -j4`, I again got this error:


[100%] Linking CXX executable ../../bin/FaceLandmarkImg                                        
../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `LandmarkDetector::DetectFaces(std::__1::vector<cv::Rect_<double>, std::__1::allocator<cv::Re
ct_<double> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&)':                    
/home/buddha/projects/tadasOpen/OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorUtils.cpp:(.text+0x6d1e): undefined reference to `cv::CascadeClassifier::detectMultiScale(cv::_InputAr
ray const&, std::__1::vector<cv::Rect_<int>, std::__1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'                                                      
../../lib/local/Utilities/libUtilities.a(RecorderOpenFace.cpp.o): In function `Utilities::RecorderOpenFace::WriteObservation()':                                                              
/home/buddha/projects/tadasOpen/OpenFace/lib/local/Utilities/src/RecorderOpenFace.cpp:(.text+0x3830): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1:
:vector<int, std::__1::allocator<int> > const&)'                                               
/home/buddha/projects/tadasOpen/OpenFace/lib/local/Utilities/src/RecorderOpenFace.cpp:(.text+0x414d): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1:
:vector<int, std::__1::allocator<int> > const&)'                                               
clang: error: linker command failed with exit code 1 (use -v to see invocation)                
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:130: recipe for target 'bin/FaceLandmarkImg' failed                                                                             
make[2]: *** [bin/FaceLandmarkImg] Error 1     
CMakeFiles/Makefile2:364: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed                                                                                   
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2                  
Makefile:129: recipe for target 'all' failed   
make: *** [all] Error 2                        

I only changed the following line in the install.sh script:

from : sudo apt-get -y install clang-3.7 libc++-dev libc++abi-dev
to :     sudo apt-get -y install clang libc++-dev libc++abi-dev

since clang-3.7 is not available. My current clang version is 4.0.1-6. Do you think that is the cause? Because I have not changed anything other than that in the install.sh script.

**Comment by TadasBaltrusaitis** [comment]
`install.sh` was not written by me and it is not as well supported and maintained. I would suggest you try going through the steps in the wiki for installation https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation, the previous error you were getting indicated that OpenFace was compiled successfully it just failed finding the model files. If you get back to that stage, we can debug from there. Are there model files in the ./bin directory of OpenFace e.g. `./bin/model/main_clnf_general.txt`?

**Comment by buddhashrestha** [comment]
ok i I will again try to install it.

one question, for the following step: 
cmake -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -I/usr/include/libcxxabi" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11 -stdlib=libc++ -lc++abi" -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=<path to opencv_contrib modules> -D BUILD_TIFF=ON -D WITH_V4L=ON -D WITH_GTK=ON -D BUILD_opencv_dnn=OFF -D WITH_TBB=ON ..

what do I replace <path to opencv_contrib modules> with?

**Comment by buddhashrestha** [comment]
So, I did exactly according to the installation:
I used following command to compile opencv, without using OPENCV_EXTRA_MODULES_PATH option :
sudo cmake -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_CXX_FLAGS="-std=c++11 -I/usr/include/libcxxabi" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11 -lc++abi" -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_TIFF=ON -D WITH_V4L=ON -D WITH_GTK=ON -D BUILD_opencv_dnn=OFF -D WITH_TBB=ON ..

and used following command to compile openface project:
 cmake -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_CXX_FLAGS="-std=c++11 -I/usr/include/libcxxabi" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11 -lc++abi" -D CMAKE_BUILD_TYPE=RELEASE ..

now, when I run: ./bin/FaceLandmarkVid -f "../samples/changeLighting.wmv" -f "../samples/2015-10-15-15-14.avi"

i get following error :
1. ./bin/FaceLandmarkVid -f "../samples/changeLighting.wmv" -f "../samples/2015-10-15-15-14.avi"
*** Error in `./bin/FaceLandmarkVid': munmap_chunk(): invalid pointer: 0x00007ffedeee4e02 ***
zsh: abort (core dumped)  ./bin/FaceLandmarkVid -f "../samples/changeLighting.wmv" -f 

2. ./bin/FaceLandmarkImg -fdir "../samples/" -wild 
Attempting to read from directory: ../samples/
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: No such file or directory: "=
zsh: abort (core dumped)  ./bin/FaceLandmarkImg -fdir "../samples/" -wild

is there anything I could do?

**Comment by buddhashrestha** [comment]
Hi @TadasBaltrusaitis  ,

Could you please provide me with any suggestions? I have tried many approaches, but I am not able to run the demo. It would be a great help.

**Comment by TadasBaltrusaitis** [comment]
Hi,

You seemed to have managed to install OpenFace correctly, when you hit the error with the application not being able to find the model files. If you are able to retrace those steps we could debug from there.

It seems like there are various versions of dependencies compiled with both clang and gcc leading to various clashes.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, re-open if there is an issue.

**Comment by deluxerootit** [comment]
I am installing OpenFace via Jenkins. I got the following errors:

`06:07:11 Scanning dependencies of target FaceLandmarkVid
06:07:11 Scanning dependencies of target FaceLandmarkImg
06:07:11 [ 84%] Building CXX object exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/FaceLandmarkVid.cpp.o
06:07:11 [ 86%] Building CXX object exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o

06:07:21 [ 88%] Linking CXX executable ../../bin/FaceLandmarkVid

06:07:22 ../../lib/local/LandmarkDetector/libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o): In function `int dlib::lapack::gesvd<double, 0l, 0l, 0l, 0l, 0l, 0l, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char> >(char, char, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&)':
06:07:22 /vol/robocamp/releases/test/include/dlib/matrix/lapack/gesvd.h:38: undefined reference to `dgesvd_'
06:07:22 /vol/robocamp/releases/test/include/dlib/matrix/lapack/gesvd.h:38: undefined reference to `dgesvd_'
06:07:22 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dsyevr_'
06:07:22 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dpotrf_'
06:07:22 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dpbtrf_'
06:07:22 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dgetrf_'
06:07:22 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `sgetrf_'
06:07:22 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dgesdd_'
06:07:22 collect2: error: ld returned 1 exit status
06:07:22 exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/build.make:122: recipe for target 'bin/FaceLandmarkVid' failed
06:07:22 make[2]: *** [bin/FaceLandmarkVid] Error 1
06:07:22 CMakeFiles/Makefile2:366: recipe for target 'exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/all' failed
06:07:22 make[1]: *** [exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/all] Error 2
06:07:22 make[1]: *** Waiting for unfinished jobs....

06:07:25 [ 90%] Linking CXX executable ../../bin/FaceLandmarkImg

06:07:26 CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o: In function `int dlib::lapack::gesvd<double, 0l, 0l, 0l, 0l, 0l, 0l, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char> >(char, char, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&)':
06:07:26 /vol/robocamp/releases/test/include/dlib/matrix/lapack/gesvd.h:38: undefined reference to `dgesvd_'
06:07:26 /vol/robocamp/releases/test/include/dlib/matrix/lapack/gesvd.h:38: undefined reference to `dgesvd_'
06:07:26 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dsyevr_'
06:07:26 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dpotrf_'
06:07:26 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dpbtrf_'
06:07:26 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dgetrf_'
06:07:26 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `sgetrf_'
06:07:26 /vol/robocamp/releases/test/lib/libdlib.so.19.14.0: undefined reference to `dgesdd_'
06:07:26 collect2: error: ld returned 1 exit status
06:07:26 exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:122: recipe for target 'bin/FaceLandmarkImg' failed
06:07:26 make[2]: *** [bin/FaceLandmarkImg] Error 1
06:07:26 CMakeFiles/Makefile2:308: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
06:07:26 make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
06:07:26 Makefile:129: recipe for target 'all' failed
06:07:26 make: *** [all] Error 2
06:07:26 Build step 'Execute shell' marked build as failure
06:07:26 Finished: FAILURE

`
Any idea how to solve?
