### ISSUE TITLE
Question about how to update the mean_shape and principal comps

### ISSUE THREAD

**Issue by breadbread1984** [TadasBaltrusaitis/OpenFace#377]
I read your code and find it hard to understand how to update the mean_shape and principal components according to the face counter of a specific person, so I decide to seek for your help directly. Could you provide some information about how you do it, or could you refer me to some materials related to this topic. Thx.

**Comment by TadasBaltrusaitis** [comment]
Can you explain your question in more detail? Are you referring to the mean shape of the landmarks in `PDM.h` or the median feature vector used for action unit extraction? Also what do you mean by the face counter?

Thanks,
Tadas

**Comment by breadbread1984** [comment]
yeah I want to figure out the mechanism of class PDM. I found there is a param_local in PDM which contains the weight of eigen vectors of difference from 3D facial mean shape. how do you update param_local?

**Comment by TadasBaltrusaitis** [comment]
The update is done using a version of the Regularised Landmark Mean Shift algorithm (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.708.5598&rep=rep1&type=pdf), you can find more details here - http://www.cl.cam.ac.uk/~tb346/pub/papers/iccv2013.pdf . The algorithm fits both rigid (location, translation and scale) and non-rigid (the expression and identity) parameters of a face model. As the face model is in 3D, an approximation of 3D facial landmarks can be determined from a 2D image.

**Comment by breadbread1984** [comment]
Thx it helps!
