### ISSUE TITLE
Issue with Command Line commands on macOS

### ISSUE THREAD

**Issue by b1t3s1z3** [TadasBaltrusaitis/OpenFace#378]
Hi there,

I believe I have successfully(?) installed and built OpenFace, but I can't get any of the Command Line commands to work. For instance,

When I input...
`$ bin/FaceLandmarkImg -f "/Users/trevor/Desktop/AcademicFiles/MastersThesis/OpenFace-master/sample1.jpg "`

I get...
`dyld: Library not loaded: /usr/local/opt/opencv/lib/libopencv_hdf.3.4.dylib
  Referenced from: /Users/trevor/Desktop/AcademicFiles/MastersThesis/OpenFace-master/bin/FaceLandmarkImg
  Reason: image not found
Abort trap: 6
`

I've ensured that the image file, the executable, and working directory are all the same as per the guide in https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments.

Is this an issue with my installation of opencv? When I go to the directory /usr/local/opt/opencv/lib/ myself I do not see a "libopencv_hdf.3.4.dylib" file.

Any thoughts or help would be appreciated.

UPDATE: I have reinstalled opencv (using brew), installed older versions of opencv (again, using brew), installed older versions of boost. Looking through my /opt/opencv/lib directory, it seems like this "libopencv_hdf.3.4.dylib" is indeed the only file I am missing (cannot figure out why it is not part of the brew installation) that the CMake file is calling for - is there a way someone who has a copy of this one .dylib file can send it to me?

**Comment by TadasBaltrusaitis** [comment]
There is no restriction about the executable and the image being in the same directory, are you sure there is an image in `OpenFace-master` directory?

What happens if you execute:
`$ bin/FaceLandmarkImg -f "/Users/trevor/Desktop/AcademicFiles/MastersThesis/OpenFace-master/samples/sample1.jpg`

**Comment by b1t3s1z3** [comment]
Hi Tadas,

I've executed that command, and I get the exact same error:
`$ bin/FaceLandmarkImg -f "/Users/trevor/Desktop/AcademicFiles/MastersThesis/OpenFace-master/samples/sample1.jpg"
dyld: Library not loaded: /usr/local/opt/opencv/lib/libopencv_hdf.3.4.dylib
  Referenced from: /Users/trevor/Desktop/AcademicFiles/MastersThesis/OpenFace-master/bin/FaceLandmarkImg
  Reason: image not found
Abort trap: 6`

I moved the OpenFace-master directory to a new location on my hard drive, and had exactly the same error. I have ensured that the images are located within the OpenFace-master directory.

**Comment by b1t3s1z3** [comment]
I've fixed the problem - it seems my computer was missing the necessary HDF files in order for the installation of OpenCV to properly complete. Having fixed that on my end, everything runs like a dream now.

Thanks for your amazing project!
