### ISSUE TITLE
Screenshot of Image only and detect eyes look into center of camera

### ISSUE THREAD

**Issue by CanGriffel** [TadasBaltrusaitis/OpenFace#383]
Hey,

I´m very sorry for the issue thread of the CLM-Tracker..

Got still two questions to ask
1. In HeadposeLive the screenshots, is it possible to get only the image saved and not the whole window + without the drawed lines of the tracker?(So that it still calculate everything but just in the background)

2. How can I detect if the eyes look right into the camera?

Thank you in advance for your help!

**Comment by CanGriffel** [comment]
Is it possible to see with this function if the eyes are open, mouth closed and head estimation with tolerance straight??

                        if (yaw <= 5 && yaw >= -5 && roll <= 5 && roll >= -5)
                        {
                            headposetolerance = true;
                            
                        }

                        else if (au_regs["AU25"] <= 0)
                        {
                            mouthclosed = true;
                        }

                        else if(au_regs["AU45"]<=0)
                        {
                            eyesopen = true;
                        }

**Comment by TadasBaltrusaitis** [comment]
Hi, roll does not affect AU or landmark accuracy much as it is an in-plane rotation, pitch and yaw (out-of-plane rotations) are the ones that degrade performance. Further you may want to see if AU25 and AU45 are `< 1` or `<0.5`, as above 1 implies activation of expression, it will rarely be exactly 0.

**Comment by TadasBaltrusaitis** [comment]
Detecting if the eyes are looking at the camera is a bit trickier, but you can look at the eye gaze vector and the location of the eyes themselves in 3D and work out if they intersect (or are close to intersecting) the camera centre (which would be at 0,0,0).

**Comment by CanGriffel** [comment]
Thanks a lot Tadas Baltrusaitis was very helpful!!

My last question ist how to get only the image saved ? I´m trying to get it as a jpeg with the jpegencoder but i struggle to get it running. I´m getting an output file but its empty... the project where i want to implement this is the openfaceoffline. It also throws a lot of errors if i try to add "using System.drawing;" so i decided to go with the jpegencoder

**Comment by TadasBaltrusaitis** [comment]
OpenFace does not support saving just the input images, it does output them with detected landmarks.

**Comment by CanGriffel** [comment]
I got it working to take pictures without detected landmarks. The only thing which I still can´t solve is to get the eyes looking right into the camera. Can you please explain me that a little more detailed? I think I got a bit of what you mean but im still stuck and dont really know where to start.

Thank you so much for your support and have a nice day!

**Comment by CanGriffel** [comment]
What got out of what you mentioned is to use the both eyes gaze (gaze_angle_x, gaze_angle_y)
and compare these with the 3d eye x, y position. But which point should i use, anyone of the pupil points? (eye_lmk_X_0, eye_lmk_Y_0)

**Comment by TadasBaltrusaitis** [comment]
If the person was in the center of the image then you could look if `gaze_angle_x` and `gaze_angle_y` are close to 0.

However, if they are not you need to look at the actual gaze vectors for each eye (or average for both eyes) `gaze_0_x, gaze_0_y, gaze_0_z, gaze_1_x, gaze_1_y, gaze_1_z` and see if they intersect with camera origin when starting at eye center (landmark ids can be found here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#csv-file), or you could even use the center of the head `pose_Tx, pose_Ty, pose_Tz` as an approximation.
