### ISSUE TITLE
Getting real distances

### ISSUE THREAD

**Issue by JavierRojo** [TadasBaltrusaitis/OpenFace#385]
Hello:

First of all, congratulations for such a wonderful tool. Right now I'm trying to calculate the real distances between pairs of points, using the matlab implementation. Is it as simple as to use the 3D XYZ difference of coordinates, or must I use the rotation/translation parameters? The problems start specially when the face is not looking straight to the camera, but turning left or right.

Any help will be wellcomed

P.S.: I have access to data in the .csv generated by FeatureExtraction line command.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Glad you are finding OpenFace useful. It should be as simple as using the distances in 3D coordinates from the output .csv files, they are in world space (so real world distances from camera center). The 3D locations will be more accurate if you provide the application with the focal lengths of the camera you are using though. 

The 3D locations in the Matlab implementation are not the same representations.

**Comment by JavierRojo** [comment]
Thank you really much!  We weren't so sure about the results we were getting
