### ISSUE TITLE
What are the containers of these addresses? about AU training  matlab_version

### ISSUE THREAD

**Issue by zxc586794azxc** [TadasBaltrusaitis/OpenFace#386]
Excuse me, What are the data in these two addresses? 
1.if(exist('C:\tadas\face_datasets\fera_2015\bp4d\AUCoding/', 'file'))
    BP4D_dir = 'C:\tadas\face_datasets\fera_2015\bp4d\AUCoding/';   
    BP4D_dir_int = 'C:\tadas\face_datasets\fera_2015\bp4d\AU Intensity Codes3.0/';
2.if(exist('D:/Datasets/Bosphorus/', 'file'))
    Bosphorus_dir = 'D:\Datasets\Bosphorus/';   
else
end

Are these empty folder??

**Comment by TadasBaltrusaitis** [comment]
These locations contain the AU labels that are provided with the FERA 2015 challenge (bp4d) and the Bosphorus contains the Bosphorus facial expression dataset. They are not included with OpenFace and you would need to acquire them yourself to train the models.
