### ISSUE TITLE
CONFIG_DIR not read correctly for AUs even if defined

### ISSUE THREAD

**Issue by orgicus** [TadasBaltrusaitis/OpenFace#387]
Hi,

First of all thank you so much for sharing this awesome project.
It's a lot of clever work that went into it and it's great to to be able to learn from it.

I've started doing some tests making my own basic app by copying and modifying FaceLandmarkVid and noticed that even though I define `CONFIG_DIR` the FaceAnalyser still has a hard time finding some of the models. I've placed tweaked the code just a bit to narrow down what wasn't loading:

```bash
Reading the landmark validation module....Done
Could not find the AU detection model to load -> FaceAnalyserParameters::init()
config path: ~/AU_predictors/main_dynamic_svms.txt exists = 0
 CONFIG_DIR: 
Could not find the AU detection model to load -> FaceAnalyserParameters::FaceAnalyserParameters(vector<string> &arguments):root() else
================> loading AU_predictors/main_dynamic_svms.txt
Reading the AU analysis module from: AU_predictors/main_dynamic_svms.txt
Couldn't open the model file, aborting
```
Everything else works like a charm.

What's the recommended way of passing the config dir ?
Is there a nice to pass this without using `#define` (perhaps an extra command line/ string array  argument) ?

Thank you,
George

**Comment by TadasBaltrusaitis** [comment]
Glad you are finding OpenFace useful!

OpenFace looks for models in three directories:
- current directory
- executable directory
- CONFIG_DIR

So if you want your app to find them it should be enough to move the AU_predictors folder to the same directory as your executable. While it is possible to pass the exact location of the landmark model file using `-mloc` flag, I never implemented an equivalent for AU model files.
