### ISSUE TITLE
AU Dynamic vs Static models

### ISSUE THREAD

**Issue by ChrizzyM87** [TadasBaltrusaitis/OpenFace#389]
Dear Tadas,
what is the difference between using the dynamic vs. the static prediction models, if you use the dynamic models without post-processing? Are the models trained with the same data and same pre-processing, except that the pipeline for training the dynamic models includes the person-normalization step, which just substracts  the median values?
I'am currently trying to determine which models fit more to my use case. I'am extracting AU intensitys from long videos, with different dynamic range and I'm interested to get the most reliable data before I do any post-processing.
I compared the results for just one video and it seems to me, that using the dynamic models is better, but is there any statement you can make for this in general?
Thanks a lot in advance,
Christoph

**Comment by TadasBaltrusaitis** [comment]
Hi Christoph,

You can find some explanation of static vs. dynamic here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units#static-vs-dynamic

Dynamic model perform two corrections: 1) use median subtracted features for prediction, in a way allowing to deal with different neutral expressions across people 2) performing post-processing to counter bias in over or under prediction resulting from support vector regressors. 

In general if you have sequences that contain more neutral than expressive frames and that only contain the same person I suggest using dynamic models. This is the case for most natural interactions. 

The reason for having a choice for static analysis of videos is that in some rare cases we might want to analyse videos that only contain expressive faces (e.g. a video in which a person is mostly smiling).
