### ISSUE TITLE
What's the meaning of gaze? Why the gaze value so small?

### ISSUE THREAD

**Issue by geyuanjie** [TadasBaltrusaitis/OpenFace#391]
Hi!
I got a trouble about the gaze.The first question is why the gaze value is so small.We obsevered that the gaze angle is at least 30° in the video but the output value is only 0.2 radiam which means 11°.And we do not konw what‘s the reason.
Furthermore,we calculate each eye's gaze :x_angle=atand(gaze_0_x/gaze_0_z);y_angle=atand(gaze_0_y/gaze_0_z).We are not sure is it right.

**Comment by TadasBaltrusaitis** [comment]
Estimating gaze from a webcam video is a really challenging and unsolved problem, so you can't reach perfect results. 

Furthermore, absolute gaze is not as accurate as relative gaze, OpenFace is quite good at detecting changes in eye gaze and not always the absolute location of eye gaze. You might also want to play around with camera focal lengths (`-fx` and `-fy` parameters), as their accuracy also affects the gaze estimation.

I am not sure about your second question? The gaze angle can be computed using the inverse tangent.
