### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by Hardik1496** [TadasBaltrusaitis/OpenFace#392]
/usr/bin/ld: /usr/local/lib/libopencv_core.a(ocl.cpp.o): undefined reference to symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm@@GLIBCXX_3.4.21'
/home/hardik/anaconda2/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:160: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:364: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TadasBaltrusaitis** [comment]
Can you provide more details about the error? It is difficult to interpret without any more details.

A quick google also leads to this, that might be worth trying - https://stackoverflow.com/questions/5083047/linker-problem-with-libstdc-so-6-in-connection-with-cuda

**Comment by Hardik1496** [comment]
Thanks for you quick response.
Following error popped up when executing make commands.
Execution ended at 92% while Linking CXX executable ../../bin/FaceLandmarkImg 
giving above mentioned error.

**Comment by TadasBaltrusaitis** [comment]
You should be able to pass it when calling make I believe.

**Comment by TadasBaltrusaitis** [comment]
You could also try using gcc instead of clang as suggested in other posts.

**Comment by TadasBaltrusaitis** [comment]
Can you try with the new version of OpenFace?

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, re-open if there is an issue.

**Comment by Rtoax** [comment]
```
Consolidate compiler generated dependencies of target CGroupTest
[ 37%] Building CXX object examples/cpp/CMakeFiles/CGroupTest.dir/CGroupTest.cc.o
[ 37%] Linking CXX executable CGroupTest
/usr/bin/ld: /usr/lib64/libLLVMBPFAsmParser.a(BPFAsmParser.cpp.o): undefined reference to symbol '_ZSt21__glibcxx_assert_failPKciS0_S0_@@LLVM_14'
/usr/bin/ld: /usr/lib64/libLLVM-14.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/cpp/CMakeFiles/CGroupTest.dir/build.make:163: examples/cpp/CGroupTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:1013: examples/cpp/CMakeFiles/CGroupTest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
