### ISSUE TITLE
Data(.mat files) manipulation of MPIIGaze Data set

### ISSUE THREAD

**Issue by trakaros** [TadasBaltrusaitis/OpenFace#393]
- I have a problem with  the large **data manipulation** of MPIIGaze. 
- I try to **extract** the data using the Mat2HDF5.m script provided in Project Website
- However,  in **line 9** the command total_num = total_num+length(temp.errors);
matlab can't find the field **errors** in the mat files. I guess that i have considered something wrong, but i dont know what
- Do you have any idea about that?
- I have also created 2 matlab scripts in order to extract manually the data **from .mat to .txt** recursively from MPIIGAZE/ directory
Scripts are here: 
https://github.com/trakaros/MPIIGaze/tree/master/Data(link now not working...i am going to fix it as soon)

**Comment by TadasBaltrusaitis** [comment]
Do you have a version of MPIIGaze with full face images? That dataset is not publicly available and OpenFace evaluates on it.

**Comment by trakaros** [comment]
Hi Tadas,
- I don't have the full face images. The starting images( Original/ ) are 1280x720 images, where in each photo both you can see both. But not the full face
-  Then i have the "Normalized" folder, where each eye is separated from the other and images are 36x60

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, OpenFace will not be able to work on this subset of MPIIGaze, it requires the full face images. You can always try getting in touch with the authors of the dataset to see if you could get access to them.
