### ISSUE TITLE
Possible to combine with existing face recognition library?

### ISSUE THREAD

**Issue by saturnia** [TadasBaltrusaitis/OpenFace#394]
Has anyone been able to combine this brilliant library with an existing
face recognition lib so as to get both the ability to detect known faces
and use the features of openface to detect facial landmarks and gaze etc?

**Comment by TadasBaltrusaitis** [comment]
Not that I'm aware of, but there are a number of open source face recognition libraries that could be used, and it would be quite a nice project.

**Comment by delta42** [comment]
On this topic ... the newer dlib C++ itself has an implementation based on DNN that may work well:
http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html

Now this sample might not do exactly what we would like to achieve, but it may be similar enough to be easily adapted. At some point in the future I would like to experiment with this, perhaps after OpenFace updates dlib.

My main concerns would be: how long does it take to generate a face template and how long does matching take? It's likely that matching will be "fast enough" but that template creation may be problematic for some use cases. If it takes more than 30ms for example it would not be suitable for inserting directly into a webcam video loop but might need to be "threaded-in".

Looking at the [DNN sample] https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp) it seems a frontal_face_detector is used just like OpenFace. So ideally it would be possible to attach the template creation code and/or matching code right in the middle of OpenFace's processing loop.
