### ISSUE TITLE
How to generate the pdm_28_l_eye_3D_closed.txt file?

### ISSUE THREAD

**Issue by loopvoid** [TadasBaltrusaitis/OpenFace#395]
Hi Tadas,
when i use the FaceLandmarkVid.exe tool，i found it loads some data files as follow:

Reading part based module....left_eye_28
Reading the CLNF landmark detector/tracker from: model\model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: model\model_eye\clnf_left_synth.txt
Reading the PDM module from: model\model_eye\pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done

i didn't find any code in your project can train such data files，Could you please tell me how could I train eye 3d pdm and patch expert by myself? A piece of code or paper would help a lot! Thanks!

**Comment by TadasBaltrusaitis** [comment]
The code for generating the eye landmark PDMs has not been released, there is nothing special about it, I just never got round to cleaning it up and packaging it nicely (although it is on my to do list). 

It uses eye landmark data from the SynthesEyes dataset - https://www.cl.cam.ac.uk/research/rainbow/projects/syntheseyes/, but augments it to generate some closed eye examples. It uses the same code as was used to construct the 68 point landmark annotations.

**Comment by loopvoid** [comment]
think you very much!
i will try it.
