### ISSUE TITLE
Some Questions about Gaze-related Output

### ISSUE THREAD

**Issue by sherkwast** [TadasBaltrusaitis/OpenFace#396]
I am using the windows version. I noticed that when using the offline GUI, there is real-time gaze data(Left-right, Up/down) shown in geometry features section. And I also got csv files containing output like (gaze_0_x, gaze_0_y, gaze_0_z) and (gaze_angle_x, gaze_angle_y). 

What I want to ask : 
1. What is the relationship between these two kinds of data? 
2. What does " world coordinates" mean? Is gaze direction relative to head pose? Or is gaze direction relative to a predefined direction such as the direction when people are directly looking at the center of the screen?
3. It seems there is no clear tutorial about how to use it on ubuntu, if I have some videos, What should I do to input them and get these gaze results just like using the windows GUI?

**Comment by TadasBaltrusaitis** [comment]
Hi,

You can find the explanation of what the outputs represent here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format (I updated it slightly just now to add a bit more explanation).

The gaze vectors are the direction of the eye gaze represented as a vector (think of it as a ray going from the eye in the direction of the eye gaze). 

Gaze angles represent the gaze direction in radians averaged for both eyes. If a person is looking left-right this will results in the change of gaze_angle_x and, if a person is looking up-down this will result in change of gaze_angle_y, if a person is looking straight ahead both of the angles will be close to 0 (within measurement error)

The instructions of how to use the command line interface (both Windows/Ubuntu/OSX) is here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments, the outputs from GUI and the command line interface should be identical

**Comment by sherkwast** [comment]
Thank you for quick reply! I'll have a try.
By the way, there are some papers mentioned in citation. Does the one related to eye gaze tracking exactly describe what methods you're using in your implementation?

**Comment by TadasBaltrusaitis** [comment]
Yes, specifically the OpenFace paper - https://www.cl.cam.ac.uk/research/rainbow/projects/openface/wacv2016.pdf

**Comment by sherkwast** [comment]
You said gaze vectors are the direction of the eye gaze. What confuse me is whether the coordinate is based on head pose? or just absolute position of that frame

**Comment by TadasBaltrusaitis** [comment]
The gaze direction vector just identifies the direction of the gaze. If you want to work out what the person might be looking at you would need to look at the origin of the gaze (the 3D location of the eye) and cast a ray in the direction of the gaze vector.

**Comment by sherkwast** [comment]
Could you tell me what exact data are you using in the file `extract_mpii_gaze_test.m`? I just downloaded MPIIGAZE dataset and put it in the database_root variable, but it didn't work.

**Comment by TadasBaltrusaitis** [comment]
The full MPII Gaze dataset on which you could run `extract_mpii_gaze_test.m` is not publicly available. See - https://github.com/TadasBaltrusaitis/OpenFace/issues/134
