### ISSUE TITLE
Adjusting brightness and contrast before running OpenFace?

### ISSUE THREAD

**Issue by Eichhof** [TadasBaltrusaitis/OpenFace#398]
Hello

Does the brightness or contrast of the video matter, i.e. should it be adjusted before running OpenFace so that the face is the best visible?

**Comment by TadasBaltrusaitis** [comment]
Hi,

There is internal correction for brightness and contrast when detecting facial landmarks so it should not matter too much, as long as the image is not over- or under-exposed. General lighting of the scene is more important, you can expect best results with uniform lighting across the face.
