### ISSUE TITLE
Error on FaceLandmarkImg

### ISSUE THREAD

**Issue by mgm248** [TadasBaltrusaitis/OpenFace#40]
When I run this line: bin/FaceLandmarkImg -f ./image_sequence/001.jpg -oi ./output3, the program loads the model but then I get this error:
OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /tmp/opencv3-20160729-19925-gxxi24/opencv-3.1.0/modules/imgcodecs/src/loadsave.cpp, line 459
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160729-19925-gxxi24/opencv-3.1.0/modules/imgcodecs/src/loadsave.cpp:459: error: (-2) could not find a writer for the specified extension in function imwrite_

I have experienced problems with opencv on this program in the past. I did this as a test, what I really want to run is FeatureExtraction, but when I run that, it says "Starting tracking", and then nothing else. The output file is always just an empty .mov. Any ideas?

**Comment by TadasBaltrusaitis** [comment]
The reason is because you didn't specify the output file format in  `-oi ./output3`, instead use something like ` -oi ./output3.jpg` or ` -oi ./output3.bmp`

Are you seeing any output being displayed when you are running the code on the .mov file? Make sure the `-q` flag is not there to see the tracking being visualized.

**Comment by mgm248** [comment]
I apologize, I am not very experienced in coding, what do you mean running the code on the .mov file? I attempted open it, that didn't work, and then I attempted to open it as a text file, (which I noticed will have some text in a normal .mov file), and that showed up empty.

If you mean when I am running FeatureExtraction, no, I don't see anything after "Starting tracking"

**Comment by mgm248** [comment]
You're right about the image, just needed to specific .jpg.

I tried specifying the output as a .txt, and got a file of what looked like only headers, with no data.

Thanks for the help

**Comment by mgm248** [comment]
Problem solved! Must have been something wrong with the video, tried a different one and it worked. Thanks!
