### ISSUE TITLE
Please help! Need x, y, z of individual points

### ISSUE THREAD

**Issue by TheRealSin** [TadasBaltrusaitis/OpenFace#405]
Hello,

I know I can see the X_0, Y_0 ... in the CSV, but can i extract them as well while it´s running?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
To do that you would need to edit the code or include it in one of your projects. You can have a look at the `./exe/FaceLandmarkVid/FaceLandmarkVid.cpp` to see how the features are extracted and visualised in real time, you can then add your own code to interact with your system.

**Comment by TheRealSin** [comment]
And where are they saved in OpenFace?
If I got it right, then it´s the `face_model.detected_landmarks` ?
Still can´t manage to get while ist running the actual coordinates, even in OpenFace.

**Comment by TadasBaltrusaitis** [comment]
You can have a look at the API example documentation for that - https://github.com/TadasBaltrusaitis/OpenFace/wiki/API-calls

**Comment by TheRealSin** [comment]
Thank you!!

Now I was trying to get the head pose and read the pose_Rx as a test.
But it´s returning me:

'An unhandled exception of type 'System.IndexOutOfRangeException' occurred in System.Data.dll

Additional information: An der Position 294 befindet sich keine Zeile.'


The Code I´m using is:

string[] csvRows = File.ReadAllLines(fileN);

                    dt = new DataTable(); 
                    `dt.Columns.Add(csvRows[0]);`

                    for (int x = 1; x < csvRows.Length; x++)
                    {
                        dt.Rows.Add(csvRows[x]);
                    }

                    string OfFile = dt.Rows[294][2].ToString(); //first [0] refers to the column and the second [0] to the cell

**Comment by TheRealSin** [comment]
I hope you can see straight away what the Problem might be. I think It´s just something little what I might do wrong..

**Comment by TadasBaltrusaitis** [comment]
Are you sure the CSV file has 295 rows? also you seem to be accessing the 3rd column? Which would not be the rotation around the x axis?

**Comment by TheRealSin** [comment]
You are totaly right. I was so confused that I tried everything to get it working..
Just want to save as example the pose_Rx in a value, no matter if it is from the .csv file or the `face_model.detected_landmarks`
Could you suggest me any simple way of doing this?

Sorry I´m just not so experienced but willing to learn and don´t want to give up

**Comment by TheRealSin** [comment]
And thanks for all your helpful answers, I appreciate everything!

**Comment by TadasBaltrusaitis** [comment]
To convert from radians to degrees, multiply by 180/pi (approx 57.2958)

**Comment by TheRealSin** [comment]
Tried that out and works fine, thank you!

When I take big Pictures with a Resolution of 5184 x 3456(74dpi) and let them run in the open Image it throws this exception..

An unhandled exception of type 'System.Runtime.InteropServices.SEHException' occurred in CppInerop.dll

Additional information: An extern component has thrown an exception.

Is there anything I can do to fix that?

**Comment by TadasBaltrusaitis** [comment]
I will investigate the high resolution problem. Which executable is causing this issue? Would you mind sharing the exact image that causes this issues so I can debug.

**Comment by TheRealSin** [comment]
The executable I´m using is OpenFaceOffline and the Exception Line is jumping from one to the other but mostly its coming from "DetectLandmarksInImage" of LandmarkDetectorInterop Line 209
![pic1exception](https://user-images.githubusercontent.com/38355669/39312786-e074342a-495f-11e8-938f-7f5570898e0a.PNG)
![pic2exception](https://user-images.githubusercontent.com/38355669/39312787-e0c3a410-495f-11e8-87c9-1cd81366dce6.PNG)

These Pictures are some examples of High Resolution 

![img_0396](https://user-images.githubusercontent.com/38355669/39312921-35cff60c-4960-11e8-93a0-ad3215719762.JPG)
![img_0381](https://user-images.githubusercontent.com/38355669/39312922-36022d3e-4960-11e8-8942-1928dfcebe5d.JPG)


Thanks for the quick and helpful Support!

**Comment by TadasBaltrusaitis** [comment]
That definitely looks like a bug, I will investigate it soon.

**Comment by TheRealSin** [comment]
Can you please tell me how I can check if the .csv file is created already? I´m trying to attempt it via OpenFace mainwindow.xaml.cs but it´s too fast and tells me the file is not there because it is still creating it. Sleep function is a bad solving of that issue and the filesystemwatcher doesn´t work always. 

Thank you very much!

**Comment by TheRealSin** [comment]
Everythings working even the big Pictures. I tried one of the new versions of OpenFace and all seems to be good now
