### ISSUE TITLE
What is the development environment for this project?

### ISSUE THREAD

**Issue by tuji-sjp** [TadasBaltrusaitis/OpenFace#406]
What is the development environment for this project?  Thanks to the people who can help me.

**Comment by manvikamboj** [comment]
Running the python script in Canopy on Windows.

**Comment by TadasBaltrusaitis** [comment]
There are two environments, a set of Matlab scripts and functions for prototyping and a C++ project for runtime performance (Visual Studio 2015 for Windows or cmake for linux), there is also a C# interface for Windows. For more details see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Code-Layout
