### ISSUE TITLE
Need help for training AU.

### ISSUE THREAD

**Issue by EhsanSaZ** [TadasBaltrusaitis/OpenFace#407]
I read the instruction.txt  in au training directory but cant understand the second instruction clearly.
How to train AU exactly?

**Comment by TadasBaltrusaitis** [comment]
You need to compile the OpenFace code, see wiki for details on how to do it - https://github.com/TadasBaltrusaitis/OpenFace/wiki

If you are using Windows you can also download it from the releases on github - https://github.com/TadasBaltrusaitis/OpenFace/releases). 

OpenFace executables are needed to extract the features for AU training.

**Comment by EhsanSaZ** [comment]
thanks.
i download   executables  for windows and im using the exe  but the problem
is the exe file cant find any action unit :
*-*-*-*-*
WARNING: no Action Unit models found
Attempting to read from file: E:\term8\final
project\OpenFace_1.0.0_win_x64\samples\sample1.jpg
Device or file opened
Starting tracking
0% Postprocessing the Action Unit predictions

what should i do ?

**Comment by TadasBaltrusaitis** [comment]
Can you re-download the binaries? There was an issue with the x64 version that should be fixed now.

**Comment by EhsanSaZ** [comment]
Ok.
But i download it yesterday.is there any changes from yesterday to now?

**Comment by TadasBaltrusaitis** [comment]
Yes it has

**Comment by EhsanSaZ** [comment]
Thank you
