### ISSUE TITLE
face recognition through tracking help

### ISSUE THREAD

**Issue by MyraBaba** [TadasBaltrusaitis/OpenFace#408]
Hi,

For face detection can we use the face / object tracking to say the algorithm this is the same face without recognition algorithm ? Because this is same object, same people and the same scene just face moved little or changed its angle ?  So we can have a buch of faces for same people for further clustering ?

Best

**Comment by TadasBaltrusaitis** [comment]
It is definitely possible if scenarios you are interested do not include too many people leaving or entering the scene or crossing paths.
