### ISSUE TITLE
Running software on .wmv videos on a mac

### ISSUE THREAD

**Issue by mgm248** [TadasBaltrusaitis/OpenFace#41]
I realize many of the videos I would like to run through FeatureExtraction are .wmv files. It looks like the software is open and run them, I think because I am trying to run .wmv files on a mac. I do have software that can play the videos (mplayerx), is there a way I could implement this? 

I have tried converting them to a different format, but the converted videos seemed to be lower quality, and when OpenFace ran them the visualization was a small window, rather than the whole screen. I am afraid this is affecting the software's ability to detect facial features, am I correct?

Thanks for any help

**Comment by TadasBaltrusaitis** [comment]
It seems that OSX has difficulty opening .wmv files with OpenCV:
http://stackoverflow.com/questions/21669632/how-do-i-open-wmv-files-with-opencv-on-mac

It might be that converted videos were downsampled, you should try converting them to a high quality compression such as h264 and without changing the resolution. The lower the quality of the video the more difficulty the software will have to track faces, ideally you want faces at least 140px across.

Thanks,
Tadas

**Comment by mgm248** [comment]
Looks like you're right--even though bit and frame rate set as high as possible, my converter decreased the frame height and width. This is a big problem because a lot of my videos have the face somewhat far from the camera, and I think this confounded that problem.

Thanks for the help!
