### ISSUE TITLE
How to get landmark coordinate

### ISSUE THREAD

**Issue by qmj123** [TadasBaltrusaitis/OpenFace#412]
Hi!
I have a problem that how to express the landmark coordinate in FaceLandmarkVid.cpp?
Can you help me ?
Thank you very much!

**Comment by TadasBaltrusaitis** [comment]
Hi,

`FaceLandmarkVid` executable is only performing tracking visualization and does not output detected landmarks, if you want to output them you can either use `FeatureExtraction.cpp` or modify `FaceLandmarkVid.cpp`

Thanks,
Tadas

**Comment by qmj123** [comment]
Thanks！
