### ISSUE TITLE
how to get where the eye ball is  in form of translation vector and euler angle 

### ISSUE THREAD

**Issue by 5730684221-AB** [TadasBaltrusaitis/OpenFace#415]
how to get where eye ball is  in form of translation vector and euler angle i try to read gaze estimate but i dont understand so i decided to ask the knower

**Comment by TadasBaltrusaitis** [comment]
You can find the relevant outputs described here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format, it contains both 3D eye landmark locations and gaze vectors.
