### ISSUE TITLE
Using COFW data file for landmark detection, how to generate tris_29.txt?

### ISSUE THREAD

**Issue by spark123456789** [TadasBaltrusaitis/OpenFace#418]
Deal Sir,
       I want to use the ccnf_patches_0.25_cofw.txt, ccnf_patches_0.5_cofw.txt,ccnf_patches_0.35_cofw.txt to generate face landmark. But I don't know how to generate the related tris_29.txt? Could you give me some advice? Thank you!

**Comment by TadasBaltrusaitis** [comment]
Hi,

The tris_29.txt can be generated by just taking a Delaunay triangulation of the 29 2D landmarks. However, it is used for face tracking validation and face alignment for expression detection, which would require their own models trained that can use the 29 landmarks.

If you only care about landmark detection in images you could generate tris_29.txt and disable the landmark validation in the C++ code.

Another, probably easier, version is to just use the matlab landmark detection code that does not do detection validation or expression recognition. 

You also have to be a bit careful of how the bounding box is provided to the detector, as the 29 landmarks do not cover the same area of the face the bounding box has to be adjusted accordingly. The code expects the bounding box to be sitting tightly around the landmarks.
