### ISSUE TITLE
Build lib for older C++ version

### ISSUE THREAD

**Issue by MimoMoreno** [TadasBaltrusaitis/OpenFace#420]
Hi!
I'm working with C++98/VS2012 (I **have to**) and I need to use the OpenFace library in a project (specifically the landmarks detector). Therefore I've downloaded the source code and I'm trying to build it with CMake, but I am getting the following error:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBLAS.cmake:699 (message):
  A required library with BLAS API not found.  Please specify library location.
Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)
```

I know that [here](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation) says that compatibility is not guaranteed, but I am trying it anyway.
Can anyone help me? Thanks!

**Comment by TadasBaltrusaitis** [comment]
There is a much older version of OpenFace (before it was called that) - https://github.com/TadasBaltrusaitis/CLM-framework that is compatible with VS2012 if you want to try that.

The current OpenFace uses a number of C++11 features so you would need to change the code to make it work with C++98. Further, CMake is not supported on Windows, I haven't tested it on Windows in a very long time so I don't expect it to work.

**Comment by MimoMoreno** [comment]
First of all, thanks for the response!
Does that older version have the correct implementation of landmarks detection? Or have there been improvements or other kind of changes in the implementation?

**Comment by TadasBaltrusaitis** [comment]
It uses the same algorithm, but does not have certain bug fixes, performance tweaks, accuracy improvements, and stability fixes that have been included into OpenFace over the years. It also does not have GUI support. 

But the core landmark detection algorithm is the same.
