### ISSUE TITLE
Update dlib C++ version?

### ISSUE THREAD

**Issue by delta42** [TadasBaltrusaitis/OpenFace#421]
I admit this may be a strange question, but I noticed that OpenFace uses dlib C++version 18.10 from August 2014 (I was going to work on DNN but saw there is no support for it in the dlib used by OpenFace).

There seem to several updates to dlib C++ since then, although to be honest I am not keeping track of what aspects Davis is improving on or what functionality he is adding.

I'm just wondering if OpenFace would have anything to gain to update to a newer dlib, or if it's just the case of "if it ain't broke don't fiddle with it" :-)

Thanks.

**Comment by TadasBaltrusaitis** [comment]
Updating the version of dlib is definitely on my TODO list, I just haven't gotten around to doing it. I expect to tackle it in a month or so :)

**Comment by delta42** [comment]
Cool. Thanks for the info.

**Comment by quentinsf** [comment]
Hi Tadas - 

The dlib version is also one of the current problems with compiling on a Mac.

The included version of Dlib has an

    include/dlib/matrix/matrix_blas_bindings.h

which has a set of function definitions that aren't quite the same as the definitions in the included version of OpenBLAS's:

    include/cblas.h

The Mac's C compiler is fussy about that.

**Comment by TadasBaltrusaitis** [comment]
Hi Quentin,

Thanks for the suggestion. I will be updating dlib with reasonably high priority. It has been causing issues for quite some time now (both with boost and OpenBLAS). 

Do you happen to know if the newer version avoids the OpenBLAS issues?

**Comment by quentinsf** [comment]
I haven't tried it, but I had a quick look on Github and the current headers:

https://github.com/davisking/dlib/blob/master/dlib/matrix/matrix_blas_bindings.h

and 

https://github.com/xianyi/OpenBLAS/blob/develop/cblas.h

do at least look a bit closer, so I think there's a good chance!

Looking forward to trying the new version!  Other than for demos, though, I don't really need the GUI aspects at present, so I may try building it as a Docker container...

**Comment by TadasBaltrusaitis** [comment]
Dlib has been updated to 19.13
