### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by Lhemamou** [TadasBaltrusaitis/OpenFace#425]
Hi Tadas , first congratulations for your work ! it's really impressive ! Secondly, i am looking for an answer concerning the case where success=0. The values of the other features (landmarks or AU) are not all the time equal to 0. Do you have any information about the procedure in the case of success=0 ? 

Thanks for all,

Léo

**Comment by TadasBaltrusaitis** [comment]
Thanks for your kind words!

The procedure how those values are produced is the same as it is for frames with success=1. There is a separate module that estimates the success of facial landmark tracking that estimates if landmark detection worked. However, as it is not always 100% accurate, the landmark and expression results are still reported. Hope that helps.

**Comment by TadasBaltrusaitis** [comment]
Thanks for pointing this out and for the example. This is a bug and it will be fixed in the next version.
