### ISSUE TITLE
How we can Detect closed eyes ? 

### ISSUE THREAD

**Issue by MyraBaba** [TadasBaltrusaitis/OpenFace#426]
Hi,

I saw lots of params in eye_lmk_xxx . etc. 

Can we detect closed eyes from here ?

any hint_

**Comment by TadasBaltrusaitis** [comment]
You could look at the Action Unit corresponding to the blink (AU45) or you could look at the distance between upper and lower eyelid landmarks, the IDs for which you can find here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#csv-file
