### ISSUE TITLE
Want to know details of training eye's patch experts! 

### ISSUE THREAD

**Issue by EDMIG** [TadasBaltrusaitis/OpenFace#429]
I just wondered how to train these patch experts: ccnf_patches_*_synth_left_eye.mat(s),
would you mind providing some details or related codes? 

Thanks!

**Comment by TadasBaltrusaitis** [comment]
I never packaged the eye model training code, but have a look at:
https://github.com/TadasBaltrusaitis/OpenFace/issues/334

It is on my todo list to include it, but other features are taking precedence.
