### ISSUE TITLE
The program can not run normally on windows10 and VS2015...

### ISSUE THREAD

**Issue by chhxnut** [TadasBaltrusaitis/OpenFace#43]
Hello.
 I downloaded the code, and compile it successfully. But it can not run normally using command line, VS debug window tells "facelandmarkvid.exe have some unprocessed win32 exception".
Then I downloaded the zip, and use the compiled facelandmarkvid.exe in this packet.  The problem is same.
What is wrong? Thanks.

**Comment by TadasBaltrusaitis** [comment]
Can you provide me with more details, what appears on the console? You can try using the debug mode as that should tell you exactly where the exception is thrown.

It runs fine on my Windows 10 machine both compiled from code and running the binaries.

**Comment by chhxnut** [comment]
Nothing on the console. Just a window tells that facelandmarkvid.exe had stoped.
In the debug mode for X64, a exception is thrown in Line 244("face_template_scale = 0.3; ") in File LandmarkDetectorParameters.cpp.  Then I deleted this line, a new exception is thrown in 253("sigma = 1.5;"). I can not find any problem.
Now I suspect there are some mismatch in the character set(unicode or ...).

**Comment by TadasBaltrusaitis** [comment]
That is possible, those lines should definitely not throw exceptions. Can you try 32 bit mode?

**Comment by chhxnut** [comment]
32 bit is OK。。。

**Comment by TadasBaltrusaitis** [comment]
Maybe you do not have a 64 bit machine then? Is your operating system 64 bit?

**Comment by chhxnut** [comment]
No，my machine and the windows version are all 64 bit.

**Comment by TadasBaltrusaitis** [comment]
It might be something to do with the instruction set. In project properties, under `C/C++ -> Code Generation -> Enable Enhanced Instruction Set` try setting it to `Not Set` or to some other option for all of the projects.

**Comment by chhxnut** [comment]
You are right. Disabling Enhanced Instruction Set is OK. Thanks very much. I am sorry to reply you so late.
