### ISSUE TITLE
'PDM' in namespace 'FaceAnalysis' does not name a type

### ISSUE THREAD

**Issue by edgarrt** [TadasBaltrusaitis/OpenFace#431]
Error:
![openfaceerror](https://user-images.githubusercontent.com/14653074/39879234-207af2aa-542f-11e8-85c9-250ec8d88391.png)

Code Sample:

`

    #include <iostream>
    #include <stdio.h>
    #include <parser.h>
    #include <opencv2/video/tracking.hpp>
    #include <string>
    #include <math.h>
    #include <opencv2/core/core.hpp>
    #include <opencv2/highgui/highgui.hpp>
    #include "OpenFace/LandmarkCoreIncludes.h"
    // System includes
    #include <fstream>
    // OpenCV includes
    #include <opencv2/core/core.hpp>
    #include <opencv2/highgui/highgui.hpp>
    #include <opencv2/imgproc.hpp>
    // Boost includes
    #include <filesystem.hpp>
    #include <filesystem/fstream.hpp>

    #include <dlib/image_processing/frontal_face_detector.h>

    #include <tbb/tbb.h>

    #include <FaceAnalyser.h>
    #include <GazeEstimation.h>

    #include <ImageCapture.h>
    #include <Visualizer.h>
    #include <VisualizationUtils.h>
    #include <RecorderOpenFace.h>
    #include <RecorderOpenFaceParameters.h>

 
    using namespace cv;
    using namespace std;

    int main( int argc, char** argv )
    {
     if( argc != 2)
    {
     cout <<" Usage: display_image ImageToLoadAndDisplay" << endl;
     return -1;
    }

    Mat image;
    image = imread(argv[1], CV_LOAD_IMAGE_COLOR);   // Read the file

    if(! image.data )                              // Check for invalid input
    {
        cout <<  "Could not open or find the image" << std::endl ;
        return -1;
    }

    namedWindow( "Display window", WINDOW_AUTOSIZE );// Create a window for display.
    imshow( "Display window", image );                   // Show our image inside it.

    waitKey(0);                                          // Wait for a keystroke in the window
    return 0;
    }

`

**Comment by TadasBaltrusaitis** [comment]
This should be fixed in the newest version.
