### ISSUE TITLE
"FeatureExtraction.exe has stopped working" on WIn 10

### ISSUE THREAD

**Issue by Eliz4be7h** [TadasBaltrusaitis/OpenFace#432]
![openface command line error](https://user-images.githubusercontent.com/38447058/39939810-4c12833c-550c-11e8-86a9-0cee99327faf.png)

video plays fine

**Comment by TadasBaltrusaitis** [comment]
Can you try the new version? I released OpenFace 2.0 recently. If the error still persists could you share the video you used, it is difficult to debug without knowing what exactly causes the error.

Thanks,
Tadas
