### ISSUE TITLE
Want the paper "OpenFace 2.0:"

### ISSUE THREAD

**Issue by lzwhard** [TadasBaltrusaitis/OpenFace#438]
Thanks for your work, but I couldn't find the paper, can you give me a link?

**Comment by lzwhard** [comment]
Thank you for that, but this link is old openface(openface1.0). I'm looking for openface 2.0

**Comment by TadasBaltrusaitis** [comment]
You can find the paper here - https://www.dropbox.com/s/ki1inrjcjbwm24j/FG2018_camera_ready.pdf?dl=0, it has just been published so has not been uploaded to IEEE yet.

**Comment by fxfactorial** [comment]
@TadasBaltrusaitis What is the difference between your Openface project and https://github.com/cmusatyalab/openface in terms of capabilities? Is your project more state fo the art in terms of latest algorithms used?

**Comment by TadasBaltrusaitis** [comment]
They offer very different functionality, the current project is intended for facial behavior analysis: detecting and tracking facial landmarks, estimating head pose and eye gaze and detecting facial expressions.

The project that you linked to is intended for face recognition - identifying the person in the image.
