### ISSUE TITLE
Output formatting meaning for visualizations

### ISSUE THREAD

**Issue by fxfactorial** [TadasBaltrusaitis/OpenFace#439]
I'm not entirely clear about how the values produced in a CSV, for example `FaceLandmarkImg` dumps out about 800 columns. What column ranges map onto a face? 

I was looking through the C# UI code, but guidance appreciated because some magic numbers abound.

**Comment by TadasBaltrusaitis** [comment]
Hi,

The CSV file should have the names of the columns that explain what each column means. You can also find a more detailed explanation of the meaning of the columns here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

**Comment by TadasBaltrusaitis** [comment]
The dots on the face are drawn in the locations specified by `(x_0,y_0), ... (x_68, y_68)` in the csv file.
