### ISSUE TITLE
[Update] Mac Installation WiKi

### ISSUE THREAD

**Issue by hanton** [TadasBaltrusaitis/OpenFace#440]
In the [Mac Installation](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation)-Prerequisites:
The `brew tap homebrew/science` is deprecated. 
```
"Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated."
```

It is good to use the following commands instead: 

```
brew tap brewsci/bio
brew tap brewsci/science
```

Please see this [Github Issue](https://github.com/Homebrew/homebrew-science/issues/6365) for reference.

**Comment by TadasBaltrusaitis** [comment]
The wiki has been updated.
