### ISSUE TITLE
An option to save the storage

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#441]
Thanks for dramatic update in 2.0!

I remember that in one of previous versions, Openface saved only 'successful' frame instead of all frames.
Is there any option or possible way to do same thing with 2.0?
Since I extract the face with quite high resolutions, it consumes huge amount of storage with black frames.
It will be really helpful to let the user select wether they save all or 'successfully tracked' frames.

Bests,
J.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Can you explain in more detail what you mean by saving successful frames? Is it for the output aligned images? Or the tracked video/image output? Or the output CSV?

Thanks,
Tadas

**Comment by iPsych** [comment]
Hello, 

It is for output aligned images.

**Comment by TadasBaltrusaitis** [comment]
This feature has been added, see `-nobadaligned`
