### ISSUE TITLE
Opencv fails with long video.

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#442]
I found the OpenFace 2.0 works properly with small video, but crashes repeatedly during a big (1GB, 30min) video in similar point. below is the error messages.

I am afraid the OpenCV version is too high and the bug related to it, or some size restriction in buffer/temporary folder...

```
20% Face too small for landmark detection
Face too small for landmark detection
Face too small for landmark detection
Face too small for landmark detection
OpenCV(3.4.1) Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/opencv-20180307-19209-1d8dn7a/opencv-3.4.1/modules/core/src/matrix.cpp, line 464
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.1) /tmp/opencv-20180307-19209-1d8dn7a/opencv-3.4.1/modules/core/src/matrix.cpp:464: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
```

**Comment by TadasBaltrusaitis** [comment]
Is there any chance of sharing that video so I can debug the problem, as now I don't know what is causing it or which line is causing it.

**Comment by TadasBaltrusaitis** [comment]
If there is any chance for you to share the videos that would help with debugging (I understand if they are private and you can't share them).

**Comment by NumesSanguis** [comment]
Unfortunately the database I ran it on was a private one. In the future I will run it on a public database. I'll let you know if I run into problems then.

**Comment by TadasBaltrusaitis** [comment]
Can you try it with the new version?

**Comment by iPsych** [comment]
I tested it just before and still killed 9 error.
Also, I used the command below

`bin/FaceLandmarkVidMulti -f /Users/ERI/Downloads/Nanum.180511.mp4 -q -verbose -simsize 600 -simalign -wild -multiview 1
`
However it doesnot quite the graphical output.

And it seems the performance of newly trained model is not better for at least people with dark-color skins...

**Comment by iPsych** [comment]
I resolved model search fails manually in above #475 .
However, FaceLandmarkVidMulti never saves any aligned images by default, or with any combinations of simsize simalign options.

**Comment by iPsych** [comment]
It seems something wrong with OpenCV 3.4.x in OSX (unfortunately, it's almost impossible to roll back, if you didn't installed 3.3 or 3.2 before....)

I tested another video, but same error...
OpenCV(3.4.1) Error: Assertion failed (ssize.area() > 0) in remapBilinear, file /tmp/opencv-20180529-49540-yj8rbk/opencv-3.4.1/modules/imgproc/src/imgwarp.cpp, line 662
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.1) /tmp/opencv-20180529-49540-yj8rbk/opencv-3.4.1/modules/imgproc/src/imgwarp.cpp:662: error: (-215) ssize.area() > 0 in function remapBilinear

Tested another mp4 file and got similar error...
OpenCV(3.4.1) Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/opencv-20180529-49540-yj8rbk/opencv-3.4.1/modules/core/src/matrix.cpp, line 464
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.1) /tmp/opencv-20180529-49540-yj8rbk/opencv-3.4.1/modules/core/src/matrix.cpp:464: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

30% 40% Abort trap: 6
Balthasar:bin ERI$

**Comment by iPsych** [comment]
Update : I tried to test many possible settings.
In mac OS Sierra 10.12.6 with Xcode 9.2, 
newly installed OpenCV older than 3.4.0 will cause segmentation 11 error.
When I test openface 2.0 with opencv 3.4.3_5 installed via homebrew, it will lead above OpenCV error.
Also, when I test openface 2.0 with opencv 3.2.0 installed long ago in different machine, it gives same error in middle of analysis.

`OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/opencv-20180111-19143-hiyf7b/opencv-3.2.0/modules/core/src/matrix.cpp, line 522
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20180111-19143-hiyf7b/opencv-3.2.0/modules/core/src/matrix.cpp:522: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

Abort trap: 6
`

**Comment by TadasBaltrusaitis** [comment]
Thanks for the information, I'm trying to reproduce the error, can you help me narrow it down:
- Does this happen all the time, or only for a particular video? 
- What are the exact command line arguments you are using?
- Can you try the same command on the sample videos, e.g. `samples/multi_face.avi`, does it produce an expected output?
- Is this issue observed with all executables? e.g. `FaceLandmarkVid`, `FeatureExtraction`, `FaceLandmarkVidMulti`

**Comment by iPsych** [comment]
- Does this happen all the time, or only for a particular video?
    All long videos (more than 20min?). both avi, mp4 format
- What are the exact command line arguments you are using?
    For example, I used below command
./FeatureExtraction -f /Users/user/Downloads/Nanum.180511.mp4 -out_dir /Users/user/Downloads/temp_proc/ -of test

- Can you try the same command on the sample videos, e.g. samples/multi_face.avi, does it produce an expected output?
The sample clip works perfectly. It also works when I change it to mp4.
I think the size or length of the input video matters. Can you test some really long video clip?

- Is this issue observed with all executables? e.g. FaceLandmarkVid, FeatureExtraction, FaceLandmarkVidMulti

Yes When I test, all three shows same errors.

**Comment by NumesSanguis** [comment]
I ran OpenFace 2.0.2 without error on the MAHNOB Mimicry database (https://mahnob-db.eu/mimicry/) for more than 16 hours (420 min of video on 60fps).
I still have to re-run it on our personal database to see if 2.0.2 has fixed it (which I originally had a problem with), so I'll get back to you when I have time to test that.

**Comment by NumesSanguis** [comment]
Update: After 62 videos about 15 min each from the MAHNOB database (session 15 to 45 (2 participants each)) I got the error "OpenFaceOffline has stopped working" on Windows 10.

**Comment by NumesSanguis** [comment]
I re-downloaded the latest binary v2.0.2 and it consistently crashes on the post-processing phase or when it switches to the next video when running it on 45 P2 (see above) from the MAHNOB database (which is freely available to researchers).

**Comment by iPsych** [comment]
for your recent commit 5a3cf77 <https://github.com/TadasBaltrusaitis/OpenFace/commit/5a3cf77863dad8872502cbd1c70021f50437ae04>,
It was compiled properly in Mac, but when I run it, below errors happened.


BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
Segmentation fault: 11

**Comment by TadasBaltrusaitis** [comment]
I'm still investigating the long video issue.

The BLAS memory error is off topic to this issue, please create a new one (but I know what is causing it and it will be fixed with a new release that is coming in a couple of days).

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, re-open if there is an issue.
