### ISSUE TITLE
Correct way to Compile on OS X  with OpenBLAS

### ISSUE THREAD

**Issue by fxfactorial** [TadasBaltrusaitis/OpenFace#443]
`HEAD` currently doesn't compile on OS X, 

Maybe this could be added as shell script where you change boost or openblas to your respective directories. 

```
#!/bin/bash

mkdir build
cd build

BOOST_ROOT=/usr/local/Cellar/boost@1.60/1.60.0/ cmake \
		  -D CMAKE_BUILD_TYPE=Debug \
		  -D CMAKE_PREFIX_PATH=/usr/local/Cellar/openblas/0.2.20_2 ..
```

and in the rootmost CMakeLists.txt

change

```
find_package( BLAS REQUIRED )
include_directories( ${BLAS_INCLUDE_DIRS} )
LINK_DIRECTORIES(${BLAS_LIBRARY_DIRS})
```
to 

```
find_package( OpenBLAS REQUIRED )
include_directories( ${OpenBLAS_INCLUDE_DIRS} )
LINK_DIRECTORIES(${OpenBLAS_LIBRARY_DIRS})
```

**Comment by mpj2104** [comment]
Yes! I can confirm that this works. I changed CMakeLists.txt as suggested and then ran the above shell script in place of `cmake -D CMAKE_BUILD_TYPE=RELEASE .` as written in the [Mac installation wiki](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation). I then ran `make` in the build folder successfully.

Thanks @fxfactorial !

**Comment by sukun1045** [comment]
Hi, if I changed the CMakelist.txt and ran the above shell script, I get the error

> BOOST_ROOT: command not found

What is the problem here?

**Comment by fxfactorial** [comment]
That's an environment variable, you probably have some spacing issues. 

If you don't need to change the boost Libraries, then you do don't need to set that environment variable.

**Comment by TadasBaltrusaitis** [comment]
Hi @fxfactorial, thanks for all of your suggestions for compiling OpenFace on Mac! I don't have much experience of OS X and don't have an easy way to test all the scripts. Would you be open to editing the wiki instructions for OS X installation? That would be really helpful to the community. 

I would mention your name in the wiki to credit your help.

**Comment by fxfactorial** [comment]
Sure! I’m also making a python cross platform GUI, PR will be open this week

**Comment by elahia** [comment]
@fxfactorial  is it possible to explain it a bit more...
where i have to build a new directory and change the  boost_root  parameter???
and where is most root cmakelist.txt?
Are you speaking about the root of system or Openface directory....

**Comment by fxfactorial** [comment]
Please don’t post Ubuntu issues in this thread about OS X.
