### ISSUE TITLE
Build problem in Mac

### ISSUE THREAD

**Issue by sukun1045** [TadasBaltrusaitis/OpenFace#444]
When i try to make, it gives me the following two types errors, Can anyone help with me?

> /Users/kunsu/Dropbox/OpenFace-master/lib/3rdParty/dlib/include/dlib/image_processing/../matrix/matrix_trsm.h:524:17: error: no matching function for
      call to 'cblas_strsm'
                cblas_strsm(Order, Side, Uplo, TransA, Diag, M, N, alpha, A, lda, B, ldb);
                ^~~~~~~~~~~
/Users/kunsu/Dropbox/OpenFace-master/lib/local/LandmarkDetector/../../3rdParty/OpenBLAS/include/cblas.h:296:6: note: candidate function not viable: no
      known conversion from 'const enum CBLAS_ORDER' (aka 'const dlib::blas_bindings::CBLAS_ORDER') to 'const enum CBLAS_ORDER'
      (aka 'const CBLAS_ORDER') for 1st argument
void cblas_strsm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_SIDE Side, OPENBLAS_CONST enum CBLAS_UPLO Uplo, OPENBLAS_CON...
     ^

> /Users/kunsu/Dropbox/OpenFace-master/lib/3rdParty/dlib/include/dlib/image_processing/../matrix/lapack/getrf.h:17:22: error: functions that differ only
      in their return type cannot be overloaded
                void DLIB_FORTRAN_ID(dgetrf) (integer* m, integer *n, double *a, 
                ~~~~ ^
/Users/kunsu/Dropbox/OpenFace-master/lib/3rdParty/dlib/include/dlib/image_processing/../matrix/lapack/fortran_id.h:32:31: note: expanded from macro
      'DLIB_FORTRAN_ID'
#define DLIB_FORTRAN_ID( id ) id##_
                              ^
<scratch space>:301:1: note: expanded from here
dgetrf_
^
/Users/kunsu/Dropbox/OpenFace-master/lib/local/LandmarkDetector/../../3rdParty/OpenBLAS/include/f77blas.h:658:5: note: previous declaration is here
int BLASFUNC(dgetrf)(blasint *, blasint *, double *, blasint *, blasint *, blasint *);
 ^
/Users/kunsu/Dropbox/OpenFace-master/lib/local/LandmarkDetector/../../3rdParty/OpenBLAS/include/openblas_config.h:46:24: note: expanded from macro
      'BLASFUNC'
#define BLASFUNC(FUNC) FUNC##_
                       ^
<scratch space>:410:1: note: expanded from here
dgetrf_
^

**Comment by sukun1045** [comment]
Yes, I also tried to work the way in issue #443 , but i still get the same errors.

**Comment by sukun1045** [comment]
Well, i change to use linux and that works fine. I guess the problem in mac may be related to the compiler. During the build, the errors in Mac will only be the warning in linux

**Comment by fxfactorial** [comment]
Your issue is explained in the script i posted.

**Comment by funkmeisterb** [comment]
@sukun1045 I had the same errors as you, it is because of some residual cmake files. The instructions in #443 work fine from a clean copy of the code in macOS.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, re-open if there is an issue.
