### ISSUE TITLE
result of bounding box

### ISSUE THREAD

**Issue by jhlf** [TadasBaltrusaitis/OpenFace#445]
Hello, I noticed that the program can get a 3d bouding box.
![sample1](https://user-images.githubusercontent.com/22660610/40288141-4351cbf6-5ce4-11e8-9188-bd05fb4123ac.jpg)

But these points are not provided. How can output these points?

**Comment by TadasBaltrusaitis** [comment]
These points are not exposed in the output, but you can find them in the `DrawBox` and `CalculateBox` function calls in `VisualizationUtils.cpp`, you can also compute that box from the translation and rotation of the head that is output.
