### ISSUE TITLE
the issues about ce-clm_training

### ISSUE THREAD

**Issue by LingQiu** [TadasBaltrusaitis/OpenFace#449]
Hi,
I want to know the relationship between the models in the link [https://www.dropbox.com/sh/o8g1530jle17spa/AADRntSHl_jLInmrmSwsX-Qsa?dl=0](url)  and the code in `model_training/ce-clm_training`？And how to generate the `.dat`  and `validator_cnn_68.txt`?
Many Thanks!

**Comment by TadasBaltrusaitis** [comment]
The models in the link are the packaged results of the scripts in `model_training/ce-clm_training`. To generate the `.dat` files you need to train the models using scripts in `model_training/ce-clm_training` and then run `matlab_version\models\cen\create_cen_experts_*` on the output, this will create the `.dat` files.

The scripts are a bit difficult to use at the moment and we are working on creating better instructions for them. Also their training will take a significant amount of time, even on a powerful GPU.

**Comment by LingQiu** [comment]
@TadasBaltrusaitis Thank you very much. I still have three questions.

1. I used the scripts in `model_training/ce-clm_training` and generated the `.h5` files of every landmark. 
   Any script can generate `.dat` files from `.h5` files directly?

2. I run the scripts in `matlab_version\models\cen\create_cen_experts_*` and i do not understand why 
    load `ccnf_patches_0.25_general.mat` at the begining. Why is CCNF?

3. At the same time, I do not find the file `MultiGeneral_arch4general_%s_profile%d_%d_512.mat` in the 
   process to run the script of `matlab_version\models\cen\create_cen_experts_gen.m`. How to generate?
   What's more, the module of `arch4` was used to train patch experts, right?

Expect the reply and better instructions.

**Comment by ichinaapple** [comment]
MultiGeneral_arch4general_%s_profile%d_%d_512.mat， I cant not find ，how to generate？

**Comment by A2Zadeh** [comment]
Hello @LingQiu. Please find answers to your questions below:

1. I believe there should be. I think @TadasBaltrusaitis could weigh in on this issue.
2. We load that to simply get some parameters from the mat file. The CCNF data is not directly used.
3. @ichinaapple also included. There seems to be a URL hard coded. Once you get the patches for all scales and landmarks, MultiGeneral_arch4general_%s_profile%d_%d_512.mat was the pattern that generated file names. The pattern would be filled with (in order) %s: landmark scale, %d: profile or frontal number %d:landmark number. Please don't hesitate to ask questions if this did not clarify. We will look into quick fixes for this issue.

**Comment by LingQiu** [comment]
@A2Zadeh Thank you.  I want to know the URL hard coded. Perhaps, some examples of the pattern of the generated file.
