### ISSUE TITLE
How to train facelandmark model

### ISSUE THREAD

**Issue by Hardold** [TadasBaltrusaitis/OpenFace#45]
How can I train my facelandmark model ? Do you have guide to train a  landmark detection model for facial landmark detection ?

**Comment by TadasBaltrusaitis** [comment]
To train a facial landmark detection model you need to train 3 models (the last one is optional):
Point Distribution Model (PDM) - `.matlab version/pdm_generation` 
Patch experts - https://github.com/TadasBaltrusaitis/CCNF
(Optional) face validation - `./face_validation_svr`
