### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Niekvdschaaff** [TadasBaltrusaitis/OpenFace#450]
Hi!

First of all, great work! I was wondering if there is any way to leave out certain landmarks in FeatureExtraction, like X_0, since I don't need all the landmarks for my project. Thanks!

**Comment by TadasBaltrusaitis** [comment]
Thanks!

There is no functionality to extract just the subset of points, but you could just pick the rows that interest you from the `.csv` file. Alternatively, you could change the recording code to only record landmarks of interest to you (in `RecorderCSV.cpp`).
