### ISSUE TITLE
Easier way to get CSV data without dealing with files

### ISSUE THREAD

**Issue by fxfactorial** [TadasBaltrusaitis/OpenFace#452]
Looking for an easier way to get `FaceAnalyzer` to dump information facial results rather than from dumping to a CSV and then reading that.

**Comment by fxfactorial** [comment]
real-time usage. 

I mean, you have like:

```
  face_analyser.PostprocessOutputFile(open_face_rec.GetCSVFile());
```

something like that, but no public methods available to dumping values say as a vector of vectors (each nested vector being analogous to a record/line in the CSV way)

**Comment by elahia** [comment]
@fxfactorial  Hey, I'm exactly looking for something similar, would you please inform me if you get it?

Thanks

**Comment by TadasBaltrusaitis** [comment]
There are no public methods for dumping values, but there are methods for extracting them, e.g:
`face_analyser.GetCurrentAUsReg()`, `face_analyser.GetCurrentAUsClass())`, `face_model.detected_landmarks`, `face_model.GetShape(sequence_reader.fx, sequence_reader.fy, sequence_reader.cx, sequence_reader.cy)` etc.

What types of methods do you think are missing? The recording function does not do any additional computation, it just dumps data to disk. 

The one exception is the post-processing of AU data, but that data can't be done in an online setting anyway.

**Comment by fxfactorial** [comment]
I suppose I want for now the Action Units describing what is on the face. Is that contained in one of the things you mentioned? 

What does the post processing do exactly and why can't it be done online?

**Comment by fxfactorial** [comment]
For 1. 

This could be though implemented as an optimization, that is, after 3000 frames seen, then code is run to median. 

2. Also sounds implementation detail...

I'd love to help out this project with something like that.

**Comment by TadasBaltrusaitis** [comment]
For 1. this is roughly how it currently works, it keeps track of a "running median" that it uses and prediction is getting better with time. The postprocessing just goes to the first 3000 frames and corrects them. 3000 is chosen fairly arbitrarily, based on the fact that not much needs to be stored in memory.

For 2. It might be implemented real-time as well, however this would make post-processing more difficult as it would need to track both the 'raw' and 'corrected' predictions.

**Comment by TadasBaltrusaitis** [comment]
Intensities range [0, 5], this is the range commonly used in AU community.

**Comment by fxfactorial** [comment]
appreciate it

**Comment by abhishekunnam** [comment]
@TadasBaltrusaitis - is it possible that we can skip the post-processing step and give real-time AU intensities? if yes where do we have to change this?

**Comment by TadasBaltrusaitis** [comment]
You can tell the `FeatureExtraction` executable to treat videos as static images using `-au_static` flag, this will be close to real-time intensities, but not exact as it will always use static AU predictors (trained on non sequence-normalized data), rather than dynamic ones, but it will also not post-process the predictions.

Another option is to just delete, the following line from `FeatureExtraction.cpp`:
`face_analyser.PostprocessOutputFile(open_face_rec.GetCSVFile());`

Any particular reason you would like to do this? The dynamic predictions should be more accurate.

**Comment by tjusxh** [comment]
Are there the same size between face_analyser.GetCurrentAUsReg() and face_analyser.GetCurrentAUsClass())?  I found that the former one is 17 and the second one is  18.  The missing item is AU28 in former.

**Comment by TadasBaltrusaitis** [comment]
No they are not the same set (due to some datasets having only class labels and not intensity labels).
