### ISSUE TITLE
eigenVals only has one effect value when produce pdm

### ISSUE THREAD

**Issue by xunkaixin** [TadasBaltrusaitis/OpenFace#454]
Hi,
     eigenVals only has one effect value when produce pdm, the landmark number is 12. the dataset is produce from menpo and 300w. But when use multi pie dataset with 12 landmark, the pdm is normal.
   how can i produce the proper pdm?  If need, i can provide the pts and tri result.
                   thanks.

**Comment by TadasBaltrusaitis** [comment]
If you share the .pts and tri result I can have a look.

**Comment by xunkaixin** [comment]
https://pan.baidu.com/s/1r60FtofGptiJFIH1l-gHLQ    password: 7k6p


thank you!!!!!!

**Comment by TadasBaltrusaitis** [comment]
Did you manage to resolve the issue? I was planning to look at it later this week

**Comment by xunkaixin** [comment]
thank you, i cannot resolve the issue, but i get the pdm from your pdm (M E V) according to the corresponding landmark. maybe this is another solution.
