### ISSUE TITLE
command line stops working on folder

### ISSUE THREAD

**Issue by Homer-G** [TadasBaltrusaitis/OpenFace#455]
I moved to OpenFace 2.0 recently but I found that "-fdir" command stops working.

After successful build and install, "FaceLandmarkImg -fdir sample" will stuck on "Start tracking". And the ./processed folder will only contain the result for the first image "sample1.jpg" in ./sample.

**Comment by TadasBaltrusaitis** [comment]
Can you provide more details and test a couple of things: 
- Does it work on the included samples image folder?
- Can you try the -verbose flag
- How big are the images, it might just be taking a long time for them, especially if they are very large or contain a large number of faces

**Comment by Homer-G** [comment]
I was mentioning the included ./samples folder

**Comment by TadasBaltrusaitis** [comment]
What are the exact command line arguments did you use? It works my end on a Windows machine, so I'm trying to narrow down the issue. What OS are you using?

**Comment by Homer-G** [comment]
I was using FaceLandmarkImg -fdir samples.
My OS is Ubuntu 16.04, and with latest version of OpenFace. 
Before pulling the newest repo, it works fine so I reset the repo to 92770ee156852276ae84d7a6ae93835be1f4dd61, where I had no issue. And I build it again then -fdir works.

**Comment by TadasBaltrusaitis** [comment]
I identified the bug and am working on the fix, it should be fixed in the next version.

**Comment by TadasBaltrusaitis** [comment]
I identified the bug and am working on the fix, it should be fixed in the next version.

**Comment by Homer-G** [comment]
Hi, Tadas. I built the latest version on my Ubuntu 16.04 and it works now.
Thanks for your hot fix. It it a good time to close this issue.
