### ISSUE TITLE
MultiGeneral_arch4general_%s_profile%d_%d_512.mat， I cant not find ，how to generate？

### ISSUE THREAD

**Issue by ichinaapple** [TadasBaltrusaitis/OpenFace#456]
MultiGeneral_arch4general_%s_profile%d_%d_512.mat， I cant not find ，how to generate？

**Comment by A2Zadeh** [comment]
Please see our updated readme in OpenFace/matlab_version/models/cen/

This is simply the name of the files generated from OpenFace/model_training/ce-clm_training/cen_training/
