### ISSUE TITLE
Can us see "Facial Action Unit Recognition"?

### ISSUE THREAD

**Issue by hoseahsu** [TadasBaltrusaitis/OpenFace#46]
hi,
  can i run the FeatureExtraction and the see the right window of the picture **(https://github.com/TadasBaltrusaitis/OpenFace/blob/master/imgs/au_sample.png)**, it's the "Facial Action Unit Recognition", it looks very good, i want to test it.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Not just yet, I will be adding the GUI functionality for Windows this month, I just want to make sure it is stable and has all the right functions.

You can still use the same action unit recognition, but you would need to use command line tools for that, for more info see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units

Thanks,
Tadas

**Comment by liwfpgz** [comment]
hi
Did you have added the GUI functionality for Windows?I don't see GUI when run the FeatureExtraction.
Thanks,
Wang
