### ISSUE TITLE
Is it possible to increase the number of deformation shapes to improve  landmarks' accuracy?

### ISSUE THREAD

**Issue by EDMIG** [TadasBaltrusaitis/OpenFace#461]
model_training/pdm_generation/Wild_data_pdm/Reconstruct_Torresani.m:  line#15: 

e.g.,  let  K=55

**Comment by TadasBaltrusaitis** [comment]
It is worth a try, but this change is not guaranteed to result in better landmark accuracy. Having more deformation parameters can allow for reconstruction of more unusual shapes, but it can also lead to modelling some noise as well.
