### ISSUE TITLE
how to get cen*.mat from .h5 file

### ISSUE THREAD

**Issue by xunkaixin** [TadasBaltrusaitis/OpenFace#462]
i have generate some .h5 file using train_cen.py,  but  i cannot get cen*.mat using create_cen_experts_*.m, 
MultiGeneral_arch4general_%s_frontal_%d_512.mat is missing and no code  related to .h5 files

**Comment by xunkaixin** [comment]
ok, i get the result data from .h5 by coding in matlab.

**Comment by Irene-rtc1** [comment]
@xunkaixin can you teach me how to get the result data form .h5 to .mat that used in matlab???
