### ISSUE TITLE
Where are the member variables for `Landmarks locations in 3D`

### ISSUE THREAD

**Issue by fxfactorial** [TadasBaltrusaitis/OpenFace#466]
I'm looking for the right member variable for where the Landmarks locations in 3D are stored, not seeing on FaceAnalyzer.

**Comment by TadasBaltrusaitis** [comment]
It is part of `LandmarkDetector::CLNF face_model`, e.g. in `FeatureExtraction.cpp` you can access 3D locations through:
`face_model.GetShape(sequence_reader.fx, sequence_reader.fy, sequence_reader.cx, sequence_reader.cy)`

You can  find more details here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/API-calls#landmark-results

**Comment by fxfactorial** [comment]
thanks!
