### ISSUE TITLE
compiling error on ubuntu 14.04

### ISSUE THREAD

**Issue by ooxopcmr** [TadasBaltrusaitis/OpenFace#468]
OS: ubuntu 14.04
Compiler: GCC 6.4
OpenCV: 3.4

I followed the instructions on the "Unix Installation" page, but I got a linking error while making OpenFace, and I have no idea how to solve that. A screenshot is attached. Thanks in advance.
![link_error](https://user-images.githubusercontent.com/16432873/40844430-e53c196c-6581-11e8-973c-73823c94fc1c.png)

**Comment by TadasBaltrusaitis** [comment]
Have a look at this issue - https://github.com/TadasBaltrusaitis/OpenFace/issues/16

**Comment by fxfactorial** [comment]
@ooxopcmr Look at this PR to land hopefully https://github.com/TadasBaltrusaitis/OpenFace/pull/469

**Comment by ooxopcmr** [comment]
Thanks for your help. The problem has been solved.
I downgraded the libvtk from version 6 to version 5.
`sudo apt install libvtk5-dev`
`sudo apt autoremove`
And then rebuilt and reinstalled opencv. Then Everything works.
One thing to mention is that, it requires me to build opencv using GCC4.8 after I downgraded libvtk. (Previous I used GCC6.4)
