### ISSUE TITLE
compensate the bounding box of CLNF 

### ISSUE THREAD

**Issue by chasonyang** [TadasBaltrusaitis/OpenFace#47]
Hi
I found that bounding box of  DLib‘s HOG Face detector and opencv‘s Haar Face detector need to compensate.
I want to try some other face detector,like NPD Detector,so what's your standard  bounding box of LFPW ,Helen and so on.
or I have to transform it through  the  two offered scaling?

Thanks in advance.

**Comment by TadasBaltrusaitis** [comment]
Hi,

You are right that the bounding boxes need to be compensated for optimal performance with CLNF. I compensated the Haar Face and HOG face ones using the code in the repository:
`matlab_version\bounding_box_mapping`

If you want to use a new detector you will have to learn how to compensate it as well. The ideal detector should return a bounding box that tightly covers the 68 landmark points. One way to do it is to run the new detector on a dataset you have ground truth labels on (such as 300W) and then learn a mapping from your bounding box to an ideal bounding box.

Thanks,
Tadas
