### ISSUE TITLE
Full face marking detection

### ISSUE THREAD

**Issue by heryvandoro** [TadasBaltrusaitis/OpenFace#470]
Is possible to get full point(x,y) including object forehead? 

Like this :
![image](https://user-images.githubusercontent.com/16014981/40926477-7ce0ccd8-6846-11e8-9243-c6bbf961abf5.png)

**Comment by TadasBaltrusaitis** [comment]
OpenFace only detects the 68 landmarks seen in the image + eye landmarks. The area of the forehead is not very well defined (it's ambiguous where the forehead ends and will be quite different from person to person), so there are not many datasets to train such landmark detectors on.
