### ISSUE TITLE
How to get gaze angle from SynthesEyes dataset?

### ISSUE THREAD

**Issue by tjusxh** [TadasBaltrusaitis/OpenFace#471]
In the Apperance-base Gaze Estimation paper, it transforms the rotation vector to polar  coordinate system. I transform SynthesEyes dataset to polar coordinate system according to the following:

look_vec-- get gaze direction from your data

gaze_theta = math.asin((-1)*look_vec[1])
gaze_phi = math.atan2((-1) * look_vec[0], (-1) * look_vec[2])

Consequence ,I found the data is not very right. The first dim means yaw, and the second dim means pitch. the eyeball look up in the following picture, but one of the yaw data is more than zero, another is less zero. I don't sure if I have a error deal.  Please help me.
![image](https://user-images.githubusercontent.com/9691664/40954996-028b18ca-68ba-11e8-96cc-402713ca2688.png)

**Comment by TadasBaltrusaitis** [comment]
This is the code I use to get gaze angles as yaw and pitch:
	`double x_angle = atan2(gaze_vector.x, -gaze_vector.z);`
	`double y_angle = atan2(gaze_vector.y, -gaze_vector.z);`

The above code is used in OpenFace, I don't recall how gaze is exactly represented in SynthesEyes so you might need to invert z axis.

Sometimes, the eye images themselves look very misleading as our perception of gaze angle is influenced by head pose direction, so sometimes it might look like the person is looking straight at us, when they are actually looking up for example.
