### ISSUE TITLE
Where are your dataset about gaze estimation from?

### ISSUE THREAD

**Issue by tjusxh** [TadasBaltrusaitis/OpenFace#472]
Thanks for your public project, It's very useful. According to your code, I found you train two model about left and right eye. But I only download the left right data from Syntheseye dataset https://www.cl.cam.ac.uk/research/rainbow/projects/syntheseyes/. Please how do you train the right eye model? Thanks very much!

**Comment by TadasBaltrusaitis** [comment]
I just flipped the trained models horizontally (both the PDM and patch experts), there is no separate right eye dataset as such, the models are just mirrors of each other.

**Comment by zhao181** [comment]
Dear tjusxh,
Would you please send me a copy of the SynthesEyes Dataset? I could not download it from the website. 
My email is 565898179@qq.com. Thanks very much.

**Comment by TadasBaltrusaitis** [comment]
We're trying resolving the hosting issue now

**Comment by TariqAHassan** [comment]
@TadasBaltrusaitis 

Sorry for posting on a closed issue, but were the hosting issues ever resolved?

**Comment by brmarkus** [comment]
https://www.cl.cam.ac.uk/research/rainbow/projects/syntheseyes/

Isn't "http://www.cl.cam.ac.uk/~eww23/data/syntheseyes_data.zip" working for you?

**Comment by TariqAHassan** [comment]
Hi @brmarkus 

No, it returns a 403 error.

**Comment by zhao181** [comment]
yes, thanks, solved. I wrote a letter to the author, and he sent me the working exe.





At 2019-11-19 18:11:45, "Tariq Hassan" <notifications@github.com> wrote:


@TadasBaltrusaitis

Sorry for posting on a closed issue, but were the hosting issues ever resolved?

**Comment by kuhnkeF** [comment]
Is anyone able to download http://www.cl.cam.ac.uk/~eww23/data/syntheseyes_data.zip? 
Maybe anyone willing to share the zip file?

**Comment by Nicolas1203** [comment]
Link is down.
Could anyone share the zip?

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, the University stopped hosting the dataset.

You can find it here though:
https://www.dropbox.com/s/1ba3z00ff7lqmvy/synth_eye_data.zip?dl=0

**Comment by hszyq1234** [comment]
Can you send me the working exe? My Email is zhuyanqing8706@163.com. Thanks!



> yes, thanks, solved. I wrote a letter to the author, and he sent me the working exe. At 2019-11-19 18:11:45, "Tariq Hassan" <notifications@github.com> wrote: @TadasBaltrusaitis Sorry for posting on a closed issue, but were the hosting issues ever resolved? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TadasBaltrusaitis** [comment]
Hi, there's no publicly available executable for SynthesEyes, but you can use UnityEyes, which is follow up work https://www.cl.cam.ac.uk/research/rainbow/projects/unityeyes/
