### ISSUE TITLE
Is there any possibility to set up the ROI size?

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#474]
Is there any possibility to set up the ROI size?
I searched the issues but couldn't found one.

For example, let the OpenFace to ignore the face <30pixels in x or something similar.

Bests,
J.

**Comment by TadasBaltrusaitis** [comment]
Sorry there is currently no support for a feature like that, you could however, change the face detection code to ignore faces that are smaller than a certain size.

**Comment by iPsych** [comment]
Thanks. Can you let me know which code I should change?
It will save a lot of time especially in current project.

**Comment by TadasBaltrusaitis** [comment]
You can change the default minimum face size in the following function declaration in the `FaceDetectorMTCNN.h`:

    `bool DetectFaces(vector<cv::Rect_<float> >& o_regions, const cv::Mat& input_img, std::vector<float>& o_confidences, int min_face = 60, float t1 = 0.6, float t2 = 0.7, float t3 = 0.7);`

You can set the `min_face` to something higher.

Thanks,
Tadas
