### ISSUE TITLE
In mac os, model search fails (maybe path issue)

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#475]
This issue is related to the another issue.
https://github.com/TadasBaltrusaitis/OpenFace/issues/442

My environment is OS X 10.12 with Xcode 9.2.

I tested ./FeatureExtraction -f ./Nanum.180511.mp4 -q
put the movie file in same bin directory, and ran the executable file inside bin directory.
Then most of 'cannot find' errors are gone except below. 
"Could not find the HAAR face detector location"

I think model search path is changed or disrupted.

**Comment by iPsych** [comment]
The problem resolved by make 'classifier' folder inside 'bin' folder and copied 'haarcascade_frontalface_alt.xml' from library/3rd_party : )

**Comment by nishagandhi** [comment]
I am working on Ubuntu 16.04.
I tested (for multiple faces) ./bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi to get the following output:

Reading the landmark detector/tracker from: ./build/bin/model/main_ceclm_general.txt
Reading the landmark detector module from: ./build/bin/model/cen_general.txt
Reading the PDM module from: ./build/bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./build/bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: ./build/bin/model/patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: ./build/bin/model/patch_experts/cen_patches_0.35_of.dat....Done
Reading the intensity CEN patch experts from: ./build/bin/model/patch_experts/cen_patches_0.50_of.dat....Done
Reading the intensity CEN patch experts from: ./build/bin/model/patch_experts/cen_patches_1.00_of.dat....Done
Reading part based module....left_eye_28
Reading the landmark detector/tracker from: ./build/bin/model/model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: ./build/bin/model/model_eye/clnf_left_synth.txt
Reading the PDM module from: ./build/bin/model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./build/bin/model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./build/bin/model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Could not find the landmark detection model to load
Done
Reading part based module....right_eye_28
Reading the landmark detector/tracker from: ./build/bin/model/model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: ./build/bin/model/model_eye/clnf_right_synth.txt
Reading the PDM module from: ./build/bin/model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./build/bin/model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./build/bin/model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Could not find the landmark detection model to load
Done
Reading the landmark validation module....Done
Reading the MTCNN face detector from: ./build/bin/model/mtcnn_detector/MTCNN_detector.txt
Reading the PNet module from: ./build/bin/model/mtcnn_detector/PNet.dat
Reading the RNet module from: ./build/bin/model/mtcnn_detector/RNet.dat
Reading the ONet module from: ./build/bin/model/mtcnn_detector/ONet.dat
Reading the AU analysis module from: ./build/bin/AU_predictors/main_static_svms.txt
Reading the AU predictors from: ./build/bin/AU_predictors/AU_all_static.txt... Done
Reading the PDM from: ./build/bin/AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:./build/bin/AU_predictors/tris_68_full.txt... Done
Attempting to read from file: ./samples/multi_face.avi
Device or file opened
WARNING: using a AU detection in multiple face mode, it might not be as accurate and is experimental
Starting tracking

There is no visual output whatsoever.

However, on testing feature extraction : ./bin/FeatureExtraction -verbose -f "../samples/default.wmv", I get the same error **Could not find the landmark detection model to load**, but I can see the visual output.

What is the expected output for multiple faces video and what might be going wrong here?

**Comment by TadasBaltrusaitis** [comment]
@iPsych thanks for pointing out the error with location of found models

@nishagandhi, the reporting of **Could not find the landmark detection model** to load is incorrect, I've been meaning to fix that for a bit.

Typically `FaceLandmarkVidMulti`  and `FeatureExtraction` do not provide a visual output unless `-verbose` flag is specified. They both will output the processed features into `processed` folder (relative to the working directory, i.e. directory you made the call from). Please have a look at the following wiki pages for details:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

**Comment by nishagandhi** [comment]
Hi @TadasBaltrusaitis,

Oh yes, I can visualize it now. Thanks a lot :)

**Comment by iPsych** [comment]
I checked this problem resolved in latest release.(2.04)
