### ISSUE TITLE
wrong parameter in wiki

### ISSUE THREAD

**Issue by vcuculo** [TadasBaltrusaitis/OpenFace#478]
Please update the wiki page 
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

From:
> -multi-view <0/1> should multi-view initialisation be used (more robust, but slower), off by default

To:
> -multi_view <0/1> should multi-view initialisation be used (more robust, but slower), off by default

**Comment by TadasBaltrusaitis** [comment]
Thanks!

**Comment by TadasBaltrusaitis** [comment]
Thanks!
