### ISSUE TITLE
Possible enhancement: support opening .webm files in GUI

### ISSUE THREAD

**Issue by luke777** [TadasBaltrusaitis/OpenFace#480]
Would it be possible to support opening .webm files in the OpenFaceOffline app?  The command line program seems to handle .webm files.  As well as this, when I manually rename  video.webm to video.mov, I can open it and analyse it with OpenFaceOffline but this causes problems when I try to open it in other programs.

**Comment by TadasBaltrusaitis** [comment]
Sure, I will add it for the next  version of OpenFace, coming out in a couple of weeks.

**Comment by TadasBaltrusaitis** [comment]
Should work now.
