### ISSUE TITLE
Win 10  Compile problem

### ISSUE THREAD

**Issue by YuanSkyFace** [TadasBaltrusaitis/OpenFace#482]
hi Tadas
I try many times to compile the code using VS2015 x64 release model , but it still appear thoes questions 
I changes the AVX  ,it does not work . 

so  can you tell me what wrong with my platform.

1>CameraEnumerator.lib(DeviceEnumerator.obj) : error LNK2001: 无法解析的外部符号 __imp_CoUninitialize
1>CameraEnumerator.lib(DeviceEnumerator.obj) : error LNK2001: 无法解析的外部符号 __imp_CoCreateInstance
1>D:\VSProject\VSproject2015\OpenFace-master\x64\Release\CppInerop.dll : fatal error LNK1120: 2 个无法解析的外部命令

4>CSC : error CS0006: Metadata file 'D:\VSProject\VSproject2015\OpenFace-master\x64\Release\CppInerop.dll' could not be found
4>CSC : error CS0006: Metadata file 'D:\VSProject\VSproject2015\OpenFace-master\x64\Release\OpenFaceDemo.exe' could not be found
4>CSC : error CS0006: Metadata file 'D:\VSProject\VSproject2015\OpenFace-master\x64\Release\OpenFaceOffline.exe' could not be found

**Comment by tjusxh** [comment]
You can try to compile the projects one by one. OpenFaceOffline is in GUI project. If you didn't need it, you don't need to compile it.

**Comment by YuanSkyFace** [comment]
@tjusxh  thanks for you advices  I compile the projects one by one  ,the all show success  but when I run the projects  there show  can not find landmark detector  ,do you know what ‘s wrong with it

**Comment by YuanSkyFace** [comment]
@tjusxh    error like  this    ERROR: Could not load the landmark detector
do you know how to do this?

**Comment by TadasBaltrusaitis** [comment]
Hi,

Have you made sure you downloaded the required models? https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download

The models are placed in the correct location during compilation, so after you download them, make sure to re-compile the code (clean and then build).

Thanks,
Tadas

**Comment by YuanSkyFace** [comment]
I solved this question @TadasBaltrusaitis , thanks！
