### ISSUE TITLE
 Is the gaze estimation relative or absolute?

### ISSUE THREAD

**Issue by tjusxh** [TadasBaltrusaitis/OpenFace#483]
OpenFace has better performance in gaze estimation. I want to get the relative yaw and pitch of the gaze to head pose. I try to understand the EstimateGaze and SetObservationGaze functions. But I can't understand them.  Could you help me ?

**Comment by tjusxh** [comment]
According to
               double x_angle = atan2(gaze_direction0.x, -gaze_direction0.z);
		double y_angle = atan2(gaze_direction0.y, -gaze_direction0.z);

                x_angle = atan2(gaze_direction1.x, -gaze_direction1.z);
		y_angle = atan2(gaze_direction1.y, -gaze_direction1.z);

I get the angle of the left and right eye. But There are big gap between left and right eye in yaw. But the visualizer shows normal. Is there the left and right the different reference object?

The part of log shows following:
head pose eular [-3.72124, 3.3319, 3.42267]theta phi 3.71495 3.33891 left= [8.39248, -3.9369]; right=[6.98244, -1.45028]
head pose eular [-12.0535, 1.30168, 3.60124]theta phi 12.0503 1.33098 left= [13.211, -4.43714]; right=[7.86771, -10.4028]
head pose eular [-12.0523, 1.14984, 3.83077]theta phi 12.0499 1.17572 left= [15.3056, -1.4455]; right=[8.97458, -9.68005]
head pose eular [-3.85404, 3.29126, 3.58394]theta phi 3.84768 3.2987 left= [9.42506, -1.22022]; right=[6.72317, -1.17989]
head pose eular [-3.01032, 3.41415, 3.30355]theta phi 3.00497 3.41886 left= [10.8756, -2.05062]; right=[7.12273, -0.630901]
head pose eular [-4.18269, 3.32688, 3.59334]theta phi 4.17564 3.33573 left= [9.49473, -2.22776]; right=[7.29289, -1.62149]
head pose eular [-4.38382, 3.30007, 3.63217]theta phi 4.37654 3.30972 left= [7.49414, -3.98205]; right=[6.92315, -1.65223]
head pose eular [-3.43386, 3.329, 3.52566]theta phi 3.42807 3.33497 left= [7.35731, -5.18307]; right=[6.84059, -1.3439]
head pose eular [0.630042, 3.70931, 2.91621]theta phi -0.628723 3.70953 left= [11.1194, 2.57351]; right=[4.28773, -3.13505]
head pose eular [-3.71824, 3.18997, 3.66371]theta phi 3.71248 3.19668 left= [9.81482, -4.25331]; right=[6.65766, -1.53865]
head pose eular [-2.9792, 3.32599, 3.3512]theta phi 2.97419 3.33048 left= [10.7986, -3.6715]; right=[6.79642, -1.00657]
head pose eular [-5.17311, 1.73973, 1.66267]theta phi 5.17072 1.74683 left= [0.720886, 6.46417]; right=[-10.76, 11.2012]
head pose eular [-5.04118, 1.75418, 1.68429]theta phi 5.03881 1.76098 left= [0.677518, 5.99884]; right=[-12.7243, 13.2369]
head pose eular [-4.45408, 1.74635, 1.53049]theta phi 4.45201 1.75163 left= [0.996714, 6.01306]; right=[-13.1729, 13.4758]
head pose eular [7.57713, 3.176, 0.953735]theta phi -7.56543 3.20389 left= [2.36249, 11.9783]; right=[-12.4705, 19.3319]
head pose eular [9.36434, 2.93061, 0.687728]theta phi -9.35199 2.97009 left= [1.7426, 13.0581]; right=[-12.2274, 18.5353]
head pose eular [7.78052, 3.09373, 0.822903]theta phi -7.76912 3.12239 left= [1.40393, 12.5169]; right=[-12.2625, 19.4797]
head pose eular [9.56401, 3.33098, 0.288246]theta phi -9.54772 3.37777 left= [3.82451, 15.6527]; right=[-13.2647, 20.1762]
head pose eular [9.61344, 3.21099, 0.596373]theta phi -9.59822 3.25658 left= [1.54776, 14.096]; right=[-13.3945, 19.3363]
head pose eular [10.232, 3.25755, 0.472244]theta phi -10.2153 3.31003 left= [7.60641, 18.5114]; right=[-14.9846, 21.0561]
head pose eular [5.37823, 3.65301, 0.853587]theta phi -5.36728 3.66911 left= [3.34215, 14.4372]; right=[-12.6333, 19.6115]
head pose eular [6.78837, 3.20138, 0.971521]theta phi -6.77774 3.22391 left= [1.81308, 13.7714]; right=[-13.2455, 19.4436]
head pose eular [5.13847, 2.94337, 1.08351]theta phi -5.13167 2.95522 left= [0.791651, 12.3411]; right=[-12.296, 18.1699]
head pose eular [5.04821, 2.96738, 0.967213]theta phi -5.04143 2.9789 left= [1.00836, 11.2507]; right=[-13.3752, 18.7099]
head pose eular [4.58961, 3.12629, 0.79975]theta phi -4.58277 3.13632 left= [5.95514, 11.4359]; right=[-14.04, 19.9855]
head pose eular [4.41407, 2.9116, 1.02182]theta phi -4.40837 2.92024 left= [4.01925, 11.0774]; right=[-12.6544, 17.6008]
head pose eular [4.35064, 2.86867, 0.899485]theta phi -4.34518 2.87694 left= [8.07213, 14.8483]; right=[-13.4946, 17.9321]
head pose eular [4.19235, 2.83102, 1.27294]theta phi -4.18723 2.83859 left= [8.14802, 15.7434]; right=[-13.7238, 14.2106]
head pose eular [5.05985, 3.05532, 1.32847]theta phi -5.05265 3.06724 left= [8.24592, 16.7647]; right=[-13.8394, 13.4095]
head pose eular [5.21291, 3.50043, 0.599014]theta phi -5.20317 3.51492 left= [4.8733, 20.513]; right=[-11.2031, 12.3594]
head pose eular [7.29101, 3.06993, 0.23035]theta phi -7.2805 3.09488 left= [2.41374, 18.0426]; right=[-12.9666, 10.6157]
head pose eular [7.0509, 3.25162, 0.55963]theta phi -7.0395 3.27632 left= [7.04219, 20.745]; right=[-11.9441, 11.4506]

**Comment by TadasBaltrusaitis** [comment]
First, gaze estimation is absolute and not in terms of the head pose. In order to compute it in terms of head pose you can use the head pose orientation matrix and correct the gaze angles by it.

With regards to yaw angles being different, there are several things that can be causing this:
1. The yaw angle between both eyes will only be the same if a person is looking at the horizon (https://en.wikipedia.org/wiki/Vergence). So the visualization of gaze will look correct but the angles will be slightly different.
2. Further, depending on conditions the mean angle error you can expect from OpenFace in eye gaze is between 4-10 degrees, so the difference you see is often within the error range.

**Comment by AnaisServais** [comment]
Hi, 

So to get gaze angle corrected with head pose: you recommend to multiply the inverse matrix of head rotation by the vector of eye rotation. Do you mean gaze_angle_x and gaze_angle_x or gaze_0_x, gaze_0_y, gaze_0_z ?
Thanks for helping!
