### ISSUE TITLE
Please consider adding filename into .csv file.

### ISSUE THREAD

**Issue by CastellanLiu** [TadasBaltrusaitis/OpenFace#487]
When using File->Open image directory (as sequence), the outputs are [xxx.avi, xxx.csv, xxx.txt], but there is no information about which image a certain row of the csv file belongs to. Please consider adding filename into .csv file so that we can better use the results, many thanks!

my version: win_x64 2.0.2 binary release.

**Comment by TadasBaltrusaitis** [comment]
The idea behind "open image directory (as sequence)" is that the images will be sorted in an alphanumerical order and are assumed to come from a sequence (e.g. created from a video), so each row will correspond to a frame in that sequence. If you sort the names of the images then their order will correspond to the row of each image.
