### ISSUE TITLE
multi-person tracking  in GUI

### ISSUE THREAD

**Issue by wynwpu** [TadasBaltrusaitis/OpenFace#489]
I want to realize  multi-person tracking in  GUI of HeadPoseLive should be how to modify the code?

**Comment by TadasBaltrusaitis** [comment]
The code is available, so you should be able to modify it. You can have a look how multiple people tracking was implemented in C++ by having a look at `FaceLandmarkVidMulti.cpp`

**Comment by wynwpu** [comment]
I noticed that the function of NonOverlapingDetections( ), if this function is important, how to change it to c # code

**Comment by TadasBaltrusaitis** [comment]
There are multiple ways:
- you could write a wrapper for it in visual C++ (examples of wrapper functions can be seen in CppInerop project
- you could re-implement it in C#
