### ISSUE TITLE
Lowering the threshold for face detection

### ISSUE THREAD

**Issue by ArashVahabpour** [TadasBaltrusaitis/OpenFace#49]
Hi,
It turns out that for low-resolution videos this package is unable to detect faces with high recall. I am wondering if there exists some sort of threshold for Haar face detection that I can decrease, and later on remove false alarms through some other approach?
Thanks

**Comment by TadasBaltrusaitis** [comment]
Low resolution videos are problematic as face detection in them is unreliable, also landmark detection degrades with smaller images as well. There's not much that can be done about that. You can always upsample the images, but that will lead to some false positives.
