### ISSUE TITLE
mp4 format cannot generate simalign images

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#493]
In mac OS X (both Sierra, and high sierra),
OpenFace 2.0, 2.2 and most recent comitt (5a3cf77) cannot generate simaligned images from mp4 files.
I run same code for .avi, and it successfully generated images.
however, when input file is mp4, it just generated hog and result csv files, rather than aligned images.

**Comment by iPsych** [comment]
actually, it turned out that the problem was not a video format...
Same videos works properly with 'FeatureExtraction' but NOT with 'FaceLandmarkVidMulti'.

I think some size or memory issue is there, since
The multi_face.avi works properly, but the other (bigger, longer) videos with exactly same codec doesn't works.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Can you be a bit more specific please? What are the exact command line arguments you used and what size are the input videos (length and resolution). Also do they contain multiple faces?

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, re-open if persists.
