### ISSUE TITLE
How to train model_eye?

### ISSUE THREAD

**Issue by Irene-rtc1** [TadasBaltrusaitis/OpenFace#494]
I have trained the PDM and patch experts models. but I donnot know how to train the 28 points eye model?? can you help me?

**Comment by TadasBaltrusaitis** [comment]
Hi,

Please have a look at the following issues:
https://github.com/TadasBaltrusaitis/OpenFace/issues/334
https://github.com/TadasBaltrusaitis/OpenFace/issues/395

Eye model training is one aspect that is not as well documented or packaged yet.
