### ISSUE TITLE
How to be sure about the model used?

### ISSUE THREAD

**Issue by Lhemamou** [TadasBaltrusaitis/OpenFace#495]
Hi Tadas,

I'm currently applying OpenFace FeatureExtraction on a large set of video. However, before, i would like to be sure that i'm using the right model (MT-CNN for face detection and CE-CLM for landmarks detection). On my command line , I'm using -mloc \"model/main_ceclm_general.txt\" .

1) How to be sure that MT-CNN is used?
2) How to be sure that effectively both models are used and are not switched with another model in case of problems?

Thanks you for all,

Léo

**Comment by TadasBaltrusaitis** [comment]
If you are using the default parameters (e.g. just `FeatureExtraction` with `-f` for specifying files to process) you will be using MT-CNN and CE-CLM. 

You can actually look at the console output to see what models are being read in and you should see CEN patch experts and MT-CNN models being read in.

The models are not switched with others unless you explicitly specify that using `-mloc`

**Comment by yuhaimei** [comment]
Is this bug fixed? I encountered this error just now. 
Also, what should the outcome be after running the test from the home page? Should there be a picture with landmark labels on it?
Thanks a lot!!

**Comment by TadasBaltrusaitis** [comment]
The incorrect error message is still there. Is the tracker working correctly for you?
