### ISSUE TITLE
in OS X, mp4 long video issue

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#498]
This issue is an addition to below issue.
https://github.com/TadasBaltrusaitis/OpenFace/issues/442

When I use FaceLandmarkVidMulti, your example (Video 1) works perfectly, but the other videos 
(Video 2 and Video3) doesn't give tracked video or aligned images. (The HOG and txt result looks proper...)

Below is the information.
Does the input videos need strict codec condition or bitrate?

Video 1 (multi_face.avi) 
Duration: 00:00:23.40, start: 0.000000, bitrate: 1026 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (DIVX / 0x58564944), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 1020 kb/s, 30 fps, 30 tbr, 30 tbn, 30 tbc

Video 2
Duration: 00:25:58.53, start: 0.000000, bitrate: 4007 kb/s
    Stream #0:0: Video: mpeg4 (Simple Scalable Profile) (DX50 / 0x30355844), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3999 kb/s, 30 fps, 30 tbr, 30 tbn, 30 tbc

Video 3
Duration: 00:25:58.57, start: 0.000000, bitrate: 3540 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3343 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)

**Comment by iPsych** [comment]
Successfully track, and save successfully aligned images.
`./bin/facelandmarkvidmulti -f ./Samples/multi_face.avi -nobadaligned`

Successfully track, but no luck in save aligned images and tracked video.
`./bin/facelandmarkvidmulti -f /Users/cogsys/Downloads/test.mp4 -nobadaligned`

I changed the video to avi and xVID codec, no luck.
`./bin/facelandmarkvidmulti -f /Users/cogsys/Downloads/test.avi -nobadaligned`

I moved it to the sample forder and tried again, no luck.
`./bin/facelandmarkvidmulti -f ./Samples/test.mp4 -nobadaligned`

I have a few hypothesis.
video size (resolution)
video size (filesize)
too high framerate (bitrate)
29.7 fps (tested with converted video with 30fps, 24fps, but no luck... so we can eliminate this).

**Comment by TadasBaltrusaitis** [comment]
What is the resolution and length of `test.mp4`?

Bitrate should not affect the results, each frame is treated somewhat independently.

Thanks,
Tadas

**Comment by iPsych** [comment]
I sent you google drive share link.
usually 20 to 40 min and 1920-720.

June Kang, Ph.D.
Research Professor | 
Department of Brain and Cognitive Engineering, 
Korea University
Director | 
Empathy Research Institute

| Email :  june.kang@empathy-research.org
| Blog : www,ipsych.com

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now, let me know if the issue still persists.
