### ISSUE TITLE
Face too small for landmark detection - OpenCV region of interest

### ISSUE THREAD

**Issue by elifbozkurt** [TadasBaltrusaitis/OpenFace#499]
Hello,

I am testing FeatureExtraction.exe of OpenFace_2.0.2_win_x64 executables on a video file which includes a single subject who moves frequently and sometimes gets out of the field of view.  I get consecutive warnings that the face is too small for landmark detection. Then, an OpenCV error message occurs and the program crashes. I also rebuilt the source code and tested again and received the same error message:

OpenCV Error: Assertion failed (ssize.area() > 0) in cv::remapBilinear, file C:\
build\master_winpack-build-win64-vc14\opencv\modules\imgproc\src\imgwarp.cpp, li
ne 662

or 

OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.widt
h <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in
 cv::Mat::Mat, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core
\src\matrix.cpp, line 538

depending on the input video file. 

Facial landmark detection may fail up to 110 frames in some videos. I tested version 2.0.0 and 2.0.1, as well and received above errors again.

If I use OpenFace version 1.0.0, I do not get above messages and can track features. 

Thank you.

**Comment by TadasBaltrusaitis** [comment]
Is there any chance of sharing the video? I saw a couple of errors like this myself, but was not able to reliably reproduce them.

Thanks,
Tadas

**Comment by TadasBaltrusaitis** [comment]
Can you try to see if this has been fixed in the following branch?
https://github.com/TadasBaltrusaitis/OpenFace/tree/feature/2.0.4

I'm not able to reproduce the issue, but I believe this should solve it. If it does, I will move the fix to the master branch.

Thanks,
Tadas

**Comment by elifbozkurt** [comment]
I tested the branch you sent on all video files I had and now FeatureExtraction executable works well.

Thank you.

**Comment by tjusxh** [comment]
I had the same issue when I testing FaceLandmarkImg.exe.  And the link can't be visited.  
Thanks

**Comment by TadasBaltrusaitis** [comment]
The link has expired, as the branch has been incorporated into master, and the issue should be fixed.

**Comment by tjusxh** [comment]
I really had the issue. I verified my images. I found that there are two faces, and one is very small and the angle of the face is very big. Thanks very much.

**Comment by TadasBaltrusaitis** [comment]
Do you still have the issue? Can you reproduce it?

**Comment by tjusxh** [comment]
Yes, but the reason actual is the face is too small. So it isn't one issue for me. Thanks for your quickly response.
