### ISSUE TITLE
Facial landmark detection is performed using Dlib?

### ISSUE THREAD

**Issue by mrgloom** [TadasBaltrusaitis/OpenFace#50]
Facial landmark detection is performed using Dlib?

**Comment by TadasBaltrusaitis** [comment]
No it is not, dlib is used for face detection and Histogram of Oriented Gradient extraction. For facial landmark detection Constrained Local Neural Field method is used.

**Comment by mrgloom** [comment]
Is it just [module of OpenFace](https://github.com/TadasBaltrusaitis/OpenFace/tree/master/lib/local/LandmarkDetector) or it's some external lib?

How it's related to this projects?
https://github.com/TadasBaltrusaitis/CLM-framework
https://github.com/TadasBaltrusaitis/CCNF

**Comment by TadasBaltrusaitis** [comment]
It's a module in OpenFace and not an external library, it is related to CLM-framework as the same landmark detection algorithm is used in both. It is also related to CCNF as it uses CCNF model internally.
