### ISSUE TITLE
What are the difference between OpenFace and openface?

### ISSUE THREAD

**Issue by jiapei100** [TadasBaltrusaitis/OpenFace#500]
Hi:

Just wonder what are the differences between [https://github.com/cmusatyalab/openface](https://github.com/cmusatyalab/openface) and [https://github.com/TadasBaltrusaitis/OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) ?

Cheers

**Comment by TadasBaltrusaitis** [comment]
They are only related by name and the fact that they are intended for face analysis.

This OpenFace (https://github.com/TadasBaltrusaitis/OpenFace) is intended for facial landmark detection, head pose estimation, eye gaze tracking and expression analysis (facial behavior analysis in short).

The other openface (https://github.com/cmusatyalab/openface) is intended for face recognition only (from what I know, I am not involved in that project)
