### ISSUE TITLE
How to match face

### ISSUE THREAD

**Issue by liuyanmin120** [TadasBaltrusaitis/OpenFace#501]
I can not found a function to match one person face. examples in videos, I want to find the person, how to do it?

**Comment by TadasBaltrusaitis** [comment]
Sorry, I'm not sure I understand your question. What do you mean by matching a face, and what example videos are you referring to?

**Comment by liuyanmin120** [comment]
give a people picture,i want to find the persion in videos, how to do it, i not found.

**Comment by liuyanmin120** [comment]
give a people picture,i want to find the person in videos, how to do it, i not found.

**Comment by liuyanmin120** [comment]
i study the project, i know how to get LandmarkDetector::CLNF, but i not found a function to compare CLNF, to find the CLNF in videos.

**Comment by liuyanmin120** [comment]
DetectSingleFaceHOG, this function can not compare is the same person,
![image](https://user-images.githubusercontent.com/5358902/42125657-86ba909c-7cad-11e8-9e0c-bcfbc52b79b2.png), I want to Authentication，such as face Sign in。

**Comment by TadasBaltrusaitis** [comment]
Hi,

OpenFace does not do face recognition or verification. While you could use HOG features to do that, there are better features for that task, you can have a look at another project (also called openface) for features suitable fore recognition and verification - https://cmusatyalab.github.io/openface/
