### ISSUE TITLE
Make OpenFace errors

### ISSUE THREAD

**Issue by deepalianeja** [TadasBaltrusaitis/OpenFace#502]
I followed the wiki instructions but I get the following errors at the last stage (make)
..............

[ 76%] Building CXX object lib/local/Utilities/CMakeFiles/Utilities.dir/src/VisualizationUtils.cpp.o
[ 78%] Building CXX object lib/local/Utilities/CMakeFiles/Utilities.dir/src/Visualizer.cpp.o
[ 80%] Linking CXX static library libUtilities.a
[ 80%] Built target Utilities
Scanning dependencies of target FaceLandmarkImg
[ 83%] Building CXX object exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/FaceLandmarkImg.cpp.o
[ 85%] Linking CXX executable ../../bin/FaceLandmarkImg
**../../lib/local/Utilities/libUtilities.a(ImageCapture.cpp.o): In function `Utilities::ImageCapture::OpenDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, float, float, float)':
ImageCapture.cpp:(.text+0x2b64): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:129: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:308: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by deepalianeja** [comment]
Resolved. OpenCV was not linked correctly.

**Comment by yangyuke001** [comment]
@deepalianeja I have already installed opencv3.3.0, how to link it?thanks in advance!
