### ISSUE TITLE
How to archive feature vector??

### ISSUE THREAD

**Issue by thisisthanh** [TadasBaltrusaitis/OpenFace#503]
I am newbie OpenFace
Please help me, step by step (more detail more good) to get a feature vector from face image..
My image example is in attach file.

**Comment by thisisthanh** [comment]
![9326871 4](https://user-images.githubusercontent.com/39133352/42133374-3136f0ce-7d53-11e8-9747-47d13b6328f5.jpg)

**Comment by TadasBaltrusaitis** [comment]
Please have a look at:
1. https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments
2. https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

The first link explains how to run OpenFace on images or videos, the second one explains what output OpenFace provides (feature vectors).

If you are using Windows you can use the GUI which is a bit easier to use and should be reasonably self-explanatory (no documentation exists for it at the moment though). You can find a pre-build version of it here - https://github.com/TadasBaltrusaitis/OpenFace/releases/download/OpenFace_v2.0.3/OpenFace_2.0.3_win_x64.zip

Thanks,
Tadas
