### ISSUE TITLE
Opencv fails with long video. 

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#504]
Reopen of issue #442 

Still fails with long video with OpenCV 3.4.1_6 from homebrew, openface 2.0.3 3d5b3d.

I think it was resolved, but re-evoked after the first-frame bug fixed.

Thanks.

Below is the full error codes. It replicated with the videos I shared.

```
OpenCV(3.4.1) Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/opencv-20180630-73747-zn1npb/opencv-3.4.1/modules/core/src/matrix.cpp, line 464
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.1) /tmp/opencv-20180630-73747-zn1npb/opencv-3.4.1/modules/core/src/matrix.cpp:464: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

Abort trap: 6

```

Update :

I found below issues in opencv 4.1

https://github.com/opencv/opencv/issues/11076
https://github.com/maelvalais/homebrew-amc/issues/4

**Comment by TadasBaltrusaitis** [comment]
Can you try the following branch, I'm not 100% that this fixed the error as I'm not able to reproduce it:
https://github.com/TadasBaltrusaitis/OpenFace/tree/feature/2.0.4

This should not be related to the first frame bug though.

Thanks,
Tadas

**Comment by iPsych** [comment]
I really appreciate for your quick update.

I tested two Sierra systems and 
It works perfectly now.

(It shown segmentation fault 11 error but works after openblas reinstallation with openmp command)

homebrew version of openblas 0.3.0 built with openmp

(brew install openblas —with openmp)

June Kang, Ph.D.
Research Professor | 
Department of Brain and Cognitive Engineering, 
Korea University
Director | 
Empathy Research Institute

| Email :  june.kang@empathy-research.org
| Blog : www,ipsych.com

**Comment by iPsych** [comment]
The update worked like charm.

Can you allow me to edit the ‘mac installation’ wiki?
Also which file should I check for change ROI size for face?

**Comment by TadasBaltrusaitis** [comment]
Hi, you should be able to edit the wiki now (please let me know if you can't).

Thanks,
Tadas
