### ISSUE TITLE
How to get the ce-clm model named cen_patches_0.25_of.dat ??

### ISSUE THREAD

**Issue by Irene-rtc1** [TadasBaltrusaitis/OpenFace#505]
I have trained the train_cen.py sucessfully. 
but i did not get the model named cen_patches_0.25_of.dat which is added by openface2.0.  
I just got the result like arch6\0.35_profile1_5_256\general_epoch_25.h5. 
### create_cen_experts_gen.m scripts must load .mat file, not .h5 file;
so how to change the .h5 to .mat file, then I can use  create_cen_experts_gen.m to get .dat file.

THANK YOU!

**Comment by EDMIG** [comment]
see Wiki!

**Comment by Irene-rtc1** [comment]
@EDMIG  create_cen_experts_gen.m scripts must load the .mat files to generate .dat files, which is what I want to get. but how to get .mat files from .h5 files???  traning the models with my datasets.

**Comment by LingQiu** [comment]
In my view, the `.h5` files are saved as `.mat` files. In other words, the `.mat` files are the models of training.

**Comment by Irene-rtc1** [comment]
@LingQiu  so I need to read _.h5_ files and save it into **.mat** files. they have the same format??

**Comment by LingQiu** [comment]
@Irene-rtc1 You can save the models as the `.mat` files directly. In the link [https://www.dropbox.com/sh/o8g1530jle17spa/AADRntSHl_jLInmrmSwsX-Qsa?dl=0](url), the `.mat` files are the matlab models. It can be used as a reference.

**Comment by LingQiu** [comment]
@Irene-rtc1, how is your effect? my result is not so good.

**Comment by Irene-rtc1** [comment]
You must do the script to change it into .dat by yourself. load the model that writer published and get its structure, then you can create your .m to change its structure.

在2018-07-10 23:35:37，LingQiunotifications@github.com写道：

@Irene-rtc1, how is your effect? my result is not so good.

**Comment by LingQiu** [comment]
@Irene-rtc1 ,thanks for your reply. My results are in the attachment. I trained 10 epochs every landmark. I do not know whether it become better for more epochs. Can you give me some advices?
[result.zip](https://github.com/TadasBaltrusaitis/OpenFace/files/2212967/result.zip)

**Comment by AaboutL** [comment]
@Irene-rtc1 Hi, have you successfully transformed the ce-clm models from .h5 to .mat? Does the author provide the transformation script, or should I transform from .h5 to .mat by myself?

**Comment by TadasBaltrusaitis** [comment]
Hi,

We have updated the scripts and you can find the .h5 to .mat script here - https://github.com/TadasBaltrusaitis/OpenFace/tree/master/model_training/ce-clm_training/cen_training
