### ISSUE TITLE
how to set frame per second ?

### ISSUE THREAD

**Issue by MyraBaba** [TadasBaltrusaitis/OpenFace#507]
Hi,

I am using the FeatureExtracting in ARM based SBC and dont need more than 4-6 frame per second.

Can I set to captured frame per second to catch the real time event , how can I set this? and I dont need all the aus , how can I set only a few to speed up the processing time ? or it is nonsense 

thx

**Comment by TadasBaltrusaitis** [comment]
Hi,

Do you want to reduce the CPU load by reducing the processing fps? If so, unfortunately, you can't easily control this without changing the code. 

You can tell FeatureExtraction which features you want, see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#featureextraction-and-facelandmarkvidmulti, at the bottom it will tell you how to only output e.g. landmarks and pose without AUs, this should speed up the processing a bit.

Thanks,
Tadas
