### ISSUE TITLE
About MTCNN

### ISSUE THREAD

**Issue by lzwhard** [TadasBaltrusaitis/OpenFace#510]
Hi Tadas,

Thanks for your work. Did you reproduce the training of mtcnn, and how do you transfer to c++ version

**Comment by TadasBaltrusaitis** [comment]
Hi,

I only re-implemented the inference and not the training. I converted the original caffe model (from https://github.com/kpzhang93/MTCNN_face_detection_alignment) to a model that can be read by my C++ CPU implementation of CNN. I also did a number of CPU optimizations to make sure the MTCNN detector runs close to real-time on a machine without a GPU.

You can find my matlab models and code to convert them to c++ version in `matlab_version\face_detection\mtcnn\convert_to_cpp`
