### ISSUE TITLE
OpenBLAS : Program will terminate because you tried to start too many threads.

### ISSUE THREAD

**Issue by nandev** [TadasBaltrusaitis/OpenFace#512]
I compiled the software on mac os 10.13.4 as instructed using 
Command Line Tools for Xcode 9.4.1, opencv 3.4.2, dlib 19.13, openblas 0.3.1, tbb 2018_U5, boost 1.67.0_1

When running FaceLandmarkVid -device 0 the following error occurs:

Attempting to read from webcam: 0
Device or file opened
Starting tracking
Reading the MTCNN face detector from: bin/model/mtcnn_detector/MTCNN_detector.txt
Reading the PNet module from: bin/model/mtcnn_detector/PNet.dat
Reading the RNet module from: bin/model/mtcnn_detector/RNet.dat
Reading the ONet module from: bin/model/mtcnn_detector/ONet.dat
OpenBLAS : Program will terminate because you tried to start too many threads.
Segmentation fault: 11

Please help.

**Comment by iPsych** [comment]
I faced the same issues.
First reinstall the latest version of openblas with openmp

brew reinstall openblas —with openmp

If the problem still exists, check the last part of mac installation in wiki

BLAS performance

OpenFace uses BLAS to accelerate numerical computations and TBB for parallelization, in some cases the threading of BLAS and TBB clash, adding the below environmental variables helps with this issue:

export OMP_NUM_THREADS=1

export VECLIB_MAXIMUM_THREADS=1

**Comment by nandev** [comment]
The openblas reinstall with openmp fixed it. 
Thank you!

**Comment by informatrix** [comment]
After reinstall openblas with openmp, and set the environmental variables, still got the issue. Any way to fix it?

**Comment by adataylor** [comment]
It seems that the previous fix of 
`brew reinstall openblas --with openmp`
doesn't work, giving the error:                                                                                                                                
`Error: No available formula with the name "—-with" `

**Comment by TadasBaltrusaitis** [comment]
Other people seem to be having a similar issue - https://github.com/Homebrew/homebrew-core/issues/32557 ?
