### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by karanmartian** [TadasBaltrusaitis/OpenFace#513]
Hi,

I just came across this repo and was a little bit confused because the name related to the other OpenFace repo that's out there. Does your project currently support face recognition i.e. identifying a particular face in a realtime video stream?

**Comment by TadasBaltrusaitis** [comment]
My OpenFace project does not support face recognition, it is intended for facial behavior analysis (although it can be used as a pre-processing step for face recognition in videos)
