### ISSUE TITLE
openfaceoffline.exe , the video written by recording setting is different from observational window???

### ISSUE THREAD

**Issue by Irene-rtc1** [TadasBaltrusaitis/OpenFace#514]
in openfaceoffline.exe , I have changed the OverlayImage.xaml.cs and MainWindow.xaml.s . the display in MainWindows is correct. why the written video is different from it ??

**Comment by TadasBaltrusaitis** [comment]
It is different as the underlying C++ code is used to draw the results rather than the C# code, this is done for consistency between the C++ and C# versions (so that they both produce identical results).

**Comment by Irene-rtc1** [comment]
@TadasBaltrusaitis  Thank you for your answering. I have got it.
