### ISSUE TITLE
i want to use openface with opencv i am getting some problem

### ISSUE THREAD

**Issue by Kabariya** [TadasBaltrusaitis/OpenFace#517]
Do we have to install torch to use Openface  and if yes, then how can I install torch on windows 10

**Comment by TadasBaltrusaitis** [comment]
OpenFace does not depend on torch and you should not need to install anything on Windows to run it (except for Visual Studio if you want to develop for it or Visual Studio Redistributable if you just want to run it).

Only if you want to train the ce-clm models then you will need Keras though, and that has not been tested on Windows.

**Comment by Kabariya** [comment]
okay thanks :)
