### ISSUE TITLE
6>找不到文件 - tbb_debug.dll

### ISSUE THREAD

**Issue by linyia01** [TadasBaltrusaitis/OpenFace#518]
1>------ 已启动生成: 项目: Utilities, 配置: Debug Win32 ------
2>------ 已启动生成: 项目: CameraEnumerator, 配置: Debug Win32 ------
1>复制了 0 个文件
1>找不到文件 - tbb_debug.dll
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 命令“xcopy /I /E /Y /D /C "F:\work\C++\OpenFace-master\lib\3rdParty\tbb\bin\x86\v141\tbb_debug.dll" "F:\work\C++\OpenFace-master\Debug\"
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd”已退出，代码为 4。
1>已完成生成项目“Utilities.vcxproj”的操作 - 失败。
3>------ 已启动生成: 项目: LandmarkDetector, 配置: Debug Win32 ------
2>OpenCVDeviceEnumerator.cpp
3>找不到文件 - tbb_debug.dll
3>复制了 0 个文件
3>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 命令“xcopy /I /E /Y /D /C "F:\work\C++\OpenFace-master\lib\3rdParty\tbb\bin\x86\v141\tbb_debug.dll" "F:\work\C++\OpenFace-master\Debug\"
3>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd”已退出，代码为 4。
3>已完成生成项目“LandmarkDetector.vcxproj”的操作 - 失败。
4>------ 已启动生成: 项目: FaceAnalyser, 配置: Debug Win32 ------
5>------ 已启动生成: 项目: GazeAnalyser, 配置: Debug Win32 ------
5>找不到文件 - tbb_debug.dll
5>复制了 0 个文件
5>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 命令“xcopy /I /E /Y /D /C "F:\work\C++\OpenFace-master\lib\3rdParty\tbb\bin\x86\v141\tbb_debug.dll" "F:\work\C++\OpenFace-master\Debug\"
5>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd”已退出，代码为 4。
5>已完成生成项目“GazeAnalyser.vcxproj”的操作 - 失败。
4>找不到文件 - tbb_debug.dll
4>复制了 0 个文件
4>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 命令“xcopy /I /E /Y /D /C "F:\work\C++\OpenFace-master\lib\3rdParty\tbb\bin\x86\v141\tbb_debug.dll" "F:\work\C++\OpenFace-master\Debug\"
4>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd”已退出，代码为 4。
4>已完成生成项目“FaceAnalyser.vcxproj”的操作 - 失败。
2>DeviceEnumerator.cpp
2>正在生成代码...
2>CameraEnumerator.vcxproj -> F:\work\C++\OpenFace-master\Debug\CameraEnumerator.lib
6>------ 已启动生成: 项目: CppInerop, 配置: Debug Win32 ------
6>找不到文件 - tbb_debug.dll
6>复制了 0 个文件
6>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 命令“xcopy /I /E /Y /D /C "F:\work\C++\OpenFace-master\lib\3rdParty\tbb\bin\x86\v141\tbb_debug.dll" "F:\work\C++\OpenFace-master\Debug\"
6>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd”已退出，代码为 4。
6>已完成生成项目“CppInerop.vcxproj”的操作 - 失败。
7>------ 已启动生成: 项目: OpenFaceOffline, 配置: Debug x86 ------
7>CSC : error CS0006: 未能找到元数据文件“F:\work\C++\OpenFace-master\Debug\CppInerop.dll”
========== 生成: 成功 1 个，失败 6 个，最新 0 个，跳过 0 个 ==========

**Comment by TadasBaltrusaitis** [comment]
Are you using Visual Studio 2017? OpenFace has only been tested on Visual Studio 2015. Can you try chanign the platform toolset to v140 instead of v141?

**Comment by TadasBaltrusaitis** [comment]
Closing now. Please re-open if issue still there
