### ISSUE TITLE
How to project 3D localised landmark to 2D

### ISSUE THREAD

**Issue by deckyal** [TadasBaltrusaitis/OpenFace#519]
Hi, 

Currently I am doing a benchmark to compare my landmark tracker on the projected 3D to 2D of 300VW in the wild and would like to compare with the method used in this library. My question is, how to project the detected 3D landmark (in milimeter) to 2D (in pixels) on this library?. 

Thanks

**Comment by TadasBaltrusaitis** [comment]
Hi,

OpenFace already outputs both the detected 3D landmarks (in milimeters) and the 2D ones (in pixels), it uses perspective projection to go from 2D to 3D (using solve PnP algorithm and an approximation of 3D face shape). 

However, as the intrinsic camera parameters are not known for 300VW videos (such as focal length), this mapping from 2D to 3D is only approximate.

Thanks
