### ISSUE TITLE
TBB in dlib face detection

### ISSUE THREAD

**Issue by frankkiv** [TadasBaltrusaitis/OpenFace#52]
Hey Tadas,

The project you did It's very impressive! 

I find out you modify the dlib source code in scan_fhog_pyramid.h on both CLM-framework and OpenFace project.

It seems like you want to make create_fhog_pyramid and detect_from_fhog_pyramid run in parallel by TBB.

And I try to calculate the processing time in object_detector.h:430 in fuction void object_detector<image_scanner_type>::operator().

I got puzzled by the unexpected results.

The code without parallel is 2 times faster than code with TBB parallel.

So I'm not sure is there anything I missed or I use the wrong settings?

Thanks,
Frank

**Comment by TadasBaltrusaitis** [comment]
Hey Frank,

That's interesting, what sort of machine (how many cores) are you using and what OS? 

In my experiments some time ago I found that TBB did help quite a bit with face detection, this was on a multicore Windows machine.

Thanks,
Tadas

**Comment by frankkiv** [comment]
Hi Tadas,

I run it on my OSX.
And it's Intel i5  Dual-core CPU.

Thanks

**Comment by TadasBaltrusaitis** [comment]
I haven't tested the code much on Macs at all so it might be possible that TBB does not help face detection there. Thanks for letting me know, I'll investigate this further.

**Comment by frankkiv** [comment]
You're right.
I made a mistake on using CPU clock time to calculate processing time.
TBB made face detection almost 2 times faster on my machine.

Thanks,
Frank

**Comment by piliwilliam0306** [comment]
Hi TadasBaltrusaitis,

Would TBB work on ARM machines?

Thanks.

**Comment by TadasBaltrusaitis** [comment]
It should - https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/495003, but I have not tested it myself.
