### ISSUE TITLE
can't start the featureExtraction.exe

### ISSUE THREAD

**Issue by peiyaoooo** [TadasBaltrusaitis/OpenFace#522]
Hi, Tadas. I want to get more accurate AU predictions. 
So I want to run featureExtraction.exe. It seemed that it couldn't be opened.
Besides, I tried it in  command line, such as : FeatureExtraction.exe -f "C:\my videos\video.avi" 
There is no processed directory to display.
Could u help me?Thanks a lot!

**Comment by TadasBaltrusaitis** [comment]
Hi, was your command line opened in the same directory as FeatureExtraction.exe? Also if you are executing from powershell you might need to execute ./FeatureExtraction.exe instead.
