### ISSUE TITLE
some problems when recording the data

### ISSUE THREAD

**Issue by peiyaoooo** [TadasBaltrusaitis/OpenFace#523]
Hi, Tadas~So sorry to disturb you again.
When I run the OpenFaceOffline.exe, there may exist a zeroexception to interrupt the process of a image sequence.  (the reason of zeroexception may be no defected face  )
But I don't want the .exe stop when the zeroexception exsits. It can record down the error and keep on recording next image. I need a   continuous sequence recording.
Where can I change the solution of zeroexception to realize the continous sequence recording?
Thanks a lot.

The error is as below:
-------------------------------------------------
System.DivideByZeroException
  HResult=0x80020012
  Message=尝试除以零。
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>
-----------------------------------------------------

**Comment by TadasBaltrusaitis** [comment]
Can you give me an example of a video or an image sequence that is causing this error? It should not crash if there is not face detected.

Thanks,
Tadas

**Comment by peiyaoooo** [comment]
Hi,Tadas. I have sent the image dataset to u via the email. Have you got that?(My email account is peiyao1001@sina.cn)

**Comment by peiyaoooo** [comment]
Hi, Tadas. I also have another question to bother you. Can I use the featureExtract function  with a version of .dll/others in python script. I want to process the Au intensity of Webcamera  in real time

**Comment by TadasBaltrusaitis** [comment]
I found the cause of the error, I will fix it in the next release of OpenFace.

**Comment by peiyaoooo** [comment]
Looking forward to the next version!Thanks a lot!

**Comment by TadasBaltrusaitis** [comment]
You can use FeatureExtraction project to extract AU intensities from a webcam in real time, however, you will need to edit the code to access the values.
