### ISSUE TITLE
Can I directly analyze the rotated video directly

### ISSUE THREAD

**Issue by ywjcrazy** [TadasBaltrusaitis/OpenFace#524]
Hi Tadas,
I captured the video by my phone and the image is not frontal (left rotated by 90 degree)?
Do I have to rotate the video manually and then put it to OpenFace?
![image](https://user-images.githubusercontent.com/7609534/42925330-7273a800-8b60-11e8-9072-58b59aee81dd.png)

**Comment by ChrizzyM87** [comment]
Yes, you should rotate it before putting it to OpenFace. Alternatively you can set position- and rotation hypothesis for the landmark detection, but this is more effort and I guess not what you want.

**Comment by TadasBaltrusaitis** [comment]
Yes, you would need to do it manually, there's no automatic and easy way to do it without changing the code.
