### ISSUE TITLE
Question about module's data structure.

### ISSUE THREAD

**Issue by CerrieJ** [TadasBaltrusaitis/OpenFace#53]
Hi tadas,
    I saw that you stored the modules in .txt format,  but I don't know what every row data means, can you tell me what the data structure of the modules is?

**Comment by TadasBaltrusaitis** [comment]
What specific modules do you mean? The pre-trained models or output?

**Comment by CerrieJ** [comment]
The pre-trained models. Thanks!

**Comment by TadasBaltrusaitis** [comment]
It depends on the model - patch experts, Action Unit (AU) detectors, and the Point Distribution Model all have slightly different formats. You can either check the code writing them out or reading them in to get the format. They are not text files as such but rather binary files, making them difficult to interpret with a regular text editor. 

The code for writing the modules:

- PDM `matlab_version\pdm_generation\Wild_data_pdm\writePDM.m`
- AU - `matlab_version\AU_training\experiments\utilities\write_lin*` - depends on type of AU
- Patch Experts - https://github.com/TadasBaltrusaitis/CCNF/blob/master/patch_experts/ccnf_training/Write_patch_experts_ccnf.m, it is a part of a different project

The code for reading the modules is in the C++ code:
- PDM - `PDM::Read(string location)`
- Patch experts - `void Patch_experts::Read(vector<string> intensity_svr_expert_locations, vector<string> depth_svr_expert_locations, vector<string> intensity_ccnf_expert_locations)`
- AUs - `void SVM_dynamic_lin::Read(std::ifstream& stream, const std::vector<std::string>& au_names)` etc. depending on the model

**Comment by CerrieJ** [comment]
Hi Tadas, Thanks for your details. There are one more question, What dataset do you used to training your three models?

**Comment by TadasBaltrusaitis** [comment]
For Action Units - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units#datasets-used-for-training-aus-in-openface
For Landmarks and PDM - [CMU Multi-PIE](http://www.multipie.org/) and [300-W](http://ibug.doc.ic.ac.uk/resources/300-W/)
