### ISSUE TITLE
Openface gaze angle question

### ISSUE THREAD

**Issue by nhatminh886688** [TadasBaltrusaitis/OpenFace#530]
Does the OpenFace gaze angle affected by the head rotations? I understand that gaze angle x and y would be around 0 if a person is looking straight ahead. However, if the person rotates his head down and then looks straight ahead, would gaze angle x and y still stay near 0? Thanks.

**Comment by TadasBaltrusaitis** [comment]
Yes, the way gaze is implemented it should still be close to 0.

However, gaze estimation on non frontal faces is difficult as eyes are not as clearly visible, so this will not always be the case.
