### ISSUE TITLE
Applying PAW mask to a non-mean shape

### ISSUE THREAD

**Issue by Sharan123** [TadasBaltrusaitis/OpenFace#531]
This is a question, not an issue (i hope that is ok :) ) 
I started working on an idea to center faces in videos in such a way that the eyes are always parallel to x-axis (using plain rotation and affinewarp). But however i now wish to mask the face (also i want to include a bit of forehead as in AlignFaceMask in Face_utils.cpp) but i don't want to resize my face by applying the mask. 

Currently in AlignFaceMask you apply modified Kabsch's algorithm to convert the source landmarks to the destination landmarks (that are related to mean shape) and then apply a mask with magic constants such as -(30/0.7)*sim_scale. 
I wish to do the same but without the conversion applying Kabshch's algorithm just moving the landmarks so they cover the forehead and getting the pixel_mask from PAW. 

Is that possible and if so, how do i need to change the constants -(30/0.7)*sim_scale since i don't actually understand what is sim_scale related to (what is the default measure for mean_shape if that has any sense).

Thank you in advance i'm a long time follower of a program (I'm writing a master thesis using your program),
Daniel

**Comment by TadasBaltrusaitis** [comment]
Hi Daniel,

That should indeed be possible, The `pdm.mean_shape` is defined in millimetres, and the face size is roughly 65mm inter pupillary distance, so `sim_scale` basically controls how big the face should be in the aligned face image (https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#similarity-aligned-face-images-and-hog-binary-files). By setting it to 1, it will produce a face that has 65px between pupils, you can think of it as px/mm.

For your purposes you want to set the destination for where you want to align the face:
`cv::Mat_<float> similarity_normalised_shape = pdm.mean_shape * sim_scale;`

And the subtraction can be some multiplier of `-(30/0.7) * params_global[0]` or similar, as `params_global[0]` captures the scale. You might need to replace `-(30/0.7)` with some other constant that works. Currently that constant worked for a face of size `pdm.mean_shape`.

Thanks,
Tadas
