### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [TadasBaltrusaitis/OpenFace#533]
I would like to point out that identifiers like “[`__FACEANALYSER_h_`](https://github.com/TadasBaltrusaitis/OpenFace/blob/cdecf902cd1f4facc879b5e912bc249389e57c62/lib/local/FaceAnalyser/include/FaceAnalyser.h#L35)” and “[`__LANDMARK_DETECTOR_MODEL_h_`](https://github.com/TadasBaltrusaitis/OpenFace/blob/014207aad0845c8064d62d7ffc9a97f974cb89e7/lib/local/LandmarkDetector/include/LandmarkDetectorModel.h)” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by TadasBaltrusaitis** [comment]
Thanks for the recommendation!

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.
