### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [TadasBaltrusaitis/OpenFace#534]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [!FaceDetector](https://github.com/TadasBaltrusaitis/OpenFace/blob/79d7116dae7f6b5335016dcb0e9ea64e1f931287/lib/local/CppInerop/FaceDetectorInterop.h#L140)
- [!RecorderOpenFaceParameters](https://github.com/TadasBaltrusaitis/OpenFace/blob/79d7116dae7f6b5335016dcb0e9ea64e1f931287/lib/local/CppInerop/RecorderInterop.h#L78)
- [!SequenceReader](https://github.com/TadasBaltrusaitis/OpenFace/blob/79d7116dae7f6b5335016dcb0e9ea64e1f931287/lib/local/CppInerop/SequenceReader.h#L243)

**Comment by TadasBaltrusaitis** [comment]
Thanks for the recommendation!

**Comment by elfring** [comment]
Thanks for your source code improvement.
