### ISSUE TITLE
Use git lfs for large files

### ISSUE THREAD

**Issue by udnaan** [TadasBaltrusaitis/OpenFace#536]
The bundled models can be much more easily managed if you use lfs. 

The relevant documentation is here: https://git-lfs.github.com/

I can do a PR if it helps.

**Comment by TadasBaltrusaitis** [comment]
From what I can tell even using git lfs still requires a place to host the model files (and they are too large to be stored on github). What would be your suggestion for that?

Thanks,
Tadas

**Comment by udnaan** [comment]
Ah. I haven't tried it myself but according to [this tutorial](https://github.com/git-lfs/git-lfs/wiki/Tutorial), it is possible to use an external server. I'll give it a shot and get back once I have a suitable option.
