### ISSUE TITLE
do i must download model files?

### ISSUE THREAD

**Issue by darkkyrie** [TadasBaltrusaitis/OpenFace#538]
i downloaded a executeable version of openface(OpenFace_v0.1), it seems like OpenFaceOffline.exe but lack of menu "Face Detector" and "Landmark Detector", it doesn't contain model files as source version request (such as cen_patches_0.25_of.dat)but works pretty well,  so i wonder if i just want simple head tracking functions where can i find the code doesn't need those model files?

**Comment by TadasBaltrusaitis** [comment]
You don't need to use the newest models, if you are using the interface (OpenFaceOffline) you can actually select the older models (CLNF and CLM) which do not require you to download model files. If you are using the command line interface executables, you can specify which model to use. Have a look at `-mloc` parameter here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#common-parameters-for-all

**Comment by darkkyrie** [comment]
thank you very much, i will have a try

**Comment by darkkyrie** [comment]
really works, thanks again
