### ISSUE TITLE
use FaceLandmarkImg not with CE-CLM

### ISSUE THREAD

**Issue by darkkyrie** [TadasBaltrusaitis/OpenFace#541]
hi, now i can run OpenFaceOffline.exe running well if i didn't select CE-CLM in Landmark Detector(i haven't downloaded model files yet), but i wonder is there any option command to disable CE-CLM while running FaceLandmarkImg.exe or FaceLandmarkVid.exe?

**Comment by TadasBaltrusaitis** [comment]
You can use older models that don't require you to download anything extra, have a look here - https://github.com/TadasBaltrusaitis/OpenFace/issues/538
