### ISSUE TITLE
AUs result inconsistency

### ISSUE THREAD

**Issue by apchenstu** [TadasBaltrusaitis/OpenFace#542]
Hi, i have tried to get Facial Action Units parameters by using "FaceLandmarkImg.exe" and "OpenFaceOffline" GUI executable file, why the results from those two method is so different? Thanks!

**Comment by TadasBaltrusaitis** [comment]
They should be the same.

What exact command line arguments did you use for `FaceLandmarkImg`? Could you provide some sample images where the results differed?

**Comment by peiyaoooo** [comment]
hello,Tadas, I used the API call(Action Units from https://github.com/TadasBaltrusaitis/OpenFace/wiki/API-calls). I used the arguements('-aus'） and the static au models. The results is different from that of"OpenFaceOffline". The picture data is from genki. Besides, it also prints out that"face too small for landmark detection" while the exe didn't output this information

**Comment by apchenstu** [comment]
maybe my user is in a wrong way. I have tride some images, but none of them got a consistent result.
the command I used was: `FaceLandmarkImg.exe -f imagedir`

**Comment by TadasBaltrusaitis** [comment]
Try using:
`FaceLandmarkImg.exe -fdir imagedir -wild -multi_view 1`

The results should be identical in that case, let me know if they are not.
