### ISSUE TITLE
How to get the output files?

### ISSUE THREAD

**Issue by 2236262519** [TadasBaltrusaitis/OpenFace#543]
Hi, thanks for your code!
Sorry to bother.
I know this might be a simple question, but I am still confused.
When I use the -out_dir like this:
./bin/FaceLandmarkVid -f "../samples/changLighting.wmv" -f "../samples/2015-10-15-15-14.avi" -out_dir "../samples/result"
It seems that no directory or file created.
Maybe I ignore some docs about how to use OpenFace.
Could you tell you more about this?
Thank you!

**Comment by TadasBaltrusaitis** [comment]
Hi,

FaceLandmarkVid does not produce any output, the executable is there for visualization/illustration purposes. Have a look at `FeatureExtraction` and `FaceLandmarkImg` projects, they produce output.
