### ISSUE TITLE
Output Rectangle of detected Face FaceLandmarkImg

### ISSUE THREAD

**Issue by DirkWuerdemann** [TadasBaltrusaitis/OpenFace#544]
Dear all,
I am searching for the surrounding rectangle of the faces detected in FaceLandmarkImg. How can I find them?
Is there an cmdline option the get them saved in a file or printed out ?
kind regards
Dirk

**Comment by TadasBaltrusaitis** [comment]
Do you mean the face bounding boxes that are used before landmark detection, or the bounding box of the entire face after landmark detection?

If it is the latter, you can easily compute them from the detected facial landmarks,. by looking at minimum and maximum x and y values. For more details on the output, see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

Thanks,
Tadas

**Comment by DirkWuerdemann** [comment]
Hi Tadas,
I mean the face bounding box used before landmark detection. So the first on.
Kind regards
Dirk

**Comment by DirkWuerdemann** [comment]
Hi Tadas,
I mean the face bounding box used before landmark detection. So the first one.
Kind regards
Dirk

With best regards,
Dirk Wuerdemann, PMP

Siemens AG
GS IT PS PRJ
Freyeslebenstr. 1
91058 Erlangen, Germany 
Tel.: +49 9131 18-4521
Fax: +49 9131 18-3379
Mobile: +49 173 7012213
mailto:dirk.wuerdemann@siemens.com

(sent from my iPad)

**Comment by DirkWuerdemann** [comment]
Hi Tadas,
I mean the face bounding box used before landmark detection. So the first one.
Kind regards
Dirk

 
With best regards,
Dirk Wuerdemann, PMP

Siemens AG
GS IT PS PRJ
Freyeslebenstr. 1
91058 Erlangen, Germany 
Tel.: +49 9131 18-4521
Fax: +49 9131 18-3379
Mobile: +49 173 7012213
mailto:dirk.wuerdemann@siemens.com

(sent from my iPad)

**Comment by TadasBaltrusaitis** [comment]
Hi Dirk,

This is not exposed by the API, as the refined landmarks are much more accurate than the initial bounding box. To access them you would need to change the code itself.

Thanks,
Tadas
