### ISSUE TITLE
Question about real-time use

### ISSUE THREAD

**Issue by b1t3s1z3** [TadasBaltrusaitis/OpenFace#546]
Hi all,

I have successfully implemented OpenFace to perform AU and Gaze Tracking analysis on video clips that have already been recorded.

Does anyone know if/how I can use OpenFace to perform such analysis in real-time (with, say, the goal of  having that data read by a python program), say from a live webcam video? From looking at the Issues and Wiki it seems implied by many that I can, but I can't find the documentation on how to set that up. Apologies if I have just missed that.

Thanks,

+Trevor

**Comment by JannisBush** [comment]
Hi Trevor, 

To run OpenFace live/real-time, you have to add the device option:
e.g.: ``$ ./build/bin/FeatureExtraction -device 0 -verbose``
You have to exchange the 0 by the device number of your webcam, the standard for a notebook webcam is 0. 
If you are on linux, you can get the device number of your webcam with `ls -ltrh /dev/video*`.

On my notebook, I can run the application with 20 fps.
In principle, it should be possible to pipe the output to a python program in real time and do another task with it, but I have not tested that yet.

**Comment by katoyu** [comment]
Hi,

I tried to get the device number of my webcam, but I could not understand which one is the device number.
```
$ ls -ltrh /dev/video*
crw-rw----+ 1 root video 81, 1  4月 20 17:47 /dev/video1
crw-rw----+ 1 root video 81, 0  4月 20 17:47 /dev/video0
```
I guessed that 0, 1, or 81 is the device number. But the demo didn't work.
I think my webcam is working properly.
Please tell me about this.

os: ubuntu 18.04
webcam: Logicool, UVC Camera (046d:0821)
