### ISSUE TITLE
Estimation of Action Unit

### ISSUE THREAD

**Issue by abhigoku10** [TadasBaltrusaitis/OpenFace#547]
@severin-lemaignan @ssk2 @cyberjunk @simonmssu @yorkie  Hi , first of all thanks for the wonderful code , had few queries . 

1.How is AU getting calculated?, from the paper i was able to get that the features from HOG are given to SVM classifier 
2.Can i replace HOG feature extractor with some other algorithm , if so which one would u suggest 
3. Instead of svm , can we use any other robust classifer which works on real time 
4.How landmarks are getting converted to AU 

Thanks in advance

**Comment by TadasBaltrusaitis** [comment]
Hi,

To answer your questions:
1. Yes, it is using HOG features with geometry features (a normalized version of landmark locations). These features are normalized in video by subtracting the median feature (this accounts for different people having different neutral expressions). These features are then using with an SVM classifier (to get AU presence) or an SVR regressor (to get AU intensities)
2. You could, but you would need to retrain the whole system. Any particular reason you want to replace it? I found HOG to work quite well. Of course you could replace it with more modern deep learning based features, but from my (admittedly limited) experimentation those features didn't help much and made things much slower.
3. Some as above, you could use deep learning based methods (such as CNN), but this would provide an extra computational cost.
4. Answered in 1

Thanks,
Tadas
