### ISSUE TITLE
Possibility of jpg output instead of BMP

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#548]
is there any possibility to .jpg output (with quality option, if possible) instead of .bmp output of aligned images?

Bests,
J.

**Comment by TadasBaltrusaitis** [comment]
That's a good suggestion, I will add that feature in a future release.

Thanks,
Tadas

**Comment by zhaoyongboy** [comment]
Is it possible to use the following command to output jpg or png images with pre-built binary files?
I've tried but it still outputs BMP images.
"-format_aligned <format>  output image format for aligned faces (e.g. png or jpg), any format supported by OpenCV"

**Comment by werlang** [comment]
> Is it possible to use the following command to output jpg or png images with pre-built binary files?
> I've tried but it still outputs BMP images.
> "-format_aligned output image format for aligned faces (e.g. png or jpg), any format supported by OpenCV"

I confirm this is not working. No matter if we put png or jpg after -format_align the output is still bmp

**Comment by TadasBaltrusaitis** [comment]
This should work now. Can you try with the newest version of OpenFace in master? Or the newest binaries?

If it doesn't, could you provide the exact command line input parameters.

Thanks,
Tadas

**Comment by zhaoyongboy** [comment]
> This should work now. Can you try with the newest version of OpenFace in master? Or the newest binaries?
> 
> If it doesn't, could you provide the exact command line input parameters.
> 
> Thanks,
> Tadas

I'v just tried the newest binaries, it works well now.

For the previous version, I also succeeded to make it work after compilation. 
Thanks a lot for your great work and help!

Best,
Yong
