### ISSUE TITLE
Minimum Size for Image to run FaceLandmarkImg.exe

### ISSUE THREAD

**Issue by TimothyMwiti** [TadasBaltrusaitis/OpenFace#549]
I am trying to run the executable with an image of size 48 by 48 pixels. The picture is just of a face and I can't get OpenFace to output the csv with the features. Is there a minimum size limit for it to work? That's the only reason I can think of for not getting the features.

**Comment by TadasBaltrusaitis** [comment]
Internally the minimum face size is ~25px ear-to-ear. One reason why the csv features are not produced is that the face detection step fails. Can you send me an example of a face image that fails?
