### ISSUE TITLE
openface installation

### ISSUE THREAD

**Issue by Aftab890** [TadasBaltrusaitis/OpenFace#551]
**Hello TadasBaltrusaitis.** 
I am new to machine learning and openface. I am fade up with installing Openface on windows. I have googled so much for installing openface.But failed to install. Please help me . HOw to properly install the OPENFACE on windows 10. what are proper dependencies for openface.

**Comment by TadasBaltrusaitis** [comment]
If you just want to use it and not change the code you can just download the binaries - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation#binaries

**Comment by alhashem90** [comment]
Following up same issue, 
When I open either (Open face demo.exe) or (Head Pose Live.exe) my webcam loads (640X480) Lenovo webcam, then I press select cam as it is the only option. 
Then, Enter Subject ID box appear and after few seconds the whole window close !!?
Is there a way to fix this?
Thanks for your help in advance.

**Comment by TadasBaltrusaitis** [comment]
What happens if you try running the following line from the command line (after opening it in OpenFace binary directory):
`FaceLandmarkVid.exe -device 0`

I'm wondering if OpenCV can't cope with the webcam for some reason.

Also if you connect an external webcam, are you able to see it?
