### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wuyong139** [TadasBaltrusaitis/OpenFace#554]
I'm getting the error, and how to solve it?

[ 92%] Linking CXX executable ../../bin/FaceLandmarkVid
./../lib/local/Utilities/libUtilities.a(SequenceCapture.cpp.o)：在函数‘Utilities::SequenceCapture::OpenImageSequence(std::string, float, float, float, float)’中：
SequenceCapture.cpp:(.text+0x1950)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用      (undefined reference)
SequenceCapture.cpp:(.text+0x1af4)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用    (undefined reference)
collect2: error: ld returned 1 exit status
exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/build.make:128: recipe for target 'bin/FaceLandmarkVid' failed
make[2]: *** [bin/FaceLandmarkVid] Error 1
CMakeFiles/Makefile2:366: recipe for target 'exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/all' failed
make[1]: *** [exe/FaceLandmarkVid/CMakeFiles/FaceLandmarkVid.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 95%] Linking CXX executable ../../bin/FeatureExtraction
[ 97%] Linking CXX executable ../../bin/FaceLandmarkVidMulti
../../lib/local/Utilities/libUtilities.a(SequenceCapture.cpp.o)：在函数 ‘Utilities::SequenceCapture::OpenImageSequence(std::string, float, float, float, float)’中：
SequenceCapture.cpp:(.text+0x1950)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用 (undefined reference)
SequenceCapture.cpp:(.text+0x1af4)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用(undefined reference)
collect2: error: ld returned 1 exit status
exe/FeatureExtraction/CMakeFiles/FeatureExtraction.dir/build.make:128: recipe for target 'bin/FeatureExtraction' failed
make[2]: *** [bin/FeatureExtraction] Error 1
CMakeFiles/Makefile2:482: recipe for target 'exe/FeatureExtraction/CMakeFiles/FeatureExtraction.dir/all' failed
make[1]: *** [exe/FeatureExtraction/CMakeFiles/FeatureExtraction.dir/all] Error 2
../../lib/local/Utilities/libUtilities.a(SequenceCapture.cpp.o)：在函数‘Utilities::SequenceCapture::OpenImageSequence(std::string, float, float, float, float)’中：
SequenceCapture.cpp:(.text+0x1950)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用(undefined reference)
SequenceCapture.cpp:(.text+0x1af4)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用(undefined reference)
collect2: error: ld returned 1 exit status
exe/FaceLandmarkVidMulti/CMakeFiles/FaceLandmarkVidMulti.dir/build.make:128: recipe for target 'bin/FaceLandmarkVidMulti' failed
make[2]: *** [bin/FaceLandmarkVidMulti] Error 1
CMakeFiles/Makefile2:424: recipe for target 'exe/FaceLandmarkVidMulti/CMakeFiles/FaceLandmarkVidMulti.dir/all' failed
make[1]: *** [exe/FaceLandmarkVidMulti/CMakeFiles/FaceLandmarkVidMulti.dir/all] Error 2
[100%] Linking CXX executable ../../bin/FaceLandmarkImg
../../lib/local/Utilities/libUtilities.a(ImageCapture.cpp.o)：在函数‘Utilities::ImageCapture::OpenDirectory(std::string, std::string, float, float, float, float)’中：
ImageCapture.cpp:(.text+0x2b10)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用(undefined reference)
ImageCapture.cpp:(.text+0x2c14)：对‘boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)’未定义的引用(undefined reference)
collect2: error: ld returned 1 exit status
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:128: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:308: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I have translated the Chinese character in "( )"

**Comment by wuyong139** [comment]
choose another libboost version.

**Comment by TadasBaltrusaitis** [comment]
It seems like the boost version you have on your system is causing the issues (or you do not have boost installed)
