### ISSUE TITLE
Can Centos make openface project

### ISSUE THREAD

**Issue by zys1994** [TadasBaltrusaitis/OpenFace#555]
my service is centos,can it use openface?

**Comment by kennyseyes** [comment]
If you have sudo permission it would be easier. If you don't...

**Comment by TadasBaltrusaitis** [comment]
I believe some people have managed to get it running on centos, although it is not officially supported.

Have a look at - https://github.com/TadasBaltrusaitis/OpenFace/issues/537

**Comment by zys1994** [comment]
yeah,i have succeed running with the help of https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation
