### ISSUE TITLE
Explanation of Geometric Parameters used in SVM of AU detection

### ISSUE THREAD

**Issue by singhania1408** [TadasBaltrusaitis/OpenFace#558]
Can you please provide a detailed description of geometric parameters as mentioned in your research paper:
"As geometry based features, we used the non-rigid shape parameters and landmark locations in object space inferred during CLNF model tracking (p and Φip from Equation 1). This led to a 23 + 204 = 227 dimensional vector describing geometry."
I am unable to understand the significance of these values and how these values are calculated in PDM::Calc_Params function.
If you can mention a section regarding this method in wiki then it would be really helpful for me.
Thank You

**Comment by TadasBaltrusaitis** [comment]
Hi, 

In simple terms it is a lower dimensionality representation of facial landmark locations (similar to PCA if you're familiar with it).

There is no detailed explanation of this in the wiki, but you can find a fairly detailed explanation on non-rigid shape parameters in my PhD thesis - https://www.cl.cam.ac.uk/~tb346/pub/thesis/phd_thesis.pdf (specifically chapter 4.2), it also explains how to go from landmark locations to non-rigid parameters and vice versa.
