### ISSUE TITLE
Trouble with eye 3D coordinate.

### ISSUE THREAD

**Issue by cookiekop** [TadasBaltrusaitis/OpenFace#561]
I've noticed that the coordinate of 3D eye region is in pixel and I'd like to convert it into location respect to camera in millimeter. How can I make that happen?

**Comment by TadasBaltrusaitis** [comment]
The output also provides the 3D eye region location in millimeters, please see `eye_lmk_X_0`, and `eye_lmk_Y_0`, and `eye_lmk_Z_0` etc.

The wiki stated incorrectly that they were in pixels they in fact are in millimeters (I just fixed the wiki).
