### ISSUE TITLE
Auto-Termination of webcam Feature Extraction

### ISSUE THREAD

**Issue by b1t3s1z3** [TadasBaltrusaitis/OpenFace#567]
Can anyone think of (or know of) the best way to get the FeatureExtraction command to terminate automatically when capturing live video from a webcam (by using the `-device` flag)? Right now the only way I know of to interrupt the capture/analysis is by pressing the "q" key while the live video capture is active.

I am running the Feature Extraction command via an external python program, and would like Feature Extraction to be terminated automatically in response to other things happening in the program. I have figured out how to initialize Feature Extraction automatically/remotely, but not how to stop it.

Any ideas?

**Comment by TadasBaltrusaitis** [comment]
You could always add some form of a communication protocol (e.g. TCP/IP, named pipes, or ZeroMQ) that will send a signal to FeatureExtraction for it to stop. 

Another option might be to close/disable the webcam but that doesn't sound like a great solution.

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue is still there.
