### ISSUE TITLE
 Is there any possibility to replace the tracking algorithm?

### ISSUE THREAD

**Issue by lrd8715923** [TadasBaltrusaitis/OpenFace#569]
Dear Tadas,
I noticed behaviour of DetectLandmarksInVideo() that really confuses me.I think it is very nice to detect landmark but tracking's result is bad when face movement is fast,so i want to replace tracking algorithm with KCF,and i have KCF's API which need to import before frame's boundingbox and output current frame's boundingbox,and use this boundingbox to detect landmark.so i want to replace with it,but i don't konw how to replace it in DetectLandmarksInVideo().Please give some instructions.
Best greetings from Liruodao.

**Comment by TadasBaltrusaitis** [comment]
Hi,

OpenFace doesn't really do "tracking" as such, it instead does landmark detection in subsequent frames but with initialization from previous best location and in a smaller region of interest. As you observe this sometimes causes issues particularly with very fast face motions.

I'm not very familiar with KCF tracking algorithm, but it could be that using a tracking algorithm instead (or maybe even in addition) would help in such cases. You could use it to shift and rotate the initialization used by `DetectLandmarksInVideo()`. In fact there is a very small tracking step in that call - `			CorrectGlobalParametersVideo(grayscale_image, clnf_model, params);` that performs simple template matching based tracking and could be a good place to introduce KCF steps into.


You're very welcomeFrom my experience the tracking isn't t

**Comment by lrd8715923** [comment]
Dear Tadas,
I found the CorrectGlobalParametersVideo(grayscale_image, clnf_model, params) and understand it,it use match template to do track ,but i don't successfully introduce KCF in it.I just want to replace old boundingbox with new boundingbox(from KCF) and use new boundingbox to detect landmark.But i without found how to import boundingbox to detect landmark in DetectLandmarksInVideo().Please give some instructions again,thank you again.

**Comment by TadasBaltrusaitis** [comment]
You should have a look at the `FaceLandmarkVidMulti.cpp` file for an example how face bounding box can be provided to the landmark detection algorithm (it requires turning off internal face detection through setting `det_params.reinit_video_every = -1;`)

You can then pass the face detections using something like:
`detection_success = LandmarkDetector::DetectLandmarksInVideo(rgb_image, face_detections[detection_ind], face_models[model], det_parameters[model], grayscale_image);`
