### ISSUE TITLE
Question about the datasets to train PDM and patch experts

### ISSUE THREAD

**Issue by CerrieJ** [TadasBaltrusaitis/OpenFace#57]
Hi Tadas,
    What the relevance betwen the dataset to train the PDM and the dataset to train patch experts ?  They must be the same dataset or must be different?

**Comment by TadasBaltrusaitis** [comment]
It depends, as long as the landmarks are the same they do not have to come from the same datasets. I trained the PDM on 300W datasets, but used an extra dataset in addition to 300W ones, CMU Multi-PIE, for patch expert training.

**Comment by CerrieJ** [comment]
It seems you use less pictures to trian PDM than to train patch expert. Can you explain me the reason why you do like this?

**Comment by TadasBaltrusaitis** [comment]
The PDM trained on the 300W datasets ended up being more accurate in terms of head pose estimation and landmark detection so I use it. For patch experts using multiple datasets led to the best results, also as 300W datasets do not contain many profile faces I needed to use Multi-PIE to train profile patch experts.
