### ISSUE TITLE
need to optimized or bug fix?

### ISSUE THREAD

**Issue by berli** [TadasBaltrusaitis/OpenFace#570]
[
![gg2](https://user-images.githubusercontent.com/3395335/45861419-fe13e800-bd9e-11e8-9011-4f350fc03dfe.jpg)
](url)

**Comment by berli** [comment]
this is the source image
![gg2](https://user-images.githubusercontent.com/3395335/45861459-39161b80-bd9f-11e8-9f91-06b53cc13503.jpg)

**Comment by TadasBaltrusaitis** [comment]
Hi,

I just checked the image and it is not a bug. Have a look at the confidence values in the output file, the fake face will have a really low confidence.

The initial face detection algorithm has a false posititve face detection, so the rest of the pipeline processes that area, but by looking at confidence values you can filter out less reliable predictions.

-Tadsa
