### ISSUE TITLE
Typo in Citation

### ISSUE THREAD

**Issue by taoyudong** [TadasBaltrusaitis/OpenFace#571]
**Describe the bug**
There is a minor typo in the citation section of README.md. An additional period shows in the conference name of the paper "Rendering of Eyes for Eye-Shape Registration and Gaze Estimation".

**To Reproduce**
As you can see in the README.md file on line 82.

**Expected behavior**
To remove the period

**Screenshots**
![screen shot 2018-09-22 at 11 27 51 pm](https://user-images.githubusercontent.com/24845727/45923854-2d217b00-bebf-11e8-81ad-e7b07f64fd1e.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by TadasBaltrusaitis** [comment]
Thanks for pointing it out!
