### ISSUE TITLE
Is there an openface written by C++ released? 

### ISSUE THREAD

**Issue by hpq8085** [TadasBaltrusaitis/OpenFace#572]
Hi Tadas,
  I want to combine OpenFace with Qt, but when I use Python C++ API, it returns some unexpected issues...
  I am stumped now,so I turn you for help. Is there an openface written by C++ released?

**Comment by TadasBaltrusaitis** [comment]
Hi,

Currently there is no Python C++ API for OpenFace, it is all written in C++ and has a C# interface (there is also a Matlab implementation). Are you thinking of a different OpenFace project - https://cmusatyalab.github.io/openface/?
