### ISSUE TITLE
Detection of assimmetry?

### ISSUE THREAD

**Issue by JavierRojo** [TadasBaltrusaitis/OpenFace#574]
Dear Tadas,

I'm currently in a project aiming to detect assimmetry in differernt faces. When using OpenFace, I've noticed that landmark position gets 'symmetrized', not adjusting to the actual facial anatomy (See image below).

![sim_of](https://user-images.githubusercontent.com/22508328/46083185-220d6a00-c1a1-11e8-8be1-1b4854b10ce6.jpg)

Is there any way to avoid this? I'm quite lost in this regard so any help would be appreciated.

Thanks a lot, and congratulations for such a wonderful work.

**Comment by TadasBaltrusaitis** [comment]
Hi.

There is no separate "symmetrization" step as such. This is a side effect of most of the training data used containing symmetric expressions and mostly symmetric faces. Unfortunately, there's not an easy fix for this without extra data collection that contains more assymetric expressions.

Thanks,
Tadas
