### ISSUE TITLE
Determine occlusion

### ISSUE THREAD

**Issue by ChrizzyM87** [TadasBaltrusaitis/OpenFace#575]
Dear Tadas,
do have a recommendation how to determine the occlusion of a face?
I ask because I need to exclude faces, where e.G. a hand occludes half of the face. (by the way: really nice that the landmark tracking works anyway!)
Thanks in advance && best greetings,
Christoph

**Comment by TadasBaltrusaitis** [comment]
Hi,

There are several ways, and there's some literature on the topic, most of them require extra training data or reasonably complex implementations (e.g. https://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Wu_Robust_Facial_Landmark_ICCV_2015_paper.pdf., http://research.cs.rutgers.edu/~xiangyu/paper/CoR_Occlusion_Robust_Face_Alignment.pdf. )

Another way to do this (although I don't know how accurate it will be), is to use internal confidence for each landmark from OpenFace. Have a look at:
`face_model.landmark_likelihoods`

You would need to determine an appropriate threshold for each landmark by experimentation (higher values are higher confidence in detection of each). So in your case you could discard images in which over a certain number of landmarks are below their confidence levels.

Thanks,
Tadas
