### ISSUE TITLE
Question for eyegaze location

### ISSUE THREAD

**Issue by yj7679** [TadasBaltrusaitis/OpenFace#577]
hello Tadas. I read your source impressively. But i' m curious about eye gaze point.
I install openface in ubuntu. I want to use x, y coordinate location in eye gaze and sort by angle.
so, how can i find it and extract location? Please give some instructions. Thank you.

**Comment by yj7679** [comment]
and I only use FaceLandmarkVid code.

**Comment by TadasBaltrusaitis** [comment]
What do you mean by eye gaze point? Do you want to estimate the eye gaze location on the screen? Or are you interested in gaze angle?

Currently OpenFace provides the gaze vectors and gaze angles. 

However, to extract eye gaze location on a screen you would need to know the camera location with respect to the screen (and the screen size). Further, it would require person specific calibration for better results. OpenFace does not support these features, but they could be added with some effort.

**Comment by yj7679** [comment]
I fix location of camera on top of screen. and I want to use eye gaze angle for output.
output mean where user is looking at quadrant of screen.
How can i get user's direction of eye gaze angle on real time?
And I want to output the difference between the coordinate values  of the center of the iris and the center of eye.

**Comment by TadasBaltrusaitis** [comment]
Have a look at `FeatureExtraction.cpp`, specifically the call to:
    gazeAngle = GazeAnalysis::GetGazeAngle(gazeDirection0, gazeDirection1);

Which estimates the gaze angle with respect to the camera, you should be able to roughly estimate quadrants of the screen with it (or at least the left/right sides)

For your second point the gaze vector is roughly what you are looking for.

**Comment by yj7679** [comment]
Does the gaze vector follow the camera coordinate system?
And May I ask if there is a paper to refer to?

**Comment by TadasBaltrusaitis** [comment]
Yes it is in the camera coordinate system.

You can find the eye gaze estimation description in the following paper - https://www.cl.cam.ac.uk/~tb346/pub/papers/wacv2016.pdf

**Comment by yj7679** [comment]
Thank you so much. I'm sorry to ask so many questions.
But I have question in coordinate of eye point.
I want to get all of 6-point eyeball coordination as 'Point3f'. How can I get ?
In this capture, the red one is point of eyeball.

![screenshot 2018-10-30 21 04 20](https://user-images.githubusercontent.com/41945374/47716933-82536800-dc87-11e8-9f80-958f786a50e2.png)

**Comment by TadasBaltrusaitis** [comment]
Hi, have a look at the following API calls - https://github.com/TadasBaltrusaitis/OpenFace/wiki/API-calls#landmark-results

Alternatively you can extract them from the output csv file.

The landmark indices can be found here:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

**Comment by yj7679** [comment]
thank you for your advice tadas, but i have another question. im very wondering can we modify the openface code using visual studio 2015 in window10? we already modified the code but there is no change. please let me know about this.

**Comment by TadasBaltrusaitis** [comment]
Yes, you can definitely use Visual Studio 2015 on Windows 10 to work on OpenFace, that is the environment I use myself.
