### ISSUE TITLE
Getting 2D->3D R & T

### ISSUE THREAD

**Issue by alasin** [TadasBaltrusaitis/OpenFace#579]
Hi,

Is it possible to write the 2D landmarks as X_2d = KRT X_3d? Is it possible to access the R, T matrices from the code?

**Comment by TadasBaltrusaitis** [comment]
It is, look at the `LandmarkDetector::GetPose` function which uses solvePnP to determine the translation and rotation of the face given a camera matrix. X_2d, and X_3d. It does not construct the matrices directly, but that shouldn't be difficult

-Tadas

**Comment by alasin** [comment]
Thanks a lot. Could I just use them as is? Assuming K = [fx 0 cx, 0 fy, cy, 0 0 1] and using R and T from the above function? I tried this for a couple of 3d points and am getting considerable difference in the obtained 2d points.

**Comment by TadasBaltrusaitis** [comment]
Yous should be able to. However, you should first confirm that mapping from 3D to 2D is accurate. While it won't be identical as the method is solving a least squares problem, it should be very close.

**Comment by alasin** [comment]
I did. That's where I am getting a considerable difference (around 50 pixels at times). And the 2D landmarks seem pretty good to start so that's not a concern.

**Comment by TadasBaltrusaitis** [comment]
The difference should be within several pixels (depending on image resolution). Maybe there's an issue between converting rotation angles to rotation matrix?

**Comment by alasin** [comment]
Hi,

Thanks for the previous suggestions. Another question I wanted to ask was the difference between `LandmarkDetector::GetPose` and `LandmarkDetector::GetPoseWRTCamera`. What should we use to get the extrinsics in case 1) When head is still and camera is moving. case 2)When head is moving and camera is still.

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Most likely you want `GetPose` (`GetPoseWRTCamera` is useful when testing if the user is facing the camera, e.g. the rotations will be close to 0 if they are), while `GetPose` just places camera at the origin and estimates the extrinsics.
