### ISSUE TITLE
Unable to save output video file 

### ISSUE THREAD

**Issue by jjd10** [TadasBaltrusaitis/OpenFace#58]
While using the FaceLandmarkVid on a video stream captured by a webcam, I am unable to save the output file with -ov option. I tried writing the output with using a video file as an input but it results in similar error.

```
** (FaceLandmarkVid:4917): CRITICAL **: gst_missing_encoder_message_new: assertion 'gst_caps_is_fixed (encode_caps)' failed

(FaceLandmarkVid:4917): GStreamer-CRITICAL **: gst_element_post_message: assertion 'message != NULL' failed
OpenCV Error: Unspecified error (GStreamer: cannot link elements
) in CvVideoWriter_GStreamer::open, file /home/h2zhen/Downloads/opencv-3.1.0/modules/videoio/src/cap_gstreamer.cpp, line 1466
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/h2zhen/Downloads/opencv-3.1.0/modules/videoio/src/cap_gstreamer.cpp:1466: error: (-2) GStreamer: cannot link elements
 in function CvVideoWriter_GStreamer::open

Aborted (core dumped)

```

Just to make sure that the issue isn't related to openCV installation or codec related problem,  I wrote a short script to capture a video using webcam and write it using fourcc codec and it works perfectly fine and saves the video.

It would be great if you could please help fixing this issue.

Thanks!

**Comment by TadasBaltrusaitis** [comment]
That's odd, as the error seems to be indicating a codec error. Can you try using a different fourcc codec when outputing the video in the C++ code? Maybe the video size is not supported by the codec etc?

**Comment by Gijom** [comment]
Hi, I am using your program on a CentOS7 machine (Linux) and it does its job fine. Thanks for this great tool. However I also ran in the problem mentioned above and indeed, changing the output codec to H264 solved this issue. I thus changed the code to handle a -oc (output codec) option which takes the FOURCC as a parameter. It also outputs a warning if the VideoWriter is not created correctly, with a mention of the -oc option. I will make a pull request in the case you are interested.

**Comment by TadasBaltrusaitis** [comment]
Awesome, thanks for the feature, will review it, document it and add it to the code!

**Comment by TengFeiHan0** [comment]
@TadasBaltrusaitis Hi，I have the same question. if possible, could you tell me how to fix this problem?

**Comment by TadasBaltrusaitis** [comment]
What error message are you getting and have you tried using different output codecs?
