### ISSUE TITLE
"Segmentation fault (core dumped)" error 

### ISSUE THREAD

**Issue by wtomin** [TadasBaltrusaitis/OpenFace#582]
While I tried to extract features from example video, I expected to see the feature csv file, but instead there was an error: Segmentation fault (core dumped)

I first cmake using "cmake -D CMAKE_BUILD_TYPE=RELEASE CMAKE_CXX_FLAGS="-std=c++11" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11" ..", this is what I got:
![cmake](https://user-images.githubusercontent.com/33117903/46571633-f6615f80-c9aa-11e8-97ee-184707330f94.png)
As you can see, I use OpenCV 3.3, dlib 19.13. Both of them are built from source. When I cmake OpenCV3.3, I used "cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_CUDA=OFF -D BUILD_TIFF=ON .."

Then make is successful, I encountered no error. But when I tried to extract features from video:
![aa](https://user-images.githubusercontent.com/33117903/46571670-b484e900-c9ab-11e8-8047-49cb12bd43f2.png)

I assume this problem is caused by OpenCV3.3, so I changed it to OpenCV3.4. I got the same error.
**Desktop (please complete the following information):**
 - OS: [ubuntu 16.04]
 - Compiler [GCC]

**Comment by TadasBaltrusaitis** [comment]
Hi,

Is the same issue present without the -verbose flag?

What about other executables, do they manage to run?

**Comment by wtomin** [comment]
Thanks for your reply. I tested the command without  -verbose flag, and other executables. Unfortunately, I think all of them failed. No output files founded. The screen shots are listed blow.
![test_1](https://user-images.githubusercontent.com/33117903/46648274-f63dab80-cbc6-11e8-95b5-b5d6a2bf7649.png)
![test_2](https://user-images.githubusercontent.com/33117903/46648288-13727a00-cbc7-11e8-8614-7c3323e652ce.png)
![test_3](https://user-images.githubusercontent.com/33117903/46648304-22592c80-cbc7-11e8-94eb-3f27dfc6e028.png)
![test_4](https://user-images.githubusercontent.com/33117903/46648307-25ecb380-cbc7-11e8-8c2a-56807dc21d7a.png)

**Comment by wtomin** [comment]
I execute these lines
```     
    gdb FeatureExtraction 
     r -f "../samples/default.wmv"
```
I guess the error appeared at 2951 line. 
```
...
Reading the landmark validation module....Done
Reading the AU analysis module from: AU_predictors/main_dynamic_svms.txt
Reading the AU predictors from: AU_predictors/AU_all_best.txt... Done
Reading the PDM from: AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:AU_predictors/tris_68_full.txt... Done
Attempting to read from file: ../samples/default.wmv

Thread 1 "FeatureExtracti" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xffffffffffffffff) at malloc.c:2951
2951	malloc.c: No such file or directory.
```
I am not familiar with gdb. Hope I did it right.

**Comment by wtomin** [comment]
BTW, I run /matlab_runners/Demos/run_test_img_seq.m in matlab. It worked. The outputs are aligned faces images, csv files with features, hog files. HOWEVER, the three videos 'image_sequence.avi', 'image_sequence_16bit.avi', 'image_sequence_gray.avi' are empty files.

**Comment by TadasBaltrusaitis** [comment]
Also it seems like FaceLandmarkImg worked? Did it produce any output?

It might be the video writing that is causing issues, can you try calling the method with
`./FeatureExtraction -f "../../samples/default.wmv" -2Dfp`

This will only output detected landmark points without video output.

**Comment by wtomin** [comment]
Hi, sorry for the delay. I executed this line:
```
./bin/FaceLandmarkImg -fdir "../samples/image_sequence" -out_dir "../samples/output"
```
I think it worked. In "../samples/output" directory, there are aligned&cropped faces, feature files(csv), hog files and detail files(txt). 

But when I call this line:
```
./FeatureExtraction -f "../../samples/default.wmv" -2Dfp
```
It still raised the same error:
```
... 
Attempting to read from file: ../../samples/default.wmv
Segmentation fault (core dumped)
```
I start to think, maybe the problem exists in both reading and writing video files? Any suggestions?

**Comment by wtomin** [comment]
There's more information about debugging with gdb by ` gdb FeatureExtraction 
     r -f "../samples/default.wmv"`. I hope it is helpful.

```
...
Reading the landmark validation module....Done
Reading the AU analysis module from: AU_predictors/main_dynamic_svms.txt
Reading the AU predictors from: AU_predictors/AU_all_best.txt... Done
Reading the PDM from: AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:AU_predictors/tris_68_full.txt... Done
Attempting to read from file: ../samples/default.wmv

Thread 1 "FeatureExtracti" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xffffffffffffffff) at malloc.c:2951
2951	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0xffffffffffffffff) at malloc.c:2951
#1  0x00007ffff5579e49 in av_packet_free_side_data ()
   from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#2  0x00007ffff557adbd in av_packet_unref ()
   from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#3  0x00000000006fc617 in CvCapture_FFMPEG::close() ()
#4  0x00000000006fc838 in CvCapture_FFMPEG::open(char const*) ()
#5  0x00000000006fcb54 in cvCreateFileCapture_FFMPEG ()
#6  0x000000000070085f in cvCreateFileCapture_FFMPEG_proxy(char const*) ()
#7  0x00000000006dc26d in cvCreateFileCaptureWithPreference ()
#8  0x00000000006dce18 in cv::VideoCapture::open(cv::String const&) ()
#9  0x000000000062e69d in Utilities::SequenceCapture::OpenVideoFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, float, float, float) ()
#10 0x0000000000630bbb in Utilities::SequenceCapture::Open(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#11 0x00000000005016a8 in main ()
(gdb) l
2946	in malloc.c
```

**Comment by TadasBaltrusaitis** [comment]
It seems like an ffmpeg issue (which OpenCV uses for dealing with videos), can you try reinstalling ffmpeg or recompiling OpenCV with ffmpeg?

**Comment by TadasBaltrusaitis** [comment]
Have you managed to resolve this?

Closing for now, please re-open if the issue still persists.
