### ISSUE TITLE
Question regarding FACS output and video option

### ISSUE THREAD

**Issue by blakeob** [TadasBaltrusaitis/OpenFace#584]
Sometimes I find the binary FACS detector e.g. "AU01_c" as a 0 but the intensity e.g. "AU01_r" output is detected at a small level. How can this be interpreted?

For FACS video analysis, is there an option to select specific timeframes for the detector to run within a given video? For example, if I want to analyze 15 seconds of a 30 second video.

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

There is no guarantee of consistency between occurrence and intensity predictions, this is due to different models and training data used, see the following note for details - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units#intensity-and-presence-of-aus
