### ISSUE TITLE
Landmark Position[2D/3D]

### ISSUE THREAD

**Issue by cogito666** [TadasBaltrusaitis/OpenFace#585]
Hello. Thanks for your sharing your remarkable work.
I know you much be so busy with your research. So that I want to get some high-level concept to advise.

I am using your program for a research project associated with mouth movement analysis.
So I need to get each landmark position information available from the .csv file that your program output. But there's a problem to get the exact position in the 2D plane.

When I see the output video which overlay all the landmarks and estimated head-position, I could see all landmarks are fit so well. But when I put all landmarks on MATLAB based on 2D position information in CVS file, it's not fitting well.

Here's my pipeline.
1) Extract all 2D landmarks position ( x_(), y_() from CSV file).
2) 2D translation based on (pose_Tx, pose_Ty from CSV).
3) 2D rotation based on (pose_Rz).

IDK, maybe I am wrong. To get find positions of all landmarks in 2D and 3D, which pipeline you suggest?
I want to get it as accurate as possible.

Thanks.
Dohyeong.

**Comment by TadasBaltrusaitis** [comment]
Hi, thanks for taking an interest in OpenFace.

The 2D landmarks x_() and y_() are already in the image space, so you do not need to transform them in any way to visualize them. The pose_T and pose_R values can be used to project the 3D landmark locations to 2D.

There's an example of how to process data output by OpenFace in Matlab in `matlab_runners\Demos\feature_extraction_demo_vid.m`, it includes drawing landmarks on images as well.

Thanks,
Tadas
