### ISSUE TITLE
Some problem about LandmarkDetectorUtils and clnf_model.detected_landmarks

### ISSUE THREAD

**Issue by zxc586794azxc** [TadasBaltrusaitis/OpenFace#586]
hellow, I want to ask two auestions.

First, In LandmarkDetectorUtils, the Draw part, there is a part about "int n = shape2D.rows/2; ", how can I input to obtain the mouth area? 

Second, In "clnf_model.detected_landmarks" , how can I input to obtain mouth area? 

thanks!

**Comment by TadasBaltrusaitis** [comment]
You can find the exact definition of landmark IDs here:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

Thanks,
Tadas
