### ISSUE TITLE
Is there is a way to obtain the cropped face images with background？

### ISSUE THREAD

**Issue by RegisWu** [TadasBaltrusaitis/OpenFace#587]
Dear Baltrusaitis,

I am working on a face-related project. We want to obtain the face alignment images (a.k.a. face registration images, with eyes at the same location after transformation), but not want to crop out all the background information. 

May I know whether there is a way to output the aligned face images with environmental information?

Otherwise, after obtaining the facial landmark, there should be a method to align the face image based on that, could you briefly introduce the algorithms you used in the project? It would be better if there is a paper about this.

Thank you very much.

**Comment by TadasBaltrusaitis** [comment]
You can specify the `-nomask` flag, have a look here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#similarity-aligned-face-images-and-hog-binary-files

Is this what you wanted?

**Comment by RegisWu** [comment]
> You can specify the `-nomask` flag, have a look here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#similarity-aligned-face-images-and-hog-binary-files
> 
> Is this what you wanted?

Thanks for your quick reply.

Absolutely this is what I want. But may I know more details about the face alignment algorithm? For instance, assuming that we have obtained the facial landmarks of a rotated face image, how can we transform the images to make the eyes located on specific location (or make eyes on a horizontal line with customized distance)? 

Could you please give me some cues about it? I tried searching for this but have not found satisfying results yet. Or may I know the settings of your algorithms? So that I can create another API based on your results for further processing.

Again, thank you very much.

**Comment by TadasBaltrusaitis** [comment]
The method is fairly basic, so there's not paper that describes the algorithm as such. What is happening is a similarity transform (basically affine transformation without shearing https://uk.mathworks.com/discovery/affine-transformation.html)

The transformation is computed from the detected 2D landmarks to a set of "canonical" landmarks in the aligned image which are constructed from neutral expression of an average face. You can find the exact implementation details in `AlignFace` and `AlignFaceMask` functions in `lib\local\FaceAnalyser\src\Face_utils.cpp`

The transform is briefly described in 4.B section of this paper - https://www.cl.cam.ac.uk/~tb346/pub/papers/FG2015_camera_ready.pdf

**Comment by RegisWu** [comment]
I see. Thank you very much.
