### ISSUE TITLE
Eye Landmark is not accyuracy

### ISSUE THREAD

**Issue by tjusxh** [TadasBaltrusaitis/OpenFace#588]
Hi, Thanks for your awesome project. I found one small issue. When I close eyes . The landmarks of eye are still open large. (point 38 and point 42 or point 44 and point 48). If give me some suggestion to adjust the model. Thanks for your help.

**Comment by TadasBaltrusaitis** [comment]
Yes, I'm aware of this issue. Unfortunately, there is not an easy fix that can be applied to it. It needs more training data with people that have eyes closed.
