### ISSUE TITLE
Could not load the landmark detector

### ISSUE THREAD

**Issue by FrancisLeon** [TadasBaltrusaitis/OpenFace#591]
**Describe the bug**
After I run the ./install.sh and install the openface and test
```
./bin/FaceLandmarkVid -f "../samples/changeLighting.wmv" -f "../samples/2015-10-15-15-14.avi"
```
error:
```
ERROR: Could not load the landmark detector
```
happens

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Version [14.0.4]
 - Compiler [gcc 5.4.0]

**Comment by FrancisLeon** [comment]
Sure, I did. However, I think it's due to anaconda. After I uninstall it and re-install following your instructions, 
it works. Thanks.

**Comment by JACKHAHA363** [comment]
Could you be specific on what did you do? I have the same issue with an isolate conda env.

**Comment by maqduni** [comment]
> Could you be specific on what did you do? I have the same issue with an isolate conda env.

Try downloading the models first and then running `make` in the build folder.
