### ISSUE TITLE
Implementation of API in sending position data to third party app

### ISSUE THREAD

**Issue by floatingworld3** [TadasBaltrusaitis/OpenFace#592]
I am attempting to create a websocket in order to  send position data of vertices  to my 3d app...
I am using this implementation of your API:

vectors: brfv4.__brf_get_opticalFlowPoints () {
								return {
									x: Math.round(point[0]),
									y: Math.round(point[1])
								}

(see attached html)
I am using the js version
What should follow brfv4.__brf_get_opticalFlowPoints to return the set of vectors?
[html.txt](https://github.com/TadasBaltrusaitis/OpenFace/files/2512683/html.txt)

**Comment by TadasBaltrusaitis** [comment]
Are you posting on the wrong project? There is no js version of OpenFace API
