### ISSUE TITLE
Process to maximize 3D tracking data

### ISSUE THREAD

**Issue by Rileyjs** [TadasBaltrusaitis/OpenFace#595]
Thanks for this amazing tool! I have a couple questions to make sure I understand how to best use it.

For the 3D location marking, the distance is relative to the camera? So, if my model is 1.4 meters away I should expect to see Z at around 1,400?

I’ve been unable to find my cameras focal length and optical centre online, so my plan is to use the opencv calibration tool. https://docs.opencv.org/3.1.0/dc/dbb/tutorial_py_calibration.html 
Once I’ve done that I can take the matrix that calibrateCamera returns and plug those values in for fx, fy, cx and cy?  To maximize accuracy of head pose estimation, those are the only parameters I need to worry about correct?

Thanks again for publishing all this code!

**Comment by TadasBaltrusaitis** [comment]
Thanks for taking an interest in OpenFace, to answer your questions:
1. Yes, the distance is relative to the camera.
2. Yes you can directly plug the values for fx, fy, cx, and cy and they are the only parameters you need to worry about, further fx and fy are much more important that cx and cy (which would most likely not affect the accuracy that much and could be estimated as the image center).
3. Further, you could also un-distort the image using the estimates of camera intrinsics, but this would likely not affect results much unless you have severe distortion.
