### ISSUE TITLE
Video input

### ISSUE THREAD

**Issue by floatingworld3** [TadasBaltrusaitis/OpenFace#596]
Is it possible to use a video session of a face performance instead of a web cam? If so, where can I find the  the line of code that can do this? thanks for your time

**Comment by TadasBaltrusaitis** [comment]
Yes, have a look at - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

You can use the `-f` command line flag and provide the video file or image to be processed.
