### ISSUE TITLE
AUs estimate question

### ISSUE THREAD

**Issue by PCH10507323** [TadasBaltrusaitis/OpenFace#599]
Hi, thanks for your project, but I have a question here,
the question is why I use these two command for the same image but get different result for the AUs estimate
./bin/FeatureExtraction -verbose -f "000.jpeg" -out_dir "./output"
./bin/FaceLandmarkImg -f "000.jpeg" -out_dir "./output"

**Comment by TadasBaltrusaitis** [comment]
Hi,

`FeatureExtraction` is optimized for face tracking in videos, while `FaceLandmarkImg` is intended for images, this means that they will use different prediction models and data normalization, hence leading to possibly different results.

See - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#example-uses for more details
