### ISSUE TITLE
Could the code run by opencv in linux?

### ISSUE THREAD

**Issue by ShangLpose** [TadasBaltrusaitis/OpenFace#6]
Could the code run by opencv in linux?

**Comment by TadasBaltrusaitis** [comment]
Yes it can, for instructions please see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

Instructions for Ubuntu 15 coming soon.

**Comment by ShangLpose** [comment]
Thank you very much！And I have another question .
When I run the ''OpenFace.exe'' in computer ,I could see the Orientation in ''Geometry'' window. What can I do to see the Orientation in Linux ?

**Comment by TadasBaltrusaitis** [comment]
At the moment there is no GUI for the Linux version, only for Windows. You would need to visualize that yourself.

Thanks,
Tadas

**Comment by chiragraman** [comment]
Hello,

If it helps, installation instructions for Ubuntu 15.10 are now live on the wiki.
