### ISSUE TITLE
Duplicated landmark mapping in 'main_clnf_general.txt'

### ISSUE THREAD

**Issue by cyberjunk** [TadasBaltrusaitis/OpenFace#60]
Hey,

the file 'main_clnf_general.txt' seems to contain a duplicated mapping for main and inner landmarks:
https://github.com/TadasBaltrusaitis/OpenFace/blob/master/lib/local/LandmarkDetector/model/main_clnf_general.txt#L2

The mappings go from 17:0 to 67:50 and then start all over again with the same ones?
Is there any reason behind this? The others (e.g. eyes) don't have this duplicated mapping.

Thanks

**Comment by TadasBaltrusaitis** [comment]
Thanks for spotting this, this should definitely not be there, I'm going to fix that for the next version.
