### ISSUE TITLE
FaceLandmarkImg with Matlab. Error : "symbol lookup error" and "undefined symbol"

### ISSUE THREAD

**Issue by ccsvcckpz** [TadasBaltrusaitis/OpenFace#605]
Hi !

As I'm runing the demo for FaceLandmarkImg with Matlab 2016b (on Ubuntu 16.04), Matlab opens the model, loads it, reads a lot of things and then I get this: 
`Starting tracking
/home/usr/Documents/OpenFace/build/bin/FaceLandmarkImg: symbol lookup error: /home/usr/Documents/OpenFace/build/bin/FaceLandmarkImg: undefined symbol: _ZN3tbb8internal24concurrent_queue_base_v818internal_push_moveEPKv` 
(I replaced my name by usr).
And the script stops.

Do you have any idea of what could be the problem ?

Thanks in advance !

**Comment by ccsvcckpz** [comment]
Yes I have it installed (the latest version) but matlab may be unable to find it (I don't know).
I tried to preload matlab with it (as I did successfully for libstdc++.so.6 and libtiff.so.5) but it didn't work.
Do you have any other idea ?

**Comment by TadasBaltrusaitis** [comment]
Does the executable work outside of Matlab?

**Comment by ccsvcckpz** [comment]
I don't think so. I did this on my terminal: `~/Documents/OpenFace/build$ ./bin/FaceLandmarkImg -fdir "../samples/" -wild` as I saw [here](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation) 

And this was returned: `Attempting to read from directory: ../samples/
Loading the model
Reading the landmark detector/tracker from: ./bin/model/main_ceclm_general.txt
Reading the landmark detector module from: ./bin/model/cen_general.txt
Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.35_of.dat....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.50_of.dat....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_1.00_of.dat....Done
Reading part based module....left_eye_28
Reading the landmark detector/tracker from: ./bin/model/model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: ./bin/model/model_eye/clnf_left_synth.txt
Reading the PDM module from: ./bin/model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading part based module....right_eye_28
Reading the landmark detector/tracker from: ./bin/model/model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: ./bin/model/model_eye/clnf_right_synth.txt
Reading the PDM module from: ./bin/model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading the landmark validation module....Done
Model loaded
Reading the AU analysis module from: ./bin/AU_predictors/main_static_svms.txt
Reading the AU predictors from: ./bin/AU_predictors/AU_all_static.txt... Done
Reading the PDM from: ./bin/AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:./bin/AU_predictors/tris_68_full.txt... Done
Reading the MTCNN face detector from: ./bin/model/mtcnn_detector/MTCNN_detector.txt
Reading the PNet module from: ./bin/model/mtcnn_detector/PNet.dat
Reading the RNet module from: ./bin/model/mtcnn_detector/RNet.dat
Reading the ONet module from: ./bin/model/mtcnn_detector/ONet.dat
Starting tracking`

I did not find the results...

**Comment by ccsvcckpz** [comment]
It may have worked better with: 
`~/Documents/OpenFace/build$ ./bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi`

Because I received this (after the long list of "Reading ..."):
`Device or file opened
WARNING: using a AU detection in multiple face mode, it might not be as accurate and is experimental
Starting tracking
0% 10% 20% 30% 40% 50% Face too small for landmark detection
60% 70% 80% 90% 100% 
Closing output recorder
Closing input reader
Closed successfully
`

**Comment by TadasBaltrusaitis** [comment]
The results should be in `./processed/` folder, in the directory you ran from. You can also specify `-f output_location` to specify where to output the results.

But from the log it seems like the tracking worked, it seems like the issue is when launching through Matlab that fails to find the relevant libraries.

**Comment by ccsvcckpz** [comment]
Thanks!
Yes, you're right, it worked (both FaceLandmarkImg and FaceLandmarkVidMulti)! I found the results in ./processed/ as you said.

I think it's exactly the right problem with Matlab: it is unable to find the relevant libraries... Do you have any idea on how I could fix it?

**Comment by ccsvcckpz** [comment]
I finally have the solution!
I had a problem with other libraries before. So I found the library related to tbb (libtbb.so) and I launched matlab with this library (and the 2 others of my previous problem):
`LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libtiff.so.5 /usr/lib/x86_64-linux-gnu/libtbb.so" ./matlab`
And the demo worked with Matlab!
