### ISSUE TITLE
Is there an easier way to run on MAC?

### ISSUE THREAD

**Issue by Andy-ZYA** [TadasBaltrusaitis/OpenFace#606]
**Describe the bug**
Seems it take a lot of work to install and run OpenFace on Mac. Is there an easier way to set up and run OpenFace on Mac? 

Thanks

**Comment by TadasBaltrusaitis** [comment]
This does not really sound like a bug?

It isn't that difficult if you're already using homebrew though. What step are the issue?

**Comment by Andy-ZYA** [comment]
The error that I had is posted here https://github.com/TadasBaltrusaitis/OpenFace/issues/607#issue-379887896

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue is still there, the installation has been simplified..
