### ISSUE TITLE
Build Error in Mac

### ISSUE THREAD

**Issue by Andy-ZYA** [TadasBaltrusaitis/OpenFace#607]
Hi guys,

I got this error when following the mac installation wiki.

`[  2%] Building CXX object lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o
In file included from /Users/zhouyuan/OpenFace-master/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
In file included from /Users/zhouyuan/OpenFace-master/lib/local/LandmarkDetector/include/stdafx.h:19:
In file included from /usr/local/include/opencv2/core/core.hpp:48:
In file included from /usr/local/include/opencv2/core.hpp:54:
In file included from /usr/local/include/opencv2/core/base.hpp:58:
In file included from /usr/local/include/opencv2/core/cvstd.hpp:62:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: 
      no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: 
      no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error: 
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/math.h:749:12: note: 
      'finite' declared here
extern int finite(double)
           ^
In file included from /Users/zhouyuan/OpenFace-master/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
In file included from /Users/zhouyuan/OpenFace-master/lib/local/LandmarkDetector/include/stdafx.h:19:
In file included from /usr/local/include/opencv2/core/core.hpp:48:
In file included from /usr/local/include/opencv2/core.hpp:54:
In file included from /usr/local/include/opencv2/core/base.hpp:58:
In file included from /usr/local/include/opencv2/core/cvstd.hpp:62:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:316:9: error: 
      no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:317:9: error: 
      no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: 
      no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:9: error: 
      no member named 'isgreater' in the global namespace
using ::isgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:9: error: 
      no member named 'isgreaterequal' in the global namespace
using ::isgreaterequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: 
      no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: 
      no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: 
      no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: 
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: 
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
In file included from /Users/zhouyuan/OpenFace-master/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp:35:
In file included from /Users/zhouyuan/OpenFace-master/lib/local/LandmarkDetector/include/stdafx.h:27:
In file included from /usr/local/include/dlib/image_processing/frontal_face_detector.h:7:
In file included from /usr/local/include/dlib/image_processing/../image_processing/object_detector.h:7:
In file included from /usr/local/include/dlib/image_processing/../geometry.h:10:
In file included from /usr/local/include/dlib/image_processing/../geometry/point_transforms.h:9:
In file included from /usr/local/include/dlib/image_processing/../geometry/../matrix/../optimization/../matrix.h:11:
In file included from /usr/local/include/dlib/image_processing/../matrix/matrix_la.h:9:
/usr/local/include/dlib/image_processing/../geometry/../matrix/../optimization/optimization_line_search.h:218:31: error: 
      expected unqualified-id
        if (temp == 0 || std::fpclassify(temp) == FP_SUBNORMAL)
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/math.h:127:5: note: 
      expanded from macro 'fpclassify'
    ( sizeof(x) == sizeof(float)  ? __fpclassifyf((float)(x))            \
    ^
14 errors generated.
make[2]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/src/CCNF_patch_expert.cpp.o] Error 1
make[1]: *** [lib/local/LandmarkDetector/CMakeFiles/LandmarkDetector.dir/all] Error 2
make: *** [all] Error 2`

Can someone help?
Thanks

**Comment by TadasBaltrusaitis** [comment]
It looks like a possible issue with OpenCV installation, what version of OpenCV do you have?

**Comment by Andy-ZYA** [comment]
I think it is 3.4.3

`zhouyuan$ brew info opencv
opencv: stable 3.4.3 (bottled)
Open source computer vision library
https://opencv.org/
/usr/local/Cellar/opencv/3.4.3 (619 files, 215.0MB) *
  Poured from bottle on 2018-11-06 at 02:03:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✘
Required: eigen ✔, ffmpeg ✘, jpeg ✔, libpng ✔, libtiff ✘, numpy ✔, openexr ✔, python ✘, python@2 ✔, tbb ✔
==> Analytics
install: 16,778 (30 days), 50,883 (90 days), 241,631 (365 days)
install_on_request: 15,791 (30 days), 47,663 (90 days), 219,633 (365 days)
build_error: 0 (30 days)
`

**Comment by Andy-ZYA** [comment]
> It looks like a possible issue with OpenCV installation, what version of OpenCV do you have?

Which version of OpenCV should I use?

**Comment by TadasBaltrusaitis** [comment]
OpenFace should work with OpenCV 3.4.3, although currently I'm testing with OpenCV 3.4. One option would be to build OpenCV 3.4 manually and see if that helps.

In the meantime I will see if 3.4.3 works on my setup.

**Comment by Andy-ZYA** [comment]
Is there any progress? I try to downgrade opencv to 3.4.0 using homebrew but it does not work well

**Comment by TadasBaltrusaitis** [comment]
What issues are you encountering with 3.4.0 with `homebrew`?

**Comment by TadasBaltrusaitis** [comment]
Actually OpenCV 4, should work with OpenFace, you can find instructions of how to install it here - https://www.pyimagesearch.com/2018/08/17/install-opencv-4-on-macos/

**Comment by zxu7** [comment]
I got exactly the same errors when I used opencv@3 from brew.
Now I tried OpenCV4 and problem remains. Please advise, thanks!

**Comment by TadasBaltrusaitis** [comment]
I can't reproduce this issue my end, but I found a similar problem face here that might help - https://github.com/kripken/emscripten/issues/5435

**Comment by xyli1905** [comment]
I have met the same problem, in my case it seems to be caused by some incomparabilities between the opencv3.4.5 and openface. When I reinstall OpenCV with version 3.4.3 it can be built successfully.

**Comment by zxu7** [comment]
@xyli1905 Glad to see you found a solution! Could you share more on how you solved this? Like did you reinstall it from brew or recompile openCV 3.4.3? Also, what's the Mojave version you are on?

**Comment by xyli1905** [comment]
I reinstall openCV from homebrew using the old opencv.rb for 3.4.3 version.

my Mojave version is 10.14.2 and Xcode version is 10.1 (10B61)

here is my gcc version and configuration:
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

Not sure if I have provided enough information, hope they would helpful
