### ISSUE TITLE
Download script (download_models.ps1) in the windows build of OpenFace 2.0.6 does not work

### ISSUE THREAD

**Issue by Milania1** [TadasBaltrusaitis/OpenFace#608]
**Describe the bug**
In the package with the Windows binaries (x64) the path to the model contains the prefix `lib/local/LandmarkDetector/` which is only suitable when [compiling from source](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download). Hence, the download fails.

I noticed that in previous binaries (OpenFace 2.0.0) the script contained the correct paths (e.g. `$destination = "model/patch_experts/cen_patches_0.25_of.dat"`).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version OpenFace 2.0.6

I don't know what the intention here is and whether the path is adjusted otherwise but one solution may be to check for existence of the `lib` folder and adjusting the model path accordingly:
```powershell
# Determine the correct path to the model files
if([System.IO.File]::Exists("lib"))
{
    # If the lib folder exists, code is compiled from source
    $modelPath = "lib/local/LandmarkDetector/"
}
else
{
    # Otherwise, binaries are used
    $modelPath = ""
}

# Start with 0.25 scale models
$destination = $modelPath + "model/patch_experts/cen_patches_0.25_of.dat"
# ...
```

This way, the script should work in both situations (compiling from source and using the binaries). If this sounds like a good idea to you, I can make a PR.

**Comment by TadasBaltrusaitis** [comment]
That's a great idea! Thanks

This issue was caused by my binary packaging code not using the correct powershell script, but your suggestion would fix the issue.

**Comment by TadasBaltrusaitis** [comment]
Fixed
