### ISSUE TITLE
Bitmap/BitmapSource to RawImage

### ISSUE THREAD

**Issue by deepakakkil001** [TadasBaltrusaitis/OpenFace#609]
The RawImage class, which is a wrapper for OpenCV Mat is used in all the C# examples. 
The examples show how to create a RawImage from image or video files/directly from camera feed using sequence reader.  Is there a built-in way to convert a C# image format, such as Bitmap/BitmapSource/WriteableBitmap  to the RawImage type?

I have a pre-processed image in WriteableBitmap  format that I need to feed into the pose estimation method.

**Comment by TadasBaltrusaitis** [comment]
I haven't implemented that functionality, but I'll look into it for the next version. 

One option would be to save the WriteableBitmap as an image and use a sequence or image reader on that data.

**Comment by TadasBaltrusaitis** [comment]
This is implemented in the newest release.
