### ISSUE TITLE
Video Orientation Issue with OpenFace GUI

### ISSUE THREAD

**Issue by SampsonW1** [TadasBaltrusaitis/OpenFace#612]
**Describe the bug**
There are a few videos have been rotated clockwisely 90 degrees while inputting those into OpenFace GUI. Any recommendations about that issue? Thanks,

**To Reproduce**
Steps to reproduce the behavior, with error description (and images/videos if failing on them).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Compiler [if compilation or linker error]

**Additional context**

**Comment by TadasBaltrusaitis** [comment]
Was the video recorded on a mobile device?

Have a look at this issue - https://github.com/TadasBaltrusaitis/OpenFace/issues/294

It might be that the video is actually rotated and OpenCV is interpreting it differently to various video players.
