### ISSUE TITLE
get error in cmake 

### ISSUE THREAD

**Issue by banxia1994** [TadasBaltrusaitis/OpenFace#617]
hi, i get error in cmake
as follow:

![image](https://user-images.githubusercontent.com/22139336/49016414-fa4a7a80-f1c0-11e8-8f6c-a3160dfbe830.png)

default opencv version is 2.4.8, i compiled 3.4.0 ,and  get '3.4.0' when i check the new opencv version. 

**Desktop (please complete the following information):**
 - OS:  ubuntun 14.04
 - Compiler  gcc+ 4.8

have any ideal? many thanks!!

**Comment by banxia1994** [comment]
> Same problem here

I solve the problem, you should compile opencv with TIFF, take the ' -D BUILD_TIFF=ON' when you cmake opencv.

**Comment by TadasBaltrusaitis** [comment]
Thanks for the suggestion @banxia1994 , I added that flag to the instructions now for building OpenCV.

**Comment by banxia1994** [comment]
@TadasBaltrusaitis  
hi, i compiled openface completely，but i get another error when run it 
-> ./bin/FeatureExtraction -verbose -f "../samples/default.wmv"
"

BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

"

-> ./bin/FaceLandmarkImg -fdir "../samples/" -wild

"
Model loaded
Reading the AU analysis module from: ./bin/AU_predictors/main_static_svms.txt
Reading the AU predictors from: ./bin/AU_predictors/AU_all_static.txt... Done
Reading the PDM from: ./bin/AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:./bin/AU_predictors/tris_68_full.txt... Done
Reading the MTCNN face detector from: ./bin/model/mtcnn_detector/MTCNN_detector.txt
Reading the PNet module from: ./bin/model/mtcnn_detector/PNet.dat
Reading the RNet module from: ./bin/model/mtcnn_detector/RNet.dat
Reading the ONet module from: ./bin/model/mtcnn_detector/ONet.dat
Error: Could not open the image: ../samples/sample1.jpg

"

have any ideal ?

**Comment by TadasBaltrusaitis** [comment]
Have a look at:
https://github.com/TadasBaltrusaitis/OpenFace/issues/537
https://github.com/TadasBaltrusaitis/OpenFace/issues/512

**Comment by banxia1994** [comment]
> Have a look at:
> #537
> #512

Thanks for your reply !!
related issue have read，  problem “BLAS : Program is Terminated. Because you tried to allocate too many memory regions.” have solved by reinstall openblas, 

How about "Error: Could not open the image: ../samples/sample1.jpg" ? 
I found that para have "-fdir " for FaceLandmarkImg、FeatureExtraction all wrong。

for "FeatureExtraction"  get Error 
"
Reading the triangulation from:./bin/AU_predictors/tris_68_full.txt... Done
Attempting to read from directory: ../samples/image_sequence
Device or file opened
Floating point exception (core dumped)
" 
for "FaceLandmarkImg" get 
"

Reading the MTCNN face detector from: ./bin/model/mtcnn_detector/MTCNN_detector.txt
Reading the PNet module from: ./bin/model/mtcnn_detector/PNet.dat
Reading the RNet module from: ./bin/model/mtcnn_detector/RNet.dat
Reading the ONet module from: ./bin/model/mtcnn_detector/ONet.dat
Error: Could not open the image: ../samples/image_sequence/001.jpg

"

sorry to bother you again.

regards !

**Comment by TadasBaltrusaitis** [comment]
Hi,

Sorry I'm not entirely sure about the issue you are having. Can you specify the exact command line arguments you used and the error you got.

Are you only having issues with opening images or videos as well?
