### ISSUE TITLE
x64 binaries crash

### ISSUE THREAD

**Issue by pi-null-mezon** [TadasBaltrusaitis/OpenFace#62]
Hi. First let me say thank you for your library! It is very useful.
Secondly i found that your binaries for x64 does not work (particlarly I have tested FeatureExtraction.exe and it was always crashed on start). Seems that wrong *.dll version is loaded. I also have tried to build project from the source code but for 64 bit find same behaviour (crash). At the same time 32 version works well. I have checked msvc2015x64 redistributable - it was installed on my pc. So what else is wrong? 
I have build on machine with MS Windows7x64.

**Comment by pi-null-mezon** [comment]
I have successfuly builded and ran on different machine, so the issue is no longer needed.

**Comment by TadasBaltrusaitis** [comment]
The fix might be related to this issue - https://github.com/TadasBaltrusaitis/OpenFace/issues/43

**Comment by pi-null-mezon** [comment]
Hi, yes, I have faced with exactly the same behavior. Old machine (with issue) works on Intel Core Quad Q9400 and the new one (works well) on Intel Core i5-3230M. So, once again, thank you!
