### ISSUE TITLE
-oc codec selection in facelandmarkvidmulti

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#620]
Does -oc fourcc function is implemented to FaceLandmarkVidMulti or only featureextraction?

**Comment by TadasBaltrusaitis** [comment]
It should work the same way on both, let me know if you do not observe that behavior.

**Comment by iPsych** [comment]
My current command is as below.
It gives me a huge sized 'tracked' video.
Can I somehow get the raw aligned image and aligned image with tracked feature points instead of the whole video?
` /bin/FaceLandmarkVidMulti -f video_file  -out_dir out_dir -oc h264 -format_aligned png -nobadaligned -simsize 600 -wild -multi_view 1 -nomask`

**Comment by TadasBaltrusaitis** [comment]
Are the sizes different when using `FeatureExtraction` vs `FaceLandmarkVidMulti`? There is a chance that your system does not support `h264` encoding, do you see any messages about failure to create the codec? You can try out different codecs, such as `divx` or `xvid`

**Comment by iPsych** [comment]
I checked some variations, but all files have same size and they are DivX4 file, when checked with Mediainfo.

**Comment by TadasBaltrusaitis** [comment]
Were you successful in using mp4v or avc1 with OpenFace? Or are you suggesting that there's a bug with OpenFace rather than an OpenCV issue?

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue is still there.
