### ISSUE TITLE
Missing files from download_models.sh

### ISSUE THREAD

**Issue by adataylor** [TadasBaltrusaitis/OpenFace#621]
**Describe the bug**
Script for the Mac install downloads similar but not-sufficent files from the dropbox:
https://github.com/TadasBaltrusaitis/OpenFace/blob/master/download_models.sh

Specifically, none of the "cen_patches_0.25_of.dat" or "cen_patches_0.xx_of.dat" files are downloaded automatically, require manual download.

**To Reproduce**
Run download_model.sh

**Comment by TadasBaltrusaitis** [comment]
Can you provide more details? How are the files not-sufficient, do they differ from the ones downloaded manually?

The script seems to work my end.

**Comment by adataylor** [comment]
Again, all the files were downloaded except for the "_of" set.

cen_patches_0.25_of.dat
cen_patches_0.35_of.dat
cen_patches_0.50_of.dat
cen_patches_1.00_of.dat

I was prompted for these files at runtime; manually downloading them from the Dropbox and adding them to the correct location seemed to work.

**Comment by TadasBaltrusaitis** [comment]
The only 4 files the script is downloading are the "cen_patches_*_of.dat", what do you mean by all other files? I'm trying to debug this issue, but the script seems to work my end (both on Ubuntu and on OSX)

**Comment by TadasBaltrusaitis** [comment]
Please reopen if the issue persists.
