### ISSUE TITLE
build/bin/FaceLandmarkVid -device 0 .  on OS X  error

### ISSUE THREAD

**Issue by sundayxcn** [TadasBaltrusaitis/OpenFace#622]
hi.  im new fish. i cmd  build/bin/FaceLandmarkVid -device 0  is error  according to  Mac ....
i cant understand the error. help me please.
appleMacBook-Pro-3:OpenFace apple$ build/bin/FaceLandmarkVid -device 0
Reading the landmark detector/tracker from: build/bin/model/main_ceclm_general.txt
Reading the landmark detector module from: build/bin/model/cen_general.txt
Reading the PDM module from: build/bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: build/bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: build/bin/model/patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: build/bin/model/patch_experts/cen_patches_0.35_of.dat....Done
OpenCV Error: Assertion failed (s >= 0) in setSize, file /Users/apple/OpenFace/opencv-3.4.0/modules/core/src/matrix.cpp, line 310
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/apple/OpenFace/opencv-3.4.0/modules/core/src/matrix.cpp:310: error: (-215) s >= 0 in function setSize

Reading the intensity CEN patch experts from: build/bin/model/patch_experts/cen_patches_0.50_of.dat....Abort trap: 6

**Comment by TadasBaltrusaitis** [comment]
This looks like the models were not downloaded successfully (0.25 and 0.35 scale models were downloaded) but the 0.50 one seems to have been corrupted. Could you try deleting the models and re-downloading them (you will find them in `lib\local\LandmarkDetector\model\patch_experts` directory, with extension `.dat`).

There should be 4 `..dat` files, with sizes 59MB, 59MB, 150MB, 150MB

**Comment by sundayxcn** [comment]
> This looks like the models were not downloaded successfully (0.25 and 0.35 scale models were downloaded) but the 0.50 one seems to have been corrupted. Could you try deleting the models and re-downloading them (you will find them in `lib\local\LandmarkDetector\model\patch_experts` directory, with extension `.dat`).
> 
> There should be 4 `..dat` files, with sizes 59MB, 59MB, 150MB, 150MB

exciting！！！ success!  thank you very mush!
