### ISSUE TITLE
Make error on ubuntu 16.04

### ISSUE THREAD

**Issue by haiewu** [TadasBaltrusaitis/OpenFace#625]
Hi,guys
  i was getting following error when make the Openface and opencv version is 3.1.0:

/../../OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorModel.cpp: In member function ‘bool LandmarkDetector::CLNF::DetectLandmarks(const cv::Mat_<unsigned char>&, LandmarkDetector::FaceModelParameters&)’:
/../../OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorModel.cpp:683:4: error: invalid initialization of reference of type ‘const cv::ParallelLoopBody&’ from expression of type ‘LandmarkDetector::CLNF::DetectLandmarks(const cv::Mat_<unsigned char>&, LandmarkDetector::FaceModelParameters&)::<lambda(const cv::Range&)>’
   });
    ^
In file included from /usr/local/include/opencv2/core.hpp:3216:0,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /../../OpenFace/lib/local/LandmarkDetector/include/stdafx.h:19,
                 from /../../OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorModel.cpp:35:
/usr/local/include/opencv2/core/utility.hpp:478:17: note: in passing argument 2 of ‘void cv::parallel_for_(const cv::Range&, const cv::ParallelLoopBody&, double)’
 CV_EXPORTS void parallel_for_(const Range& range, const ParallelLoopBody& body, double nstripes=-1.);

**Comment by TadasBaltrusaitis** [comment]
Hi,

I've only tested OpenFace with OpenCV versions 3.3 and up, can you try upgrading your OpenCV version?

-Tadas

**Comment by TadasBaltrusaitis** [comment]
Please re-open if the issue is still there.
