### ISSUE TITLE
Mac install problem about model download

### ISSUE THREAD

**Issue by 854811200** [TadasBaltrusaitis/OpenFace#628]
**Describe the bug**
If build openface from source on Mac, the wiki said:
The C++ models have the .dat extension and should  be place in the lib\local\LandmarkDetector\model\patch_experts folder 

but it is wrong
Instead it should be replaced at 
OpenFace/build/bin/model/patch_experts

**Comment by TadasBaltrusaitis** [comment]
It is not wrong, the build process will place the models to the `OpenFace/build/bin/model/patch_experts` if they are downloaded correctly before the build.
