### ISSUE TITLE
i got an error when i make OpenFace on jetson tk1 

### ISSUE THREAD

**Issue by puface** [TadasBaltrusaitis/OpenFace#63]
hi  
     the OpenFace can work to well in x86  . but  i got an error on my jetson tk1 (arm) . the issues come from dlib version or other . i can success make  dlib alone in tk1  .anyone can  help me  thanks 

  ubuntu@tegra-ubuntu:~/OpenFace/build$ make
[  1%] Building CXX object lib/3rdParty/dlib/CMakeFiles/dlib.dir/include/dlib/base64/base64_kernel_1.o
c++: error: unrecognized command line option ‘-msse’
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
make[2]: **\* [lib/3rdParty/dlib/CMakeFiles/dlib.dir/include/dlib/base64/base64_kernel_1.o] Error 1
make[1]: **\* [lib/3rdParty/dlib/CMakeFiles/dlib.dir/all] Error 2
make: **\* [all] Error 2

**Comment by TadasBaltrusaitis** [comment]
dlib relies on the SSE instruction set, which is probably not supported on the jetson tk1. There might be a way to not use the SSE instruction set when compiling dlib (I think through using certain macros).

**Comment by puface** [comment]
hi TadasBaltrusaitis  
     the jetson tk1 can work .but run so slow when not use SEE  .  thank your help . i want to know  OpenFace will support cuda or other good idea ?  i found dlib 19.1 only support cuda7.5 version

**Comment by TadasBaltrusaitis** [comment]
I did not have a plan for CUDA support any time soon, but it would be nice to have eventually.
