### ISSUE TITLE
Need some help for training new models

### ISSUE THREAD

**Issue by haimingZZ** [TadasBaltrusaitis/OpenFace#64]
Hi,

I am working on training my own model. I succeed training the patch expert for face. And I came to some tricky problems.

1> there are some key files in folder model/model_eye/ and i don't know how to train these files. 
2> When i use the file \CCNF_Train\matlab_version\face_validation\Train_face_checker_68_cnn; there is an error in "C:/Users/Tadas/Dropbox/AAM/test data//Bounding Boxes/bounding_boxes_afw.mat", cannot find.

Is there any chance i can get these files?

Thanks a lot. 

Haiming

**Comment by TadasBaltrusaitis** [comment]
Hi Haiming,

To answer your questions:
1. I have not integrated the eye model training in as nice a way as other models. The data for training eye models is here - https://www.cl.cam.ac.uk/research/rainbow/projects/syntheseyes/
2. I uploaded this to be part of the repository (you will need to change the locations of where the file is expected)

Thanks,
Tadas
