### ISSUE TITLE
Linker issue Visual Studio 2017

### ISSUE THREAD

**Issue by pablolq** [TadasBaltrusaitis/OpenFace#641]
After cloning the repo using Visual Studio 2017(Windows 10)  I open the OpenFace_vs2017 solution but when I build I get the following Linker error in multiple projects:

Error	LNK1104	cannot open file 'opencv_world340.lib'	CppInerop	

Also with FaceLandmarkVid, FaceLandmarkVidMulti, FaceLandmarkImg and Feature Extraction.

I have checked the project properties to see the linkers additional dependencies input path and they are inherited or defined with macros so the path to the .lib file seems to be correct. Any ideas of how can this be solved? Or which is the parent project from wich all inherit properties from to edit the dependecies path?

**Comment by TadasBaltrusaitis** [comment]
I'm currently resolving this issue, and it should be resolved in the next version of OpenFace.

**Comment by HairySags** [comment]
Not trying to pester, but is there a workaround for now?

**Comment by TadasBaltrusaitis** [comment]
You can look at the following branch in the meantime - https://github.com/TadasBaltrusaitis/OpenFace/tree/feature/VS2017_changes

It includes the VS2017 related fixes.

**Comment by HairySags** [comment]
Thanks you, this worked

**Comment by goigle** [comment]
Pinging off this - I also get this in VS2019. Earlier I was getting the same as OP, but currently I get 
`Error	LNK1104	cannot open file 'MSCOREE.lib'	CppInerop`

**Comment by kesimeg** [comment]
Hi I had the same problem,after using the branch in the link I build the project. In exes such as FaceLandmarkVid, FaceLandmarkVidMult it gave an error about not finding opencv_world340d.dll. I searched it in the folders and copy-pasted it into the same directory. Now the applications (OpenFaceOffline etc.) work but they are extremely slow. I only get 1 fps.  However in OpenFace_2.1.0_win_x64 I get around 20 fps or above. Where might be the problem?

**Comment by TadasBaltrusaitis** [comment]
Should be fixed in the new version.
