### ISSUE TITLE
How to generate the derivatives of euler angles  in ComputeRigidJacobian

### ISSUE THREAD

**Issue by waterball** [TadasBaltrusaitis/OpenFace#644]
I'm trying to calculate the derivatives of  rotation terms by myself. But I have no idea how to do it. I notices the comments "The rigid jacobian from the axis angle rotation matrix approximation using small angle assumption (R * R')". Could you explain it a little bit or could you give me any reference to read?

**Comment by TadasBaltrusaitis** [comment]
You can find the derivation here - https://www.dropbox.com/s/vuvwxadjquxi16o/ThesisFinal.pdf?dl=0, specifically chapter 4.2.4

**Comment by waterball** [comment]
thanks a lot
