### ISSUE TITLE
Question about Output Image Size

### ISSUE THREAD

**Issue by megq** [TadasBaltrusaitis/OpenFace#645]
It appears in OpenFace_2.0.5 you are able to click Record > Output Image Size and choose to output to any size. We are using a Windows 10 PC and are interested in having our images as large as possible. Is there a size you would recommend not going above? Have there been any bugs or anything not tested at a certain size? Thank you!

**Comment by TadasBaltrusaitis** [comment]
What is the reason for wanting the images as large as possible? I wouldn't recommend going above the original face size as that would require image upsampling, of course it all depends on the application you are interested in.

I'm not aware of any issues with large images, but I have not explored it much, as you rarely need higher than 200x200 images of faces for most applications.
