### ISSUE TITLE
Docker Container issue: dlib: Finddlib.cmake missing

### ISSUE THREAD

**Issue by cadgi** [TadasBaltrusaitis/OpenFace#646]
I ran into a small problem when trying to rebuild the Docker container on my Linux box  using the following OpenFace DockerFile:

**https://hub.docker.com/r/algebr/openface/dockerfile** 

and the following GitHub Repo:

**git clone https://github.com/TadasBaltrusaitis/OpenFace.git**

I edited the DockerFile to use Ubuntu 16.04 (as Cmake was out of date for Ubuntu 14.04). I used the following command to build the container:

**sudo docker build -t openface .**

When I tried to build the container, I got the following error message (see screenshot below). 
It is seems I am missing  a Finddlib.cmake for DLIB (in the GitHub Repo)? 

-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
Boost information:
  Boost_VERSION: 105800
  Boost_INCLUDE_DIRS: /usr/include
  Boost_LIBRARIES: /usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so
  Boost_LIBRARY_DIRS: /usr/lib/x86_64-linux-gnu
CMake Warning at CMakeLists.txt:147 (find_package):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" (requested
  version 19.13) with any of the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Error at CMakeLists.txt:156 (message):
  dlib not found in the system, please install dlib

-- Configuring incomplete, errors occurred!
See also "/home/openface-build/build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cd ${OPENFACE_DIR} && mkdir -p build && cd build &&     cmake -D CMAKE_BUILD_TYPE=RELEASE .. &&     make -j4' returned a non-zero code: 1

Here is a screenshot of the error I get:

![image](https://user-images.githubusercontent.com/25137373/52303480-f7000780-2944-11e9-855a-0c2b6508013e.png)

**Comment by TadasBaltrusaitis** [comment]
I have little experience with docker, and the docker file was made some time ago, before a lot of changes to the model. I might investigate creating a new dockerfile, as it seems to be quite useful for a number of people.

**Comment by farukarakaya** [comment]
I had same problem, but I managed to cretae image and I created [https://github.com/TadasBaltrusaitis/OpenFace/pull/692](PR).

**Comment by TadasBaltrusaitis** [comment]
There is now a newer docker image in master, please see - `docker\README.md`
