### ISSUE TITLE
There is no pts type file in the output.

### ISSUE THREAD

**Issue by HJLYU0519** [TadasBaltrusaitis/OpenFace#649]
**Describe the bug**
I use the following commond:
~/OpenFace-master/build/bin/FaceLandmarkImg -fdir "./tmp-input-dir/" -out_dir "./tmp-output-dir/" -oidir "./tmp-output-dir/" -wild -multi-view 1

I want to get the pts type file (including npoints:68, eul_x,eul_y,eul_z,au intensities and au_occurences) corresponding to each image in the output folder. But I did not find it.
Is this because the version of the code has been updated? Or is it because I can extract pts files from csv files?

**Comment by TadasBaltrusaitis** [comment]
Everything has been unified now to produce a CSV file that is the same format from both video and image processing (as opposed to a separate pts and separate csv files). This was to simplify downstream processing and code.
