### ISSUE TITLE
OpenFace Windows Issue

### ISSUE THREAD

**Issue by PVNathan** [TadasBaltrusaitis/OpenFace#65]
Hi 
Firstly thanks for implementing it, really useful. Is there more documentation available in terms of how to train using our own database i.e. if thats possible? I am trying to use your implementation and build on top or it and hence need to retrain.

I appreciate your help.
Thanks

**Comment by TadasBaltrusaitis** [comment]
There is some documentation, please see - https://github.com/TadasBaltrusaitis/OpenFace/blob/master/matlab_version/readme.txt specifically the model training section, each part of the model will have their own readme describing how to train them.

Thanks,
Tadas
