### ISSUE TITLE
Landmarks likelihoods

### ISSUE THREAD

**Issue by noamzafrir** [TadasBaltrusaitis/OpenFace#652]
Hello,
What is the range of values of "landmark_likelihoods"?

Thanks,
Noam.

**Comment by TadasBaltrusaitis** [comment]
They will be positive numbers (they are not normalized to lie between 0 and 1 for computational efficiency). Roughly will range from 0-5, with some variability for each landmark.

For more details - they come from a kernel density estimate on the landmark detection heatmap (patch response) centered around a current estimate for the landmark).

**Comment by noamzafrir** [comment]
Thank you for this helpful reply.

What about the total "model_likelihood"? what is the range of values of this parameter?
I see it can get negative values so it's obviously not a simple average of the likelihood of each landmark.

**Comment by TadasBaltrusaitis** [comment]
The overall model_likelihood is the mean sum of all of the log likelihoods (this is equivalent to just multiplying the likelihoods together and taking their log but more numerically stable). The values are not very well bounded, but will roughly range from -10 to 10, higher values meaning more reliable detections.

The values themselves are a bit tricky to interpret, but their ordering is fairly reliable (with higher values meaning more reliable fits)

**Comment by noamzafrir** [comment]
Understood.
Thank you.
