### ISSUE TITLE
Landmark of MTCNN in OpenFace is missing

### ISSUE THREAD

**Issue by ardeal** [TadasBaltrusaitis/OpenFace#657]
Hi,

The functionalities of OpenFace is really good!
But I noticed that the landmark of MTCNN is missing.

This might be the code(Line 847 to Line 845 in FaceDetectorMTCNN.cpp file) of the output of MTCNN:
```C
		std::vector<cv::Mat_<float> > onet_out = ONet.Inference(prop_img, true, false);

		float prob = 1.0 / (1.0 + cv::exp(onet_out[0].at<float>(0) - onet_out[0].at<float>(1)));
		scores_all[k] = prob;
		proposal_corrections_all[k].x = onet_out[0].at<float>(2);
		proposal_corrections_all[k].y = onet_out[0].at<float>(3);
		proposal_corrections_all[k].width = onet_out[0].at<float>(4);
		proposal_corrections_all[k].height = onet_out[0].at<float>(5);

```
according to the code the landmark of MTCNN is missing, could I get the landmark of MTCNN if I customize your code?
if yes, how to modify the code?

Thanks and Best Regards,
Ardeal

**Comment by junxianlee** [comment]
Hi,
Are you running the programme with xcode on mac?

Best Reagrds,
Lee

**Comment by ardeal** [comment]
Hi Lee,

I am running the code on VS2015 on Windows 10.

Thanks and Best Regards,
Ardeal

**Comment by TadasBaltrusaitis** [comment]
I didn't use the lanamark part of MTCNN as I didn't find it useful for my purposes (it is too unreliable for profile faces and often ended up misleading OpenFace), so that functionality is not implemented and the MTCNN model in OpenFace does not contain the weights for landmarks from MTCNN.
