### ISSUE TITLE
how are euler angles direction represented

### ISSUE THREAD

**Issue by avisangray** [TadasBaltrusaitis/OpenFace#66]
what is the direction of axis for euler angles in FaceLandmarkImg?

**Comment by TadasBaltrusaitis** [comment]
Rotation is in radians around X,Y,Z axes with the convention R = Rx * Ry * Rz, left-handed positive sign.

**Comment by avisangray** [comment]
positive z away from camera?

**Comment by TadasBaltrusaitis** [comment]
See - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format

Positive Z is away from camera.

**Comment by avisangray** [comment]
ok thanks sir

**Comment by iqbalnaved** [comment]
@TadasBaltrusaitis Could you please tell me what is the range of the euler angles ? Is it [-pi,pi] or [-1,1] ? Thanks.

**Comment by TadasBaltrusaitis** [comment]
They are in radians, so will roughly range from `[-pi,pi]`

**Comment by iqbalnaved** [comment]
@TadasBaltrusaitis  Thanks, but when I am getting the values using FaceLandmkImg, the values seem very small e.g. 0.396767 0.773298 -0.10933. Do you normalize the range between some small interval ?

**Comment by TadasBaltrusaitis** [comment]
As I mentioned before, the values are in radians (https://en.wikipedia.org/wiki/Radian), so the values are expected to be in the range you mention, `[0.39, 0.77, -0.10] radians =  [22.34, 44.1, -5.7] degrees`
