### ISSUE TITLE
how can I download the executables?

### ISSUE THREAD

**Issue by junxianlee** [TadasBaltrusaitis/OpenFace#661]

**Comment by junxianlee** [comment]
For mac.

**Comment by Arwwarrr** [comment]
.exe work only in windows

**Comment by junxianlee** [comment]
@Arwwarrr Have you read the "Command line arguments"? I absolutely know that .exe files are only working in windows. So how can I compile these OpenFace codes and run them on mac? How do you understand "For Ubuntu or Mac OS X omit the .exe. " 
![Screen Shot 2019-03-09 at 11 41 14 AM](https://user-images.githubusercontent.com/36917978/54065806-96742b00-4260-11e9-88dc-7a22b655d898.png)

**Comment by TadasBaltrusaitis** [comment]
The executables are not included for a mac, you need to build them yourself, see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation
