### ISSUE TITLE
Some files are lost on github

### ISSUE THREAD

**Issue by junxianlee** [TadasBaltrusaitis/OpenFace#663]
![screen shot 2019-03-08 at 7 05 13 pm](https://user-images.githubusercontent.com/36917978/54025362-41d79e00-41d5-11e9-89f7-e93a5cb74039.png)
I cannot find "build" file and "x64/Release" file on github. That means the executable files are missed.
Please check, thank you!

**Comment by TadasBaltrusaitis** [comment]
You need to build the executable yourself, as it is not included with the code, for building instructions for various operating systems see:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

Alternatively you can download the pre-built executables for Windows here - https://github.com/TadasBaltrusaitis/OpenFace/releases
