### ISSUE TITLE
Some questions of running OpenFace on macbook

### ISSUE THREAD

**Issue by junxianlee** [TadasBaltrusaitis/OpenFace#664]
1. In the matlab file "feature_extraction_demo_vid.m", I cannot run the executable file "FeatureExtraction". It can only be run on the docker.
![54065806-96742b00-4260-11e9-88dc-7a22b655d898](https://user-images.githubusercontent.com/36917978/54070350-d7d4fc80-4299-11e9-9606-f2d9101bd011.png)
What do the meaning of "For Ubuntu or Mac OS X omit the .exe"?

2. Because I cannot get the csv files, aligned files, I running the executable "FeatureExtraction" on the docker, I put the processed data out of the docker, and find that the Hog files cannot be visualized. 
I know that "HOG feature visualization is currently done only during the processing of the data, so if you process the original files with -verbose setting you will see the visualization. " 
However, if so, I should still running the "feature_extraction_demo_vid.m" on matlab. It means these codes below should be run through.
![Screen Shot 2019-03-09 at 6 09 35 PM](https://user-images.githubusercontent.com/36917978/54070351-ddcadd80-4299-11e9-9a14-7d285450adf3.png)

In the conclusion, because of lack of the .exe files, I put the .csv and avi. files directly to the matlab path to run the program. However, the HOG still need that exe and -verbose something to be visualized.

Does anyone have the experience of running OpenFace on Macbook?
I am begging a helping hand to fix these problems. Thank you very much!!

**Comment by TadasBaltrusaitis** [comment]
The binaries/executables on mac or ubuntu do not contain the `.exe` extension, hence the instruction about skipping it. However, you need to build the binaries yourself, see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation for details.
