### ISSUE TITLE
Compiling for ARM - sgemm_ symbol not found

### ISSUE THREAD

**Issue by santo4ul** [TadasBaltrusaitis/OpenFace#668]
Hi, I'm trying to cross-compile OpenFace for ARM. I've compiled all relevant OpenFace dependencies (dlib, OpenCV, libboost, OpenBLAS). 

At the time of linking the applications (FaceLandmarkImg, FaceLandmarkVidMulti, etc.), I get the following link error, 

```
CNF_patch_expert.cpp:(.text+0x3e84): undefined reference to `sgemm_'
CCNF_patch_expert.cpp:(.text+0x401c): undefined reference to `sgemm_'

```
OpenBLAS (v0.3.5) that I've built  doesn't seem to have the symbol `sgemm_`. I followed the instructions to build OpenBLAS for ARM from [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android). 

The `sgemm_` used in OpenFace is a Fortran implemenation? Looks like the C version (cblas_sgemm) has parameter mismatch. 

Am I missing something? Before digging any further, I'd like to get some thoughts on it. Appreciate any inputs/pointers. 

Thank you.

**Comment by santo4ul** [comment]
Based on the comment below, It looks like a Fortran call. I can't think if any quick workaround. One option is to implement the SGEMM in C (will be slow). Appreciate if someone could suggest other better ideas to quickly get the code running on ARM platform. 


```
		// Perform matrix multiplication in OpenBLAS (fortran call)
		float alpha1 = 1.0;
		float beta1 = 1.0;
		char N[2]; N[0] = 'N';
		sgemm_(N, N, &J.cols, &J_w_t.rows, &J_w_t.cols, &alpha1, (float*)J.data, &J.cols, (float*)J_w_t.data, &J_w_t.cols, &beta1, (float*)Hessian.data, &J.cols);

```

**Comment by santo4ul** [comment]
I was able to build OpenFace for ARM successfully. Followed the instructions from [here](https://github.com/buffer51/android-gfortran) and built a toolchain that includes aarch64-linux-android-gfortran for ARM. Later re-built OpenBLAS with FORTRAN support as given [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android). 

Hope this helps someone. 

Thank you.

**Comment by TadasBaltrusaitis** [comment]
Thanks for the investigation and the instructions! I'm sure someone will find them helpful.

The reason I'm using the FORTRAN call is that I experimentally found it to be significantly faster, hence it is used instead of the C call.
