### ISSUE TITLE
How to train my own face key point data

### ISSUE THREAD

**Issue by zhouhao-learning** [TadasBaltrusaitis/OpenFace#670]
Hello, I have a face data with 98 face key points. I use your network to train my data so that I can predict 98 key points, but there is no explanation in your explanation. Please tell me how should I start?

**Comment by TadasBaltrusaitis** [comment]
Hi, 

There is not one tutorial that describes how to train all of the necessary modules, but you can have a look at the code in the following folders to get you started:
https://github.com/TadasBaltrusaitis/OpenFace/tree/master/model_training

You will need to train a Point Distribution Model (PDM) and the patch experts themselves (CCNF or CEN based ones).

For more details on the models, I suggest you have a look at the relevant papers - https://arxiv.org/pdf/1611.08657.pdf
