### ISSUE TITLE
Get the index value (row, col) of the points detected.

### ISSUE THREAD

**Issue by nikunj95** [TadasBaltrusaitis/OpenFace#672]
Hi,

I am trying to find the index value - row, col of every location. The output given are only the pixel value of each location. Could you guide to get the row, col of each location?

**Comment by TadasBaltrusaitis** [comment]
Hi,

I'm not entirely sure what you mean by this question? The pixel values correspond to the row and column location of an image array/matrix

**Comment by abdou31** [comment]
Same problem , i see only one pixel in the output csv for each point

**Comment by TadasBaltrusaitis** [comment]
I'm not sure I understand? What do you mean one pixel? There are `x` and `y` values for each landmark corresponding to `col` and `row` of your image matrix.

**Comment by abdou31** [comment]
i see only x coordinate for iris landmarks ( for exemple ) 
what parameters shoul i set to get x abd y values fo each pixel in the output file?

**Comment by TadasBaltrusaitis** [comment]
There should be an equivalent `y_` and `eye_lmk_y_` values, are they not in the output?

**Comment by abdou31** [comment]
I solved this issue.
I have other problems now with OpenFace I will open an issue when I finished the work with the Android SDK
