### ISSUE TITLE
How do I run this test code?

### ISSUE THREAD

**Issue by moranlouie** [TadasBaltrusaitis/OpenFace#673]
`./bin/FaceLandmarkImg -fdir "../samples/" -wild`

While cd is still at OpenFace/build (from the last instruction on the installation manual), I get this error:

`ERROR: Could not load the landmark detector`

I looked through #591. I don't understand those instructions and I'm not sure if those apply to my installation. I followed the "Advanced Ubuntu installation"

**Comment by TadasBaltrusaitis** [comment]
Have you downloaded the patch expert models before building the project? https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download

**Comment by Ulia-Demidova** [comment]
Hi, TadasBaltrusaitis!
I try to download the patch expert models (download_models.sh). There is an error 404: Not Found

--2019-06-13 02:16:28--  https://onedrive.live.com/download?cid=2E2ADA578BFF6E6E
Recognizing onedrive.live.com (onedrive.live.com)... 13.107.42.13
Connect to onedrive.live.com (onedrive.live.com)|13.107.42.13|:443... connection established.
HTTP-request sent. Waiting for answer... 404 Not Found
2019-06-13 02:16:28 ERROR 404: Not Found.

**Comment by kjacks21** [comment]
I am experiencing the same issue. `404: Not Found`

**Comment by kjacks21** [comment]
@Ulia-Demidova in the meantime, you can download the four files from OneDrive to the appropriate folder specified on the [wiki](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download) page. For me, the location was in `bin/model/patch_experts`

**Comment by TadasBaltrusaitis** [comment]
You can find direct download links here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download#manual-download

It seems like the links have expired, thanks for letting me know.

**Comment by TadasBaltrusaitis** [comment]
It seems like the link is missing the authkey part, which is in both the scripts and the direct links.

Can you try running the download_models.sh again?

**Comment by kjacks21** [comment]
I'm on Ubuntu 18 and running `bash download_models.sh` saved the files to `/OpenFace/lib/local/LandmarkDetector/model/patch_experts`, which didn't let me run the examples. Moving the files over to `OpenFace/build/bin/model/patch_experts` worked.

**Comment by TadasBaltrusaitis** [comment]
You need to download the models before compiling the code (the make steps moves the patch experts to the right location).

**Comment by kjacks21** [comment]
This has been resolved and can be closed.
