### ISSUE TITLE
Mac installation: OpenCV 4.0.1 not accepted

### ISSUE THREAD

**Issue by Hugomeyer95** [TadasBaltrusaitis/OpenFace#674]
**Describe the bug**
When following the steps for the mac installation of OpenFace, I have an issue when running the following command: 
"cmake -D CMAKE_BUILD_TYPE=RELEASE CMAKE_CXX_FLAGS="-std=c++11" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11" .."

The error I get:
"CMake Error at CMakeLists.txt:30 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake, version: 4.0.1"

I thought OpenFace had been updated to be compatible with OpenCV 4.0?

**To Reproduce**
Download the project on mac and run the commands indicated in the "Mac installation" section.

**Expected behavior**
I exected to have the "cmake" command work and the OpenCV current version to be compatible with OpenFace.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave 
 - Version 10.14.3
 - Compiler [if compilation or linker error]

**Additional context**

**Comment by Rasipuram** [comment]
Hi,

Were you able to fix the issue? I also get the same error on mac.

"Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake, version: 4.0.1"

**Comment by TadasBaltrusaitis** [comment]
Hi. the official version of OpenFace does not support OpenCV 4.0 just yet, but you can look at the following branch - https://github.com/TadasBaltrusaitis/OpenFace/tree/feature/opencv4

The next release will support it.

Thanks,
Tadas

**Comment by Rasipuram** [comment]
Hi,

I fixed the issue by changing the CMakeLists.txt file. 

Modify "find_package( OpenCV 3. " line to 
"find_package( OpenCV 4.0.1"

Make was successful after changing this line.
