### ISSUE TITLE
Clarification about openface usage in surveillance/spying

### ISSUE THREAD

**Issue by fxfactorial** [TadasBaltrusaitis/OpenFace#679]
I am not clear about openfaces licensing as the commercial component seems like a case to case basis? 

Can you clarify if openface has been licensed for use in surveillance technologies like the ones used by China to racially profile more than 10 million Uighers? 

https://www.nytimes.com/2019/04/14/technology/china-surveillance-artificial-intelligence-racial-profiling.html

**Comment by TadasBaltrusaitis** [comment]
I can confirm that we have not licensed OpenFace to SenseTime or CloudWalk. I'm also not aware of any companies that we license to having any surveillance products of such nature.

However, us not licensing the product does not prevent certain companies from using OpenFace illegally and without our knowledge, as the source code and various trained models are available for download.
