### ISSUE TITLE
FaceAnalyzer.lib is not a valid Win32 application

### ISSUE THREAD

**Issue by windowshopr** [TadasBaltrusaitis/OpenFace#681]
Hey! Love your efforts and am extremely eager to get started using the software. I was able to get the out of the box version working just fine, but seem to be having an issue in compiling/running through VS2015 and Windows 10 x64.

**Describe the bug**
I build the OpenFace.sln file (tried both Win32 and x64 from the dropdown), both build successfully. When I try to run the project without debugger attached and in Release mode for speed using CTRL + F5 instead of F5, I receive an error saying:

    Unable to start program
    ...\x64\Debug\FaceAnalyser.lib

    ...\x64\Debug\FaceAnalyser.lib is not a valid win32 application.

I'm wondering, is there any benefit to running this program through VS2015 with manual building, or does the version that's pre-built with exe's ("Out of the box") do the same things? Otherwise, looks like my machine is having an issue with this .lib file.

Didn't see anyone else having this issue so it's probably something I'm just not seeing, but would love to figure it out, if there's a benefit to running through VS2015. Thanks a million again!

**Comment by TadasBaltrusaitis** [comment]
You are trying to start the library rather than executable, which is why you get the error `is not a valid win32 application.`, to run the executable you have to select it as the "StartUp project". You can do that by right clicking on the project you want (e.g. FeatureExtraction or OpenFaceOffline) from the Solution Explorer.

**Comment by windowshopr** [comment]
Thank you!

**Comment by dameunltd** [comment]
man i was giving myself a headache and this is all i needed lol thank you a year later!
