### ISSUE TITLE
CMake Error at cmake/modules/FindOpenBLAS.cmake:103 

### ISSUE THREAD

**Issue by abdou31** [TadasBaltrusaitis/OpenFace#682]
Hello , 
I tried to compile OpenFace using CMAKE but i get some problems .

+ https://i.imgur.com/1VnSMJT.png

I have OpenBLAS installed in C:/Users/Abdou/OpenBLAS as mentionned in this picture:

+ https://i.imgur.com/mE7KtT7.png

And i have compiled it using Powershell with CMAKE and MVSC 2017 x64

+ https://i.imgur.com/mkHnKhg.png

How to solve this error?

Thanks

**Comment by TadasBaltrusaitis** [comment]
Are you still facing the issue, or did you manage to compile using the solution file?

**Comment by abdou31** [comment]
For now no,
Those issues are open when i compiled with Cmake .
You can close this issue.
Thanks
