### ISSUE TITLE
Problems when execute .exe file

### ISSUE THREAD

**Issue by abdou31** [TadasBaltrusaitis/OpenFace#683]
After successfully building with Visual studio 2017 ( Release x64 ) for ALL_BUILD,
When i execute .exe file i get some erros , how to solve those problems ?
+ Could not find the landmark detection model to load
+  Could not find the HAAR face detector location
+ Could not find the MTCNN face detector location
+ Could not find the landmark detection model to load
+ Reading the landmark detector/tracker from: model/main_ceclm_general.txt
+ Couldn't open the model file, aborting
+ ERROR: Could not load the landmark detector
Thanks

**Comment by TadasBaltrusaitis** [comment]
Have you downloaded the patch expert models before compilation - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download?

**Comment by abdou31** [comment]
I solved the problem and i compiled the Openface.sln
Thanks , test work fine and perfectly
I have other questions about training model for now 
Can i ask you by email?

**Comment by TadasBaltrusaitis** [comment]
Sure.
