### ISSUE TITLE
Executable is very slow

### ISSUE THREAD

**Issue by PVNathan** [TadasBaltrusaitis/OpenFace#69]
I am using the 32 bit binaries but when I compile openface.sln there is no x86 folder. When I run the precompiled exe files in the OpenFace_0.1_win_x86 folder they run fine except FaceLandMarkImg.exe does not hold the output image long enough. There are exe files generated in the Openface-master\Debug folder when I compile sln file but they are too slow. Which exe file should I use in the win 32 bit version since I don't see any folder named x86? The compile said build successful, but when I run (F5) it says '....\Debug\LandMarkDetector.lib is not a valid win32 application'.

I tried setting up the 64 bit version which runs (F5) successfully without giving any error, outputs files to folder called x64 but in the folder I don't see a folder called Release. I don't have matlab to see if the matlab demo is still working since the codes seem to use exe files from \x64\Release.

 I am trying to use FaceLandMarkImg to take images and output landmark points.Any help is appreciated!!

**Comment by TadasBaltrusaitis** [comment]
Please see the Windows installation instructions for more details - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation about the Debug/Release mode and how to set up the correct executable.

You will find the exacutables in `Release` (for 32 bit in Release mode) or in `x64/Release` (for 64 bit in Release mode). If you compile the project in Debug mode the code will run much slower than in Release mode. The precompiled binaries are in Release mode, hence the image does not stay up for very long (which is intended).

**Comment by PVNathan** [comment]
Thanks. I appreciate it.
