### ISSUE TITLE
How to detect landmarks of a profile face?

### ISSUE THREAD

**Issue by EDMIG** [TadasBaltrusaitis/OpenFace#690]
Hi,

I used matlab_version\demo\face_image_demo.m on  
https://img.zcool.cn/community/01bebd5ac02bafa8012062e37696f5.jpg, 

and this demo cannot give the right result ！ How can I get the profile landmarks?

Thank you a lot!

xg

**Comment by TadasBaltrusaitis** [comment]
Hi,

The Matlab demo is not as accurate as the C++ version of the code by default (as it is quite slow). I just tried your image with the C++ version (or the Windows GUI) and the detection worked quite well:
https://www.dropbox.com/s/dgcjspuuoo3oevc/01bebd5ac02bafa8012062e37696f5.jpg?dl=0

You do need to make sure you are using `-multi_view 1` and `-wild` flags though.

Thanks,
Tadas

**Comment by EDMIG** [comment]
That's great!　I'll try!

Thanks!
