### ISSUE TITLE
NonOverlappingDetections bug

### ISSUE THREAD

**Issue by ChrizzyM87** [TadasBaltrusaitis/OpenFace#693]
Dear Tadas,

in NonOverlappingDetections() of [FaceLandmarkVidMulti.cpp](https://github.com/TadasBaltrusaitis/OpenFace/blob/master/exe/FaceLandmarkVidMulti/FaceLandmarkVidMulti.cpp) is a computation which should return the relative amount of overlap of two rectangles. The intersection area is devided by `(a.area() + b.area() - 2 * intersection_area)`. Actually it must be devided by  `(a.area() + b.area() -  intersection_area)`. Proof: In case that rectangles are the same (-> overlapping 100%) now it would lead to a division by 0. With the fix the relativ amount of overlap would by 1.

Kind regards
Christoph

**Comment by TadasBaltrusaitis** [comment]
You're absolutely right, will fix that in the next release! Thanks.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed in the new version.
