### ISSUE TITLE
OpenFaceOffline.exe is crush when input is image

### ISSUE THREAD

**Issue by abdou31** [TadasBaltrusaitis/OpenFace#694]
I get this erreur when i try to open image to test it with Openfaceoffline.exe

![image](https://user-images.githubusercontent.com/19480228/57301324-0aa04300-70d9-11e9-8b8d-7a0186e2e072.png)

How to solve this?

**Comment by TadasBaltrusaitis** [comment]
Can you provide more details for me to be able to reproduce this error? E.g. the data image you executed it on, or does it happen for all images?

**Comment by abdou31** [comment]
It happens for all images ,
Note : That I have compiled this project in windows 10 x64 and i have copied this folder that contains openface copied to my external storage and i formated my PC and i reinstall windows 10 again and i just copied from my external storage to the new windows 10 installed
I dont think that what i have do maybe give error like this .

**Comment by TadasBaltrusaitis** [comment]
Would it be possible for you to run the project with the debugger attached (e.g. from Visual Studio directly). This will allow you to better debug what might be causing the issue, by identifying which line of code is causing this.

**Comment by abdou31** [comment]
After running with debugger (visual studio 2017 ) i get this : 
![image](https://user-images.githubusercontent.com/19480228/57404968-97ccc000-71dd-11e9-86ee-00872df899f1.png)

**Comment by TadasBaltrusaitis** [comment]
It seems to fail when writing image out to disk. Could you try running OpenFace as administrator? It might be you don't have write privileges to the folder.

**Comment by abdou31** [comment]
Doesn't work also when i runing as administrator .

**Comment by TadasBaltrusaitis** [comment]
It seems that for some reason the extension to the output is not added correctly, can you untick record aligned images from output in the GUI and try again?

**Comment by abdou31** [comment]
If mean like this, it doesn't work : 
![image](https://user-images.githubusercontent.com/19480228/57692227-8b65be80-7646-11e9-8ca5-506f3c0eff7d.png)
![image](https://user-images.githubusercontent.com/19480228/57692426-07600680-7647-11e9-9aa2-aa21e1f8c131.png)

**Comment by JerryGan2** [comment]
windows8.1 
It crash when OpenFaceOffline.exe ->Files ->OpenImages.
But the Newest release build(https://github.com/TadasBaltrusaitis/OpenFace/releases/download/OpenFace_2.0.5/OpenFace_2.0.5_win_x64.zip) work well。

problem crash in 
    RecorderOpenFace.cpp 
           bool out_success = cv::imwrite(tracked_data.first, tracked_data.second); //line 106
tracked_data.first is "imagename.“. without extension.

modify RecorderOpenFaceParameters.cpp
     add 
        this->image_format_aligned = "bmp";
	this->image_format_visualization = "jpg";
   after 
       this->output_codec = "DIVX";  //line 178
may solve this problem.

**Comment by TadasBaltrusaitis** [comment]
Thanks for the info, I'm further investigating this.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed in the new version.
