### ISSUE TITLE
Build with c++17 trigger error C2872: 'byte': ambiguous symbol

### ISSUE THREAD

**Issue by wolfviking0** [TadasBaltrusaitis/OpenFace#698]
**Describe the bug**
Build openface with c++17 give an issue on my windows because std now have std::byte
https://developercommunity.visualstudio.com/content/problem/93889/error-c2872-byte-ambiguous-symbol.html

**To Reproduce**
Enable the CXX_STANDARD 17 trigger the issue

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Compiler MSVC

**Comment by TadasBaltrusaitis** [comment]
This is a clash between `byte` definition in `dlib` and in `std`, I'm fixing this issue and moving the entire codebase to C++17, the new version will have it fixed.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed in the new version.
