### ISSUE TITLE
Annotated dataset using openface

### ISSUE THREAD

**Issue by abdou31** [TadasBaltrusaitis/OpenFace#705]
Hello Tadas, 
I want to know, can i use the tool for annotated a dataset to get dataset annotated with .pts files ?
Can i generate .csv files from folder containes dataset ( folder of images .jpg for e.g) ?

Desktop (please complete the following information):
 - OS: Windows 10 x64

**Comment by TadasBaltrusaitis** [comment]
You can. This dataset will not be as accurate as a manually annotated one, but could be used for a number of purposes (especially if you filter out less reliably detected landmarks).

Have a look at `FaceLandmarkImg.exe` and https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments for instructions of how to run it on a directory of images.
