### ISSUE TITLE
Get .pts files in the output of FaceLandmarkImg

### ISSUE THREAD

**Issue by abdou31** [TadasBaltrusaitis/OpenFace#708]
Hello Tadas,
Did can Openface produce .pts files in the output of LandmarkImg.exe instead of .csv files ?

**Comment by TadasBaltrusaitis** [comment]
It can only output .csv files, you will need to convert them to .pts files yourself.

**Comment by abdou31** [comment]
Thanks,
i will try to write a script that do this task
