### ISSUE TITLE
Gaze detection with external camera of drone

### ISSUE THREAD

**Issue by lalnlnlal** [TadasBaltrusaitis/OpenFace#71]
Hi,
I want to use camera images of parrot ar.drone2.0 to detect gaze. Therefore I tried to find out what camera parameters I have to apply. I tested some using the results of camera calibration with cvdrone but always got this output: 
gaze: dir_x_1, dir_y_1, dir_z_1, dir_x_2, dir_y_2, dir_z_2: 
{
0 0 -1 0 0 -1
}
My command was:
FaceLandmarkImg.exe -wild -f imgPath -opdir pathImgOutputFolder -fx 2.7959376513743410e+02 -fy 3.0948599148582457e+02 -cx 2.7102375847878392e+02 -cy 1.2960254224575255e+02
Can you please explain me if there is a possibility to detect gaze on images using adapted camera parameters? I'm also not sure if my solution determining them is correct.

Thanks a lot,
Anna

**Comment by TadasBaltrusaitis** [comment]
Gaze detection is not performed if the image of a face is too small or if the face tracking is unreliable. For best results you want to have a face that is at least 120-150 pixels across and roughly facing the camera. How big are the faces in the image? Can you post a sample image?

Thanks,
Tadas

**Comment by lalnlnlal** [comment]
Thanks for your answer. The picture was too small then, the face hat only about 80 pixels. I'll try it again!

**Comment by lalnlnlal** [comment]
I tried it again with better images but unfortunately still have the same problem. Here is am sample image I got as a result. 

![frame2_det_0](https://cloud.githubusercontent.com/assets/5907195/18829128/2c45b4b0-83db-11e6-866a-1bb5cfdee7c7.jpg)

And the output of the landmarks. Perhaps you can recognize a problem?
version: 1
npoints: 68
{
245.767 133.121
246.689 158.651
250.258 183.213
255.418 207.06
263.981 229.911
278.008 250.452
295.43 268.061
316.193 282.218
339.017 286.377
359.453 282.497
375.594 268.284
390.98 250.127
404.734 229.504
414.816 206.405
421.425 181.733
426.236 156.255
428.418 130.371
257.778 108.332
271.947 98.1885
291.45 96.4407
310.89 100.003
328.338 106.794
367.657 106.008
384.347 99.1366
400.508 96.3101
415.989 98.6546
426.077 108.305
347.899 128.666
349.018 149.54
350.237 170.327
351.395 191.262
326.815 198.853
337.106 203.379
347.65 206.682
357.743 203.462
366.551 199.339
276.759 128.941
288.538 120.985
304.226 121.975
316.349 132.672
303.182 136.021
287.643 135.733
373.102 132.455
385.3 121.407
399.662 121.3
409.021 128.65
400.703 135.319
386.561 135.699
307.744 231.545
324.081 228.035
337.491 225.623
346.105 228.183
355.313 225.3
366.664 227.702
377.177 230.658
366.823 241.516
355.378 246.285
345.563 247.43
336.014 246.514
322.861 241.961
314.346 232.858
336.585 233.702
345.618 234.641
354.9 233.269
371.979 232.133
354.853 233.344
345.598 234.713
336.467 233.498
}
pose: eul_x, eul_y, eul_z: 
{
0.355002 -0.0828761 0.0175566
}
gaze: dir_x_1, dir_y_1, dir_z_1, dir_x_2, dir_y_2, dir_z_2: 
{
0 0 -1 0 0 -1
}
au intensities: 17
{
AU01 1.38016
AU02 0.592323
AU04 0.423216
AU05 1.84649
AU06 0
AU07 0
AU09 0
AU10 0
AU12 0
AU14 0
AU15 0.204934
AU17 0.347759
AU20 0
AU23 0.750617
AU25 0
AU26 0.576885
AU45 0
}
au occurences: 18
{
AU01 0
AU02 1
AU04 1
AU05 1
AU06 0
AU07 1
AU09 0
AU10 0
AU12 0
AU14 0
AU15 0
AU17 0
AU20 0
AU23 0
AU25 0
AU26 0
AU28 0
AU45 0
}

Thanks,
Anna

**Comment by TadasBaltrusaitis** [comment]
I realized what's happening, you need to specify `-gaze` in the command line to enable gaze tracking in image mode.

Thanks,
Tadas

**Comment by lalnlnlal** [comment]
Thanks for your answer, I worked through the code this morning and also found it as the solution.

Best regards,
Anna
