### ISSUE TITLE
Are cen_patches necessary for build time?

### ISSUE THREAD

**Issue by xkortex** [TadasBaltrusaitis/OpenFace#712]
I'm cleaning up and optimizing the dockerfile. I'd like to move the cen_patches (e.g. https://www.dropbox.com/s/7na5qsjzz8yfoer/cen_patches_0.25_of.dat) to the very end to improve build speed and layer size. Is that going to cause any problems with the cmake step?

**Comment by TadasBaltrusaitis** [comment]
Cmake step does move the cen patch experts to the correct directory (from the lib to the bin folder), it does so with other model files as well (e.g. the PDMs). 

However, this step could be changed so that copy takes place at the end (or even during the make step)

**Comment by xkortex** [comment]
That's fine, just wanted to know ahead of time before I started messing with things too much. 

dlib can be compiled from any directory, it does not need to exist in OPENFACE_DIR, correct?

**Comment by TadasBaltrusaitis** [comment]
Yes, an externally built dlib can be linked, and it does not need to exist in OPENFACE_DIR

**Comment by xkortex** [comment]
Alright, after playing around with the dockerfile, I think I have a pretty good handle on the setup at this point. 

PR for the dockerfile incoming!
