### ISSUE TITLE
Meaning of fx, fy, cx, cy in ImageCapture

### ISSUE THREAD

**Issue by sziraqui** [TadasBaltrusaitis/OpenFace#716]
I see these float attributes in many places. What do they mean? I am writing nodejs bindings for OpenFace hence I need to understand the codebase thoroughly.

**Comment by TadasBaltrusaitis** [comment]
They are camera calibration parameters that you can find described here:
https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html
