### ISSUE TITLE
compile under VS2017, windows 

### ISSUE THREAD

**Issue by yuqi98** [TadasBaltrusaitis/OpenFace#717]
I'm using Visual Studio Community 2017 15.9.12, and I downloaded the branch "feature/VS2017_changes". Then I'm trying to compile OpenFace using OpenFace_vs2017.sln, it compiles successfully but when I'm trying to run the code execution, it throws out an error: 

The code execution cannot proceed because opencv_world340.dll was not found. 

Do you know how to solve this?

**Comment by igorlpa** [comment]
I am facing the same problem

**Comment by igorlpa** [comment]
This problem happens when the one accepts the VS updates the projects. If you cancel the update, the projects will run

**Comment by TadasBaltrusaitis** [comment]
I'm working on moving OpenFace to be VS2017 natively and this issue will be fixed in the next release.
