### ISSUE TITLE
Problem with C++ API, VS2015

### ISSUE THREAD

**Issue by mauman** [TadasBaltrusaitis/OpenFace#720]
**Describe the bug**
I am using the OpenFace API in C++ with VS2015. Everything works in Debug mode but the same code in Release mode give the following exception:

OpenFace2Extractor: E:\Opencv3.4\opencv-master\modules\core\src\matmul.cpp:1218: error: (-215) type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3)) in function cv::gemmImpl

The exception happens in the FaceAnalyser when the method AddNextFrame is invoked from my code.

Any ideas about how to solve it?

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Compiler VS2015 U3, C++

**Additional context**
The problem appears in Release version only.

**Comment by TadasBaltrusaitis** [comment]
Does it happen on any input or only for particular image/video?

**Comment by mauman** [comment]
I am using it with webcam input, it would be difficult for me to test it in my application with a different type of input.
If you have any hint about the error (maybe you have seen it before) that would be really helpful.
Thanks in advance,
Maurizio

**Comment by mauman** [comment]
Hi,
another update,
the error seems to happen also in Debug mode, on the following line:
pdm.CalcParams(params_global, params_local, detected_landmarks);

**Comment by mauman** [comment]
Ok,
I solved the problem, which depended, apparently, on the input image I was proving to the functions, which was a BGR image instead of a RGB image.
After changing it to RGB it started to work.
Thanks in any case, your answer pointed me in the right direction to find the problem!
Regards,
Maurizio

**Comment by TadasBaltrusaitis** [comment]
This is really strange, are you sure the issue was RGB vs. BGR? I wouldn't expect that to cause an issue, could it have been something like RGBA?
