### ISSUE TITLE
OpenFace is not open source software

### ISSUE THREAD

**Issue by wmww** [TadasBaltrusaitis/OpenFace#721]
Despite the name and being described as open source in the readme header, OpenFace is not open source software. Open source software can be given away, sold, modified and used by anyone for any purpose ([Wikipedia](https://en.wikipedia.org/wiki/Open-source_software), [the Open Source Initiative](https://opensource.org/osd)). The [OpenFace license](https://github.com/TadasBaltrusaitis/OpenFace/blob/master/OpenFace-license.txt) clearly states that it is proprietary software and can only be used for "noncommercial internal research purposes", therefore it is not open source.

Please either license OpenFace with an [open source license](https://opensource.org/licenses/category), or correct the readme. Ideally it should clearly state that OpenFace is proprietary software to avoid confusion.

**Comment by TadasBaltrusaitis** [comment]
Depends on whose definition of "open source" you follow. For example OpenFace would be consider open source based on following definition - https://www.greennet.org.uk/support/open-source-vs-proprietary-software, as it is not closed source.

Even the article in Wikipedia you linked to states that (https://en.wikipedia.org/wiki/Open-source_software#Open-source_versus_source-available) this term is used 

> to refer to software where the source is available for viewing, but which may not legally be modified or redistributed

**Comment by wmww** [comment]
If you don't chop off half the sentence, the quote reads:

> Although the OSI definition of "open source software" is widely accepted, a small number of people and organizations use the term to refer to software where the source is available for viewing, but which may not legally be modified or redistributed

* I'm all for descriptivism, but it takes more than a few people being wrong to redefine a term
* You won't find a major company (Microsoft, Google, Facebook, etc) or organization (FSF, Mozilla, etc) misusing "open source"

**Comment by TadasBaltrusaitis** [comment]
It was not my intention to confuse anyone, I just used the term as I understood it, thanks for the clarification. I amended the Readme.md.
