### ISSUE TITLE
Difference between ImageCapture and SequenceCapture

### ISSUE THREAD

**Issue by sziraqui** [TadasBaltrusaitis/OpenFace#722]
Both seem to provide the same functionality. When should I prefer one over the other?

**Comment by TadasBaltrusaitis** [comment]
The functionality is not the same, as the name states ones of for reading individual images (either single images or a collection of images in a folder). The other is fore reading sequences (either from webcam/video file/or collection of images in a folder that form a sequence).

**Comment by sziraqui** [comment]
Ok got it. Thanks. The comments in the code confused me.
