### ISSUE TITLE
PDM_68.txt arrangement

### ISSUE THREAD

**Issue by Shaunlipy** [TadasBaltrusaitis/OpenFace#726]
Hi, I'm wondering how is the 68 3D facial landmarks arranged in the "In-the-wild_aligned_PDM_68.txt" file.

Is it starting from line 5, and goes like:
[
x1 = -73.393523 
y1 = -72.775014 
z1 = -70.533638 
x2 = -66.850058 
y2 = -59.790187 
z2 = -48.368973 
...
]

or it is like:
[
x1,
x2, 
...
y1,
y2,
...
z1,
z2
...
]

Thanks

**Comment by TadasBaltrusaitis** [comment]
It is the latter [x1,x2,x3...x68, y1,y2...,z1,z2...]
