### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by arashtavakoli** [TadasBaltrusaitis/OpenFace#731]
Hi and thanks for this amazing software. I am using the windows version and I was wondering whether is a way that I can stop the app to save nothing but the CSV output? I am running it on a lot of videos and I don't want it to save all the other files as they take a lot of space and makes it difficult to delete it afterward.

**Comment by TadasBaltrusaitis** [comment]
Hi, you can specify what to output in the command line, please have a look at - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#featureextraction-and-facelandmarkvidmulti

For example if you want only what is in the CSV file, append the command line with `-2Dfp -3Dfp -pdmparams -pose -aus -gaze`
