### ISSUE TITLE
Build fails if Boost is found due to stdc++fs not linking

### ISSUE THREAD

**Issue by xkortex** [TadasBaltrusaitis/OpenFace#733]
**Describe the bug**
With Boost installed, `if(${Boost_FOUND})` evaluates true, causing `local/whatever/CMakeLists.txt` to take the first path below, which blows up when it tries to link std::filesystem stuff : 

```cmake
if(${Boost_FOUND})
	target_include_directories(LandmarkDetector PUBLIC ${Boost_INCLUDE_DIRS})
	target_link_libraries(LandmarkDetector PUBLIC ${Boost_LIBRARIES})
	MESSAGE(WARNING "Using BOOST in LMD - stdc++ fails to link")
else()
	target_link_libraries(LandmarkDetector PUBLIC stdc++fs)
	MESSAGE(WARNING "Using FS in LMD. Linking stdc++fs")
endif()
```

**To Reproduce**
Install usual dependencies, g++8,  libboost-all-dev. Cmake and build as usual.  

**Expected behavior**
successful build 

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Version latest develop
 - Compiler g++ (Ubuntu 8-20180414-1ubuntu2) 8.0.1 20180414 (experimental) [trunk revision 259383]

**Additional context**
Looks like linking against stdc++fs fixes the problem 

```cmake
if(${Boost_FOUND})
	target_include_directories(LandmarkDetector PUBLIC ${Boost_INCLUDE_DIRS})
	target_link_libraries(LandmarkDetector PUBLIC ${Boost_LIBRARIES} stdc++fs)
	MESSAGE(WARNING "works cause I added stdc++fs to target_link")
else()
	target_link_libraries(LandmarkDetector PUBLIC stdc++fs)
endif()
```

**Comment by TadasBaltrusaitis** [comment]
As mentioned in the PR, the fix is not as simple as including stdc++fs if boost is found, as some systems do not have stdc++fs even if they support C++17 with g++ compiler - https://stackoverflow.com/questions/49577343/filesystem-with-c17-doesnt-work-on-my-mac-os-x-high-sierra

**Comment by xkortex** [comment]
Huh, had no idea. So on OSX, you have to have Boost installed, but without the stdc++fs link command?

Would something like this work?

```cmake
if(${some_criteria_for_stdcfs})
	target_link_libraries(Utilities PUBLIC stdc++fs)
elseif(${Boost_FOUND})
	target_include_directories(Utilities PUBLIC ${Boost_INCLUDE_DIRS})
	target_link_libraries(Utilities PUBLIC ${Boost_LIBRARIES})
else()
	MESSAGE(FATAL_ERROR "Must either link against stdc++fs or Boost.Filesystem")
endif()
```

where `some_criteria` might be `LINUX` or some other better indicator of which fs to link against.

**Comment by TadasBaltrusaitis** [comment]
Yes, I believe something like this would work, I just don't know a good criteria to determine if stdc++fs is in the system (although I'm sure there must be a way). A last resort option could be if it's `LINUX`, but that feels less elegant compared to actually checking if the library is available (as compiling with certain versions of Clang on OSX would actually work).

**Comment by TadasBaltrusaitis** [comment]
This should be fixed in develop now. I changed it so that boost is used if it is installed and only use std::filesystem if it is not. This should resolve the issue on various OS without the need for a CMake check.
