### ISSUE TITLE
Gaze - Question

### ISSUE THREAD

**Issue by arashtavakoli** [TadasBaltrusaitis/OpenFace#739]
This is great software and thanks for providing it. I tried the code on many videos. It is interesting how sometimes the output does not include gaze at all. What would cause such an issue? I understand that if for instance, the person wears glasses that could be the case that it won't detect the gaze, but what are the other cases? Also, does the code written in a way that if the gaze is not detected, there would be no gaze column in output at all? I have all the other outputs but not gaze.

**Comment by TadasBaltrusaitis** [comment]
Hi, 

Even if the gaze is not detected there should be a gaze column (if the command line parameters specify gaze to be output, which they do by default). Further, if same arguments are used the same output columns should always be present. 

Can you give specific examples when gaze column is not found? That is the exact command line arguments used, the input videos/images and output.

**Comment by arashtavakoli** [comment]
I think I made a mistake about the command lines at that time. I am closing this issue. Thanks!
