### ISSUE TITLE
static linking issue

### ISSUE THREAD

**Issue by PVNathan** [TadasBaltrusaitis/OpenFace#74]
Hi Tadas,

I was wondering if any of your project files is linked dynamically? or are they all static links? I don't see any dll in your project but wanted to confirm. I am trying to use your LandmarkImage.cpp code with my own code that does something after face detection. 

Thanks

**Comment by TadasBaltrusaitis** [comment]
The code is statically linked although it uses dynamic libraries for OpenCV, and TBB. It is possible to convert it to dynamic linking, but it will take a bit of coding.

Thanks,
Tadas

**Comment by PVNathan** [comment]
Thanks
