### ISSUE TITLE
Feature extraction doesn't work 

### ISSUE THREAD

**Issue by ElaheMrz** [TadasBaltrusaitis/OpenFace#744]
FeatureExtractor for images does not produce the right features, the features for all faces are the same and aligned images which are saved are just black images.

and also the FaceLandmarkImg does not produce a CSV file.

**Comment by TadasBaltrusaitis** [comment]
For individual image analysis (not images coming from a video sequence), please use FaceLandmarkImg executable.

Further, can you provide more details on the error you are facing? What OS you are using, what version of OpenFace (binaries or built from code) and what are the exact command line arguments you used.

**Comment by ElaheMrz** [comment]
the images were from a video sequence, and I tried both on MAC and Ubuntu, but I found that the problem occurred bcz of image size. they were 50*50 and when I resized them to 100*100 the problem was solved.
