### ISSUE TITLE
Multi face detection

### ISSUE THREAD

**Issue by ghost** [TadasBaltrusaitis/OpenFace#75]
Hi OpenFace committee,

Please let me know how can I active the multi-face detection in OpenFace?
I actually work with some video files containing 2 people.

Thanks.

Regards,
Omid

**Comment by TadasBaltrusaitis** [comment]
Have a look at the `FaceLandmarkVidMulti` project and executable, it is designed for tracking and detecting multiple faces in videos.

Thanks,
Tadas
