### ISSUE TITLE
download_libraries.ps1 PowerShell script

### ISSUE THREAD

**Issue by Wini1680** [TadasBaltrusaitis/OpenFace#750]
sorry I don‘t see the file named download_libraries.ps1 in OpenFace_2.2.0/OpenFace_v2.2.0_win_x64.zip ,and I just see it in the master,so I download the file and run it in the powershell, but I got a Flashed in the screen😢

**Comment by TadasBaltrusaitis** [comment]
Did you run `./download_models.ps1`? All the libraries are already packaged with the binaries so you don't have to run `./download_libraries.ps1`.

What do you mean by "flashed in the screen"?

**Comment by mikila85** [comment]
OpenFace_2.2.0_win_x64>python3 download_models.ps1
  File "D:\miki\ai\OpenFace_2.2.0_win_x64\download_models.ps1", line 4
    if([System.IO.Directory]::Exists( (Join-Path (Get-Location) 'lib') ))
                            ^
SyntaxError: invalid syntax

**Comment by kendrew06** [comment]
您的邮件我已收到，有需要会尽快回复This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by TadasBaltrusaitis** [comment]
Hi, this is not a python script, rather a PowerShell one, you can execute it in powershell

**Comment by RJahedan** [comment]
Hi, I downloaded the OpenFace_2.2.0_win_x64, but I cannot find the download_libraries.ps1 to execute for dependency download. I also run the download_models.ps1 with PowerShell, but it will exit with an error very fast. What step do you think I am missing?
