### ISSUE TITLE
Question about the license (usage in videos)

### ISSUE THREAD

**Issue by DenchiSoft** [TadasBaltrusaitis/OpenFace#751]
Thank you for your amazing work! I've had a lot of fun playing around with OpenFace for the last couple days.

I'm working on an open source project that uses face tracking to animate 2D characters accordingly (think free and open source [FaceRig ](https://facerig.com/)). Currently I rely on dlib for tracking, which works well enough but doesn't compare to OpenFace in terms of speed and tracking stability.

My project will be open source and I don't plan on selling anything. However, the idea is that people use the software to create videos that are then uploaded to video hosting sites including YouTube. Would that be in violation of your license or would it be okay? I'm asking because videos could potentially be monetized through ads on YouTube. Please let me know what you think. 

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

Great to hear that you enjoyed using OpenFace!

I'm not a lawyer so can't answer the question very well.  From my understanding if you are not using it commercially yourself, that should be fine. It is up to the people monetizing the videos to acquire the required licenses. 

However, I would suggest you get in touch with Cindy Chepanoske who would be able to better answer your question:
cchepano@andrew.cmu.edu

**Comment by DenchiSoft** [comment]
Thank you for the reply! I'll get in touch with her.
