### ISSUE TITLE
Proper Usage of SequenceCapture OpenWebcam

### ISSUE THREAD

**Issue by jonelkhoury** [TadasBaltrusaitis/OpenFace#753]
Hi Tadas,

Great work with the library so far. Does a lot of things that I need it to do for my school project. 

However, I'm in need of assistance regarding the proper usage of the OpenWebcam method in SequenceCapture. I'm attempting to get a live stream from a webcam and at the moment I'm simply trying to open it and seem to be having no luck doing so.

Below is my code:

#include "SequenceCapture.h"
#include <iostream>

int main()
{

	Utilities::SequenceCapture video;

	if(video.OpenWebcam(0))
	{
		std::cout << "Open" << std::endl;

	}

	return 0;

}

When compiled and run, I seem to be getting a segmentation fault. Also side question, but is OpenFace no longer compatible with OpenCV 3.4.0? 

Thanks for your assistance! 

Edit: Forgot to mention that is being done on Ubuntu 18.04 with OpenCV 4.1

**Comment by TadasBaltrusaitis** [comment]
That should work. Do you have any more details about the error (e.g. what line is causing it)?

It should still work with OpenCV 3.4.0, but the official supported version of OpenCV is 4.1.0 and I make sure to test the functionality on that version of OpenCV.

**Comment by jonelkhoury** [comment]
Thanks for the reply!

I'm not sure what the issue was but I ended up removing OpenCV completely and reinstalling it and it seemed to work. 

Also I was having trouble getting anything to link properly when I was compiling OpenCV with the BUILD_SHARED_LIBS=OFF flag and after turning it on it worked splendidly. Is there any particular reason why in your instructions you include that particular flag? For lack of better words, will this end up biting me in the butt later on?

**Comment by TadasBaltrusaitis** [comment]
Glad you managed to resolve the issue.

I don't actually remember the reason for that instruction. I think it was merely to speed up the build, but this should not cause issues down the line.
