### ISSUE TITLE
eye gaze estimation problem

### ISSUE THREAD

**Issue by Angel113110** [TadasBaltrusaitis/OpenFace#758]
Dear author
    I'm doing a project. It's about finding wonderful moment in class video through analyse. I used OpenFace for extracting facial features. Now, I have obtained feature about eyes. I want to judge when the person in the video is watching the screen. How can I use the gaze data obtained through OpenFace? Can you give me a solution?

**Comment by Angel113110** [comment]
The feature eye_gaze_angle_x and eye_gaze_angle_y I obtained are between (-1,1). Is this mean (-1,1) is the whole range you designed?

**Comment by TadasBaltrusaitis** [comment]
Hi,

There is currently no support of estimating the location of the gaze on the screen, have a look at the following issues for explanation of eye gaze:
https://github.com/TadasBaltrusaitis/OpenFace/issues/396
https://github.com/TadasBaltrusaitis/OpenFace/issues/24
https://github.com/TadasBaltrusaitis/OpenFace/issues/20

**Comment by Angel113110** [comment]
Thanks for your quickly reply. I will try other methods.

**Comment by xiakj** [comment]
@TadasBaltrusaitis hi, the openface2.0 is an excellent work. By the way, the gaze output in OpenFaceOffline is one, that is left-right, up-down, but there is two eyes, left eye and right eye. how you get the final gaze result?

**Comment by TadasBaltrusaitis** [comment]
The eye gaze estimate is average of the two eyes.
