### ISSUE TITLE
Integration with Intel Neural Compute Stick

### ISSUE THREAD

**Issue by R00iBaard** [TadasBaltrusaitis/OpenFace#762]
Hey,

I have OpenFace running on my Raspberry Pi 3 but would love to get more performance out - getting shocking video performance but kinda expected. Has anyone got it running using the Compute stick? Any tips?

Thanks!

**Comment by R00iBaard** [comment]
I think to explain it better... it looks like 90% of the overall usage on arm32 (rpi) is spent doing face detection, I would love to move this over to the VPU (vision processing unit). Any assistance/tips from anyone who succeeded with this would be much appreciated

**Comment by TadasBaltrusaitis** [comment]
You could actually change the face detector used by OpenFace, it comes with three options for face detectors:
- OpenCV Haar cascade based (least accurate but fastest)
- Dlib based HoG (mid range on both accounts)
- MTCNN (slowest CNN based model, but also the most accurate)

You can set what face detector should be used through (e.g.):
	
        LandmarkDetector::FaceModelParameters det_params(arguments);
        det_params.curr_face_detector = LandmarkDetector::FaceModelParameters::MTCNN_DETECTOR;

**Comment by R00iBaard** [comment]
> You could actually change the face detector used by OpenFace, it comes with three options for face detectors:
> 
> * OpenCV Haar cascade based (least accurate but fastest)
> * Dlib based HoG (mid range on both accounts)
> * MTCNN (slowest CNN based model, but also the most accurate)
> 
> You can set what face detector should be used through (e.g.):
> 
> ```
>     LandmarkDetector::FaceModelParameters det_params(arguments);
>     det_params.curr_face_detector = LandmarkDetector::FaceModelParameters::MTCNN_DETECTOR;
> ```

Thanks so much for the feedback. 

![OpenFaceDemo](https://user-images.githubusercontent.com/11412240/64682605-0bc7ef00-d482-11e9-9133-41b55d6ec5cb.gif)

As per  video above it runs fine when I dont move around much, moving a little will force the face detect to work harder hence causing a large delay - as expected. This is why I want to move face detect off to the VPU (Intel neural compute stick). This video is me running HAAR and -mloc "model/main_clm_general.txt" which has proven to work the best on rpi.

**Comment by R00iBaard** [comment]
Sorry, another question... please could someone explain what use_face_template is? I noticed a much bigger improvement reacting to head movement when this is enabled.

**Comment by TadasBaltrusaitis** [comment]
`use_face_template` instructs the tracker to create a face template (basically the image around a bounding box of the face) that is used with very simplistic correlation based template tracker. This template tracker finds the face motion in x,y plane and scale. This allows the model to be better initialized under that sort of motion. When framerate is high enough this effect is not noticeable, but when dealing with really low frame rate (motion of face is much larger between frames) it helps in some instances (as you noticed)

**Comment by R00iBaard** [comment]
Great stuff. Thanks for the explanation.
