### ISSUE TITLE
2D pupil center Landmark Detection

### ISSUE THREAD

**Issue by Madankumar90** [TadasBaltrusaitis/OpenFace#765]
Hey Tadas,
Is it possible to detect 2d pupil center as a landmark by CLNF method?? I came across it can be done by using SDM method. Any leads on this?? 

thanks,
Madan

**Comment by TadasBaltrusaitis** [comment]
You can detect pupil center in OpenFace (it uses CLNF for eye region landmark detection). Have a look at gaze related landmarks:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#csv-file

While you don't explicitly get the pupil center, you can average all the pupil landmarks to get teh location of the center.

**Comment by Madankumar90** [comment]
Thank you Tadas.
