### ISSUE TITLE
Eye Center and Pupil Center

### ISSUE THREAD

**Issue by Madankumar90** [TadasBaltrusaitis/OpenFace#766]
Hey Tadas,
Are eye centers and pupil centers different?? I think anatomically they aren't. But in the GazeEstimation.cpp snippet,
//
cv::Mat eyeballCentreMat = (faceLdmks3d.row(36+eyeIdx*6) + faceLdmks3d.row(39+eyeIdx*6))/2.0f + (cv::Mat(rotMat)*offset).t();
cv::Point3f eyeballCentre = cv::Point3f(eyeballCentreMat);
cv::Point3f gazeVecAxis = RaySphereIntersect(cv::Point3f(0,0,0), rayDir, eyeballCentre, 12) - eyeballCentre;
	gaze_absolute = gazeVecAxis / norm(gazeVecAxis);
//
What exactly is eyeballcenter here exactly?? i Know this is eye ball sphere in 3D and used in finding the intersection. But is it the Eye center or it is different?? I am bit confused.

Thanks,
Madan

**Comment by TadasBaltrusaitis** [comment]
The eyeball center is the actual center of the eyeball "sphere", while the pupil center is the center of the pupil opening (the part of the eye through which the light goes into the retina - https://en.wikipedia.org/wiki/Pupil). So they're quite different.

What do you mean by eye center?

Thanks,
Tadas
