### ISSUE TITLE
build error on Linux

### ISSUE THREAD

**Issue by georgesterpu** [TadasBaltrusaitis/OpenFace#775]
**Describe the bug**
The build process stops at 86% with the following error:
```
[ 86%] Linking CXX executable ../../bin/FaceLandmarkImg
/usr/bin/ld: /usr/lib/libopencv_videoio.so.4.1.1: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
/usr/bin/ld: /usr/lib/libopencv_flann.so.4.1.1: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()@GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
make[2]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:111: bin/FaceLandmarkImg] Error 1
make[1]: *** [CMakeFiles/Makefile2:298: exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**To Reproduce**
Download OpenFace 2.2.0 from github
cmake ... & make

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: testing (nearly bleeding edge)
 - Compiler g++8

I am using the same setup used in the past for building OpenFace 1.0, 2.0.x and 2.1

**Comment by georgesterpu** [comment]
I found this bug report, the problem seems related to the opencv library that I am using:
https://bugs.archlinux.org/task/63408
comment # 7 explains the issue

**Comment by georgesterpu** [comment]
GCC 9.1.0 compiles OpenFace 2.2.0 without errors or warnings, so that solves the problem for me.

**Comment by tashrifbillah** [comment]
I am trying gcc-9.3.0, OpenCV 4.1.0 and OpenFace master branch but I still get the reported error!
