### ISSUE TITLE
Get Euclidean distance between facial landmarks

### ISSUE THREAD

**Issue by wangx172** [TadasBaltrusaitis/OpenFace#779]
Hello,

I would like to measure facial rigidity to see how much a person's face changes. Ideally, I will calculate the changes in the Euclidean distances between facial landmarks. 

However, some people in my videos moved closer to the camera or turned their head, so I don't think using 2D landmark locations makes sense. Does "Landmarks locations in 3D" mean the 3D locations of the 68 facial landmarks? Should I use "Landmarks locations in 3D" instead to calculate the distance changes? Any suggestions will help!

Thank you very much!

**Comment by TadasBaltrusaitis** [comment]
Yes, that's exactly right. you should be using the 3D locations which are in millimeters and should not be affected as much by distance to camera and face turning (they will still be slightly affected as the 3D landmark location is only an estimate based on camera calibration and assumed average size of a face)

**Comment by wangx172** [comment]
Thank you! This is very helpful
