### ISSUE TITLE
Unable to build OpenFace on rpi4

### ISSUE THREAD

**Issue by R00iBaard** [TadasBaltrusaitis/OpenFace#781]
Hi there, so quick history - I have built and run OpenFace successfully on rpi3. Im now trying to get it to build and run on the pi 4. I can run it there (it runs really well!!) if I copy over the bin dir but I need to be able to build as well.

I am running into the following issue during 

`cmake -D CMAKE_CXX_COMPILER=g++-8 -D CMAKE_C_COMPILER=gcc-8 -D CMAKE_BUILD_TYPE=RELEASE ..`

I get the following output 

`-- Found OpenBLAS libraries: /opt/OpenBLAS/lib/libopenblas.so
-- Found OpenBLAS include: /opt/OpenBLAS/include
OpenBLAS information:
  OpenBLAS_LIBRARIES: /opt/OpenBLAS/lib/libopenblas.so
  OpenBLAS_INCLUDE: /opt/OpenBLAS/include
OpenCV information:
  OpenCV_INCLUDE_DIRS: /usr/local/include/opencv4
  OpenCV_LIBRARIES: opencv_core;opencv_imgproc;opencv_calib3d;opencv_highgui;opencv_objdetect
  OpenCV_LIBRARY_DIRS: 
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   filesystem
--   system
Boost information:
  Boost_VERSION: 106700
  Boost_INCLUDE_DIRS: /usr/include
  Boost_LIBRARIES: /usr/lib/arm-linux-gnueabihf/libboost_filesystem.so;/usr/lib/arm-linux-gnueabihf/libboost_system.so
  Boost_LIBRARY_DIRS: /usr/lib/arm-linux-gnueabihf
dlib information:
  dlib version: 19.13.0
-- Standalone mode detected; Enabling configuration/targets export.
-- Configuring done
CMake Warning at exe/FaceLandmarkImg/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target FaceLandmarkImg
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libopenblas.so] in /usr/lib/arm-linux-gnueabihf may be hidden by files in:
      /opt/OpenBLAS/lib

  Some of these libraries may not be found correctly.

CMake Warning at exe/FaceLandmarkVid/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target FaceLandmarkVid
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libopenblas.so] in /usr/lib/arm-linux-gnueabihf may be hidden by files in:
      /opt/OpenBLAS/lib

  Some of these libraries may not be found correctly.

CMake Warning at exe/FaceLandmarkVidMulti/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target FaceLandmarkVidMulti
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libopenblas.so] in /usr/lib/arm-linux-gnueabihf may be hidden by files in:
      /opt/OpenBLAS/lib

  Some of these libraries may not be found correctly.

CMake Warning at exe/FeatureExtraction/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target FeatureExtraction
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libopenblas.so] in /usr/lib/arm-linux-gnueabihf may be hidden by files in:
      /opt/OpenBLAS/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/pi/Documents/OpenFace/OpenFace/build`

So as you can see im having some issues where its trying to find OpenBLAS. Any ideas? I dont recall running into this during my process on pi 3.

**Comment by TadasBaltrusaitis** [comment]
Did you have to install OpenBLAS yourself? It seems like the installation of Blas somehow hid the libraries? I wonder if you could skip the explicit OpenBLAS installation step?

Also I'm curious to know how well OpenFace runs on RPI4. What models are you using for it and what FPS could you reach?

**Comment by R00iBaard** [comment]
Hey, sorry for the late reply. Dont remember the exact steps other than manually copying libopenblas.so in both /usr and /opt.... one of the options worked hahaha

Anyway, regarding rpi4... just wow! Runs INCREDIBLY well considering! I would say roughly double the performance. As per usual, using the basic landmark (mloc general) and face detect (haar) but with gaze and AUs enabled we are getting 10 fps! Extremely impressed. This is on the 4gig variant.
