### ISSUE TITLE
OpenFaceOffline Webcam Feed non-functional.

### ISSUE THREAD

**Issue by michaelDau** [TadasBaltrusaitis/OpenFace#787]
Hello!  First of all, thank you SO much for making this opensource.  This is precisely what I need to help me with my research. 

Now, for my problem: 
OpenFaceDemo works perfectly with my webcam.  OpenFaceOffline works perfectly with everything EXCEPT my webcam, and I was really hoping to use it to evaluate live video.  I can't seem to find anything wrong with webcam access rules, so I was wondering if this is an existing issue?

Also, separate note: Is there a way to slow the analysis of a picture or video in the application other than pausing the video (individual pictures process so fast that I can't click pause), so that I can see the AU data displayed next to the picture/video as it's being analyzed?  

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Some people have been reporting issues with the webcam, but I have not managed to narrow the error down (I do not experience any issues my end).

Are you using the pre-built binaries or building the project yourself? If the latter could you run it in debug mode and report the exact issue you are encountering.

Thanks,
Tadas

**Comment by michaelDau** [comment]
I'm using the Binaries

**Comment by TadasBaltrusaitis** [comment]
At what stage does it crash? After or before webcam selection screen? Do you have multiple webcams connected or just the one?

**Comment by michaelDau** [comment]
Actually, it doesn't exactly crash.  The preview window for the webcam just
shows a black screen and once selected, the feed is just static and never
actually seems to access/activate the webcam.  I'm using a single,
integrated webcam on an Alienware laptop.

**Comment by michaelDau** [comment]
Here is what I see when I choose the webcam option on OpenFaceOffline.  First, like I said, it just shows a black screen, unlike OpenFaceDemo, which shows my face.

![image](https://user-images.githubusercontent.com/32072809/66847327-34d81580-ef41-11e9-9d08-d432b7348a64.png)

Then, if I click "select camera" I see this:

![image](https://user-images.githubusercontent.com/32072809/66847394-4e795d00-ef41-11e9-9fb6-67cd95031f58.png)

**Comment by TadasBaltrusaitis** [comment]
Thanks for the info, I haven't seen this error before but will investigate the difference of OpenFaceDemo and OpenFaceOffline, it is really strange that one works and the other does not.

**Comment by michaelDau** [comment]
Thank you very much!  Please let me know if there is any more information I can provide to assist you!

**Comment by michaelDau** [comment]
@TadasBaltrusaitis 
I had my friend try running the software on his laptop and both Demo and Offline are able to successfully use his integrated webcam, so it seems that this is in fact something on my end.  I will investigate further and let you know.  If you have any theories, I'd appreciate them! :)

**Comment by michaelDau** [comment]
Actually, even more surprising: Although I have done this before, I just deleted the software, re-downloaded/extracted it, again downloaded the models using the powershell script, and now, for whatever reason, it all functions as expected.  

I don't know why it is now functioning, but I will not question it! Thank you so much for your help!
