### ISSUE TITLE
Face alignement problem in 3D

### ISSUE THREAD

**Issue by abdou31** [TadasBaltrusaitis/OpenFace#789]
**Describe the bug**
Hello Tadas, 
As you know, I have used OpenFace project for the annotation of my dataset to detect the eye region

. 
The problem is on the 3D model as you can see in the two images below, the tool gives me a false prediction.
Did you provide a parameter on your tool to solve this problem ( face alignment)?

Did can the pre-trained model solve the problem?

**Screenshots**
![flddd](https://user-images.githubusercontent.com/19480228/66760710-eecc7480-eea2-11e9-834f-19005463e5f2.PNG)
![flse](https://user-images.githubusercontent.com/19480228/66760711-eecc7480-eea2-11e9-875d-62d780cc271f.PNG)
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 x64
 - Version [e.g. 22] Openface 2.2.0
 - Compiler [if compilation or linker error]

**Comment by TadasBaltrusaitis** [comment]
Sorry, I'm not entirely sure about the question. The model does have failure cases, especially under more extreme pose/illumination/expression.

What executable are you using, and what are your command line arguments?

**Comment by abdou31** [comment]
Sorry Tadas, you are right if I have used `OpenFaceOffline.exe`, this executable gives me good predictions on the same picture instead of using `FaceLandmarkImg.exe`, the difference is very clear
But I don't know what is the reason that the second executable did not give a good prediction on the eye region when the face is orientated? ( case of 3D )


![002-000001](https://user-images.githubusercontent.com/19480228/66766612-c8143b00-eeae-11e9-93c6-f41ac7abe7b0.jpg)

**Comment by TadasBaltrusaitis** [comment]
Do you mean that the 68 landmarks are predicted correctly, but the eye ones are not?

**Comment by abdou31** [comment]
No , in my case I don't need to detect the 68 points of the face, I need just the eye and the iris region
As you can see in the first picture, this is a an annotation using `FaceLandImg.exe`
The process of the annotation is very long ( so many steps ) to produce a dataset annotated with 40 points only on the eyr region.
I have used `FaceLandImg.exe` to get prediction of a folder contains images, I have used this command, and after that I have extract only the eye region and the iris region key points ( 2D) for e.g `eye_lmk_x_0` 
and put them on a file .pts
Every image have a pts file that contains their key points coordinates x and y.
After that I have used repository of image_utility and tfrecord_utility of Yin that produce .json files with detect face and resize the image and make it with a size ( 112 × 112 ).

**Comment by abdou31** [comment]
I can say that I found the original of the problem.
So the problem is coming from `FaceLandmarkImg.exe`.
That was the result of `FaceLandmarkImg.exe`  :

The command that I use is : 
>FaceLandmarkImg.exe -f 002-000001.jpg -out_dir D:\OpenFace_2.2.0_win_x64\processed -2D

![002-000001](https://user-images.githubusercontent.com/19480228/66777260-dc653180-eec8-11e9-8a97-60962514ed51.jpg)

The result from `OpenFaceOffline.exe` : 
![image](https://user-images.githubusercontent.com/19480228/66777278-e9822080-eec8-11e9-8dfa-e1d4bb8421c2.png)

**Comment by abdou31** [comment]
I think that the problem is solved after runing this command:
>  FaceLandmarkImg -wild -mutli_view 1 -aus -gaze -2Dfp -3Dfp -fdir "D:\mydata" -out_dir
