### ISSUE TITLE
vertex features of  ComputeSigmas

### ISSUE THREAD

**Issue by chasonyang** [TadasBaltrusaitis/OpenFace#79]
Hi 
I comment some code in file:
[https://github.com/TadasBaltrusaitis/OpenFace/blob/master/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp](url)  line:135-136
and use this
`   
    Sigmas.push_back(SigmaInv);
`
that means don't do the inverse and could run a little faster .

However,when I also use the ccnf to do the patch expert response computation ,the Landmark Detector  could still work well.
I'm not sure if the inverse means much,or it just reduce some precision?

Thanks.
chason

**Comment by TadasBaltrusaitis** [comment]
It will reduce the accuracy slightly, the inverse is necessary for the smoothing of the response maps. However, I think you could remove sigma completely if you are worried about speed.
