### ISSUE TITLE
How to get gaze point?

### ISSUE THREAD

**Issue by woo1** [TadasBaltrusaitis/OpenFace#792]
![img_29_edit](https://user-images.githubusercontent.com/4454314/67059078-86c3aa00-f192-11e9-89d3-5ef8ca6cd8da.jpg)
How can I get the gaze point(x, y) with these outputs? (gaze_0_x, gaze_0_y, gaze_0_z, gaze_1_x, gaze_1_y, gaze_1_z, gaze_angle_x, gaze_angle_y)

I read your wiki but "gaze_0_x, gaze_0_y, gaze_0_z " looks like relative values.
(https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#csv-file)
![img_29_edit2](https://user-images.githubusercontent.com/4454314/67059289-61836b80-f193-11e9-920f-5a8a570e8f70.jpg)
I tried drawing from center point in two eyes (20-27, 48-55) to gaze point like this

``
gaze_point_x = center_x + center_x*gaze_point_x
``
``
gaze_point_y = center_y + center_y*gaze_point_y
``

But it looks different with original result image.
Is there any formula to get the eye gaze point(x, y)?

**Comment by TadasBaltrusaitis** [comment]
What exactly do you mean by the gaze point? The end bit of the green line?

You can find the exact code of how the gaze visualization is done in the `SetObservationGaze` code, specifically the following lines:

    // Now draw the gaze lines themselves
    cv::Mat cameraMat = (cv::Mat_<float>(3, 3) << fx, 0, cx, 0, fy, cy, 0, 0, 0);

    // Grabbing the pupil location, to draw eye gaze need to know where the pupil is
    cv::Point3f pupil_left(0, 0, 0);
    cv::Point3f pupil_right(0, 0, 0);
    for (size_t i = 0; i < 8; ++i)
    {
        pupil_left = pupil_left + eye_landmarks3d[i];
        pupil_right = pupil_right + eye_landmarks3d[i + eye_landmarks3d.size()/2];
    }
    pupil_left = pupil_left / 8;
    pupil_right = pupil_right / 8;

    std::vector<cv::Point3f> points_left;
    points_left.push_back(cv::Point3f(pupil_left));
    points_left.push_back(cv::Point3f(pupil_left) + cv::Point3f(gaze_direction0)*50.0);

    std::vector<cv::Point3f> points_right;
    points_right.push_back(cv::Point3f(pupil_right));
    points_right.push_back(cv::Point3f(pupil_right) + cv::Point3f(gaze_direction1)*50.0);

    cv::Mat_<float> proj_points;
    cv::Mat_<float> mesh_0 = (cv::Mat_<float>(2, 3) << points_left[0].x, points_left[0].y, points_left[0].z, points_left[1].x, points_left[1].y, points_left[1].z);
    Project(proj_points, mesh_0, fx, fy, cx, cy);
    cv::line(captured_image, cv::Point(cvRound(proj_points.at<float>(0, 0) * (float)draw_multiplier), cvRound(proj_points.at<float>(0, 1) * (float)draw_multiplier)),
	cv::Point(cvRound(proj_points.at<float>(1, 0) * (float)draw_multiplier), cvRound(proj_points.at<float>(1, 1) * (float)draw_multiplier)), cv::Scalar(110, 220, 0), 2, cv::LINE_AA, draw_shiftbits);

    cv::Mat_<float> mesh_1 = (cv::Mat_<float>(2, 3) << points_right[0].x, points_right[0].y, points_right[0].z, points_right[1].x, points_right[1].y, points_right[1].z);
    Project(proj_points, mesh_1, fx, fy, cx, cy);
    cv::line(captured_image, cv::Point(cvRound(proj_points.at<float>(0, 0) * (float)draw_multiplier), cvRound(proj_points.at<float>(0, 1) * (float)draw_multiplier)),
	cv::Point(cvRound(proj_points.at<float>(1, 0) * (float)draw_multiplier), cvRound(proj_points.at<float>(1, 1) * (float)draw_multiplier)), cv::Scalar(110, 220, 0), 2, cv::LINE_AA, draw_shiftbits);`

**Comment by woo1** [comment]
Thanks for your reply
