### ISSUE TITLE
Missing Success Flag in FaceLandmarkImg?

### ISSUE THREAD

**Issue by matthewvowels1** [TadasBaltrusaitis/OpenFace#796]
This may not be an issue but just unexpected behaviour. 

Is there no success flag output for FaceLandmarkImg? I have everything else (including confidence), but no success flag. Or perhaps this occurs when all images in a folder contain faces that are detected? Clarification much appreciated : ]

**Comment by TadasBaltrusaitis** [comment]
Hi,

The success flag is present only when processing the videos and not images, as every detected face in an image by a face detector is considered a "success" (defining exactly what success would be in this case is quite ambiguous anyway). If you want to filter based on more reliable results, use the confidence flag instead.

In any case the success flag for videos is based purely on the confidence measure, so having the success flag does not provide any additional information.
