### ISSUE TITLE
Expand the executable

### ISSUE THREAD

**Issue by mayun123** [TadasBaltrusaitis/OpenFace#797]
hi：

 For an executable such as FeatureExtraction,
 I want to enter the video path, the output path, 
and the parameters I want to save in the program instead of the command line, 
and I want the feature parameters to be saved in an array instead of a CSV file.
what should i do?                                                                                                                                                    

thank！

**Comment by TadasBaltrusaitis** [comment]
Hi,

What do you mean by saving it in the program? You can call the libraries directly by using the examples like FeatureExtraction (and adding your code to suit your needs). Another alternative is to write a wrapper that calls the executable internally and the saves the parameters that were passed to the executable.
