### ISSUE TITLE
Is it possible to extract hog feature from already aligned, cropped frames?

### ISSUE THREAD

**Issue by iPsych** [TadasBaltrusaitis/OpenFace#798]
Is it possible to extract hog feature from already aligned, cropped frames?
The frames are processed via Openface without hog option, and saved as .png frames.

**Comment by TadasBaltrusaitis** [comment]
You would need to write your own code for that, but as HoG features are extracted from the aligned faces it should not be too difficult using the `Extract_FHOG_descriptor` call on the aligned images.
