### ISSUE TITLE
Action unity intensity score

### ISSUE THREAD

**Issue by mrlee0708** [TadasBaltrusaitis/OpenFace#799]
Thank you for your consideration. 

Many researchers are assisted by your meaningful and valuable programs.

I have one question. 

Can not get the intensity score of AU?

For example, AU01A, AU01B, AU01C, ,,, and so on. 

Best Regards,

**Comment by TadasBaltrusaitis** [comment]
OpenFace is already predicting through intensity values, have a look here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units#intensity-and-presence-of-aus

In general 0-5 intensities correspond to AU not present to AU E level

Thanks,
Tadas
