### ISSUE TITLE
Are there any issues in moving my code from CLM to OpenFace?

### ISSUE THREAD

**Issue by alecive** [TadasBaltrusaitis/OpenFace#8]
Hello @TadasBaltrusaitis ,

I am currently using your `CLM` and `FaceAnalyser` libraries from your previous CLM code (i.e. this https://github.com/TadasBaltrusaitis/CLM-framework ), and I have been planning to move to the new OpenFace repository.

Now, I have seen that you at least changed the name of your library from `CLM` to `LandmarkDetector`. Is there anything else I should be aware of? Is the transition going to be smooth? Are there going to be significant changes in the API?

Thank you in advance for your help!

**Comment by TadasBaltrusaitis** [comment]
Hi,

It shouldn't be too difficult. The main difference is the naming and use of VisualStudio 2015 for Windows. OpenFace also has a better documentation through the wiki.

The api changed very slightly in a couple of instances.

Thanks,
Tadas

**Comment by alecive** [comment]
Thank you for the information. 

Is there any way you can tell me where the API changed in advance? I can check on my own, but I would also be sure that it does not disrupt the code significantly.
