### ISSUE TITLE
Error in pose calculation on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by pi-null-mezon** [TadasBaltrusaitis/OpenFace#805]
**Describe the bug**
A huge, but constant bias in world coordinates of the face observed.

**To Reproduce**
We need Nvidia Jetson Nano (ubuntu 18.04, aarch64 gnu linux toolchain). Build and install from sources last versions of OpenCV(4.1.2), Dlib(19.18), OpenBLAS (last commit 0) Clone OpenFace, checkout to v2.1.0 *caaefae*  (as we have only gcc version 7.4.0 on a board). Build by:
```
cmake -D CMAKE_BUILD_TYPE=Release ..
```
Run:
```
./FaceLandmarkVid -mloc /model_clnf_wild.txt -device 0
```

**Expected behavior**
Want to see correct face pose (as on OpenFace build on x86_64 CPU)

**Screenshots**
Bug:
![issue_sample1](https://user-images.githubusercontent.com/5991537/68425002-3a2e2600-01b6-11ea-9196-67c7c49d90a9.jpg)
![issue_sample2](https://user-images.githubusercontent.com/5991537/68425018-40240700-01b6-11ea-80fc-59f60f85276f.jpg)

Expected:
![expected](https://user-images.githubusercontent.com/5991537/68425426-21724000-01b7-11ea-9388-7dae3c833234.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 2.1.0
 - Compiler gcc 7.4.0 (aarch64 gnu linux toolchain)

**Additional context**
It seems something are broken inside OpenBLAS part, but I have not enough skills to find an fix this.  Also it could be anything else. I am ready to try any other build configuration.

**Comment by TadasBaltrusaitis** [comment]
It seems like it's an issue with incorrect camera calibration parameters.

Can you try using FeatureExtraction executable instead? This should produce a .txt file with contents similar to:

> Input:webcam
Camera parameters:500,500,320,240
Output video:webcam_2019-10-14-19-44.avi
Output csv:webcam_2019-10-14-19-44.csv
Gaze: 1
AUs: 1
Landmarks 2D: 1
Landmarks 3D: 1
Pose: 1
Shape parameters: 1

Specifically I'm interested in seeing what `Camera parameters` are estimated on Jetson. It would be great to work out what's causing it, but in the meantime they can be over-riden in the command line (see `-fx. -fy, -cx, -cy` flags in https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments)

**Comment by pi-null-mezon** [comment]
You are right! Thank you! My default camera parameters on Jetson is determined as: 2025,2025,1296,972. Although camera produces frames with 640x480 size. I dug down and have found that two additional lines in *SequenceCapture.cpp* fix this default behavior:
```
cv::Mat frame_to_warm_webcam;
capture.read(frame_to_warm_webcam)
```
should be placed right before: https://github.com/TadasBaltrusaitis/OpenFace/blob/ad1b3cc45ca05c762b87356c18ad030fcf0f746e/lib/local/Utilities/src/SequenceCapture.cpp#L230
