### ISSUE TITLE
Issue while running binary on mac

### ISSUE THREAD

**Issue by smadha** [TadasBaltrusaitis/OpenFace#81]
Hi, I get below error while running any binary
```
$ bin/FeatureExtraction -f test.mp4 
dyld: Library not loaded: libmkl_rt.dylib
  Referenced from: /Users/madhav/Documents/workspace/OpenFace/bin/FeatureExtraction
  Reason: image not found
Trace/BPT trap: 5
```
I have all the required libraries like boost tbb etc. I also built opencv3 like `brew install homebrew/science/opencv3 --with-examples --with-contrib --with-tbb --with-webp `

any suggestions?

**Comment by TadasBaltrusaitis** [comment]
It seems like the MKL library is not installed, it might be that OpenCV wants to link to it. An alternative to MKL is BLAS, which you might try installing. I have not encountered this error before, maybe someone else can help.

**Comment by asemyanov** [comment]
got probably the same issue, 
try:
brew install webp

**Comment by smadha** [comment]
@asemyanov I tried installing webp too but it did not work. I installed opencv again with `brew install opencv3 --with-examples --with-contrib --with-tbb --with-webp --with-python --with-mkl` and then built OpenFace again. Didn't help

I can see that mkl is found in cmake output. 
```
$ cmake -D CMAKE_BUILD_TYPE=RELEASE . -DCMAKE_INCLUDE_PATH="/usr/X11/include;path/to/miniconda/lib"

-- Searching for BLAS and LAPACK
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found Intel MKL BLAS/LAPACK library
```

Also I am able to build without error it comes while executing binary.

**Comment by smadha** [comment]
I was able to fix this by exporting DYLD_FALLBACK_LIBRARY_PATH. I think there should be a better way but I don't know.
```
$ export DYLD_FALLBACK_LIBRARY_PATH=/path/to/mkl/lib
```

Closing this issue, but if someone knows a better approach please do comment here.
