### ISSUE TITLE
how to keep landmark stable and reduce jitter when detect and track landmark in video?

### ISSUE THREAD

**Issue by Kanbo0409** [TadasBaltrusaitis/OpenFace#817]
when use openface to detect landmarks in video, it can be seen that landmarks are jitter, how to keep landmark stable? did you use any tracking method to track face or landmark?

**Comment by TadasBaltrusaitis** [comment]
There is no explicit tracking as such. Instead a landmark is detected in the first frame, and in subsequent frames the search is localized around previously detected landmarks.
