### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by pythonanonuser** [TadasBaltrusaitis/OpenFace#82]
I've run OpenFace's FaceLandmarkVid code on a relatively new machine (Intel i7-6500U CPU and a discrete NVIDIA GPU) and seem to experience high CPU usage (roughly 60% of each of the 4 cores). I've tried in Ubuntu and Windows 10 but get the same result. I've compiled with AVX and AVX2 instructions as well. Is this to be expected? If yes, can I do anything to reduce the CPU usage a little bit?

**Comment by TadasBaltrusaitis** [comment]
The code is multi-threaded so it will try running it on many cores as expected. You can remove the TBB loops and convert them to regular ones, this will force the code to run on one CPU, but it will likely run slower. Alternatively, you could tell TBB to run on a particular set of cores - http://stackoverflow.com/questions/32638743/run-tbb-code-on-specific-number-of-cpu

Thanks,
Tadas

**Comment by pythonanonuser** [comment]
I'd actually prefer it to run on multiple cores. I was just wondering why it's using 60% of each core if the load is in fact spread out over multiple cores. There isn't a lot of room left for my CPU to do a whole lot more which is why I was asking if I was perhaps running the code inefficiently.

**Comment by TadasBaltrusaitis** [comment]
It is reasonably high as there's some overhead in communication. However, in practice I found it not to clash too much with other CPU heavy applications as the scheduler should sort that out with OpenFace slowing down if other applications require CPU use.

**Comment by pythonanonuser** [comment]
I see. My hope was that I could run OpenFace at a high speed while running other things as well. I noticed OpenFace was getting slown down like you mentioned. But seems as though I'll probably need a better CPU then. Thanks!
