### ISSUE TITLE
How to disable only one of the additional parameters ?

### ISSUE THREAD

**Issue by nooshin85** [TadasBaltrusaitis/OpenFace#821]
I am using OpenFace to extract frames from a database with two million videos. currently, I am extracting the frames using the following command

"/home/.../OpenFace/build/bin/FeatureExtraction" -verbose -nobadaligned -f "/home/../Video/00001.mp4" -of "/media/../Video/train/0000001/1/"

This command works fine by extracting the features and the frames as I require; However, while extracting the frames, it generates the output video with detected landmarks (the .avi file). Is it possible to disable outputting the video file with detected landmarks? Due to the large size of the database saving such videos is not efficient considering the computational time and the physical memory.

**Comment by TadasBaltrusaitis** [comment]
It is not possible to disable individual outputs, but instead you can specify what outputs you want and not include the video or processed frames, e.g. by running:

`"/home/.../OpenFace/build/bin/FeatureExtraction" -verbose -nobadaligned -f "/home/../Video/00001.mp4" -of "/media/../Video/train/0000001/1/" -2Dfp -3Dfp -pdmparams -pose -aus -gaze -hogalign`

You can find more details in the following - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#featureextraction-and-facelandmarkvidmulti

Thanks,
Tadas

**Comment by nooshin85** [comment]
thanks a lot for the clear explanation, it solved my problem
