### ISSUE TITLE
output of FeatureExtraction and FaceLandmarkImg are not the same

### ISSUE THREAD

**Issue by zhaojun060708** [TadasBaltrusaitis/OpenFace#829]
I place two images in dir in_dir, and execute the following commands, and get different results. Both gaze and AU feature are different.

What is the reason? Many thanks.

```bash
FeatureExtraction -fdir "./in_dir"
FaceLandmarkImg -fdir "./in_dir"
```
![11](https://user-images.githubusercontent.com/26863591/71977083-c9fb4b00-31cc-11ea-8f0e-10fdaa5d65f6.jpg)
![12](https://user-images.githubusercontent.com/26863591/71977088-ca93e180-31cc-11ea-9813-ff7d77bb5055.jpg)

**Comment by TadasBaltrusaitis** [comment]
FaceLandmarkImg is intended for individual images, while FeatureExtraction for video data, they use slightly different parameters that are optimized for that sort of data. 

E.g. the search space in the image is slightly different and different cross frame normalization of data is used in FeatureExtraction case.
