### ISSUE TITLE
Segmentation fault:11 on mac

### ISSUE THREAD

**Issue by abhilashi** [TadasBaltrusaitis/OpenFace#83]
> saadhana ~/OpenFace/build(master) $ ./bin/FaceLandmarkVidMulti -f ../videos/multi_face.avi
> Segmentation fault: 11

OSX El Capitan: Version 10.11.6

Is there a verbose option to find more about this?

**Comment by TadasBaltrusaitis** [comment]
Not at the moment, but I am working on a logging system for the next release. The first thing the executable should print is the loading of the models, now it seems the model loading is not even reached. Do other executables work?

**Comment by abhilashi** [comment]
@TadasBaltrusaitis  thanks much for the quick reply. 

None of the other executables are working either. Anything I could peek into to fix this?

**Comment by TadasBaltrusaitis** [comment]
You can always try compiling the code yourself and stepping through it. It is surprising that nothing at all is being output.

**Comment by octop1** [comment]
I'm getting the same issue, running OSX 10.11.6. Segmentation fault using FeatureExtraction, and not getting any output files with FaceLandmarkImg or FaceLandmarkVid - they exit silently, no errors printed. Any way we can help in developing your logging system?

**Comment by seacloudy** [comment]
can you solve this problem ?  I meet the same problem on mac  10.12 .

**Comment by jonepatr** [comment]
I have the same problem, macos 10.12.3

**Comment by TadasBaltrusaitis** [comment]
Should be fixed, reopen if persists.
