### ISSUE TITLE
Draw the gaze in image

### ISSUE THREAD

**Issue by rakuay** [TadasBaltrusaitis/OpenFace#835]
Dear TadasBaltrusaitis,

Hello, thanks for your tools very much, it helps me a lot.

I have a quesition about gaze direction vector.
In fact, I'm trying to draw the gaze in the image.
I was doing in this way:

I let the camera at O(0,0,0). Let's say a gaze vector(gaze_0_x, gaze_0_y, gaze_0_z) is (0.92,0.32,024).
I let the vector become (92,32,24) for enlarging the length of vector.
Then I shifted the vector to the eye, and let the vector start at the center of the eye . Here I just used (92,32), because draw the gaze in the image I think it is a 2D quesion.

And I got this image.
![image1](https://user-images.githubusercontent.com/44224205/73620425-32770400-4675-11ea-8427-95cf045d783f.jpg)
But output of openface is in this way.
![sample1OutPut](https://user-images.githubusercontent.com/44224205/73620453-5c302b00-4675-11ea-8e61-5d5081519212.jpg)
It is easy to see gaze vectors are not same. So I wonder if I have wrong way at coordinates or vectors. Is the world coordinate determined by the position of the head?

Could you please give me some hints?
Thank you very much

**Comment by nd2506** [comment]
Hello @rakuay how did you resolve this issue. Was it something on your end or something on openface's end
