### ISSUE TITLE
OpenFace 2.0 unable to compile in MacOS (Undefined symbols for architecture x86_64 )

### ISSUE THREAD

**Issue by marferca** [TadasBaltrusaitis/OpenFace#837]
Make process crashes at:
[ 86%] Linking CXX executable ../../bin/FaceLandmarkImg
Undefined symbols for architecture x86_64:
  "cv::VideoWriter::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double, cv::Size_<int>, bool)", referenced from:
      Utilities::RecorderOpenFace::WriteObservationTracked()      in libUtilities.a(RecorderOpenFace.cpp.o)
  "cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)", referenced from:
      LandmarkDetector::DetectFaces(std::vector<cv::Rect_<float>, std::allocator<cv::Rect_<float> > >&, cv::Mat_<unsigned char> const&, cv::CascadeClassifier&, float, cv::Rect_<float>) in libLandmarkDetector.a(LandmarkDetectorUtils.cpp.o)
...

**To Reproduce**
Download the project
brew install gcc
brew install boost
brew install tbb
brew install --build-from-source dlib
brew install wget
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/c26fb7c3c547836f4217f34bafdd0eb67e4440a6/Formula/opencv.rb
brew pin opencv

cmake -D CMAKE_C_COMPILER=gcc-9 -D CMAKE_CXX_COMPILER=g++-9 -D CMAKE_BUILD_TYPE=RELEASE ..
make

**Screenshots**
CMake output looks fine to me
<img width="617" alt="Screenshot 2020-02-11 at 12 44 05" src="https://user-images.githubusercontent.com/43875805/74234169-882e5a80-4ccc-11ea-83c1-1a54c9a9076a.png">
<img width="619" alt="Screenshot 2020-02-11 at 12 44 52" src="https://user-images.githubusercontent.com/43875805/74234186-91b7c280-4ccc-11ea-807c-f79ff0370e89.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version: 10.14.6
 - Compiler gcc 9.2.0_3

**Additional context**
OpenCV 4.1.2

**Comment by TadasBaltrusaitis** [comment]
This looks to be an OpenCV issue, as the functions it cannot link to are OpenCV ones (VideoWriter and CascadeClassifier), could you try with an earlier version of OpenCV, e.g. 4.0?

**Comment by marferca** [comment]
Thanks for your answer!

It had something to do with CommandLineTools and Xcode. I solved this issue following the steps described in [https://stackoverflow.com/a/17980786]().

Cheers!
