### ISSUE TITLE
Bounding box location in every frame

### ISSUE THREAD

**Issue by WajWaraich** [TadasBaltrusaitis/OpenFace#84]
Hi, thanks for sharing your project with us, it is well coded. I am using the `FaceLandmarkVidMulti` sub-project and was wondering how I can access each of the faces' bounding box location for each frame.

Here are some of the things I would like to do, any guidance would be appreciated:

1) I would firstly like to uniquely identify each person in the frame, I have already implemented some simple logic for this, but unfortunately the `face_detections` vector only updates when a person is found, i.e. the size of the vector is only greater than 0 if there is an update on the faces (e.g. new person enters the frame). I have used this logic for people counting which works well, but I need the position of all the bounding boxes at all times for my logic to work in regards to uniquely identifying the faces.

2) Additionally, once I have uniquely identified the faces I would like to measure how long that individual was in the scene for - the logic I am thinking of consists of a simple tic toc implementation, timer starts when the individual enters the frame and gives the individual 5 seconds of leeway for them to enter the scene again in case the detection on the face is lost.

3) Identify where the individuals are looking, assuming the faces will be facing the camera the region where the people are looking should be fairly simple to extract using pose and gaze estimation I assume.

4) I would like to finally extract some more analytical data from the frames, i.e. gender classification, age recognition etc.

Any help will be greatly appriciated.

Thanks again for sharing your code.

**Comment by TadasBaltrusaitis** [comment]
Hi, thanks for taking an interest in our work.

To answer your questions:
1)  This call returns all the detected faces from the face detector:
`LandmarkDetector::DetectFacesHOG(face_detections, grayscale_image, clnf_models[0].face_detector_HOG, confidences);`
It is not called every frame for speed, but you can change it by removing the 'if' statement above it
2) That sounds reasonable, you can always have logic that tries to make sure the person you are tracking is the same. Having some sort of verification metric to confirm that the image of the face belongs to the same person.
3) Yes, you can use the head pose and eye gaze estimated by OpenFace, for eye gaze you will need to have fairly clear images
4) I'm not doing it at the moment, but you could use the pipeline for Action Unit recognition to build such models

Thanks,
Tadas

**Comment by WajWaraich** [comment]
@TadasBaltrusaitis Thanks a lot for your reply, your answers have been immensely helpful.

**Comment by WajWaraich** [comment]
Hi, I was wondering whether anyone could help me out, from @TadasBaltrusaitis message above I commented out the if statements and have access to the bounding boxes' location in every frame, using that I simply add some logic for overlapping bounding boxes, i.e. if a bounding box has been lost and found again (e.g. `face_detections_used.size() > 0`) then I check all the surrounding bounding boxes to see if any of them are nearby, according to a threshold that I have set if there is a match then the ID of the lost bounding box will be kept and put onto the new bounding box, this last part is what I am struggling with. 

I have tested this and it works quite well with bounding boxes that are lost for whatever reason and appear around the same area again, however, what I am struggling with is to actually assign an ID to a face and then say that this ID actually belongs to that face when found again. I was initially thinking of just creating an array of the size of maximum active models and simply correspond them to the `face_detection` array in some way but it doesn't seem as easy as that.

Any advice on how I can assign an ID to a face would be greatly appreciated, I know this probably is a long winded question and most likely is not very clear, but if you think you can help in any way I'd greatly appreciate it. 

Kind regards,
Waj

**Comment by WajWaraich** [comment]
I think what I am really struggling with is that I don't know how the bounding boxes are returned, I am not sure in what order, which faces come first, second, third etc. If I knew in what order they were returned maybe I could incorporate some logic for uniquely identifying a face. At the moment it seems like the faces are returned in a random fashion, but I doubt it is actually random.

**Comment by TadasBaltrusaitis** [comment]
Hi,

It is a fairly complex topic in itself called people tracking and re-identification and will be difficult to solve just using logic (although you can probably make a lot of progress using simple logic). Some example papers:
https://cvhci.anthropomatik.kit.edu/~mfischer/publications/2010_06_CBMI_Interactive_Person_Re-Identification_in_TV_Series.pdf
https://interact.anthropomatik.kit.edu/downloads/2012_Robust_Multi-Pose_Face_Tracking_by_Multi-Stage_Tracklet_Association.pdf
http://www.robots.ox.ac.uk/~vgg/publications/2014/Parkhi14/parkhi14.pdf

The bounding boxes returned are not ordered at all (or at least I'm not aware of the order). The face detector might detect same faces in the consecutive frames or it might not. You would need to look at the actual locations of the bounding boxes.

Thanks,
Tadas
