### ISSUE TITLE
In-the-wild_aligned_PDM_68.txt

### ISSUE THREAD

**Issue by EverettWang** [TadasBaltrusaitis/OpenFace#847]
Hi,

Thanks for the authors great paper and source code. I am not have any issue at all.  but a I have a question. I want to create a new PDM model for other part of human body for medical applications. I found that this code use PDM with In-the-wild_aligned_PDM_68.txt as model input. How to create a such a model file? the landmark 3D locations, principal components and eigen_values? Could the authors point me some directions to create such model and modify this code to train and use the system?

Thanks in advance.

Everett

**Comment by TadasBaltrusaitis** [comment]
The code for PDM generation can be found here - https://github.com/TadasBaltrusaitis/OpenFace/tree/master/model_training/pdm_generation

It contains instructions of how to train it as well.
