### ISSUE TITLE
head pose calculation

### ISSUE THREAD

**Issue by IQ17** [TadasBaltrusaitis/OpenFace#848]
Hi, I am using the release version OpenFace_2.2.0_win_x64, and I want to get the head pose values.

When I tried with OpenFaceOffline.exe, I see the "Geometry features" in GUI, which is more or less correct. But I cannot save the values to a file.

<img width="975" alt="A9D7CC4D-93F8-4c09-A2E8-AC209C2C4FD7" src="https://user-images.githubusercontent.com/5336719/76276130-01b36b80-62c0-11ea-9975-f53648b6d3a9.png">

However, when I played with the command line  .\FaceLandmarkImg -fdir .\img -pose -out_dir .\outputs  with the same image, but the values are a bit of confusing, which indicates that there is almost no rotations.

face, confidence, pose_Tx, pose_Ty, pose_Tz, pose_Rx, pose_Ry, pose_Rz
0, 0.375, -17.9, 10.1, 164.7, -0.082, -0.139, -0.010

So how can I get the values in GUI, or how I can run command line to get them?

Thanks!

**Comment by IQ17** [comment]
I also tried FeatureExtraction, instead of FaceLandmarkImg, to calucale the pose, but the outputs for the same image are changing all the time. 
 .\FeatureExtraction.exe -fdir .\img -pose -out_dir .\outputs


frame | face_id | timestamp | confidence | success | pose_Tx | pose_Ty | pose_Tz | pose_Rx | pose_Ry | pose_Rz
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 0 | 0 | 0.77 | 1 | 5.9 | 14.8 | 168.6 | -0.092 | -0.545 | -0.033
2 | 0 | 0 | 0.88 | 1 | 6.1 | 15.1 | 170 | -0.127 | -0.542 | -0.043
3 | 0 | 0 | 0.88 | 1 | 6.1 | 15.7 | 172 | -0.143 | -0.537 | -0.047
4 | 0 | 0 | 0.98 | 1 | 6.2 | 16.2 | 174.6 | -0.167 | -0.559 | -0.055
5 | 0 | 0 | 0.98 | 1 | 6 | 16.5 | 176.1 | -0.188 | -0.572 | -0.062
6 | 0 | 0 | 0.98 | 1 | 5.9 | 16.6 | 177.3 | -0.196 | -0.57 | -0.069
7 | 0 | 0 | 0.98 | 1 | 5.8 | 16.8 | 178 | -0.2 | -0.578 | -0.074
8 | 0 | 0 | 0.98 | 1 | 6 | 16.9 | 179.2 | -0.212 | -0.593 | -0.082
9 | 0 | 0 | 0.98 | 1 | 6 | 17.1 | 179.9 | -0.216 | -0.596 | -0.085
10 | 0 | 0 | 0.98 | 1 | 6.2 | 17.4 | 180.5 | -0.22 | -0.608 | -0.09
11 | 0 | 0 | 0.98 | 1 | 6.2 | 17.5 | 181.6 | -0.232 | -0.61 | -0.097
12 | 0 | 0 | 0.98 | 1 | 6.2 | 17.8 | 182.5 | -0.241 | -0.626 | -0.108
13 | 0 | 0 | 0.98 | 1 | 6.4 | 18 | 184.3 | -0.248 | -0.652 | -0.12
14 | 0 | 0 | 0.98 | 1 | 6.2 | 18.2 | 185.9 | -0.254 | -0.656 | -0.127
15 | 0 | 0 | 0.98 | 1 | 6.3 | 18.4 | 186.7 | -0.261 | -0.673 | -0.135
16 | 0 | 0 | 0.98 | 1 | 6.1 | 18.2 | 187.3 | -0.259 | -0.664 | -0.136
17 | 0 | 0 | 0.98 | 1 | 6.1 | 18.3 | 187.1 | -0.261 | -0.671 | -0.138

**Comment by TadasBaltrusaitis** [comment]
The values shown in geometry features should be identical to the ones found in the output csv file from OpenFaceOffline, the only difference is that in the GUI they are displayed as degrees, while the csv file is in radians, e.g. -0.671 radians = -38.44 degrees

**Comment by IQ17** [comment]
Thanks, I just noticed that the outputs of OpenFaceOffline GUI are located in the folder processed.

**Comment by johnbone25** [comment]
@IQ17 @TadasBaltrusaitis  how can we tell if it looks up, down, right or left from the gradians?

**Comment by johnbone25** [comment]
@IQ17 so, i obtained this values (namely gaze_angle, pose_T and so on) but how can i use them to understand if looking right, left, down or up? What are the intervals to determine if person looks right, left, up or down?

**Comment by TadasBaltrusaitis** [comment]
You can look specifically at pose_Rx, pose_Ry, and pose_Rz values, you may want to convert from radians to degrees for more interpretable values first. Rx is up-down, Ry is left-right, Rz is tilt



</body>
</html>
