### ISSUE TITLE
Head Pose Issue

### ISSUE THREAD

**Issue by RegisWu** [TadasBaltrusaitis/OpenFace#850]
Hi, I am using OpenFace to extract the head pose (rotation) of the images from RaFD dataset with heads turning to right (0 degree), frontal (90 degree) and turning to left (180 degree). 
However, the output looks quite strange. 

Here please take a look at my 5 testing images:
![Rafd000_01_Caucasian_female_angry_frontal](https://user-images.githubusercontent.com/42434854/77147621-a441ca80-6ac8-11ea-8241-bea61a6e4914.jpg)
![Rafd045_01_Caucasian_female_angry_frontal](https://user-images.githubusercontent.com/42434854/77147623-a4da6100-6ac8-11ea-9b2d-fee380be315b.jpg)
![Rafd090_01_Caucasian_female_angry_frontal](https://user-images.githubusercontent.com/42434854/77147625-a4da6100-6ac8-11ea-8fe0-a60e41554998.jpg)
![Rafd135_01_Caucasian_female_angry_frontal](https://user-images.githubusercontent.com/42434854/77147626-a572f780-6ac8-11ea-8db9-7b30351e866d.jpg)
![Rafd180_01_Caucasian_female_angry_frontal](https://user-images.githubusercontent.com/42434854/77147616-a2780700-6ac8-11ea-991b-6baca1332c94.jpg)

The (Rx, Ry, Rz) for the 5 images are:
0 degree:     (-0.013, 0.132, -0.02)
45 degree:   (0.035, 0.002, -0.035)
90 degree:   (0.166, -0.023, 0.002)
135 degree: (-0.072, -0.111, 0.03)
180 degree: (-0.012, -0.061, 0.014)

As the head poses are changing in the yaw direction, Ry should have a great change, but we cannot observe it in the outputs.

Besides, may I check that whether the unit for the rotations should be radians? And may I know what is the pose that (0, 0, 0) refer to? Should it be the 90 degree frontal pose?

I am looking forward to your reply!
Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,, 

what command line arguments are you using? Make sure you add `-wild` and `-multi_view 1` to FaceLandmarkImg as this will ensure better performance on profile images.

The output is in radians and (0,0,0) refers to a frontal pose.

**Comment by RegisWu** [comment]
Noted with thanks. The results look much better now after adding -wild and -multi_view.
