### ISSUE TITLE
more than 10 faces

### ISSUE THREAD

**Issue by rschmaelzle** [TadasBaltrusaitis/OpenFace#857]
Hi, I am using FaceLandmarkVidMulti to track a webcam video with many faces (10+), but I am only getting 4 faces. It seems there's a parameter max_faces (?), but I don't understand how to pass this into the commandline-function?
Any help would be appreciated. Thank you very much for making openface available!
Best r

**Comment by m-nasiri** [comment]
hi, in FaceLandmarkVidMulti.cpp there is a variable 
int num_faces_max = 4;
change it and recompile

**Comment by TadasBaltrusaitis** [comment]
There is no command line argument, but you can change it quite easily in the code and recompile (as suggested by @m-nasiri )

**Comment by rschmaelzle** [comment]
thank you all, that worked!
