### ISSUE TITLE
How can I change face detector with my own

### ISSUE THREAD

**Issue by Varat7v2** [TadasBaltrusaitis/OpenFace#862]
With MTCNN face detection model there are number of false detection. Hence I want to try with my own custom-trained CNN model. I glanced through FaceLandamrkImg.cpp file, but could not locate where the face detector has been loaded.

Any kind of suggestions, links would be very much helpful to me. Hope to get your reply soon.

Thank you in advance.

**Comment by TadasBaltrusaitis** [comment]
Look at lines 178-190 where face detection is taking place, it chooses if it should use HAAR, dlib, or MTCNN face detectors.
