### ISSUE TITLE
Blink Classification

### ISSUE THREAD

**Issue by DiogoBrancoNeuro** [TadasBaltrusaitis/OpenFace#866]
Dear Tadas,

First of all thank you for developing and sharing this tool.
Im using the "OpenFaceOffline.exe". 
Is there any way to output as log file the number of blinks as well each frame and timestamp? 
Saw the .csv files but they have a lot of info. 

Thank you.
Best regards,
Diogo

**Comment by TadasBaltrusaitis** [comment]
The CVS already has a blink action unit that you could use, specifically you can see AU45_r as a proxy for blink intensity, you will need to segment it to events to extract number of blinks.

**Comment by DiogoBrancoNeuro** [comment]
Thank you!
