### ISSUE TITLE
How to import mocap data for use in Daz3D

### ISSUE THREAD

**Issue by delebash** [TadasBaltrusaitis/OpenFace#869]
I would like to be able to use OpenFace output to animate a DAZ3D character.  Is this an available feature?  Or suggestions on how to use OpenFace with Daz.

Thanks.

**Comment by TadasBaltrusaitis** [comment]
There's a project that builds on top of OpenFace doing something similar - https://github.com/NumesSanguis/FACSvatar

Thanks,
Tadas

**Comment by delebash** [comment]
Thanks, I saw that project but it only outputs data in the FACS Action Units.  I have looked for a way to import FACS data into Daz but haven;t found one yet.  Anyway thanks for taking a look!
