### ISSUE TITLE
Using prebuilt binaries with MATLAB runners

### ISSUE THREAD

**Issue by JaDameron** [TadasBaltrusaitis/OpenFace#879]
Hey all,

Not so much an issue here as a question.

I recently discovered that I could use the matlab runners to call the prebuilt executables.  This saves me some time when porting projects over to a different machine.

Is there any reason not to do this?  Meaning; should I always build the project from visual studio when I want to interface with MATLAB?

Thanks.

**Comment by TadasBaltrusaitis** [comment]
You can just use the pre-built executables (if they are compatible with your system), the only reason you might need to rebuild them, is if you are using an architecture that the binaries do not exist for  (e.g. ARM), or an OS for which binaries are not provided (Linux and OSX)
