### ISSUE TITLE
Question regarding presence and intensity of AU's

### ISSUE THREAD

**Issue by delebash** [TadasBaltrusaitis/OpenFace#880]
If AU01_c = 1 and AU01_r = 0 at the same timestamp is this because they where trained on different datasets?

Even though it says AU01_c was present (AU01_c = 1) but because the intensity was 0 (AU01_r = 0) you can conclude that AUO1_c should equal 0 as in not present?

Should I use just the intensity column to determine if the AU is present or not?

**Comment by TadasBaltrusaitis** [comment]
This entry in the wiki explains it:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Action-Units#intensity-and-presence-of-aus

**Comment by TadasBaltrusaitis** [comment]
There is no

**Comment by gorish1995** [comment]
While trying to figure whether an AU is present or not, which of AUx_c or AU_r be used? i.e. which one is expected to be more accurate?

**Comment by TadasBaltrusaitis** [comment]
Depends a bit on the input, but if you have a video sequence I would say that AU_r would be more accurate, while for individual images they are probably roughly the same.
