### ISSUE TITLE
Could not find the HAAR face detector location

### ISSUE THREAD

**Issue by youssef266** [TadasBaltrusaitis/OpenFace#881]
i have followed all the instructions and downloaded the models. 

When i run ``` ./bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi``` i get the following error, i dont get any video running. 

 - OS: Ubuntu 18.04
 - OpenCV 4.1 ( The one used in the automatic install ) 

``` ./bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi
Could not find the HAAR face detector location
Reading the landmark detector/tracker from: ./bin/model/main_ceclm_general.txt
Reading the landmark detector module from: ./bin/model/cen_general.txt
Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.35_of.dat....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.50_of.dat....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_1.00_of.dat....Done
Reading part based module....left_eye_28
Reading the landmark detector/tracker from: ./bin/model/model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: ./bin/model/model_eye/clnf_left_synth.txt
Reading the PDM module from: ./bin/model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Could not find the HAAR face detector location
Done
Reading part based module....right_eye_28
Reading the landmark detector/tracker from: ./bin/model/model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: ./bin/model/model_eye/clnf_right_synth.txt
Reading the PDM module from: ./bin/model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Could not find the HAAR face detector location
Done
Reading the landmark validation module....Done
Reading the MTCNN face detector from: ./bin/model/mtcnn_detector/MTCNN_detector.txt
Reading the PNet module from: ./bin/model/mtcnn_detector/PNet.dat
Reading the RNet module from: ./bin/model/mtcnn_detector/RNet.dat
Reading the ONet module from: ./bin/model/mtcnn_detector/ONet.dat
Reading the AU analysis module from: ./bin/AU_predictors/main_static_svms.txt
Reading the AU predictors from: ./bin/AU_predictors/AU_all_static.txt... Done
Reading the PDM from: ./bin/AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:./bin/AU_predictors/tris_68_full.txt... Done
Attempting to read from file: ../samples/multi_face.avi
Device or file opened
WARNING: using a AU detection in multiple face mode, it might not be as accurate and is experimental
Starting tracking
0% 10% 20% 30% 40% 50% Face too small for landmark detection
60% 70% 80% 90% 100% 
Closing output recorder
Closing input reader
Closed successfully
```
When i run ```./bin/FaceLandmarkVid``` it runs normally but i get the same message  of ```Could not find the HAAR face detector location```

**Comment by Gie-ok-Hie-ut** [comment]
I have the same problem after running docker https://github.com/TadasBaltrusaitis/OpenFace/wiki/Docker
Do you have any solution?

**Comment by youssef266** [comment]
Yes, for me i just changes the location of the classifiers folder and put it in build/bin

**Comment by Gie-ok-Hie-ut** [comment]
Thanks for your reply! Have a good day!

**Comment by LevelCA** [comment]
hello, When i run ./bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi i get the following error,

Could not find the HAAR face detector location
Reading the landmark detector/tracker from: ./bin/model/main_ceclm_general.txt
Reading the landmark detector module from: ./bin/model/cen_general.txt
Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.25_of.dat....Could not find CEN patch experts, for instructions of how to download them, see https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download 

ERROR: Could not load the landmark detector
Do you have any solution?  you changed the location of the classifiers folder and put it in build/bin, i don't kown the where the location. thanks your reply.

**Comment by TadasBaltrusaitis** [comment]
As the error message indicates, you might not have the right model files downloaded, see instructions in  https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download for more details on how to acquire the said model files.

**Comment by JeffreyHJF** [comment]
> hello, When i run ./bin/FaceLandmarkVidMulti -f ../samples/multi_face.avi i get the following error,
> 
> Could not find the HAAR face detector location Reading the landmark detector/tracker from: ./bin/model/main_ceclm_general.txt Reading the landmark detector module from: ./bin/model/cen_general.txt Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done Reading the Triangulations module from: ./bin/model/tris_68.txt....Done

I got the same problem, Do you figure it out now? I do appreciate you share it with me if you have solved the problem.

**Comment by 1emonx** [comment]
> Yes, for me i just changed the location of the classifiers folder and put it in build/bin

I have the same problem. What are the classifiers in OpenFace, and where is the location of them?
