### ISSUE TITLE
refine_hierarchical

### ISSUE THREAD

**Issue by noamzafrir** [TadasBaltrusaitis/OpenFace#882]
Hello,
While trying to find ways to speed up the landmarks calculation I've noticed that setting refine_hierarchical to false speed up the calculation by ~25%.
What is the meaning of refine_hierarchical?

**Comment by TadasBaltrusaitis** [comment]
After detecting the standard 68 landmarks all together, the model then refines eye landmarks (for each eye), and inner face landmarks (ignoring the face outline) for added precision. If you set `refine_hierarchical` to false, this refinement is skipped, hence the speedup. Depending on the application this added precision might not be needed (especially if you do not need the fine-grained eye landmark locations).

**Comment by noamzafrir** [comment]
Thank you!
