### ISSUE TITLE
Action Units across participants

### ISSUE THREAD

**Issue by Vivlian** [TadasBaltrusaitis/OpenFace#884]
Dear Tadas,

I am using OpenFace 2.0 for the very first time for a university project, in which I am showing video clips to participants while video recording them. I want to use OpenFace to see whether the activation of AUs across participants differs for different video clips. 
First thing I want to check is how the data looks like - thus creating a box-plot for each AU, for each video, **across all participants**.

I wonder if I might need to normalize data (and if yes - how to do that) before the visual inspection (and any tests), because I am not sure if I can compare between participant the absolute values associated with the AUs. E.g. has "0.5" the same meaning for everyone, or is there some biases, for example a particular facial feature that would shift all values in one direction for some particular participants?  Is it what I already performed by using the "dynamic model"? I guess the dynamic model did "only" take into account that people have different neutral expressions, or am I mistaken?

The recorded videos of participants are 15 seconds long. During the first 10 seconds we expect participants to have a neutral expression. In the following 5 seconds participants might react to some stimuli with changing their facial expression. Am I right to use the dynamic model for the video recordings?

Thank you very much in advance and for the great OpenFace project!
Vivlian

**Comment by TadasBaltrusaitis** [comment]
> I wonder if I might need to normalize data (and if yes - how to do that) before the visual inspection (and any tests), because I am not sure if I can compare between participant the absolute values associated with the AUs. E.g. has "0.5" the same meaning for everyone, or is there some biases, for example a particular facial feature that would shift all values in one direction for some particular participants?

In theory AU annotations are constructed in a way that such comparison would be possible, with 1 being the least visible activation and 5 being the maximum activation of the AU. As the model has been trained to predict these values they should be comparable. However, in practice this does not always hold (e.g. it is hard to tell what is the maximal value of AU without ever observing it). OpenFace attempts to calibrate for that, but it might not work 100% of the time.

> I guess the dynamic model did "only" take into account that people have different neutral expressions, or am I mistaken?

It also looks at minimal and maximal values being predicted as a post-processing step to reduce the bias you speak of.

>  Am I right to use the dynamic model for the video recordings?

Yes. that's the right way to approach it, and having a reasonable long period of neutral expressions should help the model calibrate and the results to be more reliable.
