### ISSUE TITLE
AU28_r is missing in csv output file

### ISSUE THREAD

**Issue by delebash** [TadasBaltrusaitis/OpenFace#885]
**Describe the bug**
AU28_r is not being output in the csv file

**To Reproduce**
File>Recording Settings>Set output location
File>Open webcam
Record some movement the click stop
Open your csv output file and you will see that AU28_r is missing

**Expected behavior**
AU28_r should be in output file

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1909]

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, I didn't have any data to train an intensity based predictor for AU28, so only classification values are available.
