### ISSUE TITLE
face sizes are too small. 

### ISSUE THREAD

**Issue by youssef266** [TadasBaltrusaitis/OpenFace#893]
i have created my own video dataset, i get the message ``` Face is too small for landmark detection``` is there a way to make it able to detect smaller size faces ?

**Comment by TadasBaltrusaitis** [comment]
You can comment out the line in the code that stops it processing smaller faces, but I wouldn't necessarily recommend that, as landmark detection accuracy will be fairly low for such small faces (less than 40px across)

**Comment by youssef266** [comment]
would you be so kind and tell me which bit of code does that ? i am running openface on Ubuntu. 

thank you.

**Comment by TadasBaltrusaitis** [comment]
It is the following bit of code in `LandmarkDetectorModel.cpp`:

    // Can't track very small images reliably (less than ~30px across)
    if (params_global[0] < 0.25)
    {
        std::cout << "Face too small for landmark detection" << std::endl;
        return false;
    }
