### ISSUE TITLE
Landmark Position in video

### ISSUE THREAD

**Issue by Muscio-1605187** [TadasBaltrusaitis/OpenFace#90]
Hi Tadas,
first of all, congratulations for your work. It's simply awesome. I'm using your algorithm for a master thesis and I have a little problem. How can I get the position (x,y and z coordinates) of the detected landmarks w.r.t. the video?

Thank you for your attention.
Regards,
Mario

**Comment by TadasBaltrusaitis** [comment]
You can use the FeatureExtraction executable, see:
   https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments#featureextraction for command line arguments
   https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#featureextraction for the expected output format

Thanks,
Tadas
