### ISSUE TITLE
Further clarification of usage

### ISSUE THREAD

**Issue by Hunanbean** [TadasBaltrusaitis/OpenFace#901]
I do not want to use the code from this project. I simply want to use the Output of it to control that face of a game character in a closed source commercial game.

Is the Output of the program itself considered requiring a paid license, or only if i use code from the project within my game?

**Comment by TadasBaltrusaitis** [comment]
Please get in touch with CMU about a clarification on this (https://cmu.flintbox.com/#technologies/5c5e7fee-6a24-467b-bb5f-eb2f72119e59), there's a contact button in the link.
