### ISSUE TITLE
Could not find the HAAR face detector location

### ISSUE THREAD

**Issue by Lillian1082** [TadasBaltrusaitis/OpenFace#902]
I follow the instruction step by step and installed the packages successfully. However, for both the video and image, I met this issue.
$ ./bin/FaceLandmarkVid -f "../samples/changeLighting.wmv" -f "../samples/2015-10-15-15-14.avi"
Could not find the HAAR face detector location
Reading the landmark detector/tracker from: ./bin/model/main_ceclm_general.txt
Reading the landmark detector module from: ./bin/model/cen_general.txt
Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.25_of.dat....Could not find CEN patch experts, for instructions of how to download them, see https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download 

ERROR: Could not load the landmark detector

$ ./bin/FeatureExtraction -f "../samples/sample2.jpg"
Could not find the HAAR face detector location
Reading the landmark detector/tracker from: ./bin/model/main_ceclm_general.txt
Reading the landmark detector module from: ./bin/model/cen_general.txt
Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./bin/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: ./bin/model/patch_experts/cen_patches_0.25_of.dat....Could not find CEN patch experts, for instructions of how to download them, see https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download 

ERROR: Could not load the landmark detector

My device is:
 - OS: Ubuntu 16.04 LTS

Could you please help to solve this?

**Comment by tashrifbillah** [comment]
@Lillian1082 , since you closed this issue, what solution did you find?

**Comment by TadasBaltrusaitis** [comment]
To download the models, please follow instructions in this link - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-download

**Comment by tashrifbillah** [comment]
Oh I figured the download part already. Commented here to get help about:

> Could not find the HAAR face detector location

But you already mentioned the above warning is harmless.

**Comment by satheesh3** [comment]
May I know what is the issue here, I still get this error in Ubuntu 20.04

**Comment by Cb1ock** [comment]
@Lillian1082 same issue, Could you please tell me how did you solve it ?
