### ISSUE TITLE
Running simscale and simsize individually works, running them together somehow returns the fullimage

### ISSUE THREAD

**Issue by loc-trinh** [TadasBaltrusaitis/OpenFace#904]
**Describe the bug**
I tried running simscale at 0.5, it works. simsize at 299 it works. together, not quite? i got the full image sadly.

Also, is there a way to get the bounding box? otherwise, the resizing kinda destroys information right? bbox can be scaled to crop full image.

**Comment by TadasBaltrusaitis** [comment]
You can get the bounding box from the detected landmarks and do the relevant crop yourself.

Could you post an example of the simscale and simsize not working?

**Comment by loc-trinh** [comment]
Yea I ended up doing what you suggested back in August. I will close this for now, but I don't quite remember the exact command. As I recalled, it's more of running simsize and simscale together will not work as one of them will override the other.
