### ISSUE TITLE
Mac: Stream HeadPose and Gaze Features with ZeroMQ

### ISSUE THREAD

**Issue by LRNavin** [TadasBaltrusaitis/OpenFace#910]
Hi OpenFace team,

I'm working on an application with OpenFace, which requires me to **stream the extracted facial features in realtime.**

So far, I have been able to _bin/FeatureExtraction ...._ executables which dump the extracted frame wise features in a csv. I want the same features accessible at realtime. 

From the documentation I saw that it is possible to run certain .exe (in Windows) and stream via ZMQ. **Can this be achieved in Mac?** I tried by running the _bin/FeatureExtraction ...._ executable and the testing_head_pose.py script in parallel, but I was not able to get the data streams. **Am I missing something here?** 

Thanks in Advance,
Navin Lr

**Comment by TadasBaltrusaitis** [comment]
Unfortunately, this can only be achieved on Windows, as only the C# version of the GUI streams the head pose and eye gaze information over ZeroMQ
