### ISSUE TITLE
Training Pre-done?

### ISSUE THREAD

**Issue by michaelDau** [TadasBaltrusaitis/OpenFace#913]
Is the training referred to at the below link already done and factored into the OpenFace installation? Or is it something we have to do separately?

https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-Training

**Comment by TadasBaltrusaitis** [comment]
Yes all the models are already trained, the instructions are there in case you wanted to retrain the models on new data or for baseline comparisons.
