### ISSUE TITLE
Webam issues

### ISSUE THREAD

**Issue by L5mp** [TadasBaltrusaitis/OpenFace#914]
Hi!

Does anyone know why I can't use the webcam with the .exe? When I run the applications it says 'Loading cameras' 'Might take some time the first time', the webcam is recognized because the light turns on and in fact OpenFace is authorized in the camera settings but after a while it automatically closes me . At no point have I been able to see my webcam image and I don't know why that could be.

Thank you!!

**Comment by brmarkus** [comment]
Excuse me?

**Comment by Shaurya-rkk** [comment]
You have to install the models. Look at the readme.
