### ISSUE TITLE
Can OpenFace 2.0 run on GPU? If not, is it going to be a feature in the near future?

### ISSUE THREAD

**Issue by NJNischal** [TadasBaltrusaitis/OpenFace#915]
Saw a post regarding no GPU support but that was a closed issue in 2017. Wanted to know if things changed in the newer version. I do see GPU utilization while running OpenFace 2.0 on my Windows machine but it is quite low compared to CPU utilization.

**Comment by TadasBaltrusaitis** [comment]
There are currently no plans for more extended GPU support, and most of the compute is done on the CPU.
