### ISSUE TITLE
How to use API calls?

### ISSUE THREAD

**Issue by BSreenivas0713** [TadasBaltrusaitis/OpenFace#932]
I'm new to C++, but I understand the behavior of OpenFace in general. I want to create a new C++ file and use the API calls to get action units from a single image. Should I be using the same "includes" statements as FaceLandmarkImg.cpp and making the same API calls? Where should I create this C++ file so I can reference these libraries? What do I pass into GCC to compile this correctly?

Note: I'm using VSCode on Ubuntu 20.04, and the command line arguments work fine for me. I am able to get the expected behavior from this. I want to call these behaviors from a C++ file.

<img width="1032" alt="Screen Shot 2020-12-24 at 11 34 00 AM" src="https://user-images.githubusercontent.com/40176637/103101168-f07fe500-45db-11eb-9577-98ed6bef2241.png">

**Comment by Aniket3416** [comment]
Hey @BSreenivas0713!
Were you able to find a solution?
