### ISSUE TITLE
ERROR: Could not load the landmark detector - MATLAB Version

### ISSUE THREAD

**Issue by Moktar13** [TadasBaltrusaitis/OpenFace#941]
I attempted to run the test scripts found in the manual installation file and got this error. In addition to this, the error statement also contains "Could not find the HAAR face detector location" and "Could not find CEN patch experts" even though I have downloaded the models as per the guide. 

![Screenshot 2021-02-13 152238](https://user-images.githubusercontent.com/49799691/107860786-584df180-6e0f-11eb-8cdf-42ae9fe19492.png)

Desktop
 - OS: Ubuntu
 - Version: 18.04

**Comment by LevelCA** [comment]
I encountered the same problem as you, how did you solve it, I look forward to your reply, thank you!

**Comment by LonyAi55** [comment]
I also meet this problem,but I used C++ version.Do you deal with this problem?I look forward to your reply too.Thank you

**Comment by lwh8915** [comment]
I also meet this problem,but I used C++ version.Do you deal with this problem?I look forward to your reply too.Thank you
