### ISSUE TITLE
avi output modification

### ISSUE THREAD

**Issue by iyashdesh** [TadasBaltrusaitis/OpenFace#947]
OpenFace is really good, so thanks for making it.

What can I do to add the x,y,z coordinates to each facial landmark in the avi output video, as the video is playing? (see attached img)

Is there a way to change the color of each facial landmark?

Thank You

![openface enquiry](https://user-images.githubusercontent.com/48184502/110829185-bdbac400-828f-11eb-88cb-d1cf83b491bd.png)

**Comment by TadasBaltrusaitis** [comment]
You would need to change the visualization code to do that. Specifically the `SetObservationLandmarks` bit in `lib/local/Utilities/src/Visualizer.cpp`

**Comment by iyashdesh** [comment]
thank you
