### ISSUE TITLE
Error in feature_extraction_demo_vid (line 48) tab = readtable(outputFile);  

### ISSUE THREAD

**Issue by sarmadm** [TadasBaltrusaitis/OpenFace#95]
When I run feature_extraction_demo_vid this error is showing , any idea of how can I deal with it ?

Error in feature_extraction_demo_vid (line 48)
tab = readtable(outputFile);
 

    executable = '"../../x64/Release/FeatureExtraction.exe"';

    output = './output_features_vid/';

     if(~exist(output, 'file'))
      mkdir(output)
    end
    
    in_files = dir('../../videos/1815_01_008_tony_blair.avi');
    % some parameters
    verbose = true;

     command = executable;

     % Remove for a speedup
     command = cat(2, command, ' -verbose ');

    % add all videos to single argument list (so as not to load the model anew
    % for every video)
     for i=1:numel(in_files)
    
    inputFile = ['../../videos/', in_files(i).name];
    [~, name, ~] = fileparts(inputFile);
    
    % where to output tracking results
    outputFile = [output name '.txt'];
            
    if(~exist([output name], 'file'))
        mkdir([output name]);
    end
    
    outputDir_aligned = [output name];
    
    outputHOG_aligned = [output name '.hog'];
    
    output_shape_params = [output name '.params.txt'];
    
    command = cat(2, command, [' -f "' inputFile '" -of "' outputFile '"']);        
    command = cat(2, command, [' -simalign "' outputDir_aligned '" -hogalign "' outputHOG_aligned '"'    ]);    
                 
    end

    dos(command);

     %% Demonstrating reading the output files

     % First read in the column names
     tab = readtable(outputFile);
    column_names = tab.Properties.VariableNames;

    all_params  = dlmread(outputFile, ',', 1, 0);

    % This indicates which frames were succesfully tracked
    valid_frames = logical(all_params(:,4));
    time = all_params(valid_frames, 2);

    %% Finding which header line starts with p_ (basically model params)
    shape_inds = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'p_'));

    % Output rigid (first 6) and non-rigid shape parameters
    shape_params  = all_params(valid_frames, shape_inds);

    figure
    plot(time, shape_params);
    title('Shape parameters');
    xlabel('Time (s)');

     %% Demonstrate 2D landmarks
     landmark_inds_x = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'x_'));
     landmark_inds_y = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'y_'));

     xs = all_params(valid_frames, landmark_inds_x);
    ys = all_params(valid_frames, landmark_inds_y);

    figure

     for j = 1:size(xs,1)
    plot(xs(j,:), -ys(j,:), '.');
    xlim([min(xs(1,:)) * 0.5, max(xs(2,:))*1.4]);
    ylim([min(-ys(1,:)) * 1.4, max(-ys(2,:))*0.5]);
    xlabel('x (px)');
    ylabel('y (px)');
    drawnow
    end

      %% Demonstrate 3D landmarks
    landmark_inds_x = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'X_'));
    landmark_inds_y = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'Y_'));
    landmark_inds_z = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'Z_'));

    xs = all_params(valid_frames, landmark_inds_x);
    ys = all_params(valid_frames, landmark_inds_y);
    zs = all_params(valid_frames, landmark_inds_z);

    figure
    for j = 1:size(xs,1)
    plot3(xs(j,:), ys(j,:), zs(j,:), '.');axis equal;
    xlabel('X (mm)');
    ylabel('Y (mm)');    
    zlabel('Z (mm)');    
    drawnow
     end

    %% Demonstrate AUs
    au_reg_inds = cellfun(@(x) ~isempty(x) && x==5, strfind(column_names, '_r'));

    aus = all_params(valid_frames, au_reg_inds);
    figure
    plot(time, aus);
    title('Facial Action Units (intensity)');
    xlabel('Time (s)');
    ylabel('Intensity');
    ylim([0,6]);

    au_class_inds = cellfun(@(x) ~isempty(x) && x==5, strfind(column_names, '_c'));

    aus = all_params(valid_frames, au_class_inds);
    figure
    plot(time, aus);
    title('Facial Action Units (presense)');
    xlabel('Time (s)');
    ylim([0,2]);
      %% Demo pose
     pose_inds = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'pose_'));

      pose = all_params(valid_frames, pose_inds);
     figure
     plot(pose);
      title('Pose (rotation and translation)');
      xlabel('Time (s)');

        %% Demo gaze
       gaze_inds = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'gaze_'));

      % Read gaze (x,y,z) for one eye and (x,y,z) for another
      gaze = all_params(valid_frames, gaze_inds);

      % only picking left, right and up down views for visualisation
        gaze = (gaze(:,[1,2]) + gaze(:,[4,5]))/2;
        gaze(:,1) = smooth(gaze(:,1));
        gaze(:,2) = smooth(gaze(:,2));

       plot(time, gaze(:,1), 'DisplayName', 'Left - right');
       hold on;
      plot(time, gaze(:,2), 'DisplayName', 'Up - down');
     xlabel('Time(s)') % x-axis label
      ylabel('Gaze vector size') % y-axis label
     legend('show');
      hold off;

      %% Output HOG files
    [hog_data, valid_inds, vid_id] = Read_HOG_files({name}, output);

     %% Output aligned images
     img_files = dir([outputDir_aligned, '/*.png']);
     imgs = cell(numel(img_files, 1));
     for i=1:numel(img_files)
    imgs{i} = imread([ outputDir_aligned, '/', img_files(i).name]);
      imshow(imgs{i})
      drawnow
       end

**Comment by TadasBaltrusaitis** [comment]
You will need to provide me with more details about the error. What is the error message? What is the output in the command window? Is an output file produced?

Thanks,
Tadas

**Comment by sarmadm** [comment]
when I run matlab_runners\Demos\feature_extraction_demo_vid.m   file this error is showing 

feature_extraction_demo_vid
The system cannot find the path specified. 
Undefined function or variable 'outputFile'.

Error in feature_extraction_demo_vid (line 48)
tab = readtable(outputFile);

**Comment by TadasBaltrusaitis** [comment]
Are you sure you compiled the 64-bit executable of FeatureExtraction project? Do you get the following message:
`The system cannot find the path specified. `

Thanks,
Tadas

**Comment by sarmadm** [comment]
I have downloaded all OpenFace project files from github , I run OpenFace .sln in visual studio 2015 community edition . in visula studio 2015 communiy edition this error is showing : FaceLandmarkVid.pdb 

not loaded . In matlab 2016a I run matlab_runners\Demos\feature_extraction_demo_vid.m

feature_extraction_demo_vid
The system cannot find the path specified. 
Undefined function or variable 'outputFile'.

Error in feature_extraction_demo_vid (line 48)
tab = readtable(outputFile);

**Comment by TadasBaltrusaitis** [comment]
If the system cannot find the executable, that means you have not compiled it. You need to make sure that you compile the 64-bit version as that is what the demo file is looking for. Alternatively, you could compile the 32-bit one and change the first line to:
`executable = '"../../Release/FeatureExtraction.exe"';`

**Comment by sarmadm** [comment]
Hi
I put 32-bit http://www.cl.cam.ac.uk/~tb346/OpenFace/OpenFace_0.2.2_win_x86 , 64  and 

OpenFace-master  in visual studio 2015 projects folder . I run OpenFace.sln 

when I run FaceLandmarkVid , it runs in 32 mode and 64 but the webcam video freezes after a while.

I couldn't run FeatureExtraction . Is there is association between these and matlab ?



FaceLandmarkVid

**Comment by TadasBaltrusaitis** [comment]
Is the `FaceLandmarkVid.exe` able to track facial landmarks in the webcam video? What do you mean by the video freezing? It might be slow if there is no face in the video?

What do you mean about not being able to run `FeatureExtraction`? Does it not run? You can run it using the Matlab scrip as it expects there to be a `FeatureExtraction.exe`, you will just need to change the location to your one in the line:
`executable = '"../../Release/FeatureExtraction.exe"';`

Thanks,
Tadas

**Comment by sarmadm** [comment]
FaceTrackingVid.exe in \OpenFace_0.2_win_x86   folder  runs without problems.

 But FaceLandmarkVid.exe (32,64 bit mode ) in visual studio2015 runs but it the webcam display freezes ( there is face in the video ).

In matlab I chnceged executable and video folders to 


executable = '"C:/Users/mypc/Documents/MATLAB/OpenFace-master/Release/FeatureExtraction.exe"';

output = 'C:/Users/mypc/Documents/MATLAB/output_features_vid/';

if(~exist(output, 'file'))
    mkdir(output)
end
    
in_files = dir('C:/Users/mypc/Documents/MATLAB/OpenFace-master/videos/1815_01_008_tony_blair.avi');

it shows these errors 

Reading the landmark validation module....Done 
Attempting to read from file: ../../videos/1815_01_008_tony_blair.avi 
FPS of the video file cannot be determined, assuming 30 
Fatal error: Failed to open video source, exiting 
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:578) 
Error using readtable (line 143)
Unable to open file 'C:/Users/sarmad/Documents/MATLAB/output_features_vid/1815_01_008_tony_blair.txt'.

Error in feature_extraction_demo_vid (line 48)
tab = readtable(outputFile);

**Comment by TadasBaltrusaitis** [comment]
Please see the note here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation#release-mode, you need to make sure you are in Release mode as the display is not freezing but the model is really slow in Debug mode.

The video file might not be found. As you can see the video provided is not based on full path, change the full path to the video location.

Thanks,
Tadas

**Comment by sarmadm** [comment]
Hi

I have changed the full path in matlab ( feature_extraction_demo_vid.m)  


executable = '"C:/Users/mypc/Documents/MATLAB/OpenFace-master/Release/FeatureExtraction.exe"';

output = 'C:/Users/mypc/Documents/MATLAB/OpenFace-master/output_features_vid/';

if(~exist(output, 'file'))
    mkdir(output)
end
    
in_files = dir('C:/Users/mypc/Documents/MATLAB/OpenFace-master/videos/default.avi');


shows errors , I don

Fatal error: Failed to open video source, exiting 
Error using readtable (line 143)
Unable to open file 'C:/Users/mypc/Documents/MATLAB/output_features_vid/1815_01_008_tony_blair.txt'.

Error in feature_extraction_demo_vid (line 48)
tab = readtable(outputFile);
 
>>

**Comment by TadasBaltrusaitis** [comment]
You will need to change the script more, make sure that the file being loaded is actually the one you want, just changing the line with `dir` command is not enough, you need to also change the following line to point to the file you want processed:
`inputFile = ['../../videos/', in_files(i).name];`
to 
`inputFile = "C:/Users/mypc/Documents/MATLAB/OpenFace-master/videos/default.avi"`

Thanks,
Tadsa
