### ISSUE TITLE
Error: Hunk FAILED

### ISSUE THREAD

**Issue by maxdembovsky** [TadasBaltrusaitis/OpenFace#952]
**Describe the bug**
I tried to install OpenFace according to the instructions.
I am trying to run: brew install gcc --HEAD. 
Get error:

maxdembovsky@192 ~ % brew install gcc --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6a83f
Already downloaded: /Users/maxdembovsky/Library/Caches/Homebrew/downloads/c0b9dca392d2e8496747001f634c04a4bc2f5c63672b963f3c4f217e70aaa258--bigsur_2.patch
==> Cloning https://gcc.gnu.org/git/gcc.git
Updating /Users/maxdembovsky/Library/Caches/Homebrew/gcc--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 2bfd081f1bc c++: Cross-module partial specialiations [PR 99480]
==> Patching
==> Applying bigsur_2.patch
patching file gcc/config/host-darwin.c
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file gcc/config/host-darwin.c.rej
patching file gcc/config/darwin-c.c
Hunk #1 FAILED at 692.
1 out of 1 hunk FAILED -- saving rejects to file gcc/config/darwin-c.c.rej
patching file gcc/config/darwin-driver.c
Hunk #1 FAILED at 65.
Hunk #2 FAILED at 104.
Hunk #3 succeeded at 130 with fuzz 2 (offset 15 lines).
Hunk #4 FAILED at 146.
Hunk #5 FAILED at 163.
4 out of 5 hunks FAILED -- saving rejects to file gcc/config/darwin-driver.c.rej
patching file gcc/testsuite/gcc.dg/darwin-minversion-link.c
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file gcc/testsuite/gcc.dg/darwin-minversion-link.c.rej
patching file gcc/config/darwin-driver.c
Hunk #1 FAILED at 149.
1 out of 1 hunk FAILED -- saving rejects to file gcc/config/darwin-driver.c.rej
patching file gcc/config/darwin-driver.c
Hunk #1 FAILED at 43.
Hunk #2 FAILED at 63.
Hunk #3 FAILED at 229.
3 out of 3 hunks FAILED -- saving rejects to file gcc/config/darwin-driver.c.rej
patching file libsanitizer/configure.tgt
Hunk #1 FAILED at 60.
1 out of 1 hunk FAILED -- saving rejects to file libsanitizer/configure.tgt.rej
patching file gcc/configure
Hunk #1 FAILED at 15490.
1 out of 1 hunk FAILED -- saving rejects to file gcc/configure.rej
patching file libatomic/configure
Hunk #1 FAILED at 7589.
1 out of 1 hunk FAILED -- saving rejects to file libatomic/configure.rej
patching file libbacktrace/configure
Hunk #1 FAILED at 7968.
1 out of 1 hunk FAILED -- saving rejects to file libbacktrace/configure.rej
patching file libcc1/Makefile.am
Hunk #1 FAILED at 25.
1 out of 1 hunk FAILED -- saving rejects to file libcc1/Makefile.am.rej
patching file libcc1/Makefile.in
Hunk #1 FAILED at 89.
Hunk #2 FAILED at 383.
2 out of 2 hunks FAILED -- saving rejects to file libcc1/Makefile.in.rej
patching file libcc1/configure
Hunk #1 FAILED at 635.
Hunk #2 FAILED at 7252.
Hunk #3 succeeded at 14981 with fuzz 2 (offset 196 lines).
Hunk #4 succeeded at 15366 with fuzz 1 (offset 200 lines).
2 out of 4 hunks FAILED -- saving rejects to file libcc1/configure.rej
patching file libcc1/configure.ac
Hunk #1 succeeded at 110 with fuzz 2 (offset 9 lines).
patching file libffi/configure
Hunk #1 FAILED at 7762.
1 out of 1 hunk FAILED -- saving rejects to file libffi/configure.rej
patching file libgfortran/configure
Hunk #1 FAILED at 9163.
1 out of 1 hunk FAILED -- saving rejects to file libgfortran/configure.rej
patching file libgomp/Makefile.in
Hunk #1 FAILED at 16.
1 out of 1 hunk FAILED -- saving rejects to file libgomp/Makefile.in.rej
patching file libgomp/configure
Hunk #1 FAILED at 7634.
1 out of 1 hunk FAILED -- saving rejects to file libgomp/configure.rej
patching file libhsail-rt/configure
Hunk #1 FAILED at 7442.
1 out of 1 hunk FAILED -- saving rejects to file libhsail-rt/configure.rej
patching file libitm/configure
Hunk #1 FAILED at 8265.
1 out of 1 hunk FAILED -- saving rejects to file libitm/configure.rej
patching file libitm/configure.tgt
Hunk #1 FAILED at 43.
Hunk #2 FAILED at 145.
2 out of 2 hunks FAILED -- saving rejects to file libitm/configure.tgt.rej
patching file libobjc/configure
Hunk #1 FAILED at 6952.
1 out of 1 hunk FAILED -- saving rejects to file libobjc/configure.rej
patching file libphobos/configure
Hunk #1 FAILED at 8117.
1 out of 1 hunk FAILED -- saving rejects to file libphobos/configure.rej
patching file libquadmath/configure
Hunk #1 FAILED at 7256.
1 out of 1 hunk FAILED -- saving rejects to file libquadmath/configure.rej
patching file libsanitizer/configure
Hunk #1 FAILED at 8831.
1 out of 1 hunk FAILED -- saving rejects to file libsanitizer/configure.rej
patching file libsanitizer/configure.tgt
Hunk #1 FAILED at 62.
1 out of 1 hunk FAILED -- saving rejects to file libsanitizer/configure.tgt.rej
patching file libssp/configure
Hunk #1 FAILED at 7438.
1 out of 1 hunk FAILED -- saving rejects to file libssp/configure.rej
patching file libstdc++-v3/configure
Hunk #1 FAILED at 8373.
1 out of 1 hunk FAILED -- saving rejects to file libstdc++-v3/configure.rej
patching file libtool.m4
Hunk #1 FAILED at 994.
Hunk #2 FAILED at 1035.
2 out of 2 hunks FAILED -- saving rejects to file libtool.m4.rej
patching file libvtv/configure
Hunk #1 FAILED at 8732.
1 out of 1 hunk FAILED -- saving rejects to file libvtv/configure.rej
patching file zlib/configure
Hunk #1 succeeded at 6278 with fuzz 1 (offset 2878 lines).
Hunk #2 FAILED at 9705.
1 out of 2 hunks FAILED -- saving rejects to file zlib/configure.rej

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Desktop**
 - OS: MacOS Catalina
 - Version: 10.15.7 
 - Compiler: gcc (Apple clang version 12.0.0 (clang-1200.0.32.29))

Please help me fix the error.

**Comment by PranavDev** [comment]
Try this:
**brew install gcc**

Do not do: brew install gcc --HEAD
