### ISSUE TITLE
using FeatureExtraction in Python

### ISSUE THREAD

**Issue by DaddyWesker** [TadasBaltrusaitis/OpenFace#953]
Hello. 

Thanks for your code. Is it possible to use FeatreExtraction module in the python? I mean importing some sort of library, not just running terminal command via Python. I've tried to search through internet to answer that question, but haven't found anythng like that. 

Thanks in advance.

**Comment by AksharSharma** [comment]
Same question!

**Comment by ClinikerDotCom** [comment]
Hey! Did anyone find a solution to this? We can use pybind, to expose cpp functions and import them in python code. But the documentation/provided examples in this repo don't seem to be enough to figure out the exact dependencies.

**Comment by TadasBaltrusaitis** [comment]
Apologies for the delayed response. The one option you have is launching the executable directly from python, either using subprocess or os.system. You can call FeatureExtraction.exe with relevant command line arguments. such as -f etc., you can find the arguments here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

There currently is no python interface that can be called directly through python.

**Comment by DaddyWesker** [comment]
Too bad, i guess. THanks for the answer.
