### ISSUE TITLE
Haar Face Detector Location

### ISSUE THREAD

**Issue by PranavDev** [TadasBaltrusaitis/OpenFace#955]
Could not find the HAAR face detector location
Reading the landmark detector/tracker from: bin/model/main_ceclm_general.txt
Reading the landmark detector module from: bin/model/cen_general.txt
Reading the PDM module from: bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: bin/model/tris_68.txt....Done
dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

OpenCV version: '4.5.1'

I have followed every step properly. Ran the build 5-10 times. This issues keeps coming. Please help resolve.

**Comment by PranavDev** [comment]
I understood the problem for Mac installation:

For installing gcc you should do:
**brew install gcc**

No need of: brew install gcc --HEAD

**Comment by tashrifbillah** [comment]
I am not sure how the installation method lets it find HAAR face detector location but I am getting the same error in Linux.

**Comment by TadasBaltrusaitis** [comment]
Default models do not use the HAAR face detector, so the warning is not that useful and is probably not the issue you are facing?
