### ISSUE TITLE
`simsize` doesn't work?

### ISSUE THREAD

**Issue by RomainSabathe** [TadasBaltrusaitis/OpenFace#96]
Hi, thank you so much for the brilliant work. I'm trying to extract normalised faces from a folder of images. I'm using the following command:

`./bin/FeatureExtraction -fdir 'my_input_folder' -simalign 'my_output_folder/aligned' -simsize 256 -q`

I therefore expect my output images to be of size 256x256, but there are still of size 112x112. Am I doing something wrong?

Thanks!

**Comment by TadasBaltrusaitis** [comment]
Hi,

You're not doing anything wrong, it's a known bug that will be fixed in the next release of OpenFace.

Thanks,
Tadas

**Comment by TadasBaltrusaitis** [comment]
Fixed.
