### ISSUE TITLE
Action Units from Facial Landmarks

### ISSUE THREAD

**Issue by AdMeynard** [TadasBaltrusaitis/OpenFace#964]
Hi,

I have a file containing facial landmarks, extracted from a video. Its format is the same as the OpenFace output format. I'd like to know whether or not it is possible to use this file as an input to determine the action units (in lieu of the video itself).

Thanks.

**Comment by TadasBaltrusaitis** [comment]
The AUs are estimated from both the image (HoG features derived from it) and landmarks. Unfortunately, just using landmarks will not be enough.

Thanks,
Tadas
