### ISSUE TITLE
Error with finding package configuration file

### ISSUE THREAD

**Issue by biancacap** [TadasBaltrusaitis/OpenFace#975]
When I run
`cmake -D CMAKE_BUILD_TYPE=RELEASE . .`
I get a message saying: 
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindOpenBLAS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenBLAS",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenBLAS" with any
  of the following names:

    OpenBLASConfig.cmake
    openblas-config.cmake

  Add the installation prefix of "OpenBLAS" to CMAKE_PREFIX_PATH or set
  "OpenBLAS_DIR" to a directory containing one of the above files.  If
  "OpenBLAS" provides a separate development package or SDK, be sure it has
  been installed.

How do I resolve this? Thanks!

**Comment by murthy95** [comment]
@biancacap How did you resolve this ?

**Comment by biancacap** [comment]
@murthy95 From what I remember, it was this:
git clone https://url/for/openface.git openface
cd openface
mkdir build
cd build
cmake -D… ..

(the url being the url for this code)

Let me know if that helps!

**Comment by murthy95** [comment]
@biancacap It worked after I pass the absolute path. Thank you.
