### ISSUE TITLE
AU emotion detection

### ISSUE THREAD

**Issue by ShirleyYim** [TadasBaltrusaitis/OpenFace#98]
Hi, I use the Feature Extraction result to predict the facial expression, but I can only detect happy and sad.
Could you please give me some advice about how to use the SVM and SVR results together? Thank you very much.

**Comment by TadasBaltrusaitis** [comment]
Hi,

Your question does not have enough details for me to answer it. In our experiments we found that it is more reliable to recognize some facial expressions from HOG features rather than AUs. So I would start from there rather than necesserilly using AUs directly.

Thanks,
Tadas

**Comment by ShirleyYim** [comment]
Hi,
Do you mean that  it is more reliable to use HOG features and SVM to directly predict the emotions such as happy/sad?
Thanks for your answer.

**Comment by TadasBaltrusaitis** [comment]
Yes exactly. At least experimentally we found that to be more accurate for categorical emotions.

Thanks,
Tadas

**Comment by ShirleyYim** [comment]
Hi, I trained a svm model using hog features of about 200 facial expression images, and  the detection accuracy is very low. Is it because the training dataset too small ?
Thanks,
Shirley Yim

**Comment by TadasBaltrusaitis** [comment]
It depends on the complexity of the dataset you used, for some it might be enough for others not necessarily. Furthermore, you need to be careful about feature normalization and might possibly need some dimensionality reduction of the HOG features.

Thanks,
Tadas

**Comment by elahia** [comment]
Hi ,
What set of outputs, are the HOGs? I mean which columns of  709 are related to HOG?

Thanks

**Comment by TadasBaltrusaitis** [comment]
Please see:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#similarity-aligned-face-images-and-hog-binary-files

HOG are not in the CSV file, but rather in a separate .hog file

**Comment by elahia** [comment]
Perfect, Thank you,

**Comment by monajalal** [comment]
@TadasBaltrusaitis can you please provide instruction how to visualize the .hog file for each video segment? How can I layout the .hog file for each aligned frame of a short video?

**Comment by TadasBaltrusaitis** [comment]
HOG feature visualization is currently done only during the processing of the data, so if you process the original files with `-verbose` setting you will see the visualization. You can find the code for it in: `Visualise_FHOG` function in `VisualizationUtils.cpp`
