### ISSUE TITLE
HOW TO READ OUTPUTS CORRECTLY

### ISSUE THREAD

**Issue by JimmyQ9** [TadasBaltrusaitis/OpenFace#983]
Hi Tadas, this is not a bug but a question of mine. I had download introduction articles: _OpenFace 2.0: Facial Behavior Analysis Toolkit_ and _OpenFace: an open source facial behavior analysis toolkit_. I tried to understand part of them, but I was still in dark with no idea about those labels in outputs (e.g., confidence, success, eye_lmk_x_0, eye_lmk_X_0, etc ). May I have your advices guiding me to make them clear and know how to use them correctly?

**Comment by TadasBaltrusaitis** [comment]
You can find instructions explaining the output format here - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format
